/**
 * Extended country registry — additional 90+ countries to reach 190+ total.
 * Imported and merged by global-country-registry.ts
 */
import type { CountryEntry } from "./global-country-registry";

export const EXTRA_COUNTRIES: Omit<CountryEntry, never>[] = [
  // ─── EUROPE (missing) ───
  { code: "AD", name: "Andorra", flag: "🇦🇩", defaultLanguage: "es", supportedLanguages: ["es", "en", "fr"], currency: "EUR", currencySymbol: "€", locale: "ca-AD", dateFormat: "dd/MM/yyyy", timezone: "Europe/Andorra", addressFormat: "european", phonePrefix: "+376", phoneFormat: "312 345", measurementUnit: "metric", region: "europe", taxIdLabel: "NRT", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "MC", name: "Monaco", flag: "🇲🇨", defaultLanguage: "fr", supportedLanguages: ["fr", "en"], currency: "EUR", currencySymbol: "€", locale: "fr-MC", dateFormat: "dd/MM/yyyy", timezone: "Europe/Monaco", addressFormat: "european", phonePrefix: "+377", phoneFormat: "06 12 34 56 78", measurementUnit: "metric", region: "europe", taxIdLabel: "RCI", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "LI", name: "Liechtenstein", flag: "🇱🇮", defaultLanguage: "de", supportedLanguages: ["de", "en"], currency: "CHF", currencySymbol: "CHF", locale: "de-LI", dateFormat: "dd.MM.yyyy", timezone: "Europe/Vaduz", addressFormat: "european", phonePrefix: "+423", phoneFormat: "660 1234", measurementUnit: "metric", region: "europe", taxIdLabel: "AHV-Nr", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "SM", name: "San Marino", flag: "🇸🇲", defaultLanguage: "it", supportedLanguages: ["it", "en"], currency: "EUR", currencySymbol: "€", locale: "it-SM", dateFormat: "dd/MM/yyyy", timezone: "Europe/San_Marino", addressFormat: "european", phonePrefix: "+378", phoneFormat: "66 12 34 56", measurementUnit: "metric", region: "europe", taxIdLabel: "COE", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "BY", name: "Belarus", flag: "🇧🇾", defaultLanguage: "en", supportedLanguages: ["en"], currency: "BYN", currencySymbol: "Br", locale: "be-BY", dateFormat: "dd.MM.yyyy", timezone: "Europe/Minsk", addressFormat: "european", phonePrefix: "+375", phoneFormat: "029 123 45 67", measurementUnit: "metric", region: "europe", taxIdLabel: "УНП", legalDocumentTypes: ["lease-residential", "rent-receipt"] },

  // ─── AMERICAS (missing) ───
  { code: "HT", name: "Haiti", flag: "🇭🇹", defaultLanguage: "fr", supportedLanguages: ["fr", "en"], currency: "HTG", currencySymbol: "G", locale: "fr-HT", dateFormat: "dd/MM/yyyy", timezone: "America/Port-au-Prince", addressFormat: "european", phonePrefix: "+509", phoneFormat: "34 12 3456", measurementUnit: "metric", region: "americas", taxIdLabel: "NIF", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "BS", name: "Bahamas", flag: "🇧🇸", defaultLanguage: "en", supportedLanguages: ["en"], currency: "BSD", currencySymbol: "B$", locale: "en-BS", dateFormat: "dd/MM/yyyy", timezone: "America/Nassau", addressFormat: "anglo", phonePrefix: "+1", phoneFormat: "(242) 123-4567", measurementUnit: "metric", region: "americas", taxIdLabel: "NIB", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "BB", name: "Barbados", flag: "🇧🇧", defaultLanguage: "en", supportedLanguages: ["en"], currency: "BBD", currencySymbol: "Bds$", locale: "en-BB", dateFormat: "dd/MM/yyyy", timezone: "America/Barbados", addressFormat: "anglo", phonePrefix: "+1", phoneFormat: "(246) 123-4567", measurementUnit: "metric", region: "americas", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "GY", name: "Guyana", flag: "🇬🇾", defaultLanguage: "en", supportedLanguages: ["en"], currency: "GYD", currencySymbol: "G$", locale: "en-GY", dateFormat: "dd/MM/yyyy", timezone: "America/Guyana", addressFormat: "anglo", phonePrefix: "+592", phoneFormat: "612 3456", measurementUnit: "metric", region: "americas", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "SR", name: "Suriname", flag: "🇸🇷", defaultLanguage: "nl", supportedLanguages: ["nl", "en"], currency: "SRD", currencySymbol: "SRD", locale: "nl-SR", dateFormat: "dd/MM/yyyy", timezone: "America/Paramaribo", addressFormat: "european", phonePrefix: "+597", phoneFormat: "812 3456", measurementUnit: "metric", region: "americas", taxIdLabel: "ID", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "BZ", name: "Belize", flag: "🇧🇿", defaultLanguage: "en", supportedLanguages: ["en", "es"], currency: "BZD", currencySymbol: "BZ$", locale: "en-BZ", dateFormat: "dd/MM/yyyy", timezone: "America/Belize", addressFormat: "anglo", phonePrefix: "+501", phoneFormat: "612-3456", measurementUnit: "metric", region: "americas", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "PR", name: "Puerto Rico", flag: "🇵🇷", defaultLanguage: "es", supportedLanguages: ["es", "en"], currency: "USD", currencySymbol: "$", locale: "es-PR", dateFormat: "MM/dd/yyyy", timezone: "America/Puerto_Rico", addressFormat: "anglo", phonePrefix: "+1", phoneFormat: "(787) 123-4567", measurementUnit: "imperial", region: "americas", taxIdLabel: "SSN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },

  // ─── AFRICA (missing) ───
  { code: "AO", name: "Angola", flag: "🇦🇴", defaultLanguage: "pt", supportedLanguages: ["pt", "en"], currency: "AOA", currencySymbol: "Kz", locale: "pt-AO", dateFormat: "dd/MM/yyyy", timezone: "Africa/Luanda", addressFormat: "european", phonePrefix: "+244", phoneFormat: "923 456 789", measurementUnit: "metric", region: "africa", taxIdLabel: "NIF", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿", defaultLanguage: "pt", supportedLanguages: ["pt", "en"], currency: "MZN", currencySymbol: "MT", locale: "pt-MZ", dateFormat: "dd/MM/yyyy", timezone: "Africa/Maputo", addressFormat: "european", phonePrefix: "+258", phoneFormat: "84 123 4567", measurementUnit: "metric", region: "africa", taxIdLabel: "NUIT", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "CV", name: "Cabo Verde", flag: "🇨🇻", defaultLanguage: "pt", supportedLanguages: ["pt", "en"], currency: "CVE", currencySymbol: "CVE", locale: "pt-CV", dateFormat: "dd/MM/yyyy", timezone: "Atlantic/Cape_Verde", addressFormat: "european", phonePrefix: "+238", phoneFormat: "991 23 45", measurementUnit: "metric", region: "africa", taxIdLabel: "NIF", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "ST", name: "São Tomé & Príncipe", flag: "🇸🇹", defaultLanguage: "pt", supportedLanguages: ["pt", "en"], currency: "STN", currencySymbol: "Db", locale: "pt-ST", dateFormat: "dd/MM/yyyy", timezone: "Africa/Sao_Tome", addressFormat: "european", phonePrefix: "+239", phoneFormat: "991 2345", measurementUnit: "metric", region: "africa", taxIdLabel: "NIF", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼", defaultLanguage: "pt", supportedLanguages: ["pt", "en"], currency: "XOF", currencySymbol: "CFA", locale: "pt-GW", dateFormat: "dd/MM/yyyy", timezone: "Africa/Bissau", addressFormat: "european", phonePrefix: "+245", phoneFormat: "955 123 456", measurementUnit: "metric", region: "africa", taxIdLabel: "NIF", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶", defaultLanguage: "es", supportedLanguages: ["es", "fr", "en"], currency: "XAF", currencySymbol: "FCFA", locale: "es-GQ", dateFormat: "dd/MM/yyyy", timezone: "Africa/Malabo", addressFormat: "european", phonePrefix: "+240", phoneFormat: "222 123 456", measurementUnit: "metric", region: "africa", taxIdLabel: "NIF", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "DJ", name: "Djibouti", flag: "🇩🇯", defaultLanguage: "fr", supportedLanguages: ["fr", "ar", "en"], currency: "DJF", currencySymbol: "Fdj", locale: "fr-DJ", dateFormat: "dd/MM/yyyy", timezone: "Africa/Djibouti", addressFormat: "european", phonePrefix: "+253", phoneFormat: "77 12 34 56", measurementUnit: "metric", region: "africa", taxIdLabel: "NIF", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "KM", name: "Comoros", flag: "🇰🇲", defaultLanguage: "fr", supportedLanguages: ["fr", "ar", "en"], currency: "KMF", currencySymbol: "CF", locale: "fr-KM", dateFormat: "dd/MM/yyyy", timezone: "Indian/Comoro", addressFormat: "european", phonePrefix: "+269", phoneFormat: "321 23 45", measurementUnit: "metric", region: "africa", taxIdLabel: "NIF", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "SC", name: "Seychelles", flag: "🇸🇨", defaultLanguage: "en", supportedLanguages: ["en", "fr"], currency: "SCR", currencySymbol: "₨", locale: "en-SC", dateFormat: "dd/MM/yyyy", timezone: "Indian/Mahe", addressFormat: "anglo", phonePrefix: "+248", phoneFormat: "2 512 345", measurementUnit: "metric", region: "africa", taxIdLabel: "NIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "NA", name: "Namibia", flag: "🇳🇦", defaultLanguage: "en", supportedLanguages: ["en"], currency: "NAD", currencySymbol: "N$", locale: "en-NA", dateFormat: "dd/MM/yyyy", timezone: "Africa/Windhoek", addressFormat: "anglo", phonePrefix: "+264", phoneFormat: "081 123 4567", measurementUnit: "metric", region: "africa", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "BW", name: "Botswana", flag: "🇧🇼", defaultLanguage: "en", supportedLanguages: ["en"], currency: "BWP", currencySymbol: "P", locale: "en-BW", dateFormat: "dd/MM/yyyy", timezone: "Africa/Gaborone", addressFormat: "anglo", phonePrefix: "+267", phoneFormat: "71 234 567", measurementUnit: "metric", region: "africa", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "ZM", name: "Zambia", flag: "🇿🇲", defaultLanguage: "en", supportedLanguages: ["en"], currency: "ZMW", currencySymbol: "ZK", locale: "en-ZM", dateFormat: "dd/MM/yyyy", timezone: "Africa/Lusaka", addressFormat: "anglo", phonePrefix: "+260", phoneFormat: "097 1234567", measurementUnit: "metric", region: "africa", taxIdLabel: "TPIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼", defaultLanguage: "en", supportedLanguages: ["en"], currency: "ZWL", currencySymbol: "Z$", locale: "en-ZW", dateFormat: "dd/MM/yyyy", timezone: "Africa/Harare", addressFormat: "anglo", phonePrefix: "+263", phoneFormat: "077 123 4567", measurementUnit: "metric", region: "africa", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "MW", name: "Malawi", flag: "🇲🇼", defaultLanguage: "en", supportedLanguages: ["en"], currency: "MWK", currencySymbol: "MK", locale: "en-MW", dateFormat: "dd/MM/yyyy", timezone: "Africa/Blantyre", addressFormat: "anglo", phonePrefix: "+265", phoneFormat: "099 123 4567", measurementUnit: "metric", region: "africa", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "LS", name: "Lesotho", flag: "🇱🇸", defaultLanguage: "en", supportedLanguages: ["en"], currency: "LSL", currencySymbol: "L", locale: "en-LS", dateFormat: "dd/MM/yyyy", timezone: "Africa/Maseru", addressFormat: "anglo", phonePrefix: "+266", phoneFormat: "5012 3456", measurementUnit: "metric", region: "africa", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "SZ", name: "Eswatini", flag: "🇸🇿", defaultLanguage: "en", supportedLanguages: ["en"], currency: "SZL", currencySymbol: "E", locale: "en-SZ", dateFormat: "dd/MM/yyyy", timezone: "Africa/Mbabane", addressFormat: "anglo", phonePrefix: "+268", phoneFormat: "7612 3456", measurementUnit: "metric", region: "africa", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "LR", name: "Liberia", flag: "🇱🇷", defaultLanguage: "en", supportedLanguages: ["en"], currency: "LRD", currencySymbol: "L$", locale: "en-LR", dateFormat: "dd/MM/yyyy", timezone: "Africa/Monrovia", addressFormat: "anglo", phonePrefix: "+231", phoneFormat: "077 123 4567", measurementUnit: "metric", region: "africa", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "SL", name: "Sierra Leone", flag: "🇸🇱", defaultLanguage: "en", supportedLanguages: ["en"], currency: "SLE", currencySymbol: "Le", locale: "en-SL", dateFormat: "dd/MM/yyyy", timezone: "Africa/Freetown", addressFormat: "anglo", phonePrefix: "+232", phoneFormat: "076 123456", measurementUnit: "metric", region: "africa", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "GM", name: "Gambia", flag: "🇬🇲", defaultLanguage: "en", supportedLanguages: ["en"], currency: "GMD", currencySymbol: "D", locale: "en-GM", dateFormat: "dd/MM/yyyy", timezone: "Africa/Banjul", addressFormat: "anglo", phonePrefix: "+220", phoneFormat: "701 2345", measurementUnit: "metric", region: "africa", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "CF", name: "Central African Republic", flag: "🇨🇫", defaultLanguage: "fr", supportedLanguages: ["fr", "en"], currency: "XAF", currencySymbol: "FCFA", locale: "fr-CF", dateFormat: "dd/MM/yyyy", timezone: "Africa/Bangui", addressFormat: "european", phonePrefix: "+236", phoneFormat: "70 12 34 56", measurementUnit: "metric", region: "africa", taxIdLabel: "NIF", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "BI", name: "Burundi", flag: "🇧🇮", defaultLanguage: "fr", supportedLanguages: ["fr", "en"], currency: "BIF", currencySymbol: "FBu", locale: "fr-BI", dateFormat: "dd/MM/yyyy", timezone: "Africa/Bujumbura", addressFormat: "european", phonePrefix: "+257", phoneFormat: "79 123 456", measurementUnit: "metric", region: "africa", taxIdLabel: "NIF", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "ER", name: "Eritrea", flag: "🇪🇷", defaultLanguage: "en", supportedLanguages: ["en", "ar"], currency: "ERN", currencySymbol: "Nfk", locale: "en-ER", dateFormat: "dd/MM/yyyy", timezone: "Africa/Asmara", addressFormat: "anglo", phonePrefix: "+291", phoneFormat: "07 123 456", measurementUnit: "metric", region: "africa", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "SO", name: "Somalia", flag: "🇸🇴", defaultLanguage: "en", supportedLanguages: ["en", "ar"], currency: "SOS", currencySymbol: "Sh", locale: "en-SO", dateFormat: "dd/MM/yyyy", timezone: "Africa/Mogadishu", addressFormat: "anglo", phonePrefix: "+252", phoneFormat: "061 234 5678", measurementUnit: "metric", region: "africa", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "SD", name: "Sudan", flag: "🇸🇩", defaultLanguage: "en", supportedLanguages: ["en", "ar"], currency: "SDG", currencySymbol: "SDG", locale: "en-SD", dateFormat: "dd/MM/yyyy", timezone: "Africa/Khartoum", addressFormat: "arabic", phonePrefix: "+249", phoneFormat: "091 234 5678", measurementUnit: "metric", region: "africa", taxIdLabel: "National ID", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "SS", name: "South Sudan", flag: "🇸🇸", defaultLanguage: "en", supportedLanguages: ["en"], currency: "SSP", currencySymbol: "SSP", locale: "en-SS", dateFormat: "dd/MM/yyyy", timezone: "Africa/Juba", addressFormat: "anglo", phonePrefix: "+211", phoneFormat: "091 234 5678", measurementUnit: "metric", region: "africa", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "LY", name: "Libya", flag: "🇱🇾", defaultLanguage: "ar", supportedLanguages: ["ar", "en"], currency: "LYD", currencySymbol: "LD", locale: "ar-LY", dateFormat: "dd/MM/yyyy", timezone: "Africa/Tripoli", addressFormat: "arabic", phonePrefix: "+218", phoneFormat: "091 234 5678", measurementUnit: "metric", region: "africa", taxIdLabel: "National ID", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "MR", name: "Mauritania", flag: "🇲🇷", defaultLanguage: "fr", supportedLanguages: ["fr", "ar", "en"], currency: "MRU", currencySymbol: "UM", locale: "fr-MR", dateFormat: "dd/MM/yyyy", timezone: "Africa/Nouakchott", addressFormat: "european", phonePrefix: "+222", phoneFormat: "22 12 34 56", measurementUnit: "metric", region: "africa", taxIdLabel: "NIF", legalDocumentTypes: ["lease-residential", "rent-receipt"] },

  // ─── MIDDLE EAST (missing) ───
  { code: "YE", name: "Yemen", flag: "🇾🇪", defaultLanguage: "ar", supportedLanguages: ["ar", "en"], currency: "YER", currencySymbol: "﷼", locale: "ar-YE", dateFormat: "dd/MM/yyyy", timezone: "Asia/Aden", addressFormat: "arabic", phonePrefix: "+967", phoneFormat: "712 345 678", measurementUnit: "metric", region: "middle_east", taxIdLabel: "National ID", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "SY", name: "Syria", flag: "🇸🇾", defaultLanguage: "ar", supportedLanguages: ["ar", "en"], currency: "SYP", currencySymbol: "LS", locale: "ar-SY", dateFormat: "dd/MM/yyyy", timezone: "Asia/Damascus", addressFormat: "arabic", phonePrefix: "+963", phoneFormat: "093 123 4567", measurementUnit: "metric", region: "middle_east", taxIdLabel: "National ID", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "PS", name: "Palestine", flag: "🇵🇸", defaultLanguage: "ar", supportedLanguages: ["ar", "en"], currency: "ILS", currencySymbol: "₪", locale: "ar-PS", dateFormat: "dd/MM/yyyy", timezone: "Asia/Hebron", addressFormat: "arabic", phonePrefix: "+970", phoneFormat: "059 123 4567", measurementUnit: "metric", region: "middle_east", taxIdLabel: "National ID", legalDocumentTypes: ["lease-residential", "rent-receipt"] },

  // ─── ASIA-PACIFIC (missing) ───
  { code: "AF", name: "Afghanistan", flag: "🇦🇫", defaultLanguage: "en", supportedLanguages: ["en"], currency: "AFN", currencySymbol: "؋", locale: "en-AF", dateFormat: "dd/MM/yyyy", timezone: "Asia/Kabul", addressFormat: "arabic", phonePrefix: "+93", phoneFormat: "070 123 4567", measurementUnit: "metric", region: "asia_pacific", taxIdLabel: "Tazkira", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "IR", name: "Iran", flag: "🇮🇷", defaultLanguage: "en", supportedLanguages: ["en"], currency: "IRR", currencySymbol: "﷼", locale: "fa-IR", dateFormat: "yyyy/MM/dd", timezone: "Asia/Tehran", addressFormat: "arabic", phonePrefix: "+98", phoneFormat: "0912 345 6789", measurementUnit: "metric", region: "middle_east", taxIdLabel: "National Code", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "TM", name: "Turkmenistan", flag: "🇹🇲", defaultLanguage: "en", supportedLanguages: ["en"], currency: "TMT", currencySymbol: "m", locale: "tk-TM", dateFormat: "dd.MM.yyyy", timezone: "Asia/Ashgabat", addressFormat: "european", phonePrefix: "+993", phoneFormat: "65 12 34 56", measurementUnit: "metric", region: "asia_pacific", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "TJ", name: "Tajikistan", flag: "🇹🇯", defaultLanguage: "en", supportedLanguages: ["en"], currency: "TJS", currencySymbol: "SM", locale: "tg-TJ", dateFormat: "dd.MM.yyyy", timezone: "Asia/Dushanbe", addressFormat: "european", phonePrefix: "+992", phoneFormat: "93 123 4567", measurementUnit: "metric", region: "asia_pacific", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬", defaultLanguage: "en", supportedLanguages: ["en"], currency: "KGS", currencySymbol: "сом", locale: "ky-KG", dateFormat: "dd.MM.yyyy", timezone: "Asia/Bishkek", addressFormat: "european", phonePrefix: "+996", phoneFormat: "0700 123 456", measurementUnit: "metric", region: "asia_pacific", taxIdLabel: "ИНН", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "MV", name: "Maldives", flag: "🇲🇻", defaultLanguage: "en", supportedLanguages: ["en"], currency: "MVR", currencySymbol: "Rf", locale: "en-MV", dateFormat: "dd/MM/yyyy", timezone: "Indian/Maldives", addressFormat: "anglo", phonePrefix: "+960", phoneFormat: "712 3456", measurementUnit: "metric", region: "asia_pacific", taxIdLabel: "NIC", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "BT", name: "Bhutan", flag: "🇧🇹", defaultLanguage: "en", supportedLanguages: ["en"], currency: "BTN", currencySymbol: "Nu", locale: "en-BT", dateFormat: "dd/MM/yyyy", timezone: "Asia/Thimphu", addressFormat: "anglo", phonePrefix: "+975", phoneFormat: "17 12 34 56", measurementUnit: "metric", region: "asia_pacific", taxIdLabel: "CID", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "PG", name: "Papua New Guinea", flag: "🇵🇬", defaultLanguage: "en", supportedLanguages: ["en"], currency: "PGK", currencySymbol: "K", locale: "en-PG", dateFormat: "dd/MM/yyyy", timezone: "Pacific/Port_Moresby", addressFormat: "anglo", phonePrefix: "+675", phoneFormat: "7012 3456", measurementUnit: "metric", region: "asia_pacific", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "WS", name: "Samoa", flag: "🇼🇸", defaultLanguage: "en", supportedLanguages: ["en"], currency: "WST", currencySymbol: "T", locale: "en-WS", dateFormat: "dd/MM/yyyy", timezone: "Pacific/Apia", addressFormat: "anglo", phonePrefix: "+685", phoneFormat: "72 12345", measurementUnit: "metric", region: "asia_pacific", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "TO", name: "Tonga", flag: "🇹🇴", defaultLanguage: "en", supportedLanguages: ["en"], currency: "TOP", currencySymbol: "T$", locale: "en-TO", dateFormat: "dd/MM/yyyy", timezone: "Pacific/Tongatapu", addressFormat: "anglo", phonePrefix: "+676", phoneFormat: "771 2345", measurementUnit: "metric", region: "asia_pacific", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "VU", name: "Vanuatu", flag: "🇻🇺", defaultLanguage: "en", supportedLanguages: ["en", "fr"], currency: "VUV", currencySymbol: "VT", locale: "en-VU", dateFormat: "dd/MM/yyyy", timezone: "Pacific/Efate", addressFormat: "anglo", phonePrefix: "+678", phoneFormat: "591 2345", measurementUnit: "metric", region: "asia_pacific", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "SB", name: "Solomon Islands", flag: "🇸🇧", defaultLanguage: "en", supportedLanguages: ["en"], currency: "SBD", currencySymbol: "SI$", locale: "en-SB", dateFormat: "dd/MM/yyyy", timezone: "Pacific/Guadalcanal", addressFormat: "anglo", phonePrefix: "+677", phoneFormat: "741 2345", measurementUnit: "metric", region: "asia_pacific", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
  { code: "TL", name: "Timor-Leste", flag: "🇹🇱", defaultLanguage: "pt", supportedLanguages: ["pt", "en"], currency: "USD", currencySymbol: "$", locale: "pt-TL", dateFormat: "dd/MM/yyyy", timezone: "Asia/Dili", addressFormat: "anglo", phonePrefix: "+670", phoneFormat: "7712 3456", measurementUnit: "metric", region: "asia_pacific", taxIdLabel: "TIN", legalDocumentTypes: ["lease-residential", "rent-receipt"] },
];
