/**
 * Centralized route helpers for Easy-Locs.
 * Use these instead of hardcoding paths in components.
 */
export const routes = {
  home: () => `/`,
  notFound: () => `/404`,

  // QR
  qr: (code: string) => `/qr/entry/${encodeURIComponent(code)}`,
  qrEntry: (targetCode: string) => `/qr/entry/${encodeURIComponent(targetCode)}`,
  qrGenerate: () => `/admin/qr-generate`,

  // Tracking
  tracking: (orderId: string) => `/tracking/order/${encodeURIComponent(orderId)}`,

  // Driver
  driverMission: (id: string) => `/driver/mission/${encodeURIComponent(id)}`,
  driverEarnings: () => `/driver/earnings`,
  driverMissions: () => `/driver/missions`,

  // Merchant
  merchantDelivery: () => `/merchant/delivery-monitor`,
  merchantPos: () => `/merchant/pos`,
  merchantKitchen: () => `/merchant/kitchen`,
  merchantDashboard: () => `/merchant/dashboard`,
  merchantClaim: () => `/merchant/claim`,
  merchantOnboarding: () => `/merchant/onboarding`,

  // Admin
  walletDiagnostics: () => `/admin/wallet-diagnostics`,
  dispatchDiagnostics: () => `/admin/dispatch-diagnostics`,
  automations: () => `/admin/automations`,
  automationHealth: () => `/admin/automation-health`,
  opsExceptions: () => `/admin/ops-exceptions`,
  reviewQueue: () => `/admin/review-queue`,
  growthDashboard: () => `/admin/growth`,
  growthEngine: () => `/admin/growth-engine`,
  importTestBatches: () => `/admin/import-test-batches`,
  routeAudit: () => `/admin/route-audit`,
  restaurantSeedTest: () => `/admin/test-restaurants`,
  dubaiImport: () => `/admin/dubai-import`,
  alertCenter: () => `/admin/alerts`,
  incidents: () => `/admin/incidents`,
  auditDebug: () => `/admin/audit-debug`,
  opsWallboard: () => `/admin/ops-wallboard`,
  outreach: () => `/admin/outreach`,
  dinoAudit: () => `/admin/dino`,
  dinoControl: () => `/admin/dino-control`,
  seedTools: () => `/admin/seed-tools`,
  favorites: () => `/favorites`,
  searchResults: () => `/search-results`,
  adminContentOps: () => `/admin/content-ops`,
  reorder: (orderId: string) => `/order/reorder/${encodeURIComponent(orderId)}`,
  merchantOrderBoard: (merchantId: string) => `/merchant/orders/${encodeURIComponent(merchantId)}`,
  adminAnalyticsOps: () => `/admin/analytics-ops`,
  customerProfile: () => `/me`,
  notificationPreferences: () => `/settings/notification-preferences`,
  adminQualityOps: () => `/admin/quality-ops`,
  merchantReviewReplies: (merchantId: string) => `/merchant/reviews/${encodeURIComponent(merchantId)}`,
  adminCrmOps: () => `/admin/crm-ops`,
  adminHomeEngine: () => `/admin/home-engine`,
  adminMapEngine: () => `/admin/map-engine`,
  adminNotificationEngine: () => `/admin/notification-engine`,
  merchantInventory: (merchantId: string) => `/merchant/inventory/${encodeURIComponent(merchantId)}`,
  merchantLiveControl: (merchantId: string) => `/merchant/live/${encodeURIComponent(merchantId)}`,
  merchantCoupons: (merchantId: string) => `/merchant/coupons/${encodeURIComponent(merchantId)}`,
  adminGrowthOps: () => `/admin/growth-ops`,
  notifications: () => `/notifications`,
  adminRetentionOps: () => `/admin/retention-ops`,
  driverEarningsV2: () => `/driver/earnings-v2`,
  orderReceipt: (orderId: string) => `/order/receipt/${encodeURIComponent(orderId)}`,
  merchantAnalytics: (merchantId: string) => `/merchant/analytics/${encodeURIComponent(merchantId)}`,
  adminOperationsLaunchpad: () => `/admin/operations-launchpad`,
  merchantCustomers: (merchantId: string) => `/merchant/customers/${encodeURIComponent(merchantId)}`,
  adminMerchantHealth: () => `/admin/merchant-health`,
  walletTopUp: () => `/wallet/top-up`,
  walletTransfer: () => `/wallet/transfer`,
  orderRefundRequest: (orderId: string) => `/order/refund/${encodeURIComponent(orderId)}`,
  merchantBannerEditor: (merchantId: string) => `/merchant/banner-editor/${encodeURIComponent(merchantId)}`,
  adminDriverMonitor: () => `/admin/driver-monitor`,
  adminUserLookup: () => `/admin/user-lookup`,
  adminNotificationOps: () => `/admin/notification-ops`,
  adminFinanceSummary: () => `/admin/finance-summary`,
  customerSpendingInsights: () => `/me/spending-insights`,
  adminPlatformAlerts: () => `/admin/platform-alerts`,
  customerAddressBook: () => `/me/address-book`,
  merchantBusinessSummary: (merchantId: string) => `/merchant/business-summary/${encodeURIComponent(merchantId)}`,
  adminOrderWatch: () => `/admin/order-watch`,
  customerLoyaltyHistory: () => `/me/loyalty-history`,
  adminSearchWatch: () => `/admin/search-watch`,
  customerActiveOrders: () => `/my-orders/active`,
  merchantClosingMode: (merchantId: string) => `/merchant/closing-mode/${encodeURIComponent(merchantId)}`,
  adminMerchantPromoWatch: () => `/admin/merchant-promo-watch`,
  driverEarningsSummary: () => `/driver/earnings-summary`,
  adminRefundWatch: () => `/admin/refund-watch`,
  customerSupportShortcuts: () => `/support/shortcuts`,
  merchantCustomerInsights: (merchantId: string) => `/merchant/customer-insights/${encodeURIComponent(merchantId)}`,
  adminDriverHeatmap: () => `/admin/driver-heatmap`,
  customerOrderArchive: () => `/my-orders/archive`,
  merchantProductPerformance: (merchantId: string) => `/merchant/product-performance/${encodeURIComponent(merchantId)}`,
  adminWalletWatch: () => `/admin/wallet-watch`,
  customerReorder: () => `/reorder`,
  merchantAutoAccept: (merchantId: string) => `/merchant/auto-accept/${encodeURIComponent(merchantId)}`,
  adminSystemHealth: () => `/admin/system-health`,
  customerLiveLocation: () => `/location/live`,
  driverActiveMissions: () => `/driver/active-missions`,
  adminFraudDetection: () => `/admin/fraud-detection`,
  customerSavedCards: () => `/me/saved-cards`,
  merchantInventoryAlerts: (merchantId: string) => `/merchant/inventory-alerts/${encodeURIComponent(merchantId)}`,
  adminOrderTimeline: () => `/admin/order-timeline`,
  customerQuickHelp: () => `/me/quick-help`,
  driverShift: () => `/driver/shift`,
  adminMerchantApprovalQueue: () => `/admin/merchant-approval-queue`,
  customerDeliveryNotes: () => `/me/delivery-notes`,
  merchantStaffAccess: (merchantId: string) => `/merchant/staff-access/${encodeURIComponent(merchantId)}`,
  adminFailedPayments: () => `/admin/failed-payments`,
  customerReferFriend: () => `/me/refer-friend`,
  driverDocuments: () => `/driver/documents`,
  adminSupportSla: () => `/admin/support-sla`,
  customerAddressSelector: () => `/checkout/address-selector`,
  merchantDailySales: (merchantId: string) => `/merchant/daily-sales/${encodeURIComponent(merchantId)}`,
  adminDeliveryIncidents: () => `/admin/delivery-incidents`,
  customerPaymentActivity: () => `/me/payment-activity`,
  driverAvailabilityZones: () => `/driver/availability-zones`,
  adminGrowthDashboard: () => `/admin/growth-dashboard`,
  customerOrderReceipts: () => `/me/order-receipts`,
  merchantRefundRequests: (merchantId: string) => `/merchant/refund-requests/${encodeURIComponent(merchantId)}`,
  adminCouponOversight: () => `/admin/coupon-oversight`,
  customerNotificationCenter: () => `/me/notification-center`,
  driverCompletedDeliveries: () => `/driver/completed-deliveries`,
  adminActiveSessions: () => `/admin/active-sessions`,
  merchantMenuBulk: (merchantId: string) => `/merchant/menu-bulk/${encodeURIComponent(merchantId)}`,
  adminFraudMonitor: () => `/admin/fraud-monitor`,
  customerLiveTracking: (orderId: string) => `/tracking-live/${encodeURIComponent(orderId)}`,
  merchantLiveOrders: (merchantId: string) => `/merchant/live-orders/${encodeURIComponent(merchantId)}`,
  adminHeatmap: () => `/admin/heatmap`,
  customerQuickReorder: () => `/quick-reorder`,
  driverLiveMissions: () => `/driver/live-missions`,
  adminRealtimeAlerts: () => `/admin/realtime-alerts`,
  // FA-FF
  customerOrderSchedule: () => `/checkout/schedule`,
  merchantOpenClose: (merchantId: string) => `/merchant/open-close/${encodeURIComponent(merchantId)}`,
  adminRetentionDashboard: () => `/admin/retention-dashboard`,
  customerPromoWallet: () => `/me/promo-wallet`,
  driverBreakMode: () => `/driver/break-mode`,
  adminMerchantPerformance: () => `/admin/merchant-performance`,
  // FG-FL
  customerFamilyProfiles: () => `/me/family-profiles`,
  merchantPrepTime: (merchantId: string) => `/merchant/prep-time/${encodeURIComponent(merchantId)}`,
  adminRefundControl: () => `/admin/refund-control`,
  customerTipping: () => `/checkout/tip`,
  driverAcceptanceRate: () => `/driver/acceptance-rate`,
  adminDriverPerformance: () => `/admin/driver-performance`,
  // FM-FR
  customerSubscriptions: () => `/me/subscriptions`,
  merchantPromoScheduler: (merchantId: string) => `/merchant/promo-scheduler/${encodeURIComponent(merchantId)}`,
  adminDisputeCenter: () => `/admin/dispute-center`,
  customerFavoriteOrders: () => `/me/favorite-orders`,
  driverShiftScheduler: () => `/driver/shift-scheduler`,
  adminGlobalFinance: () => `/admin/global-finance`,
  // FS-FX
  adminCoreEngine: () => `/admin/core-engine`,
  // FY-GD
  customerGroupOrder: () => `/checkout/group-order`,
  merchantAutoAcceptV2: (merchantId: string) => `/merchant/auto-accept-v2/${encodeURIComponent(merchantId)}`,
  adminCashflowMonitor: () => `/admin/cashflow-monitor`,
  customerAddressBookV2: () => `/me/address-book-v2`,
  driverNavigationMode: () => `/driver/navigation-mode`,
  adminCityOps: () => `/admin/city-ops`,
  // GE-GJ
  customerMealPlanner: () => `/me/meal-planner`,
  merchantDeliveryZones: (merchantId: string) => `/merchant/delivery-zones/${encodeURIComponent(merchantId)}`,
  adminOperatorNotes: () => `/admin/operator-notes`,
  customerReceiptVault: () => `/me/receipt-vault`,
  driverVehicleProfile: () => `/driver/vehicle-profile`,
  adminNetworkStatus: () => `/admin/network-status`,
  // GK-GP
  customerSharedWallet: () => `/me/shared-wallet`,
  adminSlaMonitor: () => `/admin/sla-monitor`,
  customerOrderGifts: () => `/checkout/gift-order`,
  adminIncidentCenter: () => `/admin/incident-center`,
  // GQ-GV
  customerSplitBill: () => `/checkout/split-bill`,
  merchantKitchenDisplay: (merchantId: string) => `/merchant/kitchen-display/${encodeURIComponent(merchantId)}`,
  adminOrderAudit: () => `/admin/order-audit`,
  customerDeliveryInstructions: () => `/checkout/delivery-instructions`,
  driverDailyTarget: () => `/driver/daily-target`,
  adminMarketExpansion: () => `/admin/market-expansion`,
  // GW-HB
  customerSavedCarts: () => `/me/saved-carts`,
  merchantOutOfStock: (merchantId: string) => `/merchant/out-of-stock/${encodeURIComponent(merchantId)}`,
  adminFraudWatch: () => `/admin/fraud-watch`,
  customerContactless: () => `/checkout/contactless`,
  driverHotZones: () => `/driver/hot-zones`,
  adminDemandForecast: () => `/admin/demand-forecast`,
  // HC-HH
  customerAutoRepeat: () => `/me/auto-repeat`,
  merchantRushMode: (merchantId: string) => `/merchant/rush-mode/${encodeURIComponent(merchantId)}`,
  adminRefundQueue: () => `/admin/refund-queue`,
  customerPartyOrder: () => `/checkout/party-order`,
  driverEarningsBreakdown: () => `/driver/earnings-breakdown`,
  adminPlatformHealth: () => `/admin/platform-health`,
  // HI-HN
  customerOfficeLunch: () => `/checkout/office-lunch`,
  merchantDeliveryFees: (merchantId: string) => `/merchant/delivery-fees/${encodeURIComponent(merchantId)}`,
  adminDriverCompliance: () => `/admin/driver-compliance`,
  customerRewardRedemption: () => `/me/redeem-rewards`,
  driverFuelCosts: () => `/driver/fuel-costs`,
  adminExecutiveOverview: () => `/admin/executive-overview`,

  // Orbit
  orbitCallTest: () => `/orbit/call-test`,
  orbitIdentity: () => `/orbit/identity`,

  // Food flow
  food: () => `/food`,
  foodType: (type: string) => `/food/${encodeURIComponent(type)}`,
  foodCuisine: (type: string, cuisine: string) => `/food/${encodeURIComponent(type)}/${encodeURIComponent(cuisine)}`,
  foodRestaurant: (id: string) => `/food/restaurant/${encodeURIComponent(id)}`,

  // Settings
  settings: () => `/settings`,
  settingsAccount: () => `/settings/account`,
  settingsOrbit: () => `/settings/orbit`,
  settingsBusiness: () => `/settings/business`,
  settingsWallet: () => `/settings/wallet`,
  settingsAddresses: () => `/settings/addresses`,
  settingsNotifications: () => `/settings/notifications`,
  settingsSecurity: () => `/settings/security`,
  settingsPreferences: () => `/settings/preferences`,

  // Ghost V2/V3
  ghost: () => `/ghost`,
  ghostInbox: () => `/ghost/inbox`,
  ghostThread: (threadId: string) => `/ghost/thread/${encodeURIComponent(threadId)}`,
  ghostCall: (callId: string) => `/ghost/call/${encodeURIComponent(callId)}`,
  ghostSettings: () => `/ghost/settings`,
  ghostContacts: () => `/ghost/contacts`,

  // Public
  comingSoon: (slug: string) => `/coming-soon/${encodeURIComponent(slug)}`,
  cityMarket: (citySlug: string) => `/city-market/${encodeURIComponent(citySlug)}`,
  cityVertical: (countryCode: string, city: string, vertical: string, locale: string) =>
    `/city/${encodeURIComponent(countryCode)}/${encodeURIComponent(city)}/${encodeURIComponent(vertical)}/${encodeURIComponent(locale)}`,

  // Dashboard
  dashboard: () => `/dashboard`,
  communication: () => `/dashboard/communication`,

  // Wallet
  wallet: () => `/wallet`,
  walletHub: () => `/wallet/hub`,

  // Map / Radar
  map: () => `/map`,
  superMap: () => `/super-map`,
  radar: () => `/radar`,

  // Ride
  ride: () => `/ride`,
  rideSearch: () => `/ride/search`,

  // Cart / Checkout / Orders / Tracking
  checkout: () => `/checkout`,
  orders: () => `/orders`,
  orderDetail: (id: string) => `/order/${encodeURIComponent(id)}`,
  trackingOrder: (id: string) => `/tracking/${encodeURIComponent(id)}`,
};

export type AppRouteKey = keyof typeof routes;

export const ROUTE_REGISTRY = [
  { group: "public", label: "Home", path: "/" },
  { group: "public", label: "404", path: "/404" },

  { group: "qr", label: "QR Entry", path: "/qr/entry/:targetCode" },
  { group: "admin", label: "QR Generate", path: "/admin/qr-generate" },

  { group: "public", label: "Tracking", path: "/tracking/order/:orderId" },

  { group: "driver", label: "Driver Missions", path: "/driver/missions" },
  { group: "driver", label: "Driver Mission", path: "/driver/mission/:dispatchJobId" },
  { group: "driver", label: "Driver Earnings", path: "/driver/earnings" },

  { group: "merchant", label: "Merchant POS", path: "/merchant/pos" },
  { group: "merchant", label: "Merchant Kitchen", path: "/merchant/kitchen" },
  { group: "merchant", label: "Merchant Delivery Monitor", path: "/merchant/delivery-monitor" },
  { group: "merchant", label: "Merchant Dashboard", path: "/merchant/dashboard" },
  { group: "merchant", label: "Merchant Claim", path: "/merchant/claim" },
  { group: "merchant", label: "Merchant Onboarding", path: "/merchant/onboarding" },

  { group: "admin", label: "Wallet Diagnostics", path: "/admin/wallet-diagnostics" },
  { group: "admin", label: "Dispatch Diagnostics", path: "/admin/dispatch-diagnostics" },
  { group: "admin", label: "Automations", path: "/admin/automations" },
  { group: "admin", label: "Automation Health", path: "/admin/automation-health" },
  { group: "admin", label: "Ops Exceptions", path: "/admin/ops-exceptions" },
  { group: "admin", label: "Review Queue", path: "/admin/review-queue" },
  { group: "admin", label: "Growth Dashboard", path: "/admin/growth" },
  { group: "admin", label: "Growth Engine", path: "/admin/growth-engine" },
  { group: "admin", label: "Route Audit", path: "/admin/route-audit" },
  { group: "admin", label: "Restaurant Seed Test", path: "/admin/test-restaurants" },
  { group: "admin", label: "Alert Center", path: "/admin/alerts" },
  { group: "admin", label: "Orbit Call Test", path: "/orbit/call-test" },
  { group: "admin", label: "Runtime Audit", path: "/admin/runtime-audit" },
  { group: "admin", label: "Runtime Quick Links", path: "/admin/runtime-links" },
  { group: "admin", label: "Analytics Ops", path: "/admin/analytics-ops" },
  { group: "admin", label: "Content Ops", path: "/admin/content-ops" },
  { group: "merchant", label: "Merchant Order Board", path: "/merchant/orders/:merchantId" },
  { group: "public", label: "Customer Profile", path: "/me" },
  { group: "settings", label: "Notification Preferences", path: "/settings/notification-preferences" },
  { group: "admin", label: "Quality Ops", path: "/admin/quality-ops" },
  { group: "merchant", label: "Merchant Review Replies", path: "/merchant/reviews/:merchantId" },
  { group: "admin", label: "CRM Ops", path: "/admin/crm-ops" },
  { group: "admin", label: "Home Engine", path: "/admin/home-engine" },
  { group: "admin", label: "Map Engine", path: "/admin/map-engine" },
  { group: "admin", label: "Notification Engine", path: "/admin/notification-engine" },
  { group: "merchant", label: "Merchant Inventory", path: "/merchant/inventory/:merchantId" },
  { group: "merchant", label: "Merchant Live Control", path: "/merchant/live/:merchantId" },
  { group: "merchant", label: "Merchant Coupons", path: "/merchant/coupons/:merchantId" },
  { group: "admin", label: "Growth Ops", path: "/admin/growth-ops" },
  { group: "public", label: "Notifications", path: "/notifications" },
  { group: "admin", label: "Retention Ops", path: "/admin/retention-ops" },
  { group: "driver", label: "Driver Earnings V2", path: "/driver/earnings-v2" },
  { group: "public", label: "Order Receipt", path: "/order/receipt/:orderId" },
  { group: "merchant", label: "Merchant Analytics", path: "/merchant/analytics/:merchantId" },
  { group: "admin", label: "Operations Launchpad", path: "/admin/operations-launchpad" },
  { group: "merchant", label: "Merchant Customers", path: "/merchant/customers/:merchantId" },
  { group: "admin", label: "Merchant Health", path: "/admin/merchant-health" },
  { group: "wallet", label: "Wallet Top Up", path: "/wallet/top-up" },
  { group: "wallet", label: "Wallet Transfer", path: "/wallet/transfer" },
  { group: "public", label: "Order Refund Request", path: "/order/refund/:orderId" },
  { group: "merchant", label: "Merchant Banner Editor", path: "/merchant/banner-editor/:merchantId" },
  { group: "admin", label: "Driver Monitor", path: "/admin/driver-monitor" },
  { group: "admin", label: "User Lookup", path: "/admin/user-lookup" },
  { group: "admin", label: "Notification Ops", path: "/admin/notification-ops" },
  { group: "admin", label: "Finance Summary", path: "/admin/finance-summary" },
  { group: "public", label: "Spending Insights", path: "/me/spending-insights" },
  { group: "admin", label: "Platform Alerts", path: "/admin/platform-alerts" },
  { group: "public", label: "Address Book", path: "/me/address-book" },
  { group: "merchant", label: "Business Summary", path: "/merchant/business-summary/:merchantId" },
  { group: "admin", label: "Order Watch", path: "/admin/order-watch" },
  { group: "public", label: "Loyalty History", path: "/me/loyalty-history" },
  { group: "admin", label: "Search Watch", path: "/admin/search-watch" },
  { group: "public", label: "Active Orders", path: "/my-orders/active" },
  { group: "merchant", label: "Merchant Closing Mode", path: "/merchant/closing-mode/:merchantId" },
  { group: "admin", label: "Merchant Promo Watch", path: "/admin/merchant-promo-watch" },
  { group: "driver", label: "Driver Earnings Summary", path: "/driver/earnings-summary" },
  { group: "admin", label: "Refund Watch", path: "/admin/refund-watch" },
  { group: "public", label: "Support Shortcuts", path: "/support/shortcuts" },
  { group: "merchant", label: "Customer Insights", path: "/merchant/customer-insights/:merchantId" },
  { group: "admin", label: "Driver Heatmap", path: "/admin/driver-heatmap" },
  { group: "public", label: "Order Archive", path: "/my-orders/archive" },
  { group: "merchant", label: "Product Performance", path: "/merchant/product-performance/:merchantId" },
  { group: "admin", label: "Wallet Watch", path: "/admin/wallet-watch" },
  { group: "public", label: "Reorder", path: "/reorder" },
  { group: "merchant", label: "Auto Accept Settings", path: "/merchant/auto-accept/:merchantId" },
  { group: "admin", label: "System Health", path: "/admin/system-health" },
  { group: "public", label: "Live Location", path: "/location/live" },
  { group: "driver", label: "Active Missions", path: "/driver/active-missions" },
  { group: "admin", label: "Fraud Detection", path: "/admin/fraud-detection" },
  { group: "public", label: "Saved Cards", path: "/me/saved-cards" },
  { group: "merchant", label: "Inventory Alerts", path: "/merchant/inventory-alerts/:merchantId" },
  { group: "admin", label: "Order Timeline", path: "/admin/order-timeline" },
  { group: "public", label: "Quick Help", path: "/me/quick-help" },
  { group: "driver", label: "Driver Shift", path: "/driver/shift" },
  { group: "admin", label: "Merchant Approval Queue", path: "/admin/merchant-approval-queue" },
  { group: "public", label: "Delivery Notes", path: "/me/delivery-notes" },
  { group: "merchant", label: "Staff Access", path: "/merchant/staff-access/:merchantId" },
  { group: "admin", label: "Failed Payments", path: "/admin/failed-payments" },
  { group: "public", label: "Refer a Friend", path: "/me/refer-friend" },
  { group: "driver", label: "Driver Documents", path: "/driver/documents" },
  { group: "admin", label: "Support SLA", path: "/admin/support-sla" },
  { group: "public", label: "Address Selector", path: "/checkout/address-selector" },
  { group: "merchant", label: "Daily Sales", path: "/merchant/daily-sales/:merchantId" },
  { group: "admin", label: "Delivery Incidents", path: "/admin/delivery-incidents" },
  { group: "public", label: "Payment Activity", path: "/me/payment-activity" },
  { group: "driver", label: "Availability Zones", path: "/driver/availability-zones" },
  { group: "admin", label: "Growth Dashboard", path: "/admin/growth-dashboard" },
  { group: "public", label: "Order Receipts", path: "/me/order-receipts" },
  { group: "merchant", label: "Refund Requests", path: "/merchant/refund-requests/:merchantId" },
  { group: "admin", label: "Coupon Oversight", path: "/admin/coupon-oversight" },
  { group: "public", label: "Notification Center", path: "/me/notification-center" },
  { group: "driver", label: "Completed Deliveries", path: "/driver/completed-deliveries" },
  { group: "admin", label: "Active Sessions", path: "/admin/active-sessions" },
  { group: "merchant", label: "Menu Bulk Edit", path: "/merchant/menu-bulk/:merchantId" },
  { group: "admin", label: "Fraud Monitor", path: "/admin/fraud-monitor" },
  { group: "public", label: "Live Tracking", path: "/tracking-live/:orderId" },
  { group: "merchant", label: "Live Orders", path: "/merchant/live-orders/:merchantId" },
  { group: "admin", label: "Activity Heatmap", path: "/admin/heatmap" },
  { group: "public", label: "Quick Reorder", path: "/quick-reorder" },
  { group: "driver", label: "Live Missions", path: "/driver/live-missions" },
  { group: "admin", label: "Realtime Alerts", path: "/admin/realtime-alerts" },
  // FA-FF
  { group: "public", label: "Order Schedule", path: "/checkout/schedule" },
  { group: "merchant", label: "Open/Close", path: "/merchant/open-close/:merchantId" },
  { group: "admin", label: "Retention Dashboard", path: "/admin/retention-dashboard" },
  { group: "public", label: "Promo Wallet", path: "/me/promo-wallet" },
  { group: "driver", label: "Break Mode", path: "/driver/break-mode" },
  { group: "admin", label: "Merchant Performance", path: "/admin/merchant-performance" },
  // FG-FL
  { group: "public", label: "Family Profiles", path: "/me/family-profiles" },
  { group: "merchant", label: "Prep Time", path: "/merchant/prep-time/:merchantId" },
  { group: "admin", label: "Refund Control", path: "/admin/refund-control" },
  { group: "public", label: "Tipping", path: "/checkout/tip" },
  { group: "driver", label: "Acceptance Rate", path: "/driver/acceptance-rate" },
  { group: "admin", label: "Driver Performance", path: "/admin/driver-performance" },
  // FM-FR
  { group: "public", label: "Subscriptions", path: "/me/subscriptions" },
  { group: "merchant", label: "Promo Scheduler", path: "/merchant/promo-scheduler/:merchantId" },
  { group: "admin", label: "Dispute Center", path: "/admin/dispute-center" },
  { group: "public", label: "Favorite Orders", path: "/me/favorite-orders" },
  { group: "driver", label: "Shift Scheduler", path: "/driver/shift-scheduler" },
  { group: "admin", label: "Global Finance", path: "/admin/global-finance" },
  // FS-FX
  { group: "admin", label: "Core Engine", path: "/admin/core-engine" },
  // FY-GD
  { group: "public", label: "Group Order", path: "/checkout/group-order" },
  { group: "merchant", label: "Auto Accept V2", path: "/merchant/auto-accept-v2/:merchantId" },
  { group: "admin", label: "Cashflow Monitor", path: "/admin/cashflow-monitor" },
  { group: "public", label: "Address Book V2", path: "/me/address-book-v2" },
  { group: "driver", label: "Navigation Mode", path: "/driver/navigation-mode" },
  { group: "admin", label: "City Ops", path: "/admin/city-ops" },
  // GE-GJ
  { group: "public", label: "Meal Planner", path: "/me/meal-planner" },
  { group: "merchant", label: "Delivery Zones", path: "/merchant/delivery-zones/:merchantId" },
  { group: "admin", label: "Operator Notes", path: "/admin/operator-notes" },
  { group: "public", label: "Receipt Vault", path: "/me/receipt-vault" },
  { group: "driver", label: "Vehicle Profile", path: "/driver/vehicle-profile" },
  { group: "admin", label: "Network Status", path: "/admin/network-status" },
  // GK-GP
  { group: "public", label: "Shared Wallet", path: "/me/shared-wallet" },
  { group: "admin", label: "SLA Monitor", path: "/admin/sla-monitor" },
  { group: "public", label: "Gift Order", path: "/checkout/gift-order" },
  { group: "admin", label: "Incident Center", path: "/admin/incident-center" },
  // GQ-GV
  { group: "public", label: "Split Bill", path: "/checkout/split-bill" },
  { group: "merchant", label: "Kitchen Display", path: "/merchant/kitchen-display/:merchantId" },
  { group: "admin", label: "Order Audit", path: "/admin/order-audit" },
  { group: "public", label: "Delivery Instructions", path: "/checkout/delivery-instructions" },
  { group: "driver", label: "Daily Target", path: "/driver/daily-target" },
  { group: "admin", label: "Market Expansion", path: "/admin/market-expansion" },
  // GW-HB
  { group: "public", label: "Saved Carts", path: "/me/saved-carts" },
  { group: "merchant", label: "Out of Stock", path: "/merchant/out-of-stock/:merchantId" },
  { group: "admin", label: "Fraud Watch", path: "/admin/fraud-watch" },
  { group: "public", label: "Contactless Delivery", path: "/checkout/contactless" },
  { group: "driver", label: "Hot Zones", path: "/driver/hot-zones" },
  { group: "admin", label: "Demand Forecast", path: "/admin/demand-forecast" },
  // HC-HH
  { group: "public", label: "Auto Repeat", path: "/me/auto-repeat" },
  { group: "merchant", label: "Rush Mode", path: "/merchant/rush-mode/:merchantId" },
  { group: "admin", label: "Refund Queue", path: "/admin/refund-queue" },
  { group: "public", label: "Party Order", path: "/checkout/party-order" },
  { group: "driver", label: "Earnings Breakdown", path: "/driver/earnings-breakdown" },
  { group: "admin", label: "Platform Health", path: "/admin/platform-health" },
  // HI-HN
  { group: "public", label: "Office Lunch", path: "/checkout/office-lunch" },
  { group: "merchant", label: "Delivery Fees", path: "/merchant/delivery-fees/:merchantId" },
  { group: "admin", label: "Driver Compliance", path: "/admin/driver-compliance" },
  { group: "public", label: "Reward Redemption", path: "/me/redeem-rewards" },
  { group: "driver", label: "Fuel Costs", path: "/driver/fuel-costs" },
  { group: "admin", label: "Executive Overview", path: "/admin/executive-overview" },

  { group: "public", label: "Coming Soon", path: "/coming-soon/:slug" },
  { group: "public", label: "City Market", path: "/city-market/:citySlug" },
  { group: "public", label: "City Vertical", path: "/city/:countryCode/:city/:vertical/:locale" },
] as const;
