import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.2";
import { getCorsHeaders } from "../_shared/cors.ts";

serve(async (req) => {
  const cors = getCorsHeaders(req);
  if (req.method === "OPTIONS") return new Response(null, { headers: cors });

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...cors, "Content-Type": "application/json" },
      });
    }

    const anonClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
    );
    const { data: { user } } = await anonClient.auth.getUser(authHeader.replace("Bearer ", ""));
    if (!user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...cors, "Content-Type": "application/json" },
      });
    }

    const url = new URL(req.url);
    const format = url.searchParams.get("format") ?? "csv";
    const fromDate = url.searchParams.get("from") ?? null;
    const toDate = url.searchParams.get("to") ?? null;

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
      { auth: { persistSession: false } },
    );

    let query = supabase
      .from("financial_audit_trail")
      .select("*")
      .eq("user_id", user.id)
      .order("created_at", { ascending: true })
      .limit(50000);

    if (fromDate) query = query.gte("created_at", fromDate);
    if (toDate) query = query.lte("created_at", toDate);

    const { data: entries, error } = await query;
    if (error) {
      return new Response(JSON.stringify({ error: error.message }), {
        status: 500,
        headers: { ...cors, "Content-Type": "application/json" },
      });
    }

    const rows = entries ?? [];

    if (format === "csv") {
      const header = "id,date,type,amount,currency,status,reference_type,reference_id,payment_method,counterparty_id,stripe_intent_id";
      const csvRows = rows.map((r: Record<string, unknown>) =>
        [
          r.id,
          r.created_at,
          r.transaction_type,
          r.amount,
          r.currency,
          r.status,
          r.reference_type ?? "",
          r.reference_id ?? "",
          r.payment_method ?? "",
          r.counterparty_id ?? "",
          r.stripe_payment_intent_id ?? "",
        ].map(v => `"${String(v).replace(/"/g, '""')}"`).join(",")
      );
      const csv = [header, ...csvRows].join("\n");

      return new Response(csv, {
        headers: {
          ...cors,
          "Content-Type": "text/csv; charset=utf-8",
          "Content-Disposition": `attachment; filename="easylocs-audit-trail-${new Date().toISOString().slice(0, 10)}.csv"`,
        },
      });
    }

    const htmlRows = rows.map((r: Record<string, unknown>) =>
      `<tr><td>${r.created_at}</td><td>${r.transaction_type}</td><td>${r.amount} ${r.currency}</td><td>${r.status}</td><td>${r.reference_type ?? ""}</td><td>${r.reference_id ?? ""}</td><td>${r.payment_method ?? ""}</td><td>${r.stripe_payment_intent_id ?? ""}</td></tr>`
    ).join("");

    const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Financial Audit Trail — Easy-Locs</title>
<style>
body{font-family:Arial,sans-serif;margin:20px;font-size:11px}
h1{font-size:16px;color:#1e3a5f}
table{border-collapse:collapse;width:100%}
th,td{border:1px solid #ccc;padding:4px 8px;text-align:left}
th{background:#1e3a5f;color:#fff}
.meta{color:#666;font-size:10px;margin-bottom:12px}
@media print{body{margin:0}button{display:none}}
</style></head><body>
<h1>Financial Audit Trail</h1>
<p class="meta">User: ${user.email} | Exported: ${new Date().toISOString()} | Records: ${rows.length}</p>
<p class="meta">GDPR Art. 30 — Record of Processing Activities | PSD2 Compliance</p>
<table>
<thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Status</th><th>Ref Type</th><th>Ref ID</th><th>Method</th><th>Stripe ID</th></tr></thead>
<tbody>${htmlRows}</tbody>
</table>
<p class="meta" style="margin-top:12px">Generated by Easy-Locs® Compliance Engine. This document is auto-generated and immutable at source.</p>
</body></html>`;

    return new Response(html, {
      headers: {
        ...cors,
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `attachment; filename="easylocs-audit-trail-${new Date().toISOString().slice(0, 10)}.html"`,
      },
    });
  } catch (err) {
    return new Response(
      JSON.stringify({ error: "Audit export failed", detail: String(err) }),
      { status: 500, headers: { ...getCorsHeaders(req), "Content-Type": "application/json" } },
    );
  }
});
