import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.2";
import { getCorsHeaders } from "../_shared/cors.ts";

function escapePdf(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function buildPdfReport(
  rows: Array<Record<string, unknown>>,
  userEmail: string,
): Uint8Array {
  const MARGIN = 50;
  const PAGE_WIDTH = 595;
  const PAGE_HEIGHT = 842;
  const LINE_HEIGHT = 12;
  const FONT_SIZE = 8;
  const HEADER_FONT_SIZE = 14;
  const COL_WIDTHS = [70, 65, 55, 50, 50, 55, 55, 55, 60];
  const HEADERS = ["Date", "Type", "Amount", "Currency", "Status", "Ref Type", "Ref ID", "Method", "Stripe ID"];

  const objects: string[] = [];
  let objectCount = 0;
  const offsets: number[] = [];

  function addObj(content: string): number {
    objectCount++;
    objects.push(content);
    return objectCount;
  }

  const catalogId = addObj("");
  const pagesId = addObj("");

  const pages: number[] = [];
  const contentStreams: number[] = [];
  let currentY = PAGE_HEIGHT - MARGIN;
  let currentPageContent = "";

  function startPage(): void {
    currentY = PAGE_HEIGHT - MARGIN;
    currentPageContent = "";
  }

  function finishPage(): void {
    const streamId = addObj("");
    contentStreams.push(streamId);
    const pageId = addObj("");
    pages.push(pageId);
    const streamContent = `stream\n${currentPageContent}\nendstream`;
    objects[streamId - 1] = `${streamId} 0 obj\n<< /Length ${currentPageContent.length} >>\n${streamContent}\nendobj`;
    objects[pageId - 1] = `${pageId} 0 obj\n<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Contents ${streamId} 0 R /Resources << /Font << /F1 ${objectCount + 1} 0 R >> >> >>\nendobj`;
  }

  function addText(x: number, y: number, size: number, text: string): void {
    currentPageContent += `BT /F1 ${size} Tf ${x} ${y} Td (${escapePdf(text)}) Tj ET\n`;
  }

  function ensureSpace(needed: number): void {
    if (currentY - needed < MARGIN) {
      finishPage();
      startPage();
    }
  }

  startPage();

  addText(MARGIN, currentY, HEADER_FONT_SIZE, "Financial Audit Trail - Easy-Locs");
  currentY -= 20;
  addText(MARGIN, currentY, FONT_SIZE, `User: ${userEmail} | Exported: ${new Date().toISOString()} | Records: ${rows.length}`);
  currentY -= 12;
  addText(MARGIN, currentY, FONT_SIZE, "GDPR Art. 30 - Record of Processing Activities | PSD2 Compliance");
  currentY -= 20;

  let xPos = MARGIN;
  for (let i = 0; i < HEADERS.length; i++) {
    addText(xPos, currentY, FONT_SIZE, HEADERS[i]);
    xPos += COL_WIDTHS[i];
  }
  currentY -= 4;
  currentPageContent += `${MARGIN} ${currentY} m ${PAGE_WIDTH - MARGIN} ${currentY} l S\n`;
  currentY -= LINE_HEIGHT;

  for (const row of rows) {
    ensureSpace(LINE_HEIGHT);
    xPos = MARGIN;
    const dateStr = String(row.created_at ?? "").slice(0, 19);
    const values = [
      dateStr,
      String(row.transaction_type ?? ""),
      String(row.amount ?? ""),
      String(row.currency ?? ""),
      String(row.status ?? ""),
      String(row.reference_type ?? ""),
      String(row.reference_id ?? "").slice(0, 8),
      String(row.payment_method ?? ""),
      String(row.stripe_payment_intent_id ?? "").slice(0, 10),
    ];
    for (let i = 0; i < values.length; i++) {
      const truncated = values[i].slice(0, Math.floor(COL_WIDTHS[i] / 4));
      addText(xPos, currentY, FONT_SIZE, truncated);
      xPos += COL_WIDTHS[i];
    }
    currentY -= LINE_HEIGHT;
  }

  currentY -= 10;
  ensureSpace(20);
  addText(MARGIN, currentY, 6, "Generated by Easy-Locs Compliance Engine. This document is auto-generated and immutable at source.");

  finishPage();

  const fontId = addObj(`${objectCount + 1} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj`);

  for (const pageId of pages) {
    const pageObj = objects[pageId - 1];
    objects[pageId - 1] = pageObj.replace(`${objectCount} 0 R`, `${fontId} 0 R`);
  }

  objects[pagesId - 1] = `${pagesId} 0 obj\n<< /Type /Pages /Kids [${pages.map(p => `${p} 0 R`).join(" ")}] /Count ${pages.length} >>\nendobj`;
  objects[catalogId - 1] = `${catalogId} 0 obj\n<< /Type /Catalog /Pages ${pagesId} 0 R >>\nendobj`;

  let pdfContent = "%PDF-1.4\n";
  for (let i = 0; i < objects.length; i++) {
    offsets.push(pdfContent.length);
    pdfContent += objects[i] + "\n";
  }

  const xrefOffset = pdfContent.length;
  pdfContent += `xref\n0 ${objectCount + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) {
    pdfContent += `${String(offset).padStart(10, "0")} 00000 n \n`;
  }
  pdfContent += `trailer\n<< /Size ${objectCount + 1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return new TextEncoder().encode(pdfContent);
}

serve(async (req) => {
  const cors = getCorsHeaders(req);
  if (req.method === "OPTIONS") return new Response(null, { headers: cors });

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...cors, "Content-Type": "application/json" },
      });
    }

    const anonClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
    );
    const { data: { user } } = await anonClient.auth.getUser(authHeader.replace("Bearer ", ""));
    if (!user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...cors, "Content-Type": "application/json" },
      });
    }

    const url = new URL(req.url);
    const format = url.searchParams.get("format") ?? "csv";
    const fromDate = url.searchParams.get("from") ?? null;
    const toDate = url.searchParams.get("to") ?? null;

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
      { auth: { persistSession: false } },
    );

    let query = supabase
      .from("financial_audit_trail")
      .select("*")
      .eq("user_id", user.id)
      .order("created_at", { ascending: true })
      .limit(50000);

    if (fromDate) query = query.gte("created_at", fromDate);
    if (toDate) query = query.lte("created_at", toDate);

    const { data: entries, error } = await query;
    if (error) {
      return new Response(JSON.stringify({ error: error.message }), {
        status: 500,
        headers: { ...cors, "Content-Type": "application/json" },
      });
    }

    const rows = entries ?? [];
    const dateStr = new Date().toISOString().slice(0, 10);

    if (format === "csv") {
      const header = "id,date,type,amount,currency,status,reference_type,reference_id,payment_method,counterparty_id,stripe_intent_id";
      const csvRows = rows.map((r: Record<string, unknown>) =>
        [
          r.id,
          r.created_at,
          r.transaction_type,
          r.amount,
          r.currency,
          r.status,
          r.reference_type ?? "",
          r.reference_id ?? "",
          r.payment_method ?? "",
          r.counterparty_id ?? "",
          r.stripe_payment_intent_id ?? "",
        ].map(v => `"${String(v).replace(/"/g, '""')}"`).join(",")
      );
      const csv = [header, ...csvRows].join("\n");

      return new Response(csv, {
        headers: {
          ...cors,
          "Content-Type": "text/csv; charset=utf-8",
          "Content-Disposition": `attachment; filename="easylocs-audit-trail-${dateStr}.csv"`,
        },
      });
    }

    if (format === "pdf") {
      const pdfBytes = buildPdfReport(rows, user.email ?? "unknown");

      return new Response(pdfBytes, {
        headers: {
          ...cors,
          "Content-Type": "application/pdf",
          "Content-Disposition": `attachment; filename="easylocs-audit-trail-${dateStr}.pdf"`,
        },
      });
    }

    const htmlRows = rows.map((r: Record<string, unknown>) =>
      `<tr><td>${r.created_at}</td><td>${r.transaction_type}</td><td>${r.amount} ${r.currency}</td><td>${r.status}</td><td>${r.reference_type ?? ""}</td><td>${r.reference_id ?? ""}</td><td>${r.payment_method ?? ""}</td><td>${r.stripe_payment_intent_id ?? ""}</td></tr>`
    ).join("");

    const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Financial Audit Trail — Easy-Locs</title>
<style>
body{font-family:Arial,sans-serif;margin:20px;font-size:11px}
h1{font-size:16px;color:#1e3a5f}
table{border-collapse:collapse;width:100%}
th,td{border:1px solid #ccc;padding:4px 8px;text-align:left}
th{background:#1e3a5f;color:#fff}
.meta{color:#666;font-size:10px;margin-bottom:12px}
@media print{body{margin:0}button{display:none}}
</style></head><body>
<h1>Financial Audit Trail</h1>
<p class="meta">User: ${user.email} | Exported: ${new Date().toISOString()} | Records: ${rows.length}</p>
<p class="meta">GDPR Art. 30 — Record of Processing Activities | PSD2 Compliance</p>
<table>
<thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Status</th><th>Ref Type</th><th>Ref ID</th><th>Method</th><th>Stripe ID</th></tr></thead>
<tbody>${htmlRows}</tbody>
</table>
<p class="meta" style="margin-top:12px">Generated by Easy-Locs® Compliance Engine. This document is auto-generated and immutable at source.</p>
</body></html>`;

    return new Response(html, {
      headers: {
        ...cors,
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `attachment; filename="easylocs-audit-trail-${dateStr}.html"`,
      },
    });
  } catch (err) {
    return new Response(
      JSON.stringify({ error: "Audit export failed", detail: String(err) }),
      { status: 500, headers: { ...getCorsHeaders(req), "Content-Type": "application/json" } },
    );
  }
});
