/**
 * Mock Dubai restaurant data for auto-import.
 * Simulates data from Google Maps, Deliveroo, Careem sources.
 */

export interface DubaiRestaurantSeed {
  merchant_name: string;
  contact_name: string;
  phone: string;
  email: string;
  city: string;
  area: string;
  cuisine_type: string;
  source: "google_maps" | "deliveroo" | "careem";
  source_external_id: string;
  menu_items: { name: string; price: number; description?: string; category?: string }[];
}

export const DUBAI_RESTAURANTS: DubaiRestaurantSeed[] = [
  {
    merchant_name: "Al Mallah",
    contact_name: "Ahmed K.",
    phone: "+97142981119",
    email: "almallah@email.ae",
    city: "Dubai",
    area: "Al Dhiyafah Street, Satwa",
    cuisine_type: "Lebanese",
    source: "google_maps",
    source_external_id: "gm_almallah_satwa",
    menu_items: [
      { name: "Shawarma Chicken", price: 12, category: "Wraps" },
      { name: "Shawarma Meat", price: 14, category: "Wraps" },
      { name: "Falafel Plate", price: 18, category: "Plates" },
      { name: "Hummus", price: 10, category: "Mezzeh" },
      { name: "Fresh Juice Mix", price: 15, category: "Drinks" },
    ],
  },
  {
    merchant_name: "Ravi Restaurant",
    contact_name: "Ravi P.",
    phone: "+97143311353",
    email: "ravi@email.ae",
    city: "Dubai",
    area: "Satwa",
    cuisine_type: "Pakistani",
    source: "google_maps",
    source_external_id: "gm_ravi_satwa",
    menu_items: [
      { name: "Butter Chicken", price: 22, category: "Curries" },
      { name: "Biryani Chicken", price: 20, category: "Rice" },
      { name: "Naan Bread", price: 3, category: "Bread" },
      { name: "Dal Tadka", price: 15, category: "Curries" },
    ],
  },
  {
    merchant_name: "Karak House",
    contact_name: "Fatima S.",
    phone: "+97145551234",
    email: "karakhouse@email.ae",
    city: "Dubai",
    area: "JLT",
    cuisine_type: "Café",
    source: "deliveroo",
    source_external_id: "dlv_karakhouse_jlt",
    menu_items: [
      { name: "Karak Tea", price: 5, category: "Drinks" },
      { name: "Cheese Paratha", price: 12, category: "Snacks" },
      { name: "Club Sandwich", price: 18, category: "Sandwiches" },
    ],
  },
  {
    merchant_name: "Bu Qtair",
    contact_name: "Mohammed R.",
    phone: "+97142223344",
    email: "buqtair@email.ae",
    city: "Dubai",
    area: "Jumeirah 1",
    cuisine_type: "Seafood",
    source: "google_maps",
    source_external_id: "gm_buqtair_jumeirah",
    menu_items: [
      { name: "Fried Hammour", price: 35, category: "Fish" },
      { name: "Shrimp Plate", price: 40, category: "Seafood" },
      { name: "Rice & Fish Combo", price: 30, category: "Combos" },
    ],
  },
  {
    merchant_name: "Zaroob",
    contact_name: "Hasan M.",
    phone: "+97143889900",
    email: "zaroob@email.ae",
    city: "Dubai",
    area: "Sheikh Zayed Road",
    cuisine_type: "Levantine",
    source: "deliveroo",
    source_external_id: "dlv_zaroob_szr",
    menu_items: [
      { name: "Manakish Zaatar", price: 14, category: "Manakish" },
      { name: "Knafeh", price: 20, category: "Desserts" },
      { name: "Fatteh", price: 22, category: "Plates" },
      { name: "Lemonade Mint", price: 12, category: "Drinks" },
    ],
  },
  {
    merchant_name: "Operation Falafel",
    contact_name: "Sara A.",
    phone: "+97145556677",
    email: "opfalafel@email.ae",
    city: "Dubai",
    area: "Business Bay",
    cuisine_type: "Street Food",
    source: "careem",
    source_external_id: "crm_opfalafel_bb",
    menu_items: [
      { name: "Falafel Wrap", price: 16, category: "Wraps" },
      { name: "Halloumi Wrap", price: 18, category: "Wraps" },
      { name: "Loaded Fries", price: 20, category: "Sides" },
    ],
  },
  {
    merchant_name: "Arabian Tea House",
    contact_name: "Khalid N.",
    phone: "+97143535566",
    email: "arabteahouse@email.ae",
    city: "Dubai",
    area: "Al Fahidi, Bur Dubai",
    cuisine_type: "Emirati",
    source: "google_maps",
    source_external_id: "gm_arabteahouse_fahidi",
    menu_items: [
      { name: "Machboos Chicken", price: 35, category: "Traditional" },
      { name: "Luqaimat", price: 18, category: "Desserts" },
      { name: "Regag Bread", price: 12, category: "Bread" },
      { name: "Karak Chai", price: 8, category: "Drinks" },
    ],
  },
  {
    merchant_name: "Salt Burger",
    contact_name: "Omar T.",
    phone: "+97145009988",
    email: "saltburger@email.ae",
    city: "Dubai",
    area: "Kite Beach, Jumeirah",
    cuisine_type: "Burgers",
    source: "deliveroo",
    source_external_id: "dlv_salt_kitebeach",
    menu_items: [
      { name: "Classic Salt Burger", price: 32, category: "Burgers" },
      { name: "Truffle Fries", price: 22, category: "Sides" },
      { name: "Soft Serve", price: 15, category: "Desserts" },
    ],
  },
  {
    merchant_name: "Al Ustad Special Kabab",
    contact_name: "Ali Z.",
    phone: "+97143977444",
    email: "alustad@email.ae",
    city: "Dubai",
    area: "Al Fahidi, Bur Dubai",
    cuisine_type: "Iranian",
    source: "google_maps",
    source_external_id: "gm_alustad_fahidi",
    menu_items: [
      { name: "Kubideh Kebab", price: 28, category: "Kebabs" },
      { name: "Joojeh Kebab", price: 32, category: "Kebabs" },
      { name: "Saffron Rice", price: 12, category: "Rice" },
    ],
  },
  {
    merchant_name: "Logma",
    contact_name: "Noura B.",
    phone: "+97145551122",
    email: "logma@email.ae",
    city: "Dubai",
    area: "Dubai Mall",
    cuisine_type: "Emirati Fusion",
    source: "careem",
    source_external_id: "crm_logma_dubaimall",
    menu_items: [
      { name: "Chebab Pancakes", price: 25, category: "Breakfast" },
      { name: "Wagyu Slider", price: 38, category: "Mains" },
      { name: "Date Milkshake", price: 22, category: "Drinks" },
    ],
  },
  {
    merchant_name: "Tresind Studio",
    contact_name: "Chef Himanshu",
    phone: "+97142085333",
    email: "tresind@email.ae",
    city: "Dubai",
    area: "DIFC",
    cuisine_type: "Indian Fine Dining",
    source: "google_maps",
    source_external_id: "gm_tresind_difc",
    menu_items: [
      { name: "Tasting Menu 10 Course", price: 650, category: "Tasting" },
      { name: "Tandoori Prawns", price: 120, category: "Starters" },
    ],
  },
  {
    merchant_name: "3 Fils",
    contact_name: "Manager JBR",
    phone: "+97143338833",
    email: "3fils@email.ae",
    city: "Dubai",
    area: "Jumeirah Fishing Harbour",
    cuisine_type: "Japanese-Peruvian",
    source: "deliveroo",
    source_external_id: "dlv_3fils_harbour",
    menu_items: [
      { name: "Yellowtail Sashimi", price: 65, category: "Raw" },
      { name: "Miso Black Cod", price: 95, category: "Mains" },
      { name: "Truffle Edamame", price: 35, category: "Starters" },
    ],
  },
  {
    merchant_name: "Pinza",
    contact_name: "Marco L.",
    phone: "+97142227788",
    email: "pinza@email.ae",
    city: "Dubai",
    area: "Motor City",
    cuisine_type: "Italian",
    source: "careem",
    source_external_id: "crm_pinza_motorcity",
    menu_items: [
      { name: "Margherita Pinza", price: 38, category: "Pinza" },
      { name: "Truffle Pinza", price: 55, category: "Pinza" },
      { name: "Tiramisu", price: 28, category: "Desserts" },
    ],
  },
  {
    merchant_name: "Bait Al Mandi",
    contact_name: "Youssef H.",
    phone: "+97143331199",
    email: "baitmandi@email.ae",
    city: "Dubai",
    area: "Deira",
    cuisine_type: "Yemeni",
    source: "google_maps",
    source_external_id: "gm_baitmandi_deira",
    menu_items: [
      { name: "Lamb Mandi", price: 45, category: "Mandi" },
      { name: "Chicken Mandi", price: 35, category: "Mandi" },
      { name: "Salta Soup", price: 18, category: "Soups" },
    ],
  },
  {
    merchant_name: "Reif Japanese Kushiyaki",
    contact_name: "Reif O.",
    phone: "+97142445566",
    email: "reif@email.ae",
    city: "Dubai",
    area: "DIFC",
    cuisine_type: "Japanese",
    source: "deliveroo",
    source_external_id: "dlv_reif_difc",
    menu_items: [
      { name: "Chicken Tsukune", price: 28, category: "Skewers" },
      { name: "Wagyu Kushiyaki", price: 65, category: "Skewers" },
      { name: "Matcha Crème Brûlée", price: 35, category: "Desserts" },
    ],
  },
  {
    merchant_name: "Allo Beirut",
    contact_name: "Rami J.",
    phone: "+97142667788",
    email: "allobeirut@email.ae",
    city: "Dubai",
    area: "JBR",
    cuisine_type: "Lebanese",
    source: "careem",
    source_external_id: "crm_allobeirut_jbr",
    menu_items: [
      { name: "Mixed Grill", price: 55, category: "Grills" },
      { name: "Tabbouleh", price: 18, category: "Salads" },
      { name: "Fattoush", price: 16, category: "Salads" },
      { name: "Chicken Shawarma Plate", price: 28, category: "Plates" },
    ],
  },
  {
    merchant_name: "Saffron Lounge",
    contact_name: "Priya D.",
    phone: "+97143889911",
    email: "saffronlounge@email.ae",
    city: "Dubai",
    area: "Marina Walk",
    cuisine_type: "Indian",
    source: "google_maps",
    source_external_id: "gm_saffron_marina",
    menu_items: [
      { name: "Paneer Tikka", price: 30, category: "Starters" },
      { name: "Lamb Rogan Josh", price: 45, category: "Curries" },
      { name: "Garlic Naan", price: 8, category: "Bread" },
    ],
  },
  {
    merchant_name: "Pickl",
    contact_name: "Steve F.",
    phone: "+97142008800",
    email: "pickl@email.ae",
    city: "Dubai",
    area: "JBR",
    cuisine_type: "Burgers",
    source: "deliveroo",
    source_external_id: "dlv_pickl_jbr",
    menu_items: [
      { name: "Classic Pickl", price: 30, category: "Burgers" },
      { name: "Chicken Pickl", price: 28, category: "Burgers" },
      { name: "Cheese Fries", price: 18, category: "Sides" },
    ],
  },
  {
    merchant_name: "Sikka Café",
    contact_name: "Mariam K.",
    phone: "+97143556699",
    email: "sikkacafe@email.ae",
    city: "Dubai",
    area: "Al Fahidi",
    cuisine_type: "Emirati",
    source: "google_maps",
    source_external_id: "gm_sikka_fahidi",
    menu_items: [
      { name: "Balaleet", price: 22, category: "Breakfast" },
      { name: "Harees", price: 28, category: "Traditional" },
      { name: "Saffron Latte", price: 18, category: "Drinks" },
    ],
  },
  {
    merchant_name: "Mama'esh",
    contact_name: "Lina S.",
    phone: "+97142339900",
    email: "mamaesh@email.ae",
    city: "Dubai",
    area: "City Walk",
    cuisine_type: "Street Food",
    source: "careem",
    source_external_id: "crm_mamaesh_citywalk",
    menu_items: [
      { name: "Cheese Manakish", price: 16, category: "Manakish" },
      { name: "Lamb Arayes", price: 22, category: "Grills" },
      { name: "Nutella Kunafa", price: 20, category: "Desserts" },
    ],
  },
];
