export const CANONICAL_EVENTS = {
  IDENTITY_CREATED: "identity:created",
  IDENTITY_UPDATED: "identity:updated",
  IDENTITY_VERIFIED: "identity:verified",
  IDENTITY_SESSION_RESTORED: "identity:session_restored",
  IDENTITY_LOGOUT: "identity:logout",

  ORG_CREATED: "org:created",
  ORG_UPDATED: "org:updated",
  ORG_VERIFIED: "org:verified",

  LISTING_CREATED: "listing:created",
  LISTING_UPDATED: "listing:updated",
  LISTING_PUBLISHED: "listing:published",
  LISTING_PAUSED: "listing:paused",
  LISTING_UNPUBLISHED: "listing:unpublished",
  LISTING_SOLD: "listing:sold",
  LISTING_EXPIRED: "listing:expired",
  LISTING_DELETED: "listing:deleted",

  AVAILABILITY_UPDATED: "availability:updated",
  AVAILABILITY_BLOCKED: "availability:blocked",

  CART_UPDATED: "cart:updated",
  CART_CHECKED_OUT: "cart:checked_out",
  CART_ABANDONED: "cart:abandoned",

  TRANSACTION_CREATED: "transaction:created",
  TRANSACTION_CONFIRMED: "transaction:confirmed",
  TRANSACTION_COMPLETED: "transaction:completed",
  TRANSACTION_CANCELLED: "transaction:cancelled",
  TRANSACTION_FAILED: "transaction:failed",
  TRANSACTION_REFUNDED: "transaction:refunded",

  PAYMENT_INITIATED: "payment:initiated",
  PAYMENT_AUTHORIZED: "payment:authorized",
  PAYMENT_CAPTURED: "payment:captured",
  PAYMENT_SETTLED: "payment:settled",
  PAYMENT_FAILED: "payment:failed",
  PAYMENT_REFUNDED: "payment:refunded",

  WALLET_TOP_UP: "wallet:top_up",
  WALLET_BALANCE_UPDATED: "wallet:balance_updated",
  WALLET_PAYMENT_COMPLETED: "wallet:payment_completed",
  WALLET_PAYMENT_FAILED: "wallet:payment_failed",
  WALLET_PAYMENT_SUCCESS: "wallet:payment_success",
  WALLET_TRANSFER_COMPLETED: "wallet:transfer_completed",
  WALLET_TRANSFER_SENT: "wallet:transfer_sent",
  WALLET_TRANSACTION_CREATED: "wallet:transaction_created",
  WALLET_PAYMENT_REQUESTED: "wallet:payment_requested",
  WALLET_LOCS_PURCHASED: "wallet:locs_purchased",
  WALLET_RECEIPT_GENERATED: "wallet:receipt_generated",
  WALLET_COMMISSION_SPLIT: "wallet:commission_split",

  ORBIT_MESSAGE_SENT: "orbit:message_sent",
  ORBIT_MESSAGE_RECEIVED: "orbit:message_received",
  ORBIT_MESSAGE_READ: "orbit:message_read",
  ORBIT_THREAD_CREATED: "orbit:thread_created",
  ORBIT_THREAD_UPDATED: "orbit:thread_updated",
  ORBIT_CALL_STARTED: "orbit:call_started",
  ORBIT_CALL_ENDED: "orbit:call_ended",
  ORBIT_PROFILE_UPDATED: "orbit:profile_updated",
  ORBIT_NOTIFICATION_CREATED: "orbit:notification_created",
  ORBIT_PRESENCE_CHANGED: "orbit:presence_changed",
  ORBIT_UNREAD_CORRECTED: "orbit:unread_corrected",
  ORBIT_FORCE_RELOAD: "orbit:force_reload",

  MARKETPLACE_LISTING_PUBLISHED: "marketplace:listing_published",
  MARKETPLACE_LISTING_PAUSED: "marketplace:listing_paused",
  MARKETPLACE_LISTING_SHARED: "marketplace:listing_shared",
  MARKETPLACE_BOOKING_CREATED: "marketplace:booking_created",
  MARKETPLACE_BOOKING_CONFIRMED: "marketplace:booking_confirmed",
  MARKETPLACE_BOOKING_PAID: "marketplace:booking_paid",
  MARKETPLACE_BOOKING_COMPLETED: "marketplace:booking_completed",
  MARKETPLACE_BOOKING_CANCELLED: "marketplace:booking_cancelled",
  MARKETPLACE_REVIEW_SUBMITTED: "marketplace:review_submitted",
  MARKETPLACE_CONTACT_OPENED: "marketplace:contact_opened",
  MARKETPLACE_PROVIDER_WENT_LIVE: "marketplace:provider_went_live",
  MARKETPLACE_PROVIDER_WENT_OFFLINE: "marketplace:provider_went_offline",
  MARKETPLACE_VENTE_COMPLETED: "marketplace:vente_completed",
  MARKETPLACE_STOCK_UPDATED: "marketplace:stock_updated",

  STOREFRONT_ORDER_PLACED: "storefront:order_placed",
  STOREFRONT_ORDER_PAID: "storefront:order_paid",
  STOREFRONT_ORDER_SHIPPED: "storefront:order_shipped",
  STOREFRONT_ORDER_COMPLETED: "storefront:order_completed",
  STOREFRONT_ORDER_CANCELLED: "storefront:order_cancelled",
  STOREFRONT_CART_UPDATED: "storefront:cart_updated",

  DELIVERY_DISPATCHED: "delivery:dispatched",
  DELIVERY_DRIVER_ASSIGNED: "delivery:driver_assigned",
  DELIVERY_PICKUP_ARRIVED: "delivery:pickup_arrived",
  DELIVERY_PICKED_UP: "delivery:picked_up",
  DELIVERY_IN_PROGRESS: "delivery:in_progress",
  DELIVERY_DELIVERED: "delivery:delivered",
  DELIVERY_COMPLETED: "delivery:completed",
  DELIVERY_FAILED: "delivery:failed",
  DELIVERY_VALIDATED: "delivery:validated",

  PROPERTY_UNIT_CREATED: "property:unit_created",
  PROPERTY_PUBLISHED_TO_MARKETPLACE: "property:published_to_marketplace",

  PM_LEASE_CREATED: "pm:lease_created",
  PM_LEASE_ACTIVATED: "pm:lease_activated",
  PM_RENT_CALL_CREATED: "pm:rent_call_created",
  PM_PAYMENT_RECEIVED: "pm:payment_received",
  PM_RECEIPT_GENERATED: "pm:receipt_generated",
  PM_INTERVENTION_CREATED: "pm:intervention_created",
  PM_DOCUMENT_SHARED: "pm:document_shared",

  RADAR_LOCATION_SHARED: "radar:location_shared",
  RADAR_PIN_SELECTED: "radar:pin_selected",
  RADAR_ENTITY_SELECTED: "radar:entity_selected",
  RADAR_GEO_UPDATED: "radar:geo_updated",

  DASHBOARD_REFRESH: "dashboard:refresh",
  DASHBOARD_COUNTERS_REFRESH: "dashboard:counters_refresh",

  DEAL_CREATED: "deal:created",
  DEAL_OFFER_SENT: "deal:offer_sent",
  DEAL_ACCEPTED: "deal:accepted",
  DEAL_CANCELLED: "deal:cancelled",

  TRACKING_STARTED: "tracking:started",
  TRACKING_POSITION_UPDATED: "tracking:position_updated",
  TRACKING_STATUS_CHANGED: "tracking:status_changed",
  TRACKING_COMPLETED: "tracking:completed",

  SYSTEM_CURRENCY_CHANGED: "system:currency_changed",
  SYSTEM_SYNC_COMPLETED: "system:sync_completed",
  SYSTEM_ONLINE_RECOVERED: "system:online_recovered",

  ONBOARDING_STARTED: "onboarding:started",
  ONBOARDING_STEP_COMPLETED: "onboarding:step_completed",
  ONBOARDING_COMPLETED: "onboarding:completed",
  ONBOARDING_FAILED: "onboarding:failed",

  IMPORT_STARTED: "import:started",
  IMPORT_COMPLETED: "import:completed",
  IMPORT_FAILED: "import:failed",

  PUBLISH_GATE_PASSED: "publish:gate_passed",
  PUBLISH_GATE_BLOCKED: "publish:gate_blocked",

  SUPPORT_TICKET_CREATED: "support:ticket_created",
  SUPPORT_TICKET_RESOLVED: "support:ticket_resolved",

  NOTIFICATION_CREATED: "notification:created",
  NOTIFICATION_READ: "notification:read",

  ENGINE_BOOTED: "engine:orchestrator:booted",
  ENGINE_STOPPED: "engine:stopped",
  ENGINE_HEALTH_CRASH: "engine:health:crash",

  REPAIR_COMPLETED: "repair:pipeline:completed",

  MARKETPLACE_RESERVATION_CREATED: "marketplace:reservation_created",
  MARKETPLACE_AVAILABILITY_UPDATED: "marketplace:availability_updated",

  ORBIT_SESSION_RESTORED: "orbit:session_restored",
  ORBIT_MEDIA_ATTACHED: "orbit:media_attached",

  LISTING_VIEWED: "listing:viewed",

  STOREFRONT_LOYALTY_EARNED: "storefront:loyalty_earned",
  STOREFRONT_GROWTH_MILESTONE: "storefront:growth_milestone",

  KYC_STATUS_CHANGED: "kyc:status_changed",
  COMPLIANCE_AML_ALERT: "compliance:aml_alert",

  ADMIN_AUDIT_LOGGED: "admin:audit_logged",
  ADMIN_USER_ACTION: "admin:user_action",

  SUPPORT_TICKET_ESCALATED: "support:ticket_escalated",

  MODERATION_ACTION_TAKEN: "moderation:action_taken",
  MODERATION_CONTENT_FLAGGED: "moderation:content_flagged",

  SLA_WARNING: "sla:warning",
  SLA_BREACHED: "sla:breached",
  SLA_ESCALATED: "sla:escalated",

  PROPERTY_DEVICE_STATE_CHANGED: "property:device_state_changed",
  PROPERTY_ACCESS_GRANTED: "property:access_granted",
  PROPERTY_AUTOMATION_TRIGGERED: "property:automation_triggered",

  AUTOMATION_WORKFLOW_STARTED: "automation:workflow_started",
  AUTOMATION_WORKFLOW_COMPLETED: "automation:workflow_completed",
  AUTOMATION_WORKFLOW_FAILED: "automation:workflow_failed",

  TENANT_CREATED: "tenant:created",
  TENANT_PLAN_UPGRADED: "tenant:plan_upgraded",
  TENANT_MEMBER_INVITED: "tenant:member_invited",
  TENANT_QUOTA_WARNING: "tenant:quota_warning",

  API_REQUEST_COMPLETED: "api:request_completed",
  API_RATE_LIMIT_HIT: "api:rate_limit_hit",
  API_WEBHOOK_DELIVERED: "api:webhook_delivered",

  UI_INTERACTION_PERFORMED: "ui:interaction_performed",
  UI_GESTURE_DETECTED: "ui:gesture_detected",
  UI_PANEL_CHANGED: "ui:panel_changed",

  ORBIT_PROFILE_LOADED: "orbit:profile_loaded",
  ORBIT_MESSAGE_EDITED: "orbit:message_edited_optimistic",
  ORBIT_MESSAGE_DELETED: "orbit:message_deleted",
  ORBIT_IDENTITY_UPDATED: "orbit:identity_updated",
  ORBIT_GROUP_UPDATED: "orbit:group_updated",
  ORBIT_GROUP_CREATED: "orbit:group_created",
  ORBIT_EPHEMERAL_TIMER_CHANGED: "orbit:ephemeral_timer_changed",
  ORBIT_CONTACTS_UPDATED: "orbit:contacts_updated",

  MEDIA_VIEWER_OPEN: "media:viewer_open",
  MEDIA_VIEWER_CLOSE: "media:viewer_close",
  LOCATION_LIVE_UPDATE: "location:live_update",
  LOCATION_LIVE_STOPPED: "location:live_stopped",

  SYSTEM_MODULE_STATUS_CHANGED: "system:module_status_changed",
  SYSTEM_SYNC_REQUESTED: "system:sync_requested",
  SYSTEM_USER_ONLINE: "system:user_online",
  SYSTEM_MEMORY_PRESSURE: "system:memory_pressure",
  SYSTEM_PIPELINE_COMPLETED: "system:pipeline_completed",
  SYSTEM_PIPELINE_ERROR: "system:pipeline_error",
  SYSTEM_STALE_QUERIES_DETECTED: "system:stale_queries_detected",

  BOOKING_REQUESTED: "booking:requested",
  BOOKING_PAYMENT_REQUIRED: "booking:payment_required",
  BOOKING_CONFIRMATION_REQUIRED: "booking:confirmation_required",
  BOOKING_CONFIRMED: "booking:confirmed",
  BOOKING_CANCELLED: "booking:cancelled",
  BOOKING_COMPLETED: "booking:completed",
  BOOKING_CREATED: "booking:created",

  CALL_STARTED: "call:started",
  CALL_ENDED: "call:ended",
  CALL_REQUEST: "call:request",

  CAMERA_OPENED: "camera:opened",
  CAMERA_CLOSED: "camera:closed",

  CONTACT_OPENED: "contact:opened",
  CONVERSATION_CREATED: "conversation:created",
  MESSAGE_SENT: "message:sent",
  MESSAGE_CREATED_OPTIMISTIC: "message:created_optimistic",
  MESSAGE_PERSISTED: "message:persisted",
  MESSAGE_RECONCILED: "message:reconciled",
  MESSAGE_FAILED: "message:failed",

  GEO_PERMISSION_CHANGED: "geo:permission_changed",
  GEO_POSITION_UPDATED: "geo:position_updated",

  QR_SCAN_STARTED: "qr:scan_started",
  QR_SCAN_DECODED: "qr:scan_decoded",
  QR_SCAN_FAILED: "qr:scan_failed",
  QR_SCAN_EXPIRED: "qr:scan_expired",
  QR_RESOLVE_STARTED: "qr:resolve_started",
  QR_RESOLVE_COMPLETED: "qr:resolve_completed",
  QR_PAYMENT_INITIATED: "qr:payment_initiated",
  QR_PAYMENT_COMPLETED: "qr:payment_completed",
  QR_PAYMENT_FAILED: "qr:payment_failed",
  QR_NAVIGATION: "qr:navigation",

  ATTACHMENT_GALLERY_SAVED: "attachment:gallery_saved",
  ATTACHMENT_GALLERY_FAILED: "attachment:gallery_failed",
  ATTACHMENT_PREVIEW_READY: "attachment:preview_ready",
  ATTACHMENT_UPLOADED: "attachment:uploaded",
  ATTACHMENT_RECONCILED: "attachment:reconciled",

  ORBIT_MEDIA_UPLOAD_COMPLETED: "orbit:media_upload_completed",
  ORBIT_VOICE_UPLOAD_COMPLETED: "orbit:voice_upload_completed",
  ORBIT_PAYMENT_RECEIVED: "orbit:payment_received",

  RADAR_OPEN_LOCATION: "radar:open_location",
  STORY_RADAR_REVOKE: "story:radar_revoke",

  ORDER_STATUS_CHANGED: "order:status_changed",
  PAYMENT_INTENT_CREATED: "payment:intent_created",

  COMMERCE_ORDER_CREATED: "commerce:order_created",
  COMMERCE_ORDER_VALIDATED: "commerce:order_validated",
  COMMERCE_ORDER_CANCELLED: "commerce:order_cancelled",
  COMMERCE_PAYMENT_AUTHORIZED: "commerce:payment_authorized",
  COMMERCE_PAYMENT_CAPTURED: "commerce:payment_captured",
  COMMERCE_PAYMENT_SETTLED: "commerce:payment_settled",
  COMMERCE_PAYMENT_REVERSED: "commerce:payment_reversed",
  COMMERCE_DRIVER_ASSIGNED: "commerce:driver_assigned",
  COMMERCE_INTENT_PREPARED: "commerce:intent_prepared",

  DISPATCH_JOB_CREATED: "dispatch:job_created",
  DISPATCH_OFFER_SENT: "dispatch:offer_sent",
  DISPATCH_BROADCAST_STARTED: "dispatch:broadcast_started",
  DISPATCH_DRIVER_ACCEPTED: "dispatch:driver_accepted",
  DISPATCH_DRIVER_DECLINED: "dispatch:driver_declined",
  DISPATCH_DRIVER_ASSIGNED: "dispatch:driver_assigned",

  STOREFRONT_REVIEW_POSTED: "storefront:review_posted",
  STOREFRONT_DEAL_ACCEPTED: "storefront:deal_accepted",
  STOREFRONT_DEAL_CONVERTED: "storefront:deal_converted",
  STOREFRONT_STOCK_LOW: "storefront:stock_low",
  STOREFRONT_TRUST_UPDATED: "storefront:trust_updated",
  STOREFRONT_RISK_FLAGGED: "storefront:risk_flagged",
  STOREFRONT_CRM_UPDATED: "storefront:crm_updated",
  STOREFRONT_DELIVERY_DISPATCHED: "storefront:delivery_dispatched",
  STOREFRONT_RETURN_REQUESTED: "storefront:return_requested",
  STOREFRONT_RETURN_PROCESSED: "storefront:return_processed",

  MARKETPLACE_LISTING_UNPUBLISHED: "marketplace:listing_unpublished",
  MARKETPLACE_LISTING_SOLD: "marketplace:listing_sold",

  AUTOMATION_WORKFLOW_CREATED: "automation:workflow_created",
  AUTOMATION_WORKFLOW_STOPPED: "automation:workflow_stopped",
  AUTOMATION_WORKFLOW_CANCELLED: "automation:workflow_cancelled",
  AUTOMATION_STEP_FAILED: "automation:step_failed",
  AUTOMATION_SCHEDULER_STARTED: "automation:scheduler_started",
  AUTOMATION_SCHEDULER_STOPPED: "automation:scheduler_stopped",
  AUTOMATION_PRIORITY_ESCALATED: "automation:priority_escalated",
  AUTOMATION_EXCEPTION_CREATED: "automation:exception_created",
  AUTOMATION_EXCEPTION_RESOLVED: "automation:exception_resolved",

  WALLET_LOADED: "wallet:loaded",
  WALLET_TRANSFER_RECEIVED: "wallet:transfer_received",

  TEXT_INTEGRITY_VIOLATION: "text:integrity_violation",
  LAYOUT_INTEGRITY_VIOLATION: "layout:integrity_violation",
  I18N_LOCALIZATION_VIOLATION: "i18n:localization_violation",

  DASHBOARD_CARD_AUDIT_COMPLETED: "dashboard:card_audit_completed",
  DASHBOARD_CARD_REPAIR_COMPLETED: "dashboard:card_repair_completed",
} as const;

export type CanonicalEventName = (typeof CANONICAL_EVENTS)[keyof typeof CANONICAL_EVENTS];
