export type SchemaVerdict = "KEEP" | "MERGE" | "REBUILD" | "REMOVE";

export interface SchemaRegistryEntry {
  name: string;
  domain: string;
  role: string;
  source_of_truth: string;
  relations: string[];
  required_fields: string[];
  fields_to_remove: string[];
  duplicates_detected: string[];
  conflicts_detected: string[];
  verdict: SchemaVerdict;
}

export const MASTER_SCHEMA_REGISTRY: SchemaRegistryEntry[] = [
  {
    name: "identity",
    domain: "foundation",
    role: "Single canonical user/account record",
    source_of_truth: "profiles + auth.users (merged via user_id)",
    relations: ["organization (owner)", "wallet_account", "seller_profile", "contact", "device_session", "consent"],
    required_fields: ["user_id", "account_type", "phone_e164", "identity_status", "country_code", "default_currency"],
    fields_to_remove: [],
    duplicates_detected: ["orbit_profiles_v2 duplicates display_name/avatar from profiles"],
    conflicts_detected: ["profiles.full_name vs orbit_profiles_v2.display_name vs storefront_pages.business_name — 3 name sources"],
    verdict: "MERGE",
  },
  {
    name: "organization",
    domain: "foundation",
    role: "Single canonical org/shop/agency/provider entity",
    source_of_truth: "storefront_pages (merged with org fields)",
    relations: ["identity (owner)", "address", "listing (many)", "transaction (many)"],
    required_fields: ["org_id", "org_type", "display_name", "owner_user_id", "status", "country"],
    fields_to_remove: [],
    duplicates_detected: ["shop, business, provider_company treated as separate concepts but share identical structure"],
    conflicts_detected: ["storefront_pages.business_name vs profiles.full_name for same provider"],
    verdict: "MERGE",
  },
  {
    name: "address",
    domain: "foundation",
    role: "Universal address/geolocation for all modules",
    source_of_truth: "canonical_address table (to be created)",
    relations: ["organization", "listing", "property", "venue", "service_profile"],
    required_fields: ["address_id", "country", "city", "lat", "lng"],
    fields_to_remove: [],
    duplicates_detected: ["Multiple address formats: listing.location, property.address, user delivery addresses — all different shapes"],
    conflicts_detected: ["No unified address structure across modules"],
    verdict: "REBUILD",
  },
  {
    name: "media",
    domain: "foundation",
    role: "Universal media storage for photos, videos, documents",
    source_of_truth: "Supabase storage + media metadata",
    relations: ["listing", "message", "banner", "menu_item", "identity (avatar)"],
    required_fields: ["media_id", "owner_type", "owner_id", "media_kind", "url", "moderation_status"],
    fields_to_remove: [],
    duplicates_detected: ["No unified media table — each module stores URLs inline"],
    conflicts_detected: ["listing.mediaUrls vs property.images vs profile.avatar_url — inconsistent media reference"],
    verdict: "REBUILD",
  },
  {
    name: "taxonomy",
    domain: "foundation",
    role: "Canonical category/vertical classification",
    source_of_truth: "src/lib/taxonomy/category-tree.ts + canonical-registry.ts",
    relations: ["listing", "search_document", "filter_registry", "page_config"],
    required_fields: ["taxonomy_id", "vertical", "category", "canonical_label", "slug"],
    fields_to_remove: [],
    duplicates_detected: ["category-tree.ts, subcategory-vertical-map.ts, taxonomy-aliases.ts — partially overlapping"],
    conflicts_detected: ["Some modules use local category strings instead of taxonomy IDs"],
    verdict: "MERGE",
  },
  {
    name: "canonical_event",
    domain: "foundation",
    role: "Audit trail for all domain events",
    source_of_truth: "platform-bus event log + domain-event-bus",
    relations: ["All domains (emitters)", "proof_record (consumer)"],
    required_fields: ["event_id", "event_name", "domain", "actor_id", "target_id", "trace_id"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "listing",
    domain: "marketplace",
    role: "Universal publishable entity: annonce, article, service, property, offer",
    source_of_truth: "marketplace_services + storefront_pages (merged)",
    relations: ["taxonomy", "address", "media", "listing_detail", "listing_attribute", "availability", "transaction"],
    required_fields: ["listing_id", "listing_type", "vertical", "seller_type", "seller_id", "title", "status", "publication_status"],
    fields_to_remove: [],
    duplicates_detected: ["marketplace_services, storefront_pages, property listings — 3 separate listing-like tables"],
    conflicts_detected: ["No universal listing schema — each vertical manages its own"],
    verdict: "MERGE",
  },
  {
    name: "listing_detail",
    domain: "marketplace",
    role: "Extended listing data (specs, policies, FAQ, SEO)",
    source_of_truth: "New canonical table",
    relations: ["listing"],
    required_fields: ["listing_detail_id", "listing_id"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "listing_attribute",
    domain: "marketplace",
    role: "Filterable key-value attributes for search",
    source_of_truth: "New canonical table",
    relations: ["listing", "filter_registry"],
    required_fields: ["attribute_id", "listing_id", "attribute_key", "attribute_type"],
    fields_to_remove: [],
    duplicates_detected: ["Filters hardcoded differently per vertical in radar-filter-schemas.ts"],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "availability",
    domain: "marketplace",
    role: "Unified availability for stock, calendar, reservation",
    source_of_truth: "New canonical table",
    relations: ["listing", "room_type", "service_slot", "unit"],
    required_fields: ["availability_id", "owner_type", "owner_id", "status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "seller_profile",
    domain: "marketplace",
    role: "Public seller identity for marketplace",
    source_of_truth: "New canonical table (derived from identity + org)",
    relations: ["identity", "organization", "listing"],
    required_fields: ["seller_profile_id", "user_id", "seller_type", "display_name"],
    fields_to_remove: [],
    duplicates_detected: ["profiles, orbit_profiles_v2, storefront_pages all contain seller-like data"],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "cart",
    domain: "commerce",
    role: "Shopping cart / purchase intent",
    source_of_truth: "cartStore (Zustand) + DB",
    relations: ["cart_item", "identity (buyer)"],
    required_fields: ["cart_id", "buyer_id", "status", "currency", "grand_total"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "transaction",
    domain: "commerce",
    role: "Universal transaction: order, booking, reservation, service_request",
    source_of_truth: "New canonical table (unifies marketplace_bookings, concierge_orders, booking_requests)",
    relations: ["listing", "payment", "receipt", "identity (buyer/seller)", "proof_record"],
    required_fields: ["transaction_id", "transaction_type", "buyer_id", "seller_id", "status", "payment_status"],
    fields_to_remove: [],
    duplicates_detected: ["marketplace_bookings, concierge_orders, booking_requests, deals — 4 separate transaction-like tables"],
    conflicts_detected: ["order_status, booking_status, deal_status — no common base"],
    verdict: "MERGE",
  },
  {
    name: "payment",
    domain: "commerce",
    role: "Payment record linked to transaction",
    source_of_truth: "wallet_transactions / unified_wallet_transactions",
    relations: ["transaction", "wallet_account"],
    required_fields: ["payment_id", "transaction_id", "amount", "currency", "status"],
    fields_to_remove: [],
    duplicates_detected: ["wallet_transactions + unified_wallet_transactions — dual payment tables"],
    conflicts_detected: ["Balance derived from two sources: wallet_balances_v2 vs sum-of-transactions"],
    verdict: "MERGE",
  },
  {
    name: "wallet_account",
    domain: "commerce",
    role: "User wallet with balance and limits",
    source_of_truth: "wallet_balances_v2",
    relations: ["identity", "ledger_entry", "payment"],
    required_fields: ["wallet_account_id", "owner_user_id", "currency", "available_balance"],
    fields_to_remove: [],
    duplicates_detected: ["walletStore (Zustand) can hold stale balance vs DB"],
    conflicts_detected: ["Dual-path read: store vs DB with no guaranteed freshness"],
    verdict: "KEEP",
  },
  {
    name: "ledger_entry",
    domain: "commerce",
    role: "Immutable financial ledger for all money movements",
    source_of_truth: "wallet_transactions (ledger mode)",
    relations: ["wallet_account"],
    required_fields: ["ledger_entry_id", "wallet_account_id", "entry_type", "direction", "amount", "balance_after"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "receipt",
    domain: "commerce",
    role: "Generated proof of payment for transaction",
    source_of_truth: "New canonical table",
    relations: ["transaction", "payment"],
    required_fields: ["receipt_id", "transaction_id", "payment_id", "amount", "currency"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "contact",
    domain: "orbit",
    role: "User's contact directory",
    source_of_truth: "contacts table / orbit contacts",
    relations: ["identity (owner)", "identity (target)"],
    required_fields: ["contact_id", "owner_user_id", "target_user_id"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "conversation",
    domain: "orbit",
    role: "Canonical conversation/thread",
    source_of_truth: "conversations_v2",
    relations: ["participant", "message", "call_session"],
    required_fields: ["conversation_id", "conversation_type", "created_by", "status"],
    fields_to_remove: [],
    duplicates_detected: ["conversations_v2 + 6 legacy tables merged in client code"],
    conflicts_detected: ["8 data sources merged in JavaScript with fragile key matching"],
    verdict: "MERGE",
  },
  {
    name: "participant",
    domain: "orbit",
    role: "Conversation participant with role and status",
    source_of_truth: "conversation_participants_v2",
    relations: ["conversation", "identity"],
    required_fields: ["participant_id", "conversation_id", "user_id", "role"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "message",
    domain: "orbit",
    role: "Chat message in conversation",
    source_of_truth: "messages_v2",
    relations: ["conversation", "identity (sender)", "media"],
    required_fields: ["message_id", "conversation_id", "sender_id", "message_type", "status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "call_session",
    domain: "orbit",
    role: "Audio/video call session",
    source_of_truth: "New canonical table",
    relations: ["conversation", "identity (initiator)"],
    required_fields: ["call_id", "conversation_id", "call_type", "initiator_id", "status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "presence",
    domain: "orbit",
    role: "User online/offline status",
    source_of_truth: "Supabase realtime presence",
    relations: ["identity"],
    required_fields: ["user_id", "online", "last_seen_at"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "notification",
    domain: "support",
    role: "In-app and push notifications",
    source_of_truth: "app_notifications / notification service",
    relations: ["identity (recipient)"],
    required_fields: ["notification_id", "recipient_id", "type", "title", "body", "status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "support_ticket",
    domain: "support",
    role: "Customer support ticket",
    source_of_truth: "New canonical table",
    relations: ["identity (creator)", "transaction", "listing"],
    required_fields: ["ticket_id", "creator_id", "domain", "issue_type", "status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "proof_record",
    domain: "support",
    role: "Audit proof for critical operations",
    source_of_truth: "New canonical table",
    relations: ["transaction", "repair_record"],
    required_fields: ["proof_id", "proof_type", "domain", "reference_type", "reference_id", "trace_id"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "permission",
    domain: "security",
    role: "RBAC permission entries",
    source_of_truth: "New canonical table",
    relations: ["identity", "organization"],
    required_fields: ["permission_id", "subject_type", "subject_id", "action", "effect"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "onboarding_session",
    domain: "onboarding",
    role: "Onboarding progress tracking",
    source_of_truth: "onboarding pipeline state",
    relations: ["identity (actor)"],
    required_fields: ["onboarding_id", "actor_id", "target_type", "status", "step_key"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "import_job",
    domain: "onboarding",
    role: "Data import tracking",
    source_of_truth: "import_engine orchestrator",
    relations: ["staging_entity"],
    required_fields: ["import_job_id", "source_type", "target_vertical", "status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "staging_entity",
    domain: "onboarding",
    role: "Staging area for imported entities before publication",
    source_of_truth: "import pipeline staging",
    relations: ["import_job"],
    required_fields: ["staging_id", "import_job_id", "taxonomy_status", "media_status", "validation_status", "publish_status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "engine_registry",
    domain: "engine",
    role: "Registry of all platform engines",
    source_of_truth: "Runtime engine observer",
    relations: ["engine_run_log", "repair_record", "learning_memory"],
    required_fields: ["engine_id", "engine_name", "domain", "status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "page_config",
    domain: "discovery",
    role: "Dynamic page layout configuration",
    source_of_truth: "New canonical table",
    relations: ["section_config"],
    required_fields: ["page_config_id", "page_key", "layout_type", "status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "filter_registry",
    domain: "discovery",
    role: "Canonical filter definitions per vertical",
    source_of_truth: "radar-filter-schemas.ts (to be migrated to data-driven)",
    relations: ["taxonomy", "listing_attribute"],
    required_fields: ["filter_id", "vertical", "filter_key", "filter_type"],
    fields_to_remove: [],
    duplicates_detected: ["Filters hardcoded in radar-filter-schemas.ts, not data-driven"],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "design_system",
    domain: "system_layer",
    role: "Canonical design tokens: spacing, typography, color, elevation, animation, grid",
    source_of_truth: "src/lib/systems/design-system.ts",
    relations: ["component_library", "premium_ux"],
    required_fields: ["SPACING_SCALE", "TYPOGRAPHY_SCALE", "COLOR_TOKENS", "ELEVATION", "BREAKPOINTS"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "navigation_system",
    domain: "system_layer",
    role: "Pillar-based navigation, deep linking, quick actions",
    source_of_truth: "src/lib/systems/navigation-system.ts",
    relations: ["identity", "listing", "conversation"],
    required_fields: ["PILLAR_ROOTS", "DEEP_LINK_PATTERNS", "QUICK_ACTIONS"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "permission_framework",
    domain: "system_layer",
    role: "RBAC + ownership + visibility engine",
    source_of_truth: "src/lib/systems/permission-framework.ts",
    relations: ["identity", "organization", "permission"],
    required_fields: ["Role", "Permission", "Scope", "Visibility"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "pricing_engine",
    domain: "system_layer",
    role: "Commission, tax, delivery fee, refund calculations",
    source_of_truth: "src/lib/systems/pricing-engine.ts",
    relations: ["transaction", "wallet_account", "listing"],
    required_fields: ["PricingInput", "PricingBreakdown", "CommissionTable"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "growth_engine",
    domain: "system_layer",
    role: "Loyalty, referrals, coupons, abandoned cart recovery",
    source_of_truth: "src/lib/systems/growth-engine.ts",
    relations: ["identity", "transaction", "wallet_account"],
    required_fields: ["LoyaltyTier", "ReferralConfig", "CouponConfig"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "seller_os",
    domain: "system_layer",
    role: "Seller dashboard, payouts, performance metrics, milestones",
    source_of_truth: "src/lib/systems/seller-os.ts",
    relations: ["identity", "listing", "transaction", "wallet_account"],
    required_fields: ["SellerDashboardMetrics", "PayoutRecord", "PerformanceMetrics"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "delivery_system",
    domain: "system_layer",
    role: "Courier dispatch, tracking, proof-of-delivery, ETA",
    source_of_truth: "src/lib/systems/delivery-system.ts",
    relations: ["transaction", "identity", "tracking"],
    required_fields: ["CourierProfile", "DeliveryMission", "DispatchRule"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "realtime_engine",
    domain: "system_layer",
    role: "WebSocket channels, presence, message ordering, dedup",
    source_of_truth: "src/lib/systems/realtime-engine.ts",
    relations: ["conversation", "presence", "notification"],
    required_fields: ["RealtimeChannel", "PresenceState", "OrderingGuarantee"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "offline_system",
    domain: "system_layer",
    role: "Offline queue, sync, conflict resolution, caching",
    source_of_truth: "src/lib/systems/offline-system.ts",
    relations: ["all domains (consumer)"],
    required_fields: ["PendingAction", "CacheEntry", "ConflictResolution"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "search_engine",
    domain: "system_layer",
    role: "Cross-vertical search, ranking, personalization, trust scoring",
    source_of_truth: "src/lib/systems/search-engine.ts",
    relations: ["listing", "taxonomy", "identity"],
    required_fields: ["SearchQuery", "SearchResult", "RankingWeights"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "analytics_engine",
    domain: "system_layer",
    role: "Event tracking, funnels, feature flags, A/B testing",
    source_of_truth: "src/lib/systems/analytics-engine.ts",
    relations: ["canonical_event", "identity"],
    required_fields: ["AnalyticsEvent", "FunnelDefinition", "FeatureFlag"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "i18n_system",
    domain: "system_layer",
    role: "Locales, currencies, country configs, RTL, address formats",
    source_of_truth: "src/lib/systems/i18n-system.ts",
    relations: ["identity", "transaction", "listing"],
    required_fields: ["SupportedLocale", "SupportedCurrency", "CountryConfig"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "compliance_engine",
    domain: "system_layer",
    role: "KYC levels, AML screening, transaction limits, GDPR",
    source_of_truth: "src/lib/systems/compliance-engine.ts",
    relations: ["identity", "transaction", "wallet_account"],
    required_fields: ["KYCLevel", "KYCRequirement", "TransactionLimit", "AMLFlag"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "admin_system",
    domain: "system_layer",
    role: "Admin RBAC, audit logs, support tickets, platform metrics",
    source_of_truth: "src/lib/systems/admin-system.ts",
    relations: ["identity", "support_ticket", "permission"],
    required_fields: ["AdminRole", "AuditLogEntry", "SupportTicket", "PlatformMetrics"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "notification_system",
    domain: "system_layer",
    role: "Multi-channel notification templates, preferences, quiet hours",
    source_of_truth: "src/lib/systems/notification-system.ts",
    relations: ["identity", "notification"],
    required_fields: ["NotificationTemplate", "NotificationPreferences", "NotificationChannel"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "identity_graph",
    domain: "system_layer",
    role: "Multi-provider identity, trust scoring, risk analysis, device tracking",
    source_of_truth: "src/lib/systems/identity-graph.ts",
    relations: ["identity", "compliance_engine"],
    required_fields: ["IdentityNode", "IdentityLink", "TrustLevel"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "moderation_system",
    domain: "system_layer",
    role: "Content moderation queues, policies, strikes, bans",
    source_of_truth: "src/lib/systems/moderation-system.ts",
    relations: ["listing", "message", "identity"],
    required_fields: ["ModerationQueue", "ContentPolicy", "UserModerationState"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "catalog_engine",
    domain: "system_layer",
    role: "Cross-vertical catalog, validation, inventory, SEO slugs",
    source_of_truth: "src/lib/systems/catalog-engine.ts",
    relations: ["listing", "taxonomy", "availability"],
    required_fields: ["CatalogItem", "CategoryNode", "VariantOption"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "sla_engine",
    domain: "system_layer",
    role: "SLA policies, escalation chains, penalty calculations",
    source_of_truth: "src/lib/systems/sla-engine.ts",
    relations: ["support_ticket", "delivery_system", "seller_os"],
    required_fields: ["SLAPolicy", "SLATarget", "EscalationStep"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "smart_home_system",
    domain: "system_layer",
    role: "IoT devices, access control, automation rules for property",
    source_of_truth: "src/lib/systems/smart-home-system.ts",
    relations: ["property", "identity"],
    required_fields: ["SmartDevice", "AutomationRule", "GuestAccess"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "component_library",
    domain: "system_layer",
    role: "UI component configs: toasts, sheets, empty states, skeletons",
    source_of_truth: "src/lib/systems/component-library.ts",
    relations: ["design_system", "premium_ux"],
    required_fields: ["ToastConfig", "BottomSheetConfig", "EmptyStateConfig"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "automation_engine",
    domain: "system_layer",
    role: "Event-driven workflow orchestration with built-in flows",
    source_of_truth: "src/lib/systems/automation-engine.ts",
    relations: ["canonical_event", "notification", "transaction"],
    required_fields: ["WorkflowDefinition", "WorkflowTrigger", "WorkflowStep"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "multi_tenant_system",
    domain: "system_layer",
    role: "Tenant management, plan quotas, team members, branding",
    source_of_truth: "src/lib/systems/multi-tenant-system.ts",
    relations: ["identity", "organization", "listing"],
    required_fields: ["Tenant", "TenantMember", "TenantQuota", "PlanTier"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "api_gateway",
    domain: "system_layer",
    role: "REST API endpoints, rate limiting, API keys, webhooks",
    source_of_truth: "src/lib/systems/api-gateway.ts",
    relations: ["identity", "listing", "transaction", "wallet_account"],
    required_fields: ["APIEndpoint", "RateLimitConfig", "APIKey", "WebhookSubscription"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "premium_ux",
    domain: "system_layer",
    role: "Haptics, gestures, micro-interactions, page transitions, shimmer",
    source_of_truth: "src/lib/systems/premium-ux.ts",
    relations: ["design_system", "component_library"],
    required_fields: ["TransitionConfig", "GestureConfig", "AnimationPreset", "MicroInteraction"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
];

export function getSchemaByName(name: string): SchemaRegistryEntry | undefined {
  return MASTER_SCHEMA_REGISTRY.find((s) => s.name === name);
}

export function getSchemasByDomain(domain: string): SchemaRegistryEntry[] {
  return MASTER_SCHEMA_REGISTRY.filter((s) => s.domain === domain);
}

export function getSchemasByVerdict(verdict: SchemaVerdict): SchemaRegistryEntry[] {
  return MASTER_SCHEMA_REGISTRY.filter((s) => s.verdict === verdict);
}

export function getDuplicateReport(): { schema: string; duplicates: string[] }[] {
  return MASTER_SCHEMA_REGISTRY
    .filter((s) => s.duplicates_detected.length > 0)
    .map((s) => ({ schema: s.name, duplicates: s.duplicates_detected }));
}

export function getConflictReport(): { schema: string; conflicts: string[] }[] {
  return MASTER_SCHEMA_REGISTRY
    .filter((s) => s.conflicts_detected.length > 0)
    .map((s) => ({ schema: s.name, conflicts: s.conflicts_detected }));
}
