import type { DomainSchema } from "./domain-schemas";

export type SchemaVerdict = "KEEP" | "MERGE" | "REBUILD" | "REMOVE";

export interface SchemaRegistryEntry {
  name: string;
  pg_schema: DomainSchema | "public";
  pg_table: string;
  domain: string;
  role: string;
  source_of_truth: string;
  relations: string[];
  required_fields: string[];
  fields_to_remove: string[];
  duplicates_detected: string[];
  conflicts_detected: string[];
  verdict: SchemaVerdict;
}

export const MASTER_SCHEMA_REGISTRY: SchemaRegistryEntry[] = [
  {
    name: "identity",
    pg_schema: "identity",
    pg_table: "profiles",
    domain: "foundation",
    role: "Single canonical user/account record",
    source_of_truth: "identity.profiles (auth.users joined)",
    relations: ["organization (owner)", "wallet_account", "seller_profile", "contact", "device_session", "consent"],
    required_fields: ["user_id", "account_type", "phone_e164", "identity_status", "country_code", "default_currency"],
    fields_to_remove: [],
    duplicates_detected: ["orbit_profiles_v2 — dropped, compat view redirects to identity.profiles"],
    conflicts_detected: [],
    verdict: "MERGE",
  },
  {
    name: "organization",
    pg_schema: "identity",
    pg_table: "organizations",
    domain: "foundation",
    role: "Single canonical org/shop/agency/provider entity",
    source_of_truth: "identity.organizations",
    relations: ["identity (owner)", "address", "listing (many)", "transaction (many)"],
    required_fields: ["org_id", "org_type", "display_name", "owner_user_id", "status", "country"],
    fields_to_remove: [],
    duplicates_detected: ["storefront_pages — dropped, compat view redirects to identity.organizations"],
    conflicts_detected: [],
    verdict: "MERGE",
  },
  {
    name: "address",
    pg_schema: "public",
    pg_table: "addresses",
    domain: "foundation",
    role: "Universal address/geolocation for all modules",
    source_of_truth: "canonical_address table (to be created)",
    relations: ["organization", "listing", "property", "venue", "service_profile"],
    required_fields: ["address_id", "country", "city", "lat", "lng"],
    fields_to_remove: [],
    duplicates_detected: ["Multiple address formats: listing.location, property.address, user delivery addresses — all different shapes"],
    conflicts_detected: ["No unified address structure across modules"],
    verdict: "REBUILD",
  },
  {
    name: "media",
    pg_schema: "public",
    pg_table: "media",
    domain: "foundation",
    role: "Universal media storage for photos, videos, documents",
    source_of_truth: "Supabase storage + media metadata",
    relations: ["listing", "message", "banner", "menu_item", "identity (avatar)"],
    required_fields: ["media_id", "owner_type", "owner_id", "media_kind", "url", "moderation_status"],
    fields_to_remove: [],
    duplicates_detected: ["No unified media table — each module stores URLs inline"],
    conflicts_detected: ["listing.mediaUrls vs property.images vs profile.avatar_url — inconsistent media reference"],
    verdict: "REBUILD",
  },
  {
    name: "taxonomy",
    pg_schema: "public",
    pg_table: "canonical_taxonomy",
    domain: "foundation",
    role: "Canonical category/vertical classification",
    source_of_truth: "canonical_taxonomy table",
    relations: ["listing", "search_document", "filter_registry", "page_config"],
    required_fields: ["taxonomy_id", "vertical", "category", "canonical_label", "slug"],
    fields_to_remove: [],
    duplicates_detected: ["category-tree.ts, subcategory-vertical-map.ts, taxonomy-aliases.ts — partially overlapping"],
    conflicts_detected: ["Some modules use local category strings instead of taxonomy IDs"],
    verdict: "MERGE",
  },
  {
    name: "canonical_event",
    pg_schema: "public",
    pg_table: "canonical_events",
    domain: "foundation",
    role: "Audit trail for all domain events",
    source_of_truth: "platform-bus event log + domain-event-bus",
    relations: ["All domains (emitters)", "proof_record (consumer)"],
    required_fields: ["event_id", "event_name", "domain", "actor_id", "target_id", "trace_id"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "listing",
    pg_schema: "marketplace",
    pg_table: "listings",
    domain: "marketplace",
    role: "Universal publishable entity: annonce, article, service, property, offer",
    source_of_truth: "marketplace.listings",
    relations: ["taxonomy", "address", "media", "listing_detail", "listing_attribute", "availability", "transaction"],
    required_fields: ["listing_id", "listing_type", "vertical", "seller_type", "seller_id", "title", "status", "publication_status"],
    fields_to_remove: [],
    duplicates_detected: ["marketplace_services — dropped, compat view redirects to marketplace.listings"],
    conflicts_detected: [],
    verdict: "MERGE",
  },
  {
    name: "listing_detail",
    pg_schema: "marketplace",
    pg_table: "listing_details",
    domain: "marketplace",
    role: "Extended listing data (specs, policies, FAQ, SEO)",
    source_of_truth: "marketplace.listing_details",
    relations: ["listing"],
    required_fields: ["listing_detail_id", "listing_id"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "listing_attribute",
    pg_schema: "marketplace",
    pg_table: "listing_attributes",
    domain: "marketplace",
    role: "Filterable key-value attributes for search",
    source_of_truth: "marketplace.listing_attributes",
    relations: ["listing", "filter_registry"],
    required_fields: ["attribute_id", "listing_id", "attribute_key", "attribute_type"],
    fields_to_remove: [],
    duplicates_detected: ["Filters hardcoded differently per vertical in radar-filter-schemas.ts"],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "availability",
    pg_schema: "public",
    pg_table: "availability",
    domain: "marketplace",
    role: "Unified availability for stock, calendar, reservation",
    source_of_truth: "New canonical table",
    relations: ["listing", "room_type", "service_slot", "unit"],
    required_fields: ["availability_id", "owner_type", "owner_id", "status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "seller_profile",
    pg_schema: "public",
    pg_table: "seller_profiles",
    domain: "marketplace",
    role: "Public seller identity for marketplace",
    source_of_truth: "New canonical table (derived from identity + org)",
    relations: ["identity", "organization", "listing"],
    required_fields: ["seller_profile_id", "user_id", "seller_type", "display_name"],
    fields_to_remove: [],
    duplicates_detected: ["profiles, orbit_profiles_v2, storefront_pages all contain seller-like data"],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "cart",
    pg_schema: "commerce",
    pg_table: "carts",
    domain: "commerce",
    role: "Shopping cart / purchase intent",
    source_of_truth: "commerce.carts",
    relations: ["cart_item", "identity (buyer)"],
    required_fields: ["cart_id", "buyer_id", "status", "currency", "grand_total"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "transaction",
    pg_schema: "commerce",
    pg_table: "transactions",
    domain: "commerce",
    role: "Universal transaction: order, booking, reservation, service_request",
    source_of_truth: "commerce.transactions",
    relations: ["listing", "payment", "receipt", "identity (buyer/seller)", "proof_record"],
    required_fields: ["transaction_id", "transaction_type", "buyer_id", "seller_id", "status", "payment_status"],
    fields_to_remove: [],
    duplicates_detected: [
      "marketplace_bookings — dropped",
      "concierge_orders — dropped",
      "booking_requests — dropped",
    ],
    conflicts_detected: [],
    verdict: "MERGE",
  },
  {
    name: "booking",
    pg_schema: "commerce",
    pg_table: "bookings",
    domain: "commerce",
    role: "Commerce booking record linked to transaction",
    source_of_truth: "commerce.bookings",
    relations: ["transaction", "listing", "identity (buyer/seller)"],
    required_fields: ["booking_id", "transaction_id", "listing_id", "buyer_id"],
    fields_to_remove: [],
    duplicates_detected: ["marketplace_bookings — dropped"],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "payment",
    pg_schema: "public",
    pg_table: "payments",
    domain: "commerce",
    role: "Payment record linked to transaction",
    source_of_truth: "wallet_transactions / unified_wallet_transactions",
    relations: ["transaction", "wallet_account"],
    required_fields: ["payment_id", "transaction_id", "amount", "currency", "status"],
    fields_to_remove: [],
    duplicates_detected: ["wallet_transactions + unified_wallet_transactions — dual payment tables"],
    conflicts_detected: ["Balance derived from two sources: wallet_accounts vs sum-of-transactions"],
    verdict: "MERGE",
  },
  {
    name: "wallet_account",
    pg_schema: "wallet",
    pg_table: "wallet_accounts",
    domain: "wallet",
    role: "User wallet with balance and limits",
    source_of_truth: "wallet.wallet_accounts",
    relations: ["identity", "ledger_entry", "payment"],
    required_fields: ["wallet_account_id", "owner_user_id", "currency", "available_balance"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "ledger_entry",
    pg_schema: "wallet",
    pg_table: "wallet_ledger_entries",
    domain: "wallet",
    role: "Immutable financial ledger for all money movements",
    source_of_truth: "wallet.wallet_ledger_entries",
    relations: ["wallet_account"],
    required_fields: ["ledger_entry_id", "wallet_account_id", "entry_type", "direction", "amount", "balance_after"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "receipt",
    pg_schema: "commerce",
    pg_table: "receipts",
    domain: "commerce",
    role: "Generated proof of payment for transaction",
    source_of_truth: "commerce.receipts",
    relations: ["transaction", "payment"],
    required_fields: ["receipt_id", "transaction_id", "payment_id", "amount", "currency"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "contact",
    pg_schema: "orbit",
    pg_table: "orbit_contacts_v2",
    domain: "orbit",
    role: "User's contact directory",
    source_of_truth: "orbit.orbit_contacts_v2",
    relations: ["identity (owner)", "identity (target)"],
    required_fields: ["contact_id", "owner_user_id", "target_user_id"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "conversation",
    pg_schema: "orbit",
    pg_table: "conversations_v2",
    domain: "orbit",
    role: "Canonical conversation/thread",
    source_of_truth: "orbit.conversations_v2",
    relations: ["participant", "message", "call_session"],
    required_fields: ["conversation_id", "conversation_type", "created_by", "status"],
    fields_to_remove: [],
    duplicates_detected: ["conversations (v1) — dropped"],
    conflicts_detected: [],
    verdict: "MERGE",
  },
  {
    name: "participant",
    pg_schema: "orbit",
    pg_table: "conversation_participants_v2",
    domain: "orbit",
    role: "Conversation participant with role and status",
    source_of_truth: "orbit.conversation_participants_v2",
    relations: ["conversation", "identity"],
    required_fields: ["participant_id", "conversation_id", "user_id", "role"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "message",
    pg_schema: "orbit",
    pg_table: "chat_messages_v2",
    domain: "orbit",
    role: "Chat message in conversation",
    source_of_truth: "orbit.chat_messages_v2",
    relations: ["conversation", "identity (sender)", "media"],
    required_fields: ["message_id", "conversation_id", "sender_id", "message_type", "status"],
    fields_to_remove: [],
    duplicates_detected: ["messages (v1) — dropped"],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "call_session",
    pg_schema: "orbit",
    pg_table: "ghost_call_sessions",
    domain: "orbit",
    role: "Audio/video call session",
    source_of_truth: "orbit.ghost_call_sessions",
    relations: ["conversation", "identity (initiator)"],
    required_fields: ["call_id", "conversation_id", "call_type", "initiator_id", "status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "presence",
    pg_schema: "public",
    pg_table: "user_presence",
    domain: "orbit",
    role: "User online/offline status",
    source_of_truth: "Supabase realtime presence",
    relations: ["identity"],
    required_fields: ["user_id", "online", "last_seen_at"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "notification",
    pg_schema: "notification",
    pg_table: "app_notifications",
    domain: "notification",
    role: "In-app and push notifications",
    source_of_truth: "notification.app_notifications",
    relations: ["identity (recipient)"],
    required_fields: ["notification_id", "recipient_id", "type", "title", "body", "status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "support_ticket",
    pg_schema: "support",
    pg_table: "support_tickets",
    domain: "support",
    role: "Customer support ticket",
    source_of_truth: "support.support_tickets",
    relations: ["identity (creator)", "transaction", "listing"],
    required_fields: ["ticket_id", "creator_id", "domain", "issue_type", "status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "proof_record",
    pg_schema: "public",
    pg_table: "proof_records",
    domain: "support",
    role: "Audit proof for critical operations",
    source_of_truth: "New canonical table",
    relations: ["transaction", "repair_record"],
    required_fields: ["proof_id", "proof_type", "domain", "reference_type", "reference_id", "trace_id"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "permission",
    pg_schema: "public",
    pg_table: "permissions",
    domain: "security",
    role: "RBAC permission entries",
    source_of_truth: "New canonical table",
    relations: ["identity", "organization"],
    required_fields: ["permission_id", "subject_type", "subject_id", "action", "effect"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "onboarding_session",
    pg_schema: "onboarding",
    pg_table: "onboarding_sessions",
    domain: "onboarding",
    role: "Onboarding progress tracking",
    source_of_truth: "onboarding.onboarding_sessions",
    relations: ["identity (actor)"],
    required_fields: ["onboarding_id", "actor_id", "target_type", "status", "step_key"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "import_job",
    pg_schema: "onboarding",
    pg_table: "import_jobs",
    domain: "onboarding",
    role: "Data import tracking",
    source_of_truth: "onboarding.import_jobs",
    relations: ["staging_entity"],
    required_fields: ["import_job_id", "source_type", "target_vertical", "status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "staging_entity",
    pg_schema: "onboarding",
    pg_table: "staging_entities",
    domain: "onboarding",
    role: "Staging area for imported entities before publication",
    source_of_truth: "onboarding.staging_entities",
    relations: ["import_job"],
    required_fields: ["staging_id", "import_job_id", "taxonomy_status", "media_status", "validation_status", "publish_status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "engine_registry",
    pg_schema: "system",
    pg_table: "engine_supervisor",
    domain: "engine",
    role: "Registry of all platform engines",
    source_of_truth: "system.engine_supervisor",
    relations: ["engine_run_log", "repair_record", "learning_memory"],
    required_fields: ["engine_id", "engine_name", "domain", "status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "page_config",
    pg_schema: "public",
    pg_table: "page_configs",
    domain: "discovery",
    role: "Dynamic page layout configuration",
    source_of_truth: "New canonical table",
    relations: ["section_config"],
    required_fields: ["page_config_id", "page_key", "layout_type", "status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "filter_registry",
    pg_schema: "public",
    pg_table: "filter_registry",
    domain: "discovery",
    role: "Canonical filter definitions per vertical",
    source_of_truth: "radar-filter-schemas.ts (to be migrated to data-driven)",
    relations: ["taxonomy", "listing_attribute"],
    required_fields: ["filter_id", "vertical", "filter_key", "filter_type"],
    fields_to_remove: [],
    duplicates_detected: ["Filters hardcoded in radar-filter-schemas.ts, not data-driven"],
    conflicts_detected: [],
    verdict: "REBUILD",
  },
  {
    name: "property",
    pg_schema: "property",
    pg_table: "properties",
    domain: "property",
    role: "Real-estate property with units and leases",
    source_of_truth: "property.properties",
    relations: ["identity (owner)", "unit (many)", "lease (many)", "listing"],
    required_fields: ["property_id", "property_type", "address_id", "status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "unit",
    pg_schema: "property",
    pg_table: "units",
    domain: "property",
    role: "Individual rentable unit within a property",
    source_of_truth: "property.units",
    relations: ["property", "lease (many)"],
    required_fields: ["unit_id", "property_id", "label", "status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "lease",
    pg_schema: "property",
    pg_table: "leases",
    domain: "property",
    role: "Tenant lease agreement for a unit",
    source_of_truth: "property.leases",
    relations: ["unit", "identity (tenant)", "identity (landlord)"],
    required_fields: ["lease_id", "unit_id", "tenant_user_id", "start_date", "rent_amount", "status"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
  {
    name: "analytics_event",
    pg_schema: "analytics",
    pg_table: "user_radar_events",
    domain: "analytics",
    role: "User behaviour and radar analytics events",
    source_of_truth: "analytics.user_radar_events",
    relations: ["identity"],
    required_fields: ["event_id", "user_id", "event_type"],
    fields_to_remove: [],
    duplicates_detected: [],
    conflicts_detected: [],
    verdict: "KEEP",
  },
];

/**
 * Look up a registry entry by canonical name.
 */
export function getRegistryEntry(name: string): SchemaRegistryEntry | undefined {
  return MASTER_SCHEMA_REGISTRY.find((e) => e.name === name);
}

/**
 * Return all entries belonging to a given domain.
 */
export function getEntriesForDomain(domain: string): SchemaRegistryEntry[] {
  return MASTER_SCHEMA_REGISTRY.filter((e) => e.domain === domain);
}
