import type { DocumentTemplate } from "../types";

/* ─── Nebenkostenabrechnung (Operating Costs Settlement) ─── */
export const deNebenkostenabrechnung: DocumentTemplate = {
  id: "de-nebenkosten",
  version: "1.0.0",
  country: "DE",
  category: "rental",
  docType: "charges-regularization",
  label: "Nebenkostenabrechnung",
  description: "Jährliche Betriebskostenabrechnung gemäß § 556 BGB und BetrKV.",
  legalBasis: "BGB § 556; Betriebskostenverordnung (BetrKV); Heizkostenverordnung (HeizkV)",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "landlordName", label: "Name des Vermieters", type: "text", required: true, group: "Vermieter" },
    { key: "landlordAddress", label: "Anschrift des Vermieters", type: "text", required: true, group: "Vermieter" },
    { key: "tenantName", label: "Name des Mieters", type: "text", required: true, group: "Mieter" },
    { key: "propertyAddress", label: "Adresse der Mietwohnung", type: "text", required: true, group: "Mietobjekt" },
    { key: "periodStart", label: "Abrechnungszeitraum von", type: "date", required: true, group: "Zeitraum" },
    { key: "periodEnd", label: "Abrechnungszeitraum bis", type: "date", required: true, group: "Zeitraum" },
    { key: "totalArea", label: "Gesamtwohnfläche des Gebäudes (m²)", type: "number", required: true, group: "Umlageschlüssel" },
    { key: "tenantArea", label: "Wohnfläche des Mieters (m²)", type: "number", required: true, group: "Umlageschlüssel" },
    { key: "totalUnits", label: "Anzahl Wohneinheiten", type: "number", required: false, group: "Umlageschlüssel" },
    { key: "costsDetail", label: "Aufstellung der Betriebskosten", type: "textarea", required: true, placeholder: "Grundsteuer: 1.200 €\nWasserversorgung: 800 €\nEntwässerung: 600 €\nHeizkosten: 2.400 €\nWarmwasser: 500 €\nAufzug: 1.000 €\nMüllabfuhr: 400 €\nGebäudereinigung: 350 €\nGartenpflege: 300 €\nBeleuchtung: 200 €\nSchornsteinfeger: 150 €\nVersicherungen: 900 €\nHauswart: 600 €", group: "Kosten" },
    { key: "totalCosts", label: "Gesamtkosten (€)", type: "number", required: true, group: "Kosten" },
    { key: "tenantShare", label: "Mieteranteil (€)", type: "number", required: true, group: "Kosten" },
    { key: "prepayments", label: "Geleistete Vorauszahlungen (€)", type: "number", required: true, group: "Kosten" },
  ],
  clauses: [
    { id: "header", label: "Absender", required: true,
      text: "{landlordName}\n{landlordAddress}\n\nAn {tenantName}\n{propertyAddress}" },
    { id: "abrechnung", label: "Betriebskostenabrechnung", required: true,
      text: "BETRIEBSKOSTENABRECHNUNG\ngemäß § 556 BGB und Betriebskostenverordnung (BetrKV)\n\nAbrechnungszeitraum: {periodStart} bis {periodEnd}\nMietobjekt: {propertyAddress}\n\nUMLAGESCHLÜSSEL:\n• Gesamtwohnfläche: {totalArea} m²\n• Ihre Wohnfläche: {tenantArea} m²\n• Ihr Flächenanteil: {tenantArea}/{totalArea}\n\nAUFSTELLUNG DER BETRIEBSKOSTEN:\n(gemäß § 2 BetrKV)\n\n{costsDetail}\n\n╔══════════════════════════════════════╗\n║ Gesamtkosten                : {totalCosts} €\n║ Ihr Anteil                  : {tenantShare} €\n║ Geleistete Vorauszahlungen  : {prepayments} €\n║ ────────────────────────────────────\n║ Nachzahlung (+) / Guthaben (-):\n║ {tenantShare} - {prepayments} = Saldo\n╚══════════════════════════════════════╝\n\nHINWEISE:\n• Die Belege können innerhalb der nächsten 12 Monate nach Zugang dieser Abrechnung bei uns eingesehen werden (§ 556 Abs. 3 BGB).\n• Einwendungen sind innerhalb von 12 Monaten nach Zugang der Abrechnung geltend zu machen (§ 556 Abs. 3 Satz 5 BGB).\n• Ein eventuelles Guthaben wird mit der nächsten Mietzahlung verrechnet oder auf Ihr Konto überwiesen.\n• Eine eventuelle Nachzahlung ist innerhalb von 30 Tagen nach Zugang fällig." },
  ],
};

/* ─── Mieterhöhungsverlangen (Rent Increase Notice) ─── */
export const deMieterhoehung: DocumentTemplate = {
  id: "de-mieterhoehung",
  version: "1.0.0",
  country: "DE",
  category: "rental",
  docType: "rent-revision",
  label: "Mieterhöhungsverlangen",
  description: "Schriftliches Mieterhöhungsverlangen gemäß § 558 BGB.",
  legalBasis: "BGB §§ 558–558e (Mieterhöhung bis zur ortsüblichen Vergleichsmiete); Kappungsgrenze § 558 Abs. 3",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "landlordName", label: "Name des Vermieters", type: "text", required: true, group: "Vermieter" },
    { key: "landlordAddress", label: "Anschrift", type: "text", required: true, group: "Vermieter" },
    { key: "tenantName", label: "Name des Mieters", type: "text", required: true, group: "Mieter" },
    { key: "tenantAddress", label: "Anschrift des Mieters", type: "text", required: true, group: "Mieter" },
    { key: "propertyAddress", label: "Adresse der Wohnung", type: "text", required: true, group: "Mietobjekt" },
    { key: "currentRent", label: "Aktuelle Kaltmiete (€)", type: "number", required: true, group: "Miete" },
    { key: "newRent", label: "Neue Kaltmiete (€)", type: "number", required: true, group: "Miete" },
    { key: "mietspiegelRef", label: "Referenz Mietspiegel / Vergleichswohnungen", type: "textarea", required: true, placeholder: "Qualifizierter Mietspiegel der Stadt…\noder 3 Vergleichswohnungen:\n1. Musterstr. 1, 65 m², 8,50 €/m²\n2. Beispielweg 3, 70 m², 8,80 €/m²\n3. Testgasse 5, 60 m², 9,00 €/m²", group: "Begründung" },
    { key: "kappungsgrenze", label: "Kappungsgrenze anwendbar?", type: "select", required: true, options: [
      { value: "20", label: "20 % (Standard)" },
      { value: "15", label: "15 % (Gebiete mit Kappungsgrenze)" },
    ], defaultValue: "20", group: "Begründung" },
    { key: "effectiveDate", label: "Gewünschtes Wirksamkeitsdatum", type: "date", required: true, group: "Datum" },
    { key: "sendDate", label: "Datum des Schreibens", type: "date", required: true, group: "Datum" },
  ],
  clauses: [
    { id: "header", label: "Anschreiben", required: true,
      text: "{landlordName}\n{landlordAddress}\n\nAn\n{tenantName}\n{tenantAddress}\n\n{sendDate}" },
    { id: "erhoehung", label: "Mieterhöhungsverlangen", required: true,
      text: "Betreff: Mieterhöhungsverlangen gemäß § 558 BGB\n\nSehr geehrte(r) {tenantName},\n\nhiermit verlange ich die Zustimmung zur Erhöhung der Nettokaltmiete für die Wohnung {propertyAddress}.\n\nAktuelle Kaltmiete: {currentRent} € / Monat\nNeue Kaltmiete: {newRent} € / Monat\n\nDie Erhöhung liegt innerhalb der Kappungsgrenze von {kappungsgrenze} % gemäß § 558 Abs. 3 BGB.\n\nBEGRÜNDUNG:\n{mietspiegelRef}\n\nGemäß § 558b BGB bitte ich Sie, der Mieterhöhung bis zum Ablauf des zweiten Kalendermonats nach Zugang dieses Schreibens zuzustimmen. Bei Zustimmung ist die neue Miete ab dem {effectiveDate} geschuldet.\n\nSollten Sie der Erhöhung nicht zustimmen, bin ich berechtigt, innerhalb von drei Monaten nach Ablauf der Zustimmungsfrist Klage auf Zustimmung beim zuständigen Amtsgericht zu erheben (§ 558b Abs. 2 BGB).\n\nMit freundlichen Grüßen" },
  ],
};

/* ─── Kündigung durch den Vermieter (Landlord Termination) ─── */
export const deKuendigungVermieter: DocumentTemplate = {
  id: "de-kuendigung-vermieter",
  version: "1.0.0",
  country: "DE",
  category: "rental",
  docType: "conges-bailleur",
  label: "Kündigung durch den Vermieter",
  description: "Ordentliche oder außerordentliche Kündigung durch den Vermieter gemäß BGB.",
  legalBasis: "BGB §§ 573, 573a, 573c (ordentliche Kündigung); § 543 (fristlose Kündigung); § 569 (Sonderkündigungsrechte)",
  needsLegalReview: true,
  active: true,
  fields: [
    { key: "landlordName", label: "Name des Vermieters", type: "text", required: true, group: "Vermieter" },
    { key: "landlordAddress", label: "Anschrift", type: "text", required: true, group: "Vermieter" },
    { key: "tenantName", label: "Name des Mieters", type: "text", required: true, group: "Mieter" },
    { key: "tenantAddress", label: "Anschrift", type: "text", required: true, group: "Mieter" },
    { key: "propertyAddress", label: "Adresse der Wohnung", type: "text", required: true, group: "Mietobjekt" },
    { key: "leaseStartDate", label: "Mietbeginn", type: "date", required: true, group: "Mietverhältnis" },
    { key: "kuendigungsart", label: "Art der Kündigung", type: "select", required: true, options: [
      { value: "ordentlich-eigenbedarf", label: "Ordentlich — Eigenbedarf (§ 573 Abs. 2 Nr. 2)" },
      { value: "ordentlich-verwertung", label: "Ordentlich — Wirtschaftliche Verwertung (§ 573 Abs. 2 Nr. 3)" },
      { value: "ordentlich-pflichtverstoß", label: "Ordentlich — Schuldhafte Pflichtverletzung (§ 573 Abs. 2 Nr. 1)" },
      { value: "fristlos-zahlungsverzug", label: "Fristlos — Zahlungsverzug (§ 543 Abs. 2 Nr. 3)" },
      { value: "fristlos-vertragswidrig", label: "Fristlos — Vertragswidriger Gebrauch (§ 543 Abs. 2 Nr. 2)" },
    ], group: "Kündigung" },
    { key: "reason", label: "Ausführliche Begründung", type: "textarea", required: true, validation: { minLength: 30 }, group: "Kündigung" },
    { key: "eigenbedarfPerson", label: "Bedarfsperson (bei Eigenbedarf)", type: "text", required: false, group: "Eigenbedarf" },
    { key: "eigenbedarfRelation", label: "Verwandtschaftsverhältnis", type: "text", required: false, placeholder: "Ehegatte, Eltern, Kind, Enkel…", group: "Eigenbedarf" },
    { key: "terminationDate", label: "Kündigungsdatum zum", type: "date", required: true, group: "Fristen" },
    { key: "sendDate", label: "Datum des Schreibens", type: "date", required: true, group: "Fristen" },
  ],
  clauses: [
    { id: "header", label: "Anschreiben", required: true,
      text: "KÜNDIGUNG DES MIETVERHÄLTNISSES\n\n{landlordName}\n{landlordAddress}\n\nAn\n{tenantName}\n{tenantAddress}\n\n{sendDate}" },
    { id: "kuendigung", label: "Kündigungserklärung", required: true,
      text: "Betreff: Kündigung des Mietverhältnisses über die Wohnung {propertyAddress}\n\nSehr geehrte(r) {tenantName},\n\nhiermit kündige ich das seit dem {leaseStartDate} bestehende Mietverhältnis über die oben genannte Wohnung zum {terminationDate}.\n\nKündigungsgrund: {kuendigungsart}\n\nBEGRÜNDUNG:\n{reason}" },
    { id: "eigenbedarf", label: "Eigenbedarf", required: false,
      conditional: (data) => String(data.kuendigungsart).includes("eigenbedarf"),
      text: "BEDARFSPERSON (§ 573 Abs. 2 Nr. 2 BGB):\n\nName: {eigenbedarfPerson}\nVerhältnis zum Vermieter: {eigenbedarfRelation}\n\nDie Bedarfsperson beabsichtigt, die Wohnung als Hauptwohnsitz zu nutzen." },
    { id: "widerspruch", label: "Widerspruchsrecht", required: true,
      text: "WIDERSPRUCHSRECHT DES MIETERS (§ 574 BGB)\n\nSie können der Kündigung widersprechen und die Fortsetzung des Mietverhältnisses verlangen, wenn die vertragsgemäße Beendigung für Sie oder Ihre Familie eine Härte bedeuten würde, die auch unter Berücksichtigung meiner berechtigten Interessen nicht zu rechtfertigen ist.\n\nDer Widerspruch ist dem Vermieter spätestens zwei Monate vor Ablauf der Kündigungsfrist schriftlich mitzuteilen und zu begründen.\n\nHINWEIS: Bei Mietern über 65 Jahren oder bei Krankheit gelten besondere Härtegründe.\n\nMit freundlichen Grüßen" },
  ],
};

/* ─── Kündigung durch den Mieter (Tenant Termination) ─── */
export const deKuendigungMieter: DocumentTemplate = {
  id: "de-kuendigung-mieter",
  version: "1.0.0",
  country: "DE",
  category: "rental",
  docType: "conges-locataire",
  label: "Kündigung durch den Mieter",
  description: "Ordentliche Kündigung durch den Mieter gemäß § 573c BGB.",
  legalBasis: "BGB § 573c (Kündigungsfrist); § 568 (Form der Kündigung)",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "tenantName", label: "Name des Mieters", type: "text", required: true, group: "Mieter" },
    { key: "tenantAddress", label: "Aktuelle Anschrift", type: "text", required: true, group: "Mieter" },
    { key: "landlordName", label: "Name des Vermieters", type: "text", required: true, group: "Vermieter" },
    { key: "landlordAddress", label: "Anschrift des Vermieters", type: "text", required: true, group: "Vermieter" },
    { key: "propertyAddress", label: "Adresse der Wohnung", type: "text", required: true, group: "Mietobjekt" },
    { key: "leaseStartDate", label: "Mietbeginn", type: "date", required: true, group: "Mietverhältnis" },
    { key: "terminationDate", label: "Kündigung zum", type: "date", required: true, group: "Fristen" },
    { key: "newAddress", label: "Neue Anschrift (für Kaution)", type: "text", required: false, group: "Fristen" },
    { key: "sendDate", label: "Datum des Schreibens", type: "date", required: true, group: "Fristen" },
  ],
  clauses: [
    { id: "kuendigung", label: "Kündigung", required: true,
      text: "{tenantName}\n{tenantAddress}\n\nAn\n{landlordName}\n{landlordAddress}\n\n{sendDate}\n\nBetreff: Ordentliche Kündigung des Mietverhältnisses\n\nSehr geehrte(r) {landlordName},\n\nhiermit kündige ich das seit dem {leaseStartDate} bestehende Mietverhältnis über die Wohnung {propertyAddress} ordentlich und fristgerecht zum {terminationDate}, hilfsweise zum nächstmöglichen Termin.\n\nIch bitte um:\n• Vereinbarung eines Termins für die Wohnungsübergabe mit Übergabeprotokoll\n• Ablesung der Zählerstände bei Übergabe\n• Rückzahlung der Mietkaution innerhalb angemessener Frist (i.d.R. 3–6 Monate) an meine neue Anschrift\n\nNeue Anschrift: {newAddress}\n\nBitte bestätigen Sie den Erhalt dieser Kündigung und das Kündigungsdatum schriftlich.\n\nMit freundlichen Grüßen" },
  ],
};

/* ─── Wohnungsübergabeprotokoll (Detailed Property Handover) ─── */
export const deUebergabeprotokoll: DocumentTemplate = {
  id: "de-uebergabeprotokoll",
  version: "1.0.0",
  country: "DE",
  category: "rental",
  docType: "inventory",
  label: "Wohnungsübergabeprotokoll (detailliert)",
  description: "Ausführliches Übergabeprotokoll für Ein- und Auszug mit Zählerständen.",
  legalBasis: "BGB §§ 535, 546; BetrKV",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "protocolType", label: "Art der Übergabe", type: "select", required: true, options: [
      { value: "einzug", label: "Einzug (Wohnungsübernahme)" },
      { value: "auszug", label: "Auszug (Wohnungsrückgabe)" },
    ], group: "Allgemein" },
    { key: "propertyAddress", label: "Adresse der Wohnung", type: "text", required: true, group: "Mietobjekt" },
    { key: "surface", label: "Wohnfläche (m²)", type: "number", required: false, group: "Mietobjekt" },
    { key: "landlordName", label: "Vermieter / Verwalter", type: "text", required: true, group: "Parteien" },
    { key: "tenantName", label: "Mieter", type: "text", required: true, group: "Parteien" },
    { key: "protocolDate", label: "Datum der Übergabe", type: "date", required: true, group: "Datum" },
    { key: "meterElec", label: "Zählerstand Strom (kWh)", type: "number", required: false, group: "Zählerstände" },
    { key: "meterElecNumber", label: "Zählernummer Strom", type: "text", required: false, group: "Zählerstände" },
    { key: "meterGas", label: "Zählerstand Gas (m³)", type: "number", required: false, group: "Zählerstände" },
    { key: "meterGasNumber", label: "Zählernummer Gas", type: "text", required: false, group: "Zählerstände" },
    { key: "meterWater", label: "Zählerstand Wasser (m³)", type: "number", required: false, group: "Zählerstände" },
    { key: "meterHeating", label: "Zählerstand Heizung", type: "text", required: false, group: "Zählerstände" },
    { key: "keysCount", label: "Anzahl Schlüssel", type: "number", required: true, validation: { min: 0 }, group: "Schlüssel" },
    { key: "keysDetail", label: "Schlüssel-Details", type: "textarea", required: false, placeholder: "2× Haustür\n2× Wohnung\n1× Briefkasten\n1× Keller\n1× Garage / Tiefgarage", group: "Schlüssel" },
    { key: "roomsDescription", label: "Raum-für-Raum-Beschreibung", type: "textarea", required: true, placeholder: "FLUR:\n- Boden: Laminat — guter Zustand\n- Wände: tapeziert, weiß — guter Zustand\n- Decke: guter Zustand\n\nWOHNZIMMER:\n- Boden: Parkett — guter Zustand\n...", validation: { minLength: 20 }, group: "Zustand" },
    { key: "defects", label: "Mängel und Vorschäden", type: "textarea", required: false, group: "Zustand" },
  ],
  clauses: [
    { id: "header", label: "Kopf", required: true,
      text: "WOHNUNGSÜBERGABEPROTOKOLL — {protocolType}\n\nDatum: {protocolDate}\nObjekt: {propertyAddress}\nWohnfläche: {surface} m²\n\nVermieter/Verwalter: {landlordName}\nMieter: {tenantName}" },
    { id: "zaehler", label: "Zählerstände", required: true,
      text: "ZÄHLERSTÄNDE\n\n• Strom: {meterElec} kWh (Zähler-Nr. {meterElecNumber})\n• Gas: {meterGas} m³ (Zähler-Nr. {meterGasNumber})\n• Wasser: {meterWater} m³\n• Heizung: {meterHeating}\n\nDie Zählerstände wurden in Anwesenheit beider Parteien abgelesen." },
    { id: "schluessel", label: "Schlüssel", required: true,
      text: "SCHLÜSSEL UND ZUGANGSMITTEL\n\nAnzahl übergebener Schlüssel: {keysCount}\n\nDetails:\n{keysDetail}" },
    { id: "zustand", label: "Zustandsbeschreibung", required: true,
      text: "ZUSTAND DER WOHNUNG — RAUM FÜR RAUM\n(Boden, Wände, Decke, Fenster, Türen, Heizkörper, Sanitär, Elektrik)\n\n{roomsDescription}" },
    { id: "maengel", label: "Mängel", required: false,
      conditional: (data) => !!data.defects && String(data.defects).length > 3,
      text: "FESTGESTELLTE MÄNGEL UND VORSCHÄDEN\n\n{defects}" },
    { id: "unterschriften", label: "Unterschriften", required: true,
      text: "Das vorliegende Protokoll wurde von beiden Parteien geprüft und für richtig befunden.\n\nJede Partei erhält ein Exemplar.\n\nOrt, Datum: ____________\n\nVermieter / Verwalter: _______________\n\nMieter: _______________" },
  ],
};

/* ─── Mietschuldenfreiheitsbescheinigung (No-Debt Certificate) ─── */
export const deMietschuldenfreiheit: DocumentTemplate = {
  id: "de-mietschuldenfreiheit",
  version: "1.0.0",
  country: "DE",
  category: "administrative",
  docType: "sworn-statement",
  label: "Mietschuldenfreiheitsbescheinigung",
  description: "Bescheinigung des Vermieters über die Schuldenfreiheit des Mieters.",
  legalBasis: "Kein gesetzlicher Anspruch, jedoch übliche Praxis bei Neuvermietung",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "landlordName", label: "Name des Vermieters", type: "text", required: true, group: "Vermieter" },
    { key: "landlordAddress", label: "Anschrift", type: "text", required: true, group: "Vermieter" },
    { key: "tenantName", label: "Name des Mieters", type: "text", required: true, group: "Mieter" },
    { key: "propertyAddress", label: "Adresse der Mietwohnung", type: "text", required: true, group: "Mietobjekt" },
    { key: "leaseStart", label: "Mietbeginn", type: "date", required: true, group: "Zeitraum" },
    { key: "leaseEnd", label: "Mietende", type: "date", required: true, group: "Zeitraum" },
    { key: "issueDate", label: "Ausstellungsdatum", type: "date", required: true, group: "Datum" },
  ],
  clauses: [
    { id: "bescheinigung", label: "Bescheinigung", required: true,
      text: "MIETSCHULDENFREIHEITSBESCHEINIGUNG\n\nHiermit bestätige ich, {landlordName}, wohnhaft {landlordAddress}, als Vermieter der Wohnung {propertyAddress}, dass\n\n{tenantName}\n\ndie Wohnung im Zeitraum vom {leaseStart} bis zum {leaseEnd} bewohnt hat und während der gesamten Mietdauer sämtliche Mietzahlungen (Kaltmiete und Nebenkosten) vollständig und fristgerecht geleistet hat.\n\nEs bestehen zum Zeitpunkt dieser Bescheinigung keine offenen Forderungen aus dem Mietverhältnis.\n\nDiese Bescheinigung wird auf Wunsch des Mieters für Vorlage bei einem neuen Vermieter ausgestellt.\n\nDatum: {issueDate}\n\nUnterschrift des Vermieters:\n\n_______________" },
  ],
};

/* ─── Kautionsabrechnung (Deposit Return) ─── */
export const deKautionsabrechnung: DocumentTemplate = {
  id: "de-kautionsabrechnung",
  version: "1.0.0",
  country: "DE",
  category: "rental",
  docType: "deposit-return",
  label: "Kautionsabrechnung",
  description: "Abrechnung und Rückzahlung der Mietkaution gemäß § 551 BGB.",
  legalBasis: "BGB § 551 (Kaution); BGH-Rechtsprechung zur Abrechnungsfrist",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "landlordName", label: "Name des Vermieters", type: "text", required: true, group: "Vermieter" },
    { key: "landlordAddress", label: "Anschrift", type: "text", required: true, group: "Vermieter" },
    { key: "tenantName", label: "Name des Mieters", type: "text", required: true, group: "Mieter" },
    { key: "tenantNewAddress", label: "Neue Anschrift des Mieters", type: "text", required: true, group: "Mieter" },
    { key: "propertyAddress", label: "Adresse der Wohnung", type: "text", required: true, group: "Mietobjekt" },
    { key: "leaseEnd", label: "Mietende / Schlüsselübergabe", type: "date", required: true, group: "Zeitraum" },
    { key: "depositAmount", label: "Kaution eingezahlt (€)", type: "number", required: true, group: "Kaution" },
    { key: "interestAmount", label: "Aufgelaufene Zinsen (€)", type: "number", required: false, defaultValue: 0, group: "Kaution" },
    { key: "deductionsDetail", label: "Einbehalte / Abzüge", type: "textarea", required: false, placeholder: "Schäden laut Übergabeprotokoll: 200 €\nOffene Nebenkostenabrechnung (Einbehalt): 300 €\nEndreinigung: 150 €", group: "Kaution" },
    { key: "totalDeductions", label: "Summe der Abzüge (€)", type: "number", required: false, defaultValue: 0, group: "Kaution" },
    { key: "tenantIban", label: "IBAN des Mieters", type: "text", required: false, group: "Überweisung" },
    { key: "issueDate", label: "Datum", type: "date", required: true, group: "Datum" },
  ],
  clauses: [
    { id: "abrechnung", label: "Kautionsabrechnung", required: true,
      text: "KAUTIONSABRECHNUNG\ngemäß § 551 BGB\n\n{landlordName}\n{landlordAddress}\n\nAn\n{tenantName}\n{tenantNewAddress}\n\nDatum: {issueDate}\nMietobjekt: {propertyAddress}\nMietende: {leaseEnd}\n\nABRECHNUNG DER MIETKAUTION:\n\n╔══════════════════════════════════════╗\n║ Eingezahlte Kaution      : {depositAmount} €\n║ Aufgelaufene Zinsen       : {interestAmount} €\n║ Zwischensumme             : Kaution + Zinsen\n║ ────────────────────────────────────\n║ Abzüge:\n{deductionsDetail}\n║ Summe Abzüge              : {totalDeductions} €\n║ ────────────────────────────────────\n║ AUSZAHLUNGSBETRAG:\n╚══════════════════════════════════════╝\n\nDer Auszahlungsbetrag wird auf folgendes Konto überwiesen:\nIBAN: {tenantIban}\n\nHINWEISE:\n• Die Kaution ist vom Vermieter getrennt vom eigenen Vermögen bei einem Kreditinstitut anzulegen (§ 551 Abs. 3 BGB).\n• Die Zinsen stehen dem Mieter zu.\n• Ein angemessener Einbehalt für die noch ausstehende Nebenkostenabrechnung ist zulässig (BGH-Rechtsprechung).\n• Bei streitigen Abzügen steht dem Mieter der Rechtsweg offen.\n\nMit freundlichen Grüßen" },
  ],
};
