import type { DocumentTemplate } from "../types";

export const frFormalNotice: DocumentTemplate = {
  id: "fr-formal-notice",
  version: "2.0.0",
  country: "FR",
  category: "legal",
  docType: "formal-notice",
  label: "Mise en demeure",
  description: "Lettre de mise en demeure formelle conforme aux articles 1344 et suivants du Code civil.",
  legalBasis: "Code civil, art. 1344 et suivants ; Code de la consommation, art. L111-1",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "senderName", label: "Nom complet de l'expéditeur", type: "text", required: true, group: "Expéditeur" },
    { key: "senderAddress", label: "Adresse complète de l'expéditeur", type: "text", required: true, group: "Expéditeur" },
    { key: "senderPhone", label: "Téléphone", type: "phone", required: false, group: "Expéditeur" },
    { key: "senderEmail", label: "Email", type: "email", required: false, group: "Expéditeur" },
    { key: "recipientName", label: "Nom complet du destinataire", type: "text", required: true, group: "Destinataire" },
    { key: "recipientAddress", label: "Adresse complète du destinataire", type: "text", required: true, group: "Destinataire" },
    { key: "subject", label: "Objet de la mise en demeure", type: "text", required: true, placeholder: "Ex: Loyers impayés, travaux non réalisés, restitution du dépôt de garantie…", group: "Objet" },
    { key: "amount", label: "Montant réclamé (€)", type: "number", required: false, validation: { min: 0 }, group: "Objet" },
    { key: "factDescription", label: "Exposé détaillé des faits", type: "textarea", required: true, validation: { minLength: 20, maxLength: 5000 }, placeholder: "Décrivez chronologiquement les faits justifiant cette mise en demeure…", group: "Objet" },
    { key: "legalBasisDetail", label: "Fondement juridique (optionnel)", type: "textarea", required: false, placeholder: "Articles de loi, clauses contractuelles…", group: "Objet" },
    { key: "previousReminders", label: "Rappels préalables effectués", type: "textarea", required: false, placeholder: "Courrier du 01/01/2026, appel téléphonique du…", group: "Objet" },
    { key: "deadline", label: "Délai accordé (jours)", type: "number", required: true, validation: { min: 1, max: 90 }, defaultValue: 15, group: "Délai" },
    { key: "sendDate", label: "Date d'envoi", type: "date", required: true, group: "Délai" },
  ],
  clauses: [
    { id: "header", label: "En-tête", required: true,
      text: "LETTRE RECOMMANDÉE AVEC ACCUSÉ DE RÉCEPTION\n\n{senderName}\n{senderAddress}\n\nÀ l'attention de\n{recipientName}\n{recipientAddress}\n\nFait le {sendDate}\n\nObjet : MISE EN DEMEURE — {subject}" },
    { id: "rappel", label: "Rappel des faits", required: true,
      text: "Madame, Monsieur,\n\nPar la présente, je me permets de vous rappeler les faits suivants :\n\n{factDescription}" },
    { id: "previous", label: "Rappels antérieurs", required: false,
      conditional: (data) => !!data.previousReminders && String(data.previousReminders).length > 3,
      text: "Je vous ai d'ores et déjà adressé les relances suivantes, restées sans effet :\n\n{previousReminders}" },
    { id: "legal-basis", label: "Fondement juridique", required: false,
      conditional: (data) => !!data.legalBasisDetail && String(data.legalBasisDetail).length > 3,
      text: "Cette demande est fondée sur les dispositions suivantes :\n\n{legalBasisDetail}" },
    { id: "formal-demand", label: "Mise en demeure formelle", required: true,
      text: "EN CONSÉQUENCE, je vous mets formellement en demeure, en application des articles 1344 et suivants du Code civil, de procéder à {subject} dans un délai de {deadline} jours à compter de la réception du présent courrier.\n\nLe montant total réclamé s'élève à {amount} €." },
    { id: "consequences", label: "Conséquences en cas d'inexécution", required: true,
      text: "AVERTISSEMENT\n\nÀ défaut de régularisation de votre situation dans le délai imparti, je me réserve le droit, sans autre avis :\n\n• De saisir les juridictions compétentes (Tribunal judiciaire, Juge de proximité) pour obtenir la condamnation au paiement des sommes dues, augmentées des intérêts de retard au taux légal à compter de la présente mise en demeure (art. 1231-6 du Code civil) ;\n• De réclamer des dommages et intérêts en réparation du préjudice subi ;\n• D'engager toute procédure d'exécution forcée que la loi autorise.\n\nJe vous rappelle que les frais de procédure et honoraires d'avocat seront à votre charge en cas de condamnation.\n\nLa présente mise en demeure constitue le point de départ des intérêts moratoires conformément à l'article 1344-1 du Code civil.\n\nDans l'espoir d'un règlement amiable, je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées." },
  ],
};
