import type { DocumentTemplate } from "../types";

export const frInventory: DocumentTemplate = {
  id: "fr-inventory",
  version: "2.0.0",
  country: "FR",
  category: "rental",
  docType: "inventory",
  label: "État des lieux",
  description: "État des lieux d'entrée ou de sortie conforme à la loi ALUR et au décret n° 2016-382.",
  legalBasis: "Loi n° 89-462 du 6 juillet 1989, art. 3-2 ; Décret n° 2016-382 du 30 mars 2016",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "inventoryType", label: "Type d'état des lieux", type: "select", required: true, options: [
      { value: "entree", label: "Entrée dans les lieux" }, { value: "sortie", label: "Sortie des lieux" },
    ], group: "Type" },
    { key: "propertyAddress", label: "Adresse complète du logement", type: "text", required: true, group: "Logement" },
    { key: "propertyType", label: "Type de logement", type: "select", required: true, options: [
      { value: "appartement", label: "Appartement" }, { value: "maison", label: "Maison" }, { value: "studio", label: "Studio" },
    ], group: "Logement" },
    { key: "surface", label: "Surface habitable (m²)", type: "number", required: false, group: "Logement" },
    { key: "floor", label: "Étage", type: "number", required: false, group: "Logement" },
    { key: "landlordName", label: "Nom du bailleur (ou mandataire)", type: "text", required: true, group: "Parties" },
    { key: "tenantName", label: "Nom du locataire", type: "text", required: true, group: "Parties" },
    { key: "inventoryDate", label: "Date de l'état des lieux", type: "date", required: true, group: "Informations" },
    { key: "meterElec", label: "Relevé compteur électricité (kWh)", type: "number", required: false, group: "Compteurs" },
    { key: "meterGas", label: "Relevé compteur gaz (m³)", type: "number", required: false, group: "Compteurs" },
    { key: "meterWater", label: "Relevé compteur eau (m³)", type: "number", required: false, group: "Compteurs" },
    { key: "meterHotWater", label: "Relevé compteur eau chaude (m³)", type: "number", required: false, group: "Compteurs" },
    { key: "keysCount", label: "Nombre total de clés remises", type: "number", required: true, validation: { min: 1 }, group: "Clés" },
    { key: "keysDetail", label: "Détail des clés (badges, télécommandes…)", type: "textarea", required: false, placeholder: "2 clés porte d'entrée\n1 clé cave\n1 badge parking\n1 télécommande portail", group: "Clés" },
    { key: "rooms", label: "Description pièce par pièce", type: "textarea", required: true, placeholder: "ENTRÉE :\n- Sol : carrelage — bon état\n- Murs : peinture blanche — bon état\n- Plafond : bon état\n- Porte d'entrée : bon état\n\nSÉJOUR :\n- Sol : parquet — bon état\n- Murs : peinture blanche — bon état\n...", validation: { minLength: 20 }, group: "Description" },
    { key: "observations", label: "Observations générales et réserves", type: "textarea", required: false, placeholder: "Traces d'humidité constatées dans la salle de bains…", group: "Observations" },
  ],
  clauses: [
    { id: "header", label: "En-tête", required: true,
      text: "ÉTAT DES LIEUX D'{inventoryType}\n(Établi conformément au décret n° 2016-382 du 30 mars 2016)\n\nDate : {inventoryDate}\n\nÉtabli contradictoirement et amiablement entre :\n\n• Le bailleur (ou son mandataire) : {landlordName}\n• Le locataire : {tenantName}\n\nConcernant le logement situé au :\n{propertyAddress}\nType : {propertyType} — Surface : {surface} m² — Étage : {floor}" },
    { id: "meters", label: "Relevés des compteurs", required: true,
      text: "RELEVÉS DES COMPTEURS\n\n• Électricité : {meterElec} kWh\n• Gaz : {meterGas} m³\n• Eau froide : {meterWater} m³\n• Eau chaude : {meterHotWater} m³\n\nLes relevés ci-dessus ont été effectués en présence des deux parties." },
    { id: "keys", label: "Remise des clés", required: true,
      text: "CLÉS ET MOYENS D'ACCÈS\n\nNombre total de clés remises : {keysCount}\n\nDétail :\n{keysDetail}" },
    { id: "rooms-detail", label: "Description pièce par pièce", required: true,
      text: "DESCRIPTION DÉTAILLÉE DU LOGEMENT\n(État de chaque pièce : murs, sols, plafonds, menuiseries, équipements)\n\n{rooms}" },
    { id: "observations-clause", label: "Observations et réserves", required: false,
      conditional: (data) => !!data.observations && String(data.observations).length > 3,
      text: "OBSERVATIONS ET RÉSERVES\n\n{observations}" },
    { id: "legal-notice", label: "Mentions légales", required: true,
      text: "INFORMATIONS LÉGALES\n\n• Le présent état des lieux est établi en application de l'article 3-2 de la loi du 6 juillet 1989.\n• En cas de désaccord, chaque partie peut faire appel à un huissier de justice (art. 3-2 al. 3). Les frais sont alors partagés par moitié.\n• Le locataire dispose d'un délai de 10 jours à compter de la remise des clés pour compléter l'état des lieux d'entrée et d'un mois pour les éléments de chauffage.\n• À défaut d'état des lieux d'entrée, le locataire est présumé avoir reçu le logement en bon état (art. 1731 du Code civil).\n• L'état des lieux de sortie sera comparé à celui d'entrée pour déterminer les réparations locatives éventuellement imputables au locataire.\n\nFait en deux exemplaires, un pour chaque partie.\nChaque partie reconnaît avoir reçu un exemplaire du présent état des lieux." },
  ],
};

export const frRentRevision: DocumentTemplate = {
  id: "fr-rent-revision",
  version: "2.0.0",
  country: "FR",
  category: "rental",
  docType: "rent-revision",
  label: "Révision de loyer (IRL)",
  description: "Courrier de notification de révision annuelle du loyer basée sur l'IRL, conforme à l'article 17-1.",
  legalBasis: "Loi n° 89-462 du 6 juillet 1989, art. 17-1",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "landlordName", label: "Nom du bailleur", type: "text", required: true, group: "Bailleur" },
    { key: "landlordAddress", label: "Adresse du bailleur", type: "text", required: true, group: "Bailleur" },
    { key: "tenantName", label: "Nom du locataire", type: "text", required: true, group: "Locataire" },
    { key: "tenantAddress", label: "Adresse du locataire", type: "text", required: false, group: "Locataire" },
    { key: "propertyAddress", label: "Adresse du logement", type: "text", required: true, group: "Bien" },
    { key: "leaseDate", label: "Date de signature du bail", type: "date", required: false, group: "Bail" },
    { key: "currentRent", label: "Loyer actuel hors charges (€)", type: "number", required: true, validation: { min: 1 }, group: "Révision" },
    { key: "irlOld", label: "IRL de référence du bail (ancien)", type: "number", required: true, validation: { min: 1 }, group: "Révision" },
    { key: "irlOldQuarter", label: "Trimestre IRL ancien", type: "text", required: false, placeholder: "Ex: T4 2024", group: "Révision" },
    { key: "irlNew", label: "Nouvel IRL applicable", type: "number", required: true, validation: { min: 1 }, group: "Révision" },
    { key: "irlNewQuarter", label: "Trimestre IRL nouveau", type: "text", required: false, placeholder: "Ex: T4 2025", group: "Révision" },
    { key: "revisionDate", label: "Date d'anniversaire du bail", type: "date", required: true, group: "Dates" },
    { key: "effectiveDate", label: "Date d'effet du nouveau loyer", type: "date", required: true, group: "Dates" },
  ],
  clauses: [
    { id: "header", label: "En-tête", required: true,
      text: "{landlordName}\n{landlordAddress}\n\nÀ l'attention de {tenantName}\n{tenantAddress}\n\nFait le {revisionDate}" },
    { id: "notification", label: "Notification de révision", required: true,
      text: "Objet : Révision annuelle du loyer — Logement situé au {propertyAddress}\n\nMadame, Monsieur,\n\nConformément aux dispositions de l'article 17-1 de la loi n° 89-462 du 6 juillet 1989 et à la clause de révision prévue au contrat de bail signé le {leaseDate}, je procède à la révision annuelle de votre loyer.\n\nLa formule légale de calcul est la suivante :\nNouveau loyer = Loyer actuel × (Nouvel IRL / Ancien IRL)\n\n╔══════════════════════════════════════╗\n║ Loyer actuel HC         : {currentRent} €\n║ Ancien IRL ({irlOldQuarter})    : {irlOld}\n║ Nouvel IRL ({irlNewQuarter})    : {irlNew}\n║ ────────────────────────────────────\n║ Nouveau loyer calculé   : voir calcul\n╚══════════════════════════════════════╝\n\nLe nouveau loyer sera applicable à compter du {effectiveDate}.\n\nJe vous rappelle que cette révision est plafonnée par la variation de l'IRL et ne peut excéder le taux légal autorisé. Les charges locatives restent inchangées par cette révision.\n\nVeuillez agréer, Madame, Monsieur, l'expression de mes salutations distinguées." },
  ],
};

export const frChargesRegularization: DocumentTemplate = {
  id: "fr-charges-regularization",
  version: "2.0.0",
  country: "FR",
  category: "rental",
  docType: "charges-regularization",
  label: "Régularisation des charges",
  description: "Décompte annuel de régularisation des charges locatives conforme à l'article 23.",
  legalBasis: "Loi n° 89-462 du 6 juillet 1989, art. 23 ; Décret n° 87-713 du 26 août 1987",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "landlordName", label: "Nom du bailleur", type: "text", required: true, group: "Bailleur" },
    { key: "landlordAddress", label: "Adresse du bailleur", type: "text", required: false, group: "Bailleur" },
    { key: "tenantName", label: "Nom du locataire", type: "text", required: true, group: "Locataire" },
    { key: "propertyAddress", label: "Adresse du logement", type: "text", required: true, group: "Bien" },
    { key: "periodStart", label: "Début de la période de régularisation", type: "date", required: true, group: "Période" },
    { key: "periodEnd", label: "Fin de la période de régularisation", type: "date", required: true, group: "Période" },
    { key: "totalCharges", label: "Total des charges réelles récupérables (€)", type: "number", required: true, validation: { min: 0 }, group: "Montants" },
    { key: "provisionsPaid", label: "Total des provisions versées par le locataire (€)", type: "number", required: true, validation: { min: 0 }, group: "Montants" },
    { key: "chargesDetail", label: "Détail des charges par poste", type: "textarea", required: true, placeholder: "Eau froide/chaude : 180 €\nOrdures ménagères (TEOM) : 95 €\nEntretien parties communes : 220 €\nAscenseur : 120 €\nChauffage collectif : 350 €\nÉclairage parties communes : 45 €\nEntretien espaces verts : 60 €", group: "Détail" },
  ],
  clauses: [
    { id: "header", label: "En-tête", required: true,
      text: "{landlordName}\n{landlordAddress}\n\nÀ l'attention de {tenantName}\n\nLogement : {propertyAddress}" },
    { id: "regularization", label: "Décompte de régularisation", required: true,
      text: "RÉGULARISATION ANNUELLE DES CHARGES LOCATIVES\n(Article 23 de la loi du 6 juillet 1989)\n\nPériode concernée : du {periodStart} au {periodEnd}\n\nDÉTAIL DES CHARGES RÉCUPÉRABLES :\n(Conformément au décret n° 87-713 du 26 août 1987)\n\n{chargesDetail}\n\n╔══════════════════════════════════════╗\n║ Total charges réelles     : {totalCharges} €\n║ Provisions versées        : {provisionsPaid} €\n║ ────────────────────────────────────\n║ Solde (+ = dû par locataire, - = trop-perçu)\n╚══════════════════════════════════════╝\n\nConformément à l'article 23 de la loi du 6 juillet 1989, un mois avant la régularisation, le décompte des charges est communiqué au locataire. Les pièces justificatives sont tenues à votre disposition pendant 6 mois à compter de l'envoi du décompte.\n\nEn cas de trop-perçu, le montant sera déduit de votre prochain appel de loyer ou remboursé dans le mois suivant.\nEn cas de complément dû, celui-ci peut être étalé sur 12 mois si la régularisation n'a pas été effectuée dans l'année civile suivant l'exercice.\n\nVeuillez agréer, Madame, Monsieur, l'expression de mes salutations distinguées." },
  ],
};

export const frUnpaidNotice: DocumentTemplate = {
  id: "fr-unpaid-notice",
  version: "2.0.0",
  country: "FR",
  category: "rental",
  docType: "unpaid-notice",
  label: "Relance de loyer impayé",
  description: "Courrier de relance amiable pour loyer impayé, conforme aux bonnes pratiques juridiques.",
  legalBasis: "Code civil, art. 1728 ; Loi n° 89-462 du 6 juillet 1989",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "landlordName", label: "Nom du bailleur", type: "text", required: true, group: "Bailleur" },
    { key: "landlordAddress", label: "Adresse du bailleur", type: "text", required: true, group: "Bailleur" },
    { key: "landlordPhone", label: "Téléphone du bailleur", type: "phone", required: false, group: "Bailleur" },
    { key: "tenantName", label: "Nom du locataire", type: "text", required: true, group: "Locataire" },
    { key: "tenantAddress", label: "Adresse du locataire", type: "text", required: true, group: "Locataire" },
    { key: "propertyAddress", label: "Adresse du logement loué", type: "text", required: false, group: "Bien" },
    { key: "unpaidMonth", label: "Mois impayé", type: "text", required: true, placeholder: "Janvier 2026", group: "Impayé" },
    { key: "unpaidAmount", label: "Montant impayé (€)", type: "number", required: true, validation: { min: 1 }, group: "Impayé" },
    { key: "dueDate", label: "Date d'échéance initiale", type: "date", required: true, group: "Impayé" },
    { key: "relanceLevel", label: "Niveau de relance", type: "select", required: true, options: [
      { value: "1", label: "1ère relance (amiable)" },
      { value: "2", label: "2ème relance (ferme)" },
      { value: "3", label: "3ème relance (mise en garde)" },
    ], defaultValue: "1", group: "Impayé" },
    { key: "noticeDate", label: "Date du courrier", type: "date", required: true, group: "Date" },
  ],
  clauses: [
    { id: "header", label: "En-tête", required: true,
      text: "{landlordName}\n{landlordAddress}\n\nÀ l'attention de {tenantName}\n{tenantAddress}\n\nFait le {noticeDate}" },
    { id: "notice-1", label: "1ère relance amiable", required: false,
      conditional: (data) => data.relanceLevel === "1",
      text: "Objet : Rappel de loyer impayé — {unpaidMonth}\n\nMadame, Monsieur,\n\nSauf erreur ou omission de ma part, je constate que le loyer du mois de {unpaidMonth}, d'un montant de {unpaidAmount} €, dont l'échéance était fixée au {dueDate}, n'a toujours pas été réglé à ce jour.\n\nCette situation est peut-être due à un simple oubli. Aussi, je vous serais reconnaissant(e) de bien vouloir procéder au règlement de cette somme dans les meilleurs délais.\n\nSi toutefois vous rencontrez des difficultés de paiement, je vous invite à me contacter afin que nous puissions trouver ensemble une solution amiable (échéancier de paiement, etc.).\n\nJe vous rappelle que le paiement du loyer aux termes convenus est une obligation légale du locataire en vertu de l'article 7 de la loi du 6 juillet 1989.\n\nVeuillez agréer, Madame, Monsieur, l'expression de mes salutations distinguées." },
    { id: "notice-2", label: "2ème relance ferme", required: false,
      conditional: (data) => data.relanceLevel === "2",
      text: "Objet : SECONDE RELANCE — Loyer impayé {unpaidMonth}\n\nMadame, Monsieur,\n\nMalgré mon précédent courrier, je constate que le loyer du mois de {unpaidMonth}, d'un montant de {unpaidAmount} €, échu le {dueDate}, demeure impayé à ce jour.\n\nJe vous mets en demeure de régulariser cette situation sous huitaine à compter de la réception du présent courrier.\n\nJe vous informe que le non-paiement du loyer constitue un manquement grave aux obligations du bail pouvant entraîner :\n• La résiliation judiciaire du bail ;\n• Le commandement de payer par voie d'huissier ;\n• Le recouvrement forcé de la créance.\n\nJe vous invite instamment à procéder au règlement immédiat de cette somme ou à me contacter pour convenir d'un plan d'apurement.\n\nVeuillez agréer, Madame, Monsieur, l'expression de mes salutations distinguées." },
    { id: "notice-3", label: "3ème relance — mise en garde", required: false,
      conditional: (data) => data.relanceLevel === "3",
      text: "LETTRE RECOMMANDÉE AVEC ACCUSÉ DE RÉCEPTION\n\nObjet : DERNIÈRE RELANCE AVANT PROCÉDURE — Loyer impayé {unpaidMonth}\n\nMadame, Monsieur,\n\nMes précédentes relances étant restées sans effet, je constate avec regret que le loyer du mois de {unpaidMonth}, d'un montant de {unpaidAmount} €, échu le {dueDate}, n'est toujours pas réglé.\n\nLe présent courrier constitue ma dernière tentative de règlement amiable. À défaut de paiement intégral ou de prise de contact de votre part sous 8 jours à compter de la réception de la présente :\n\n1. Un commandement de payer sera délivré par huissier de justice, conformément à l'article 24 de la loi du 6 juillet 1989 ;\n2. La clause résolutoire du bail sera activée ;\n3. La dette sera déclarée auprès de la Commission de coordination des actions de prévention des expulsions (CCAPEX).\n\nJe vous rappelle que vous pouvez solliciter le Fonds de Solidarité pour le Logement (FSL) de votre département ou vous rapprocher d'un travailleur social.\n\nVeuillez agréer, Madame, Monsieur, l'expression de mes salutations distinguées." },
  ],
};
