import type { DocumentTemplate } from "../types";

export const frTermination: DocumentTemplate = {
  id: "fr-termination",
  version: "2.0.0",
  country: "FR",
  category: "legal",
  docType: "termination",
  label: "Résiliation de contrat",
  description: "Lettre de résiliation de contrat conforme aux lois Hamon et Chatel.",
  legalBasis: "Loi Hamon n° 2014-344 ; Loi Chatel n° 2005-67 ; Code de la consommation, art. L215-1 et suivants",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "senderName", label: "Nom complet de l'expéditeur", type: "text", required: true, group: "Expéditeur" },
    { key: "senderAddress", label: "Adresse complète", type: "text", required: true, group: "Expéditeur" },
    { key: "senderPhone", label: "Téléphone", type: "phone", required: false, group: "Expéditeur" },
    { key: "recipientName", label: "Raison sociale / Nom du prestataire", type: "text", required: true, group: "Destinataire" },
    { key: "recipientAddress", label: "Adresse du prestataire", type: "text", required: true, group: "Destinataire" },
    { key: "contractType", label: "Type de contrat", type: "select", required: true, options: [
      { value: "assurance", label: "Assurance (habitation, auto, santé)" },
      { value: "abonnement", label: "Abonnement / service (téléphonie, internet, box)" },
      { value: "bail", label: "Bail / contrat de location" },
      { value: "energie", label: "Contrat énergie (EDF, gaz)" },
      { value: "autre", label: "Autre contrat" },
    ], group: "Contrat" },
    { key: "contractRef", label: "Numéro de contrat / référence client", type: "text", required: true, group: "Contrat" },
    { key: "contractDate", label: "Date de souscription du contrat", type: "date", required: false, group: "Contrat" },
    { key: "reason", label: "Motif de résiliation", type: "textarea", required: true, validation: { minLength: 10, maxLength: 3000 }, placeholder: "Déménagement, insatisfaction du service, changement de situation, droit de résiliation annuel…", group: "Motif" },
    { key: "legalBasisType", label: "Base légale invoquée", type: "select", required: true, options: [
      { value: "hamon", label: "Loi Hamon (résiliation à tout moment après 1 an)" },
      { value: "chatel", label: "Loi Chatel (non-reconduction tacite)" },
      { value: "demenagement", label: "Déménagement (motif légitime)" },
      { value: "echeance", label: "Résiliation à l'échéance annuelle" },
      { value: "commun-accord", label: "Résiliation d'un commun accord" },
      { value: "autre", label: "Autre fondement" },
    ], defaultValue: "echeance", group: "Motif" },
    { key: "effectiveDate", label: "Date de résiliation souhaitée", type: "date", required: true, group: "Dates" },
    { key: "sendDate", label: "Date d'envoi du courrier", type: "date", required: true, group: "Dates" },
  ],
  clauses: [
    { id: "header", label: "En-tête", required: true,
      text: "LETTRE RECOMMANDÉE AVEC ACCUSÉ DE RÉCEPTION\n\n{senderName}\n{senderAddress}\n\nÀ l'attention du Service Résiliation\n{recipientName}\n{recipientAddress}\n\nFait le {sendDate}\n\nObjet : Résiliation du contrat n° {contractRef}" },
    { id: "termination-request", label: "Demande de résiliation", required: true,
      text: "Madame, Monsieur,\n\nPar la présente lettre recommandée avec accusé de réception, je vous notifie ma décision ferme et définitive de résilier le contrat référencé ci-dessus, souscrit le {contractDate}, avec effet au {effectiveDate}." },
    { id: "motif", label: "Motif détaillé", required: true,
      text: "MOTIF DE LA RÉSILIATION :\n\n{reason}" },
    { id: "legal-hamon", label: "Base légale — Loi Hamon", required: false,
      conditional: (data) => data.legalBasisType === "hamon",
      text: "Cette résiliation est effectuée en application de la loi n° 2014-344 du 17 mars 2014 (loi Hamon) qui permet la résiliation à tout moment, sans frais ni pénalités, après la première année de souscription. Conformément à l'article L113-15-2 du Code des assurances, la résiliation prend effet un mois après réception de la présente." },
    { id: "legal-chatel", label: "Base légale — Loi Chatel", required: false,
      conditional: (data) => data.legalBasisType === "chatel",
      text: "Cette résiliation est effectuée en application de la loi n° 2005-67 du 28 janvier 2005 (loi Chatel). En l'absence d'information préalable de reconduction tacite dans les délais prescrits par l'article L215-1 du Code de la consommation, je suis en droit de résilier le contrat à tout moment, par lettre recommandée, et ce sans frais ni pénalités." },
    { id: "legal-demenagement", label: "Base légale — Déménagement", required: false,
      conditional: (data) => data.legalBasisType === "demenagement",
      text: "Cette résiliation fait suite à un changement de domicile, constituant un motif légitime de résiliation conformément aux conditions générales du contrat et à la jurisprudence en la matière. Un justificatif de domicile pourra être fourni sur demande." },
    { id: "legal-echeance", label: "Base légale — Échéance", required: false,
      conditional: (data) => data.legalBasisType === "echeance",
      text: "Cette résiliation est notifiée dans le respect du préavis contractuel, conformément aux articles L215-1 et suivants du Code de la consommation et aux conditions générales du contrat. Le contrat prendra fin à sa prochaine échéance annuelle." },
    { id: "demandes", label: "Demandes complémentaires", required: true,
      text: "En conséquence, je vous demande de bien vouloir :\n\n• Prendre acte de la résiliation à la date indiquée ;\n• Cesser tout prélèvement automatique à compter de cette date ;\n• Me transmettre un courrier de confirmation de résiliation ;\n• Procéder au remboursement du trop-perçu éventuel dans les meilleurs délais ;\n• Me restituer, le cas échéant, le dépôt de garantie dans les délais légaux.\n\nJe me tiens à votre disposition pour toute formalité complémentaire. Je vous prie de bien vouloir m'adresser un accusé de réception de la présente.\n\nVeuillez agréer, Madame, Monsieur, l'expression de mes salutations distinguées." },
  ],
};
