/**
 * Seed data for Easy-Locs marketplace.
 * Demo shops, services, and products to avoid an empty app.
 * Run once from admin panel or on first boot.
 */
import { supabase } from "@/integrations/supabase/client";

export const SEED_LISTINGS = [
  // ── Shops ──
  {
    title: "Easy-Locs Concept Store Dubai",
    category: "products",
    listing_type: "shop",
    city: "Dubai",
    country: "AE",
    description: "Premium electronics, fashion, and lifestyle products in Dubai Marina. Open daily 10am–10pm.",
    price: 0,
    currency: "AED",
    price_type: "fixed",
    presence_mode: "pin",
    entity_type: "fixed_store",
    coverage_mode: "radius",
    coverage_radius_m: 2000,
    lat: 25.0762,
    lng: 55.1342,
    anchor_lat: 25.0762,
    anchor_lng: 55.1342,
  },
  {
    title: "Marché Bio Saint-Germain",
    category: "products",
    listing_type: "shop",
    city: "Paris",
    country: "FR",
    description: "Organic groceries, artisan bread, and local produce. Certified bio since 2018.",
    price: 0,
    currency: "EUR",
    price_type: "fixed",
    presence_mode: "pin",
    entity_type: "fixed_store",
    coverage_mode: "point",
    coverage_radius_m: null,
    lat: 48.8534,
    lng: 2.3343,
    anchor_lat: 48.8534,
    anchor_lng: 2.3343,
  },
  // ── Services ──
  {
    title: "Express Cleaning Pro",
    category: "services",
    listing_type: "service",
    city: "Dubai",
    country: "AE",
    description: "Professional deep cleaning for apartments and villas. Available 7/7. Same-day booking.",
    price: 150,
    currency: "AED",
    price_type: "per_hour",
    presence_mode: "live",
    entity_type: "mobile_service",
    coverage_mode: "live_radius",
    coverage_radius_m: 15000,
    lat: 25.2048,
    lng: 55.2708,
    anchor_lat: 25.2048,
    anchor_lng: 55.2708,
  },
  {
    title: "Yacht Charter & Tours",
    category: "tourism",
    listing_type: "service",
    city: "Dubai",
    country: "AE",
    description: "Luxury yacht experiences in Dubai Marina. Sunset cruises, fishing trips, and private parties.",
    price: 800,
    currency: "AED",
    price_type: "per_hour",
    presence_mode: "pin",
    entity_type: "fixed_store",
    coverage_mode: "radius",
    coverage_radius_m: 5000,
    lat: 25.0804,
    lng: 55.1372,
    anchor_lat: 25.0804,
    anchor_lng: 55.1372,
  },
  {
    title: "Mobile Phone Repair — On-site",
    category: "services",
    listing_type: "service",
    city: "Paris",
    country: "FR",
    description: "iPhone & Samsung repair at your location. Screen, battery, charging port. 30-min average.",
    price: 49,
    currency: "EUR",
    price_type: "fixed",
    presence_mode: "live",
    entity_type: "mobile_service",
    coverage_mode: "live_radius",
    coverage_radius_m: 10000,
    lat: 48.8566,
    lng: 2.3522,
    anchor_lat: 48.8566,
    anchor_lng: 2.3522,
  },
  // ── Sale listings (auto-expire 30 days) ──
  {
    title: "iPhone 15 Pro Max 256GB — Like New",
    category: "products",
    listing_type: "sale",
    city: "Dubai",
    country: "AE",
    description: "Natural Titanium, UAE warranty until Dec 2026. Includes original box and accessories.",
    price: 3200,
    currency: "AED",
    price_type: "fixed",
    presence_mode: "pin",
    entity_type: "fixed_store",
    coverage_mode: "point",
    coverage_radius_m: null,
    lat: 25.2050,
    lng: 55.2700,
    anchor_lat: 25.2050,
    anchor_lng: 55.2700,
  },
  {
    title: "MacBook Pro M3 14\" — Sealed",
    category: "products",
    listing_type: "sale",
    city: "Paris",
    country: "FR",
    description: "Brand new sealed. 18GB RAM, 512GB SSD. Official Apple France warranty.",
    price: 1899,
    currency: "EUR",
    price_type: "fixed",
    presence_mode: "pin",
    entity_type: "fixed_store",
    coverage_mode: "point",
    coverage_radius_m: null,
    lat: 48.8620,
    lng: 2.3410,
    anchor_lat: 48.8620,
    anchor_lng: 2.3410,
  },
  // ── Drivers ──
  {
    title: "VTC Premium — Airport Transfers",
    category: "services",
    listing_type: "service",
    city: "Dubai",
    country: "AE",
    description: "Luxury sedan transfers to DXB & DWC airports. Meet & greet, flight tracking, free waiting.",
    price: 200,
    currency: "AED",
    price_type: "fixed",
    presence_mode: "live",
    entity_type: "driver",
    coverage_mode: "live_radius",
    coverage_radius_m: 25000,
    lat: 25.2532,
    lng: 55.3657,
    anchor_lat: 25.2532,
    anchor_lng: 55.3657,
  },
  // ── Mobile Seller ──
  {
    title: "Fresh Juice Cart — Marina Walk",
    category: "products",
    listing_type: "shop",
    city: "Dubai",
    country: "AE",
    description: "Fresh-squeezed juices, smoothies, and açaí bowls. Moving along Marina Walk daily 8am–6pm.",
    price: 25,
    currency: "AED",
    price_type: "fixed",
    presence_mode: "live",
    entity_type: "mobile_seller",
    coverage_mode: "live_radius",
    coverage_radius_m: 3000,
    lat: 25.0780,
    lng: 55.1350,
    anchor_lat: 25.0780,
    anchor_lng: 55.1350,
  },
];

/**
 * Insert seed data into marketplace_services.
 * Requires an authenticated user with org_id and provider_id.
 */
export async function insertSeedListings(orgId: string, userId: string, providerId: string) {
  const results = [];

  for (const seed of SEED_LISTINGS) {
    const isSale = seed.listing_type === "sale";
    const expiresAt = isSale ? new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString() : null;
    const slug = seed.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-+$/, "");

    const { data, error } = await supabase.from("marketplace_services").insert({
      org_id: orgId,
      user_id: userId,
      provider_id: providerId,
      title: seed.title,
      category: seed.category,
      listing_type: seed.listing_type,
      city: seed.city,
      country: seed.country,
      description: seed.description,
      price: seed.price,
      currency: seed.currency,
      price_type: seed.price_type,
      presence_mode: seed.presence_mode,
      entity_type: seed.entity_type,
      coverage_mode: seed.coverage_mode,
      coverage_radius_m: seed.coverage_radius_m,
      lat: seed.lat,
      lng: seed.lng,
      anchor_lat: seed.anchor_lat,
      anchor_lng: seed.anchor_lng,
      booking_slug: slug,
      active: true,
      status: "published" as any,
      auto_expire: isSale,
      listing_expires_at: expiresAt,
    } as any).select("id").single();

    results.push({ title: seed.title, id: data?.id, error: error?.message });
  }

  return results;
}
