
ALTER TABLE public.marketplace_providers
  ADD COLUMN IF NOT EXISTS completed_jobs INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS response_rate INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS response_time TEXT,
  ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ;
