/**
 * DINO V8 — Auto Professional Acquisition Engine
 * Pre-creates draft profiles and triggers onboarding invitations.
 */

export interface ImportedProfessional {
  externalId: string;
  source: string;               // e.g., "directory", "import", "scan"
  name: string;
  category: string;
  subcategory?: string;
  city: string;
  country: string;
  phone?: string;
  email?: string;
  website?: string;
  address?: string;
  description?: string;
  imageUrls?: string[];
}

export interface DraftProfile {
  id: string;
  externalId: string;
  source: string;
  name: string;
  category: string;
  city: string;
  country: string;
  status: "draft" | "invited" | "pending_activation" | "active";
  completeness: number;         // 0-1
  autoGeneratedFields: string[];
  invitationSentAt?: string;
  activatedAt?: string;
}

export function createDraftProfile(imported: ImportedProfessional): DraftProfile {
  const autoGenerated: string[] = ["id", "status"];

  // Track which fields were pre-filled vs auto-generated
  if (imported.description) autoGenerated.push("description");
  if (imported.imageUrls?.length) autoGenerated.push("images");
  if (imported.phone) autoGenerated.push("phone");
  if (imported.email) autoGenerated.push("email");

  const filledFields = [
    imported.name, imported.category, imported.city, imported.country,
    imported.phone, imported.email, imported.description, imported.address,
  ].filter(Boolean).length;

  const totalFields = 8;
  const completeness = filledFields / totalFields;

  return {
    id: crypto.randomUUID(),
    externalId: imported.externalId,
    source: imported.source,
    name: imported.name,
    category: imported.category,
    city: imported.city,
    country: imported.country,
    status: "draft",
    completeness,
    autoGeneratedFields: autoGenerated,
  };
}

export function batchCreateDrafts(imports: ImportedProfessional[]): {
  drafts: DraftProfile[];
  duplicatesSkipped: number;
  created: number;
} {
  const seen = new Set<string>();
  const drafts: DraftProfile[] = [];
  let duplicatesSkipped = 0;

  for (const imp of imports) {
    const key = `${imp.name.toLowerCase()}:${imp.city.toLowerCase()}:${imp.category}`;
    if (seen.has(key)) { duplicatesSkipped++; continue; }
    seen.add(key);
    drafts.push(createDraftProfile(imp));
  }

  return { drafts, duplicatesSkipped, created: drafts.length };
}

export interface ActivationAction {
  profileId: string;
  actionType: "send_invitation" | "send_reminder" | "offer_quick_activation" | "escalate";
  channel: "email" | "sms" | "whatsapp";
  templateKey: string;
  priority: "high" | "medium" | "low";
}

export function generateActivationActions(drafts: DraftProfile[]): ActivationAction[] {
  const actions: ActivationAction[] = [];

  for (const draft of drafts) {
    if (draft.status === "draft") {
      actions.push({
        profileId: draft.id,
        actionType: "send_invitation",
        channel: "email",
        templateKey: "pro_invitation",
        priority: draft.completeness > 0.6 ? "high" : "medium",
      });
    }

    if (draft.status === "invited" && draft.invitationSentAt) {
      const daysSince = (Date.now() - new Date(draft.invitationSentAt).getTime()) / 86_400_000;
      if (daysSince > 3 && daysSince <= 7) {
        actions.push({
          profileId: draft.id, actionType: "send_reminder",
          channel: "email", templateKey: "pro_reminder", priority: "medium",
        });
      }
      if (daysSince > 7) {
        actions.push({
          profileId: draft.id, actionType: "offer_quick_activation",
          channel: "sms", templateKey: "pro_quick_activate", priority: "high",
        });
      }
    }
  }

  return actions;
}
