import type { DocumentTemplate } from "../types";

export const roLeaseResidential: DocumentTemplate = {
  id: "ro-lease-residential",
  version: "1.0.0",
  country: "RO",
  category: "rental",
  docType: "lease-residential",
  label: "Contract de închiriere (România)",
  description: "Contract de închiriere conform Codului Civil și Legii nr. 114/1996.",
  legalBasis: "Codul Civil art. 1777–1835; Legea nr. 114/1996 a locuinței",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "landlordName", label: "Numele locatorului", type: "text", required: true, validation: { minLength: 2 }, group: "Locator" },
    { key: "landlordAddress", label: "Adresa locatorului", type: "text", required: true, group: "Locator" },
    { key: "landlordCnp", label: "CNP locator", type: "text", required: false, group: "Locator" },
    { key: "tenantName", label: "Numele locatarului", type: "text", required: true, validation: { minLength: 2 }, group: "Locatar" },
    { key: "tenantAddress", label: "Adresa locatarului", type: "text", required: false, group: "Locatar" },
    { key: "propertyAddress", label: "Adresa imobilului", type: "text", required: true, group: "Imobil" },
    { key: "surface", label: "Suprafață (m²)", type: "number", required: true, validation: { min: 1 }, group: "Imobil" },
    { key: "rooms", label: "Camere", type: "number", required: true, validation: { min: 1 }, group: "Imobil" },
    { key: "rentAmount", label: "Chirie lunară (lei)", type: "number", required: true, validation: { min: 1 }, group: "Financiar" },
    { key: "depositAmount", label: "Garanție (lei)", type: "number", required: true, validation: { min: 0 }, group: "Financiar" },
    { key: "startDate", label: "Data începerii", type: "date", required: true, group: "Durată" },
    { key: "duration", label: "Durată", type: "select", required: true, options: [
      { value: "12", label: "12 luni" },
      { value: "24", label: "24 luni" },
      { value: "60", label: "5 ani" },
    ], defaultValue: "12", group: "Durată" },
  ],
  clauses: [
    { id: "parties", label: "Art. 1 — Părțile", required: true,
      text: "CONTRACT DE ÎNCHIRIERE\n\nLocator: {landlordName}, {landlordAddress}\nLocatar: {tenantName}" },
    { id: "imobil", label: "Art. 2 — Obiectul", required: true,
      text: "Imobilul situat la {propertyAddress}, {surface} m², {rooms} camere." },
    { id: "chirie", label: "Art. 3 — Chiria", required: true,
      text: "Chiria lunară: {rentAmount} lei. Garanție: {depositAmount} lei." },
    { id: "durata", label: "Art. 4 — Durata", required: true,
      text: "Contractul se încheie pe o perioadă de {duration} luni de la {startDate}." },
    { id: "inregistrare", label: "Art. 5 — Înregistrare ANAF", required: true,
      text: "Locatorul are obligația de a înregistra contractul la ANAF în termen de 30 de zile." },
  ],
};

export const roRentReceipt: DocumentTemplate = {
  id: "ro-rent-receipt",
  version: "1.0.0",
  country: "RO",
  category: "rental",
  docType: "rent-receipt",
  label: "Chitanță chirie (România)",
  description: "Chitanță pentru plata chiriei.",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "landlordName", label: "Locator", type: "text", required: true, group: "Locator" },
    { key: "tenantName", label: "Locatar", type: "text", required: true, group: "Locatar" },
    { key: "propertyAddress", label: "Adresă", type: "text", required: true, group: "Imobil" },
    { key: "rentAmount", label: "Chirie (lei)", type: "number", required: true, group: "Sume" },
    { key: "chargesAmount", label: "Utilități (lei)", type: "number", required: true, defaultValue: 0, group: "Sume" },
    { key: "period", label: "Perioadă", type: "text", required: true, placeholder: "Ianuarie 2026", group: "Perioadă" },
    { key: "paymentDate", label: "Data plății", type: "date", required: true, group: "Perioadă" },
  ],
  clauses: [
    { id: "chitanta", label: "Chitanță", required: true,
      text: "CHITANȚĂ CHIRIE\n\n{landlordName} confirmă primirea de la {tenantName}:\n\n• Chirie: {rentAmount} lei\n• Utilități: {chargesAmount} lei\n• TOTAL: {totalAmount} lei\n\npentru perioada {period}, plătit {paymentDate}.\n\nSemnătură:" },
  ],
};
