/**
 * Extra Built-In Workflow Definitions
 * Added by Automation Worker Central task (2026).
 *
 * Extends BUILT_IN_WORKFLOWS in automation-engine.ts:
 * 1. User Onboarding — welcome sequence on registration
 * 2. Merchant Onboarding — verification flow for new merchants
 * 3. Payment Confirmation Notification — payment confirmed alert
 * 4. Booking Reminder Notification — booking created alert + webhook
 * 5. Delivery Update Notification — delivery dispatched updates
 * 6. Auto Escalation — unresolved high-priority issues after timeout
 * 7. Financial Reconciliation — daily payout verification (scheduled)
 */
import type { WorkflowDefinition } from "@/lib/systems/automation-engine";

export const EXTRA_WORKFLOWS: Omit<WorkflowDefinition, "createdBy" | "createdAt" | "updatedAt" | "executionCount" | "lastExecutedAt">[] = [
  {
    workflowId: "wf_user_onboarding",
    name: "User Onboarding",
    description: "Sends a welcome sequence to new users after registration",
    trigger: { type: "event", eventName: "auth:user_registered", schedule: null, conditions: [] },
    steps: [
      {
        stepId: "send_welcome",
        name: "Send Welcome Notification",
        action: "send_notification",
        config: { templateId: "welcome_user", recipientField: "userId" },
        onSuccess: "assign_onboarding_role",
        onFailure: null,
        timeout: 5000,
        retries: 2,
      },
      {
        stepId: "assign_onboarding_role",
        name: "Assign Onboarding Status",
        action: "update_status",
        config: { entity: "user", status: "onboarding" },
        onSuccess: "emit_onboarding_started",
        onFailure: null,
        timeout: 5000,
        retries: 1,
      },
      {
        stepId: "emit_onboarding_started",
        name: "Emit Onboarding Event",
        action: "emit_event",
        config: { eventName: "onboarding:user_started" },
        onSuccess: null,
        onFailure: null,
        timeout: 3000,
        retries: 0,
      },
    ],
    version: 1,
    status: "active",
  },
  {
    workflowId: "wf_merchant_onboarding",
    name: "Merchant Onboarding",
    description: "Verifies and onboards new merchants to the platform",
    trigger: { type: "event", eventName: "merchant:registered", schedule: null, conditions: [] },
    steps: [
      {
        stepId: "notify_team",
        name: "Notify Compliance Team",
        action: "send_notification",
        config: { templateId: "merchant_pending_review", recipientId: "admin" },
        onSuccess: "assign_reviewer",
        onFailure: null,
        timeout: 5000,
        retries: 2,
      },
      {
        stepId: "assign_reviewer",
        name: "Assign Compliance Reviewer",
        action: "assign",
        config: { role: "compliance_officer", entity: "merchant" },
        onSuccess: "update_merchant_status",
        onFailure: null,
        timeout: 5000,
        retries: 1,
      },
      {
        stepId: "update_merchant_status",
        name: "Set Merchant Status to Under Review",
        action: "update_status",
        config: { entity: "merchant", status: "under_review" },
        onSuccess: "notify_merchant",
        onFailure: null,
        timeout: 5000,
        retries: 1,
      },
      {
        stepId: "notify_merchant",
        name: "Notify Merchant of Review",
        action: "send_notification",
        config: { templateId: "merchant_under_review", recipientField: "merchantId" },
        onSuccess: null,
        onFailure: null,
        timeout: 5000,
        retries: 2,
      },
    ],
    version: 1,
    status: "active",
  },
  {
    workflowId: "wf_payment_confirmation",
    name: "Payment Confirmation Notification",
    description: "Sends payment confirmation notification to payer upon successful wallet payment",
    trigger: { type: "event", eventName: "wallet:payment_completed", schedule: null, conditions: [] },
    steps: [
      {
        stepId: "notify_payer",
        name: "Notify Payer of Confirmation",
        action: "send_notification",
        config: { templateId: "payment_confirmed", recipientField: "userId" },
        onSuccess: "emit_confirmation",
        onFailure: null,
        timeout: 5000,
        retries: 2,
      },
      {
        stepId: "emit_confirmation",
        name: "Emit Payment Confirmed Event",
        action: "emit_event",
        config: { eventName: "automation:payment_notification_sent" },
        onSuccess: null,
        onFailure: null,
        timeout: 3000,
        retries: 0,
      },
    ],
    version: 1,
    status: "active",
  },
  {
    workflowId: "wf_booking_reminder",
    name: "Booking Reminder Notification",
    description: "Notifies parties when a booking is created and fires a webhook for external integrations",
    trigger: { type: "event", eventName: "marketplace:booking_created", schedule: null, conditions: [] },
    steps: [
      {
        stepId: "notify_parties",
        name: "Notify Booking Parties",
        action: "send_notification",
        config: { templateId: "booking_confirmed", recipientField: "userId" },
        onSuccess: "webhook_crm",
        onFailure: null,
        timeout: 5000,
        retries: 2,
      },
      {
        stepId: "webhook_crm",
        name: "Fire Booking Webhook",
        action: "webhook",
        config: {
          url: "/api/webhooks/booking-created",
          method: "POST",
          headers: { "Content-Type": "application/json" },
          payloadFields: ["bookingId", "userId", "propertyId", "dateTime"],
        },
        onSuccess: "emit_reminder_scheduled",
        onFailure: null,
        timeout: 10000,
        retries: 3,
      },
      {
        stepId: "emit_reminder_scheduled",
        name: "Emit Reminder Scheduled",
        action: "emit_event",
        config: { eventName: "automation:booking_reminder_scheduled" },
        onSuccess: null,
        onFailure: null,
        timeout: 3000,
        retries: 0,
      },
    ],
    version: 1,
    status: "active",
  },
  {
    workflowId: "wf_delivery_notification",
    name: "Delivery Update Notification",
    description: "Sends real-time delivery status updates to buyers when delivery is dispatched",
    trigger: { type: "event", eventName: "delivery:dispatched", schedule: null, conditions: [] },
    steps: [
      {
        stepId: "notify_buyer_dispatch",
        name: "Notify Buyer of Dispatch",
        action: "send_notification",
        config: { templateId: "delivery_dispatched", recipientField: "buyerId" },
        onSuccess: "call_tracking_api",
        onFailure: null,
        timeout: 5000,
        retries: 2,
      },
      {
        stepId: "call_tracking_api",
        name: "Register with Tracking System",
        action: "call_api",
        config: { endpoint: "delivery_tracking_register" },
        onSuccess: "emit_tracking_active",
        onFailure: "notify_dispatch_fallback",
        timeout: 10000,
        retries: 2,
      },
      {
        stepId: "emit_tracking_active",
        name: "Emit Tracking Active Event",
        action: "emit_event",
        config: { eventName: "tracking:started" },
        onSuccess: null,
        onFailure: null,
        timeout: 3000,
        retries: 0,
      },
      {
        stepId: "notify_dispatch_fallback",
        name: "Escalate Tracking Failure",
        action: "escalate",
        config: { team: "delivery_ops", reason: "tracking_registration_failed" },
        onSuccess: null,
        onFailure: null,
        timeout: 5000,
        retries: 1,
      },
    ],
    version: 1,
    status: "active",
  },
  {
    workflowId: "wf_auto_escalation",
    name: "Auto Escalation",
    description: "Escalates unresolved support issues after a configurable timeout delay",
    trigger: {
      type: "event",
      eventName: "support:ticket_created",
      schedule: null,
      conditions: [{ field: "priority", operator: "in", value: ["high", "critical"] }],
    },
    steps: [
      {
        stepId: "delay_check",
        name: "Wait for Escalation Window",
        action: "delay",
        config: { delayMs: 3600000 },
        onSuccess: "check_status",
        onFailure: null,
        timeout: 3700000,
        retries: 0,
      },
      {
        stepId: "check_status",
        name: "Check Ticket Status via API",
        action: "call_api",
        config: { endpoint: "support_ticket_status" },
        onSuccess: "escalate_team",
        onFailure: null,
        timeout: 10000,
        retries: 2,
      },
      {
        stepId: "escalate_team",
        name: "Escalate to Senior Team",
        action: "escalate",
        config: { team: "senior_support", reason: "ticket_unresolved_timeout" },
        onSuccess: "notify_escalated",
        onFailure: null,
        timeout: 5000,
        retries: 1,
      },
      {
        stepId: "notify_escalated",
        name: "Notify Escalation",
        action: "send_notification",
        config: { templateId: "ticket_escalated", recipientId: "admin" },
        onSuccess: null,
        onFailure: null,
        timeout: 5000,
        retries: 2,
      },
    ],
    version: 1,
    status: "active",
  },
  {
    workflowId: "wf_financial_reconciliation",
    name: "Financial Reconciliation",
    description: "Daily payout verification and financial reconciliation (runs at 02:00)",
    trigger: { type: "schedule", eventName: null, schedule: "0 2 * * *", conditions: [] },
    steps: [
      {
        stepId: "fetch_payouts",
        name: "Fetch Pending Payouts",
        action: "call_api",
        config: { endpoint: "payout_reconciliation_fetch" },
        onSuccess: "verify_totals",
        onFailure: "escalate_finance",
        timeout: 30000,
        retries: 3,
      },
      {
        stepId: "verify_totals",
        name: "Verify Payout Totals",
        action: "call_api",
        config: { endpoint: "payout_verification" },
        onSuccess: "webhook_finance",
        onFailure: "escalate_finance",
        timeout: 30000,
        retries: 2,
      },
      {
        stepId: "webhook_finance",
        name: "Notify Finance System via Webhook",
        action: "webhook",
        config: {
          url: "/api/webhooks/reconciliation-complete",
          method: "POST",
          headers: { "Content-Type": "application/json" },
          payloadFields: ["date", "totalPayouts", "status"],
        },
        onSuccess: "emit_reconciled",
        onFailure: "escalate_finance",
        timeout: 10000,
        retries: 2,
      },
      {
        stepId: "emit_reconciled",
        name: "Emit Reconciliation Complete",
        action: "emit_event",
        config: { eventName: "finance:reconciliation_completed" },
        onSuccess: null,
        onFailure: null,
        timeout: 5000,
        retries: 0,
      },
      {
        stepId: "escalate_finance",
        name: "Escalate to Finance Team",
        action: "escalate",
        config: { team: "finance", reason: "reconciliation_failure" },
        onSuccess: null,
        onFailure: null,
        timeout: 5000,
        retries: 0,
      },
    ],
    version: 1,
    status: "active",
  },
];
