import type { DocumentTemplate } from "../types";

/* ─── Verbale di consegna dettagliato ─── */
export const itVerbaleConsegna: DocumentTemplate = {
  id: "it-verbale-consegna",
  version: "1.0.0",
  country: "IT",
  category: "rental",
  docType: "inventory",
  label: "Verbale di consegna dell'immobile",
  description: "Verbale dettagliato di consegna e riconsegna dell'immobile con letture contatori.",
  legalBasis: "Codice Civile artt. 1590, 1587; Legge 431/1998",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "reportType", label: "Tipo di verbale", type: "select", required: true, options: [
      { value: "consegna", label: "Consegna (ingresso)" },
      { value: "riconsegna", label: "Riconsegna (uscita)" },
    ], group: "Tipo" },
    { key: "propertyAddress", label: "Indirizzo dell'immobile", type: "text", required: true, group: "Immobile" },
    { key: "cadastralData", label: "Dati catastali", type: "text", required: false, group: "Immobile" },
    { key: "landlordName", label: "Locatore", type: "text", required: true, group: "Parti" },
    { key: "tenantName", label: "Conduttore", type: "text", required: true, group: "Parti" },
    { key: "reportDate", label: "Data del verbale", type: "date", required: true, group: "Data" },
    { key: "meterElec", label: "Lettura contatore elettricità (kWh)", type: "number", required: false, group: "Contatori" },
    { key: "meterGas", label: "Lettura contatore gas (m³)", type: "number", required: false, group: "Contatori" },
    { key: "meterWater", label: "Lettura contatore acqua (m³)", type: "number", required: false, group: "Contatori" },
    { key: "keysCount", label: "Numero chiavi consegnate", type: "number", required: true, group: "Chiavi" },
    { key: "keysDetail", label: "Dettaglio chiavi", type: "textarea", required: false, placeholder: "2 chiavi portone\n2 chiavi appartamento\n1 chiave cantina\n1 telecomando garage", group: "Chiavi" },
    { key: "roomsDescription", label: "Descrizione stanza per stanza", type: "textarea", required: true, validation: { minLength: 20 }, placeholder: "INGRESSO:\n- Pavimento: piastrelle — buono stato\n- Pareti: pittura bianca — buono stato\n\nSOGGIORNO:\n- Pavimento: parquet — buono stato\n...", group: "Stato" },
    { key: "observations", label: "Osservazioni e riserve", type: "textarea", required: false, group: "Osservazioni" },
  ],
  clauses: [
    { id: "header", label: "Intestazione", required: true,
      text: "VERBALE DI {reportType} DELL'IMMOBILE\n\nData: {reportDate}\n\nRedatto tra:\n• Locatore: {landlordName}\n• Conduttore: {tenantName}\n\nImmobile: {propertyAddress}\nDati catastali: {cadastralData}" },
    { id: "contatori", label: "Letture contatori", required: true,
      text: "LETTURE DEI CONTATORI\n\n• Elettricità: {meterElec} kWh\n• Gas: {meterGas} m³\n• Acqua: {meterWater} m³\n\nLe letture sono state effettuate in presenza di entrambe le parti." },
    { id: "chiavi", label: "Consegna chiavi", required: true,
      text: "CHIAVI E MEZZI DI ACCESSO\n\nNumero totale chiavi consegnate: {keysCount}\n\nDettaglio:\n{keysDetail}" },
    { id: "stato", label: "Stato dell'immobile", required: true,
      text: "DESCRIZIONE DETTAGLIATA DELLO STATO\n(Pavimenti, pareti, soffitti, serramenti, impianti, arredi)\n\n{roomsDescription}" },
    { id: "osservazioni", label: "Osservazioni", required: false,
      conditional: (data) => !!data.observations && String(data.observations).length > 3,
      text: "OSSERVAZIONI E RISERVE\n\n{observations}" },
    { id: "firme", label: "Firme", required: true,
      text: "Entrambe le parti dichiarano la conformità del presente verbale.\n\nOgni parte riceve una copia.\n\nLuogo e data: ____________\n\nFirma del locatore:                    Firma del conduttore:" },
  ],
};

/* ─── Aggiornamento ISTAT del canone ─── */
export const itAggiornamentoIstat: DocumentTemplate = {
  id: "it-aggiornamento-istat",
  version: "1.0.0",
  country: "IT",
  category: "rental",
  docType: "rent-revision",
  label: "Aggiornamento ISTAT del canone",
  description: "Comunicazione di aggiornamento annuale del canone secondo l'indice FOI ISTAT.",
  legalBasis: "Legge 392/1978, art. 32; Legge 431/1998; Codice Civile art. 1571",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "landlordName", label: "Nome del locatore", type: "text", required: true, group: "Locatore" },
    { key: "landlordAddress", label: "Indirizzo", type: "text", required: true, group: "Locatore" },
    { key: "tenantName", label: "Nome del conduttore", type: "text", required: true, group: "Conduttore" },
    { key: "tenantAddress", label: "Indirizzo", type: "text", required: true, group: "Conduttore" },
    { key: "propertyAddress", label: "Indirizzo dell'immobile", type: "text", required: true, group: "Immobile" },
    { key: "currentRent", label: "Canone attuale (€)", type: "number", required: true, group: "Canone" },
    { key: "contractType", label: "Tipo di contratto", type: "select", required: true, options: [
      { value: "libero", label: "Canone libero (75% ISTAT)" },
      { value: "concordato", label: "Canone concordato (100% ISTAT)" },
    ], group: "Canone" },
    { key: "istatOld", label: "Indice FOI precedente", type: "number", required: true, group: "Calcolo" },
    { key: "istatNew", label: "Indice FOI nuovo", type: "number", required: true, group: "Calcolo" },
    { key: "effectiveDate", label: "Data di decorrenza", type: "date", required: true, group: "Date" },
    { key: "sendDate", label: "Data della comunicazione", type: "date", required: true, group: "Date" },
  ],
  clauses: [
    { id: "comunicazione", label: "Comunicazione", required: true,
      text: "{landlordName}\n{landlordAddress}\n\nSpett.le {tenantName}\n{tenantAddress}\n\nData: {sendDate}\n\nOggetto: Aggiornamento ISTAT del canone di locazione — Immobile {propertyAddress}\n\nEgregio/a {tenantName},\n\nai sensi dell'art. 32 della Legge 392/1978 e del contratto in essere, Le comunico l'aggiornamento annuale del canone di locazione.\n\nTipo contratto: {contractType}\nPercentuale ISTAT applicabile: 75% (canone libero) / 100% (canone concordato)\n\nIndice FOI precedente: {istatOld}\nIndice FOI nuovo: {istatNew}\n\nCanone attuale: {currentRent} €\nFormula: Nuovo canone = Canone attuale × (1 + % variazione ISTAT × quota applicabile)\n\nIl nuovo canone decorrerà dal {effectiveDate}.\n\nNOTA: In caso di opzione per la cedolare secca, il locatore rinuncia alla facoltà di aggiornamento ISTAT per tutta la durata dell'opzione (D.Lgs. 23/2011).\n\nDistinti saluti," },
  ],
};

/* ─── Disdetta anticipata del conduttore ─── */
export const itDisdettaConduttore: DocumentTemplate = {
  id: "it-disdetta-conduttore",
  version: "1.0.0",
  country: "IT",
  category: "rental",
  docType: "conges-locataire",
  label: "Disdetta anticipata del conduttore",
  description: "Comunicazione di recesso anticipato del conduttore per gravi motivi ex art. 3 L. 431/1998.",
  legalBasis: "Legge 431/1998, art. 3 comma 6; Codice Civile art. 1596",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "tenantName", label: "Nome del conduttore", type: "text", required: true, group: "Conduttore" },
    { key: "tenantCF", label: "Codice fiscale", type: "text", required: true, group: "Conduttore" },
    { key: "tenantAddress", label: "Indirizzo attuale", type: "text", required: true, group: "Conduttore" },
    { key: "landlordName", label: "Nome del locatore", type: "text", required: true, group: "Locatore" },
    { key: "landlordAddress", label: "Indirizzo del locatore", type: "text", required: true, group: "Locatore" },
    { key: "propertyAddress", label: "Indirizzo dell'immobile", type: "text", required: true, group: "Immobile" },
    { key: "contractDate", label: "Data del contratto", type: "date", required: true, group: "Contratto" },
    { key: "reason", label: "Gravi motivi", type: "textarea", required: true, validation: { minLength: 20 }, placeholder: "Trasferimento lavorativo, motivi di salute, impossibilità economica sopravvenuta…", group: "Motivo" },
    { key: "departureDate", label: "Data di rilascio prevista", type: "date", required: true, group: "Date" },
    { key: "newAddress", label: "Nuovo indirizzo (per cauzione)", type: "text", required: false, group: "Date" },
    { key: "sendDate", label: "Data di invio", type: "date", required: true, group: "Date" },
  ],
  clauses: [
    { id: "disdetta", label: "Comunicazione di disdetta", required: true,
      text: "RACCOMANDATA A/R\n\n{tenantName}\nC.F.: {tenantCF}\n{tenantAddress}\n\nSpett.le {landlordName}\n{landlordAddress}\n\nData: {sendDate}\n\nOggetto: Recesso anticipato dal contratto di locazione — {propertyAddress}\n\nEgregio/a {landlordName},\n\ncon la presente raccomandata A/R, ai sensi dell'art. 3, comma 6, della Legge 431/1998, Le comunico la mia volontà di recedere dal contratto di locazione stipulato in data {contractDate} per l'immobile sito in {propertyAddress}.\n\nGRAVI MOTIVI:\n{reason}\n\nConformemente alla legge, il recesso avrà effetto decorsi 6 mesi dalla ricezione della presente comunicazione. Prevedo di rilasciare l'immobile entro il {departureDate}.\n\nLe chiedo di:\n• Concordare una data per il verbale di riconsegna\n• Restituire il deposito cauzionale nei termini di legge\n• Comunicarmi eventuali importi residui\n\nNuovo indirizzo per la restituzione della cauzione: {newAddress}\n\nDistinti saluti," },
  ],
};

/* ─── Disdetta del locatore ─── */
export const itDisdettaLocatore: DocumentTemplate = {
  id: "it-disdetta-locatore",
  version: "1.0.0",
  country: "IT",
  category: "rental",
  docType: "conges-bailleur",
  label: "Diniego di rinnovo del locatore",
  description: "Comunicazione di diniego di rinnovo alla prima scadenza ex art. 3 L. 431/1998.",
  legalBasis: "Legge 431/1998, art. 3; Codice Civile artt. 1596-1597",
  needsLegalReview: true,
  active: true,
  fields: [
    { key: "landlordName", label: "Nome del locatore", type: "text", required: true, group: "Locatore" },
    { key: "landlordCF", label: "Codice fiscale", type: "text", required: true, group: "Locatore" },
    { key: "landlordAddress", label: "Indirizzo", type: "text", required: true, group: "Locatore" },
    { key: "tenantName", label: "Nome del conduttore", type: "text", required: true, group: "Conduttore" },
    { key: "tenantAddress", label: "Indirizzo", type: "text", required: true, group: "Conduttore" },
    { key: "propertyAddress", label: "Indirizzo dell'immobile", type: "text", required: true, group: "Immobile" },
    { key: "contractDate", label: "Data del contratto", type: "date", required: true, group: "Contratto" },
    { key: "contractEndDate", label: "Data di scadenza", type: "date", required: true, group: "Contratto" },
    { key: "motivo", label: "Motivo del diniego", type: "select", required: true, options: [
      { value: "uso-proprio", label: "Uso proprio o di familiari (art. 3, comma 1, lett. a)" },
      { value: "ristrutturazione", label: "Integrale ristrutturazione (lett. b)" },
      { value: "vendita", label: "Vendita dell'immobile (lett. g)" },
      { value: "altro", label: "Altro motivo previsto dalla legge" },
    ], group: "Motivo" },
    { key: "motivoDetail", label: "Descrizione dettagliata del motivo", type: "textarea", required: true, validation: { minLength: 20 }, group: "Motivo" },
    { key: "sendDate", label: "Data di invio", type: "date", required: true, group: "Date" },
  ],
  clauses: [
    { id: "diniego", label: "Comunicazione di diniego", required: true,
      text: "RACCOMANDATA A/R\n\n{landlordName}\nC.F.: {landlordCF}\n{landlordAddress}\n\nSpett.le {tenantName}\n{tenantAddress}\n\nData: {sendDate}\n\nOggetto: Diniego di rinnovo del contratto di locazione — {propertyAddress}\n\nEgregio/a {tenantName},\n\nai sensi dell'art. 3 della Legge 431/1998, Le comunico la mia volontà di non rinnovare il contratto di locazione stipulato in data {contractDate} per l'immobile sito in {propertyAddress}, in scadenza il {contractEndDate}.\n\nMOTIVO DEL DINIEGO:\n{motivo}\n\n{motivoDetail}\n\nIMPORTANTE:\n• Il preavviso deve essere comunicato con almeno 6 mesi di anticipo rispetto alla scadenza.\n• In caso di uso proprio, il locatore è tenuto ad adibire l'immobile all'uso dichiarato entro 12 mesi, pena il risarcimento al conduttore di 36 mensilità.\n• Il conduttore ha diritto di opporsi e di adire il giudice per verificare la sussistenza dei motivi addotti.\n\nDistinti saluti," },
  ],
};
