import type { DocumentTemplate } from "../types";

export const ieLeaseResidential: DocumentTemplate = {
  id: "ie-lease-residential",
  version: "1.0.0",
  country: "IE",
  category: "rental",
  docType: "lease-residential",
  label: "Residential Tenancy Agreement (Ireland)",
  description: "Tenancy agreement compliant with the Residential Tenancies Act 2004–2024.",
  legalBasis: "Residential Tenancies Act 2004 (as amended); RTB Registration",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "landlordName", label: "Landlord name", type: "text", required: true, validation: { minLength: 2 }, group: "Landlord" },
    { key: "landlordAddress", label: "Landlord address", type: "text", required: true, group: "Landlord" },
    { key: "landlordPpsn", label: "Landlord PPSN", type: "text", required: false, group: "Landlord" },
    { key: "tenantName", label: "Tenant name", type: "text", required: true, validation: { minLength: 2 }, group: "Tenant" },
    { key: "tenantEmail", label: "Tenant email", type: "email", required: false, group: "Tenant" },
    { key: "propertyAddress", label: "Property address (Eircode)", type: "text", required: true, group: "Property" },
    { key: "propertyType", label: "Property type", type: "select", required: true, options: [
      { value: "Apartment", label: "Apartment" },
      { value: "House", label: "House" },
      { value: "Room", label: "Room" },
    ], group: "Property" },
    { key: "surface", label: "Floor area (m²)", type: "number", required: true, validation: { min: 1 }, group: "Property" },
    { key: "rooms", label: "Bedrooms", type: "number", required: true, validation: { min: 1 }, group: "Property" },
    { key: "ber", label: "BER Rating", type: "select", required: true, options: [
      { value: "A1", label: "A1" }, { value: "A2", label: "A2" }, { value: "A3", label: "A3" },
      { value: "B1", label: "B1" }, { value: "B2", label: "B2" }, { value: "B3", label: "B3" },
      { value: "C1", label: "C1" }, { value: "C2", label: "C2" }, { value: "C3", label: "C3" },
      { value: "D1", label: "D1" }, { value: "D2", label: "D2" },
      { value: "E1", label: "E1" }, { value: "E2", label: "E2" },
      { value: "F", label: "F" }, { value: "G", label: "G" },
    ], group: "Property" },
    { key: "rentAmount", label: "Monthly rent (€)", type: "number", required: true, validation: { min: 1 }, group: "Financial" },
    { key: "depositAmount", label: "Security deposit (€)", type: "number", required: true, validation: { min: 0 }, group: "Financial" },
    { key: "startDate", label: "Tenancy start date", type: "date", required: true, group: "Term" },
    { key: "duration", label: "Tenancy type", type: "select", required: true, options: [
      { value: "part4", label: "Part 4 tenancy (indefinite after 6 months)" },
      { value: "fixed", label: "Fixed-term (12 months)" },
    ], defaultValue: "part4", group: "Term" },
  ],
  clauses: [
    { id: "parties", label: "1. Parties", required: true,
      text: "RESIDENTIAL TENANCY AGREEMENT\n\nLandlord: {landlordName}, {landlordAddress}\nTenant: {tenantName}" },
    { id: "property", label: "2. Property", required: true,
      text: "The dwelling at {propertyAddress}, type: {propertyType}, {surface} m², {rooms} bedrooms. BER: {ber}." },
    { id: "rent", label: "3. Rent", required: true,
      text: "Monthly rent: €{rentAmount}. Deposit: €{depositAmount}. Rent reviews subject to RPZ rules where applicable." },
    { id: "rtb", label: "4. RTB Registration", required: true,
      text: "The landlord shall register this tenancy with the Residential Tenancies Board (RTB) within one month." },
    { id: "termination", label: "5. Termination", required: true,
      text: "Notice periods per Residential Tenancies Act: Tenant — 28 days (first 6 months), increasing thereafter. Landlord — valid grounds required under the Act." },
  ],
};

export const ieRentReceipt: DocumentTemplate = {
  id: "ie-rent-receipt",
  version: "1.0.0",
  country: "IE",
  category: "rental",
  docType: "rent-receipt",
  label: "Rent Receipt (Ireland)",
  description: "Receipt for rent payment — Ireland.",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "landlordName", label: "Landlord", type: "text", required: true, group: "Landlord" },
    { key: "tenantName", label: "Tenant", type: "text", required: true, group: "Tenant" },
    { key: "propertyAddress", label: "Address", type: "text", required: true, group: "Property" },
    { key: "rentAmount", label: "Rent (€)", type: "number", required: true, group: "Amounts" },
    { key: "chargesAmount", label: "Service charges (€)", type: "number", required: true, defaultValue: 0, group: "Amounts" },
    { key: "period", label: "Period", type: "text", required: true, placeholder: "January 2026", group: "Period" },
    { key: "paymentDate", label: "Payment date", type: "date", required: true, group: "Period" },
  ],
  clauses: [
    { id: "receipt", label: "Receipt", required: true,
      text: "RENT RECEIPT\n\nI, {landlordName}, confirm receipt from {tenantName}:\n\n• Rent: €{rentAmount}\n• Service charges: €{chargesAmount}\n• TOTAL: €{totalAmount}\n\nfor the period {period}, paid on {paymentDate}.\n\nSignature:" },
  ],
};
