import type { RuntimeQaDefinition } from "@/lib/runtime-qa/types";

export const RUNTIME_QA_SCENARIOS: RuntimeQaDefinition[] = [
  {
    key: "orbit_thread_load",
    moduleKey: "orbit",
    routeKey: "/orbit",
    area: "messaging",
    scope: "orbit",
    description: "Orbit threads load from conversations_v2",
    severityIfFail: "critical",
    canAutoFix: false,
    steps: [
      { key: "conversations_v2_access", description: "conversations_v2 accessible" },
      { key: "chat_messages_v2_access", description: "chat_messages_v2 accessible" },
    ],
  },
  {
    key: "orbit_send_message_chain",
    moduleKey: "orbit",
    routeKey: "/orbit",
    area: "messaging",
    scope: "orbit",
    description: "Orbit send chain V2 only",
    severityIfFail: "critical",
    canAutoFix: false,
    steps: [
      { key: "message_insert_ready", description: "message insert path ready" },
      { key: "conversation_update_ready", description: "conversation metadata update ready" },
    ],
  },
  {
    key: "orbit_group_chain",
    moduleKey: "orbit",
    routeKey: "/orbit",
    area: "groups",
    scope: "orbit",
    description: "Orbit groups valid and usable",
    severityIfFail: "warning",
    canAutoFix: true,
    steps: [
      { key: "group_count", description: "group conversations exist" },
      { key: "group_participants_valid", description: "group participants valid" },
    ],
  },
  {
    key: "wallet_core_chain",
    moduleKey: "wallet",
    routeKey: "/wallet",
    area: "payments",
    scope: "wallet",
    description: "Wallet accounts and transactions are readable",
    severityIfFail: "critical",
    canAutoFix: false,
    steps: [
      { key: "wallet_accounts", description: "wallet accounts accessible" },
      { key: "wallet_transactions", description: "wallet transactions accessible" },
    ],
  },
  {
    key: "wallet_qr_chain",
    moduleKey: "wallet",
    routeKey: "/wallet/qr",
    area: "payments",
    scope: "wallet",
    description: "Wallet QR / POS path structurally ready",
    severityIfFail: "warning",
    canAutoFix: false,
    steps: [{ key: "wallet_accounts_present", description: "wallet account presence" }],
  },
  {
    key: "dashboard_core_chain",
    moduleKey: "dashboard",
    routeKey: "/dashboard",
    area: "dashboard",
    scope: "dashboard",
    description: "Dashboard core data sources accessible",
    severityIfFail: "critical",
    canAutoFix: false,
    steps: [{ key: "orgs_accessible", description: "orgs accessible" }],
  },
  {
    key: "hotel_chain",
    moduleKey: "hotel",
    routeKey: "/travel/hotel",
    area: "booking",
    scope: "hotel",
    description: "Hotel tables coherent",
    severityIfFail: "critical",
    canAutoFix: false,
    steps: [
      { key: "hotels_exist", description: "hotels exist" },
      { key: "hotel_rooms_exist", description: "hotel rooms exist" },
      { key: "hotel_rate_plans_exist", description: "hotel rate plans exist" },
      { key: "hotel_calendar_exist", description: "hotel inventory calendar exists" },
    ],
  },
  {
    key: "food_chain",
    moduleKey: "food",
    routeKey: "/marketplace/food",
    area: "marketplace",
    scope: "food",
    description: "Food merchants and menus coherent",
    severityIfFail: "critical",
    canAutoFix: false,
    steps: [
      { key: "food_merchants_exist", description: "food merchants exist" },
      { key: "food_menus_exist", description: "food menus exist" },
    ],
  },
  {
    key: "shop_chain",
    moduleKey: "shop",
    routeKey: "/marketplace",
    area: "marketplace",
    scope: "shop",
    description: "Storefront pages load correctly",
    severityIfFail: "warning",
    canAutoFix: false,
    steps: [{ key: "storefront_pages_exist", description: "storefront pages exist" }],
  },
  {
    key: "radar_chain",
    moduleKey: "radar",
    routeKey: "/radar",
    area: "map",
    scope: "radar",
    description: "Radar has live geo-ready business data",
    severityIfFail: "critical",
    canAutoFix: false,
    steps: [{ key: "geo_merchants_exist", description: "merchants with coordinates exist" }],
  },
  {
    key: "onboarding_chain",
    moduleKey: "onboarding",
    routeKey: "/onboarding",
    area: "onboarding",
    scope: "onboarding",
    description: "Onboarding profile and pipeline queue accessible",
    severityIfFail: "warning",
    canAutoFix: false,
    steps: [
      { key: "merchant_onboarding_profiles", description: "profiles accessible" },
      { key: "entity_pipeline_queue", description: "queue accessible" },
    ],
  },
  {
    key: "me_chain",
    moduleKey: "me",
    routeKey: "/me",
    area: "profile",
    scope: "me",
    description: "User profile shell data accessible",
    severityIfFail: "warning",
    canAutoFix: false,
    steps: [{ key: "auth_profile_tables", description: "profile related tables accessible" }],
  },
  {
    key: "browser_repair_chain",
    moduleKey: "browser_repair",
    routeKey: "/admin/engine-cockpit",
    area: "qa",
    scope: "browser_repair",
    description: "Browser repair subsystem alive",
    severityIfFail: "warning",
    canAutoFix: false,
    steps: [
      { key: "browser_repair_runs", description: "browser repair runs readable" },
      { key: "browser_repair_watchdog", description: "browser repair watchdog readable" },
    ],
  },
  {
    key: "live_merchant_integrity",
    moduleKey: "integrity",
    routeKey: "/marketplace",
    area: "integrity",
    scope: "global",
    description: "Live merchants have required fields",
    severityIfFail: "critical",
    canAutoFix: true,
    steps: [{ key: "live_merchants_required_fields", description: "required fields check" }],
  },
  {
    key: "stuck_engines_integrity",
    moduleKey: "integrity",
    routeKey: "/admin/engine-cockpit",
    area: "integrity",
    scope: "global",
    description: "No engines stuck in running state too long",
    severityIfFail: "warning",
    canAutoFix: true,
    steps: [{ key: "stuck_engines_check", description: "stuck engine check" }],
  },
];

export function getRuntimeQaScenarios(scope: string) {
  if (scope === "full") return RUNTIME_QA_SCENARIOS;
  return RUNTIME_QA_SCENARIOS.filter((s) => s.scope === scope || s.scope === "global");
}
