/**
 * Country-specific accounting & fiscal rules for property management.
 * Each country defines: tax rates, VAT, fiscal year, deductible categories, etc.
 */

export interface CountryAccountingRules {
  country: string;
  fiscalYearStart: string; // "01-01" or "04-01" etc.
  currency: string;
  currencySymbol: string;
  vatApplicable: boolean;
  vatRates: { standard: number; reduced?: number; rental?: number };
  rentalIncomeTax: { type: "flat" | "progressive" | "exempt"; rate?: number; bracket?: string };
  depositCap?: string; // e.g. "2 months rent"
  stampDuty?: boolean;
  capitalGainsTax?: { rate: number; exemptionYears?: number };
  deductibleCategories: string[];
  propertyTax: boolean;
  socialCharges?: number; // % on rental income
  withholding?: boolean;
  invoiceRequired: boolean;
  reportingFrequency: "monthly" | "quarterly" | "annual";
  categoryLabels: Record<string, string>;
}

const rules: Record<string, CountryAccountingRules> = {
  FR: {
    country: "FR", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 20, reduced: 10, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "1 mois (vide), 2 mois (meublé)",
    capitalGainsTax: { rate: 19, exemptionYears: 22 }, stampDuty: false,
    deductibleCategories: ["insurance", "maintenance", "management", "tax", "interest", "depreciation"],
    propertyTax: true, socialCharges: 17.2, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Loyer", charges: "Charges", deposit: "Dépôt", maintenance: "Travaux", insurance: "Assurance", tax: "Impôts & Taxes", utilities: "Services", management: "Gestion", booking: "Saisonnier", other: "Autre", interest: "Intérêts d'emprunt", depreciation: "Amortissement" },
  },
  DE: {
    country: "DE", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 19, reduced: 7, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "3 Monatsmieten",
    capitalGainsTax: { rate: 25, exemptionYears: 10 }, stampDuty: true,
    deductibleCategories: ["insurance", "maintenance", "management", "tax", "interest", "depreciation", "utilities"],
    propertyTax: true, invoiceRequired: true, reportingFrequency: "annual",
    categoryLabels: { rent: "Miete", charges: "Nebenkosten", deposit: "Kaution", maintenance: "Instandhaltung", insurance: "Versicherung", tax: "Steuern", utilities: "Betriebskosten", management: "Verwaltung", booking: "Ferienvermietung", other: "Sonstiges" },
  },
  ES: {
    country: "ES", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 21, reduced: 10, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "1 mes (vivienda), 2 meses (uso distinto)",
    capitalGainsTax: { rate: 19 }, stampDuty: true,
    deductibleCategories: ["insurance", "maintenance", "management", "tax", "interest", "depreciation", "utilities"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "quarterly",
    categoryLabels: { rent: "Alquiler", charges: "Gastos", deposit: "Fianza", maintenance: "Reparaciones", insurance: "Seguro", tax: "Impuestos", utilities: "Suministros", management: "Gestión", booking: "Alquiler vacacional", other: "Otros" },
  },
  IT: {
    country: "IT", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 22, reduced: 10, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 21, bracket: "Cedolare secca" }, depositCap: "3 mensilità",
    capitalGainsTax: { rate: 26, exemptionYears: 5 }, stampDuty: true,
    deductibleCategories: ["insurance", "maintenance", "tax", "management"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Canone", charges: "Spese", deposit: "Cauzione", maintenance: "Manutenzione", insurance: "Assicurazione", tax: "Tasse", utilities: "Utenze", management: "Gestione", booking: "Affitto breve", other: "Altro" },
  },
  PT: {
    country: "PT", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 23, reduced: 6, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 28 }, depositCap: "2 meses",
    capitalGainsTax: { rate: 28 }, stampDuty: true,
    deductibleCategories: ["insurance", "maintenance", "management", "tax"],
    propertyTax: true, invoiceRequired: true, reportingFrequency: "annual",
    categoryLabels: { rent: "Renda", charges: "Encargos", deposit: "Caução", maintenance: "Manutenção", insurance: "Seguro", tax: "Impostos", utilities: "Serviços", management: "Gestão", booking: "Alojamento local", other: "Outro" },
  },
  GB: {
    country: "GB", fiscalYearStart: "04-06", currency: "GBP", currencySymbol: "£",
    vatApplicable: false, vatRates: { standard: 20, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "5 weeks' rent",
    capitalGainsTax: { rate: 18 }, stampDuty: true,
    deductibleCategories: ["insurance", "maintenance", "management", "utilities", "letting_agent"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Service charges", deposit: "Deposit", maintenance: "Repairs", insurance: "Insurance", tax: "Council tax", utilities: "Utilities", management: "Management fees", booking: "Holiday let", other: "Other" },
  },
  US: {
    country: "US", fiscalYearStart: "01-01", currency: "USD", currencySymbol: "$",
    vatApplicable: false, vatRates: { standard: 0, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "Varies by state",
    capitalGainsTax: { rate: 15 }, stampDuty: false,
    deductibleCategories: ["insurance", "maintenance", "management", "tax", "interest", "depreciation", "utilities", "travel", "legal"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Fees", deposit: "Security deposit", maintenance: "Repairs & Maintenance", insurance: "Insurance", tax: "Property taxes", utilities: "Utilities", management: "Management", booking: "Short-term rental", other: "Other", interest: "Mortgage interest", depreciation: "Depreciation" },
  },
  AE: {
    country: "AE", fiscalYearStart: "01-01", currency: "AED", currencySymbol: "AED",
    vatApplicable: false, vatRates: { standard: 5, rental: 0 },
    rentalIncomeTax: { type: "exempt" },
    capitalGainsTax: { rate: 0 }, stampDuty: false,
    deductibleCategories: ["maintenance", "management"],
    propertyTax: false, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Fees", deposit: "Security deposit", maintenance: "Maintenance", insurance: "Insurance", management: "Management", booking: "Holiday rental", other: "Other" },
  },
  JP: {
    country: "JP", fiscalYearStart: "01-01", currency: "JPY", currencySymbol: "¥",
    vatApplicable: false, vatRates: { standard: 10, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "1~2ヶ月分",
    capitalGainsTax: { rate: 20, exemptionYears: 5 }, stampDuty: true,
    deductibleCategories: ["insurance", "maintenance", "management", "tax", "depreciation"],
    propertyTax: true, invoiceRequired: true, reportingFrequency: "annual",
    categoryLabels: { rent: "賃料", charges: "管理費", deposit: "敷金", maintenance: "修繕費", insurance: "保険", tax: "固定資産税", utilities: "光熱費", management: "管理費", booking: "民泊", other: "その他" },
  },
  BR: {
    country: "BR", fiscalYearStart: "01-01", currency: "BRL", currencySymbol: "R$",
    vatApplicable: false, vatRates: { standard: 0, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "3 meses",
    capitalGainsTax: { rate: 15 }, stampDuty: false,
    deductibleCategories: ["insurance", "maintenance", "tax", "management"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "monthly",
    categoryLabels: { rent: "Aluguel", charges: "Encargos", deposit: "Caução", maintenance: "Manutenção", insurance: "Seguro", tax: "IPTU", utilities: "Serviços", management: "Administração", booking: "Temporada", other: "Outro" },
  },
  MA: {
    country: "MA", fiscalYearStart: "01-01", currency: "MAD", currencySymbol: "DH",
    vatApplicable: false, vatRates: { standard: 20, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "2 mois",
    deductibleCategories: ["maintenance", "insurance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Loyer", charges: "Charges", deposit: "Caution", maintenance: "Entretien", insurance: "Assurance", tax: "Taxe d'habitation", management: "Gestion", other: "Autre" },
  },
  AU: {
    country: "AU", fiscalYearStart: "07-01", currency: "AUD", currencySymbol: "A$",
    vatApplicable: false, vatRates: { standard: 10, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "4 weeks' rent",
    capitalGainsTax: { rate: 0, exemptionYears: 0 }, stampDuty: true,
    deductibleCategories: ["insurance", "maintenance", "management", "tax", "interest", "depreciation", "travel"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Outgoings", deposit: "Bond", maintenance: "Repairs", insurance: "Insurance", tax: "Council rates", utilities: "Utilities", management: "Agent fees", booking: "Holiday let", other: "Other" },
  },
  IN: {
    country: "IN", fiscalYearStart: "04-01", currency: "INR", currencySymbol: "₹",
    vatApplicable: false, vatRates: { standard: 18, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "2-10 months",
    capitalGainsTax: { rate: 20, exemptionYears: 2 },
    deductibleCategories: ["maintenance", "insurance", "tax", "interest"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Maintenance charges", deposit: "Security deposit", maintenance: "Repairs", insurance: "Insurance", tax: "Property tax", utilities: "Utilities", management: "Management", other: "Other" },
  },
  SG: {
    country: "SG", fiscalYearStart: "01-01", currency: "SGD", currencySymbol: "S$",
    vatApplicable: false, vatRates: { standard: 9, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "1-2 months",
    capitalGainsTax: { rate: 0 },
    deductibleCategories: ["maintenance", "insurance", "management", "interest"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Fees", deposit: "Security deposit", maintenance: "Repairs", insurance: "Insurance", tax: "Property tax", utilities: "Utilities", management: "Management", other: "Other" },
  },
  SA: {
    country: "SA", fiscalYearStart: "01-01", currency: "SAR", currencySymbol: "SAR",
    vatApplicable: true, vatRates: { standard: 15, rental: 15 },
    rentalIncomeTax: { type: "exempt" },
    deductibleCategories: ["maintenance", "management"],
    propertyTax: false, invoiceRequired: true, reportingFrequency: "quarterly",
    categoryLabels: { rent: "Rent", charges: "Fees", deposit: "Deposit", maintenance: "Maintenance", insurance: "Insurance", management: "Management", other: "Other" },
  },
  TR: {
    country: "TR", fiscalYearStart: "01-01", currency: "TRY", currencySymbol: "₺",
    vatApplicable: false, vatRates: { standard: 20, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "3 aylık kira",
    capitalGainsTax: { rate: 0, exemptionYears: 5 },
    deductibleCategories: ["maintenance", "insurance", "tax", "management"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Kira", charges: "Aidat", deposit: "Depozito", maintenance: "Bakım", insurance: "Sigorta", tax: "Vergi", utilities: "Faturalar", management: "Yönetim", other: "Diğer" },
  },
  // ── New countries with full fiscal data ──
  BE: {
    country: "BE", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 21, reduced: 6, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "2-3 mois",
    capitalGainsTax: { rate: 16.5 }, stampDuty: true,
    deductibleCategories: ["insurance", "maintenance", "tax", "interest"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Loyer", charges: "Charges", deposit: "Garantie", maintenance: "Travaux", insurance: "Assurance", tax: "Précompte immobilier", management: "Gestion", other: "Autre" },
  },
  NL: {
    country: "NL", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 21, reduced: 9, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 31, bracket: "Box 3 (vermogen)" },
    capitalGainsTax: { rate: 0 }, stampDuty: true,
    deductibleCategories: ["maintenance", "insurance", "management"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Huur", charges: "Servicekosten", deposit: "Borg", maintenance: "Onderhoud", insurance: "Verzekering", tax: "OZB", management: "Beheer", other: "Overig" },
  },
  AT: {
    country: "AT", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: true, vatRates: { standard: 20, reduced: 10, rental: 10 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "3 Monatsmieten",
    capitalGainsTax: { rate: 30 }, stampDuty: true,
    deductibleCategories: ["insurance", "maintenance", "management", "tax", "interest", "depreciation"],
    propertyTax: true, invoiceRequired: true, reportingFrequency: "annual",
    categoryLabels: { rent: "Miete", charges: "Betriebskosten", deposit: "Kaution", maintenance: "Instandhaltung", insurance: "Versicherung", tax: "Grundsteuer", management: "Verwaltung", other: "Sonstiges" },
  },
  CH: {
    country: "CH", fiscalYearStart: "01-01", currency: "CHF", currencySymbol: "CHF",
    vatApplicable: false, vatRates: { standard: 8.1, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "3 Monatsmieten",
    capitalGainsTax: { rate: 0 },
    deductibleCategories: ["insurance", "maintenance", "management", "interest"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Miete/Loyer", charges: "Nebenkosten/Charges", deposit: "Kaution/Dépôt", maintenance: "Unterhalt/Entretien", insurance: "Versicherung/Assurance", tax: "Liegenschaftssteuer", management: "Verwaltung/Gestion", other: "Sonstiges/Autre" },
  },
  PL: {
    country: "PL", fiscalYearStart: "01-01", currency: "PLN", currencySymbol: "zł",
    vatApplicable: false, vatRates: { standard: 23, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 8.5, bracket: "Ryczałt" }, depositCap: "12-krotność czynszu",
    capitalGainsTax: { rate: 19 },
    deductibleCategories: ["insurance", "maintenance", "tax", "management"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Czynsz", charges: "Opłaty", deposit: "Kaucja", maintenance: "Remonty", insurance: "Ubezpieczenie", tax: "Podatek od nieruchomości", management: "Zarządzanie", other: "Inne" },
  },
  SE: {
    country: "SE", fiscalYearStart: "01-01", currency: "SEK", currencySymbol: "kr",
    vatApplicable: false, vatRates: { standard: 25, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 30 }, depositCap: "None",
    capitalGainsTax: { rate: 22 },
    deductibleCategories: ["insurance", "maintenance", "interest"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Hyra", charges: "Avgifter", deposit: "Deposition", maintenance: "Underhåll", insurance: "Försäkring", tax: "Fastighetsskatt", management: "Förvaltning", other: "Övrigt" },
  },
  NO: {
    country: "NO", fiscalYearStart: "01-01", currency: "NOK", currencySymbol: "kr",
    vatApplicable: false, vatRates: { standard: 25, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 22 },
    capitalGainsTax: { rate: 22 },
    deductibleCategories: ["insurance", "maintenance", "interest", "management"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Husleie", charges: "Felleskostnader", deposit: "Depositum", maintenance: "Vedlikehold", insurance: "Forsikring", tax: "Eiendomsskatt", management: "Forvaltning", other: "Annet" },
  },
  DK: {
    country: "DK", fiscalYearStart: "01-01", currency: "DKK", currencySymbol: "kr",
    vatApplicable: false, vatRates: { standard: 25, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "3 måneders husleje",
    capitalGainsTax: { rate: 42 },
    deductibleCategories: ["insurance", "maintenance", "management", "interest"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Husleje", charges: "Fællesudgifter", deposit: "Depositum", maintenance: "Vedligeholdelse", insurance: "Forsikring", tax: "Ejendomsskat", management: "Administration", other: "Andet" },
  },
  FI: {
    country: "FI", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 25.5, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 30 },
    capitalGainsTax: { rate: 30 },
    deductibleCategories: ["insurance", "maintenance", "management", "interest", "depreciation"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Vuokra", charges: "Vastikkeet", deposit: "Vakuus", maintenance: "Ylläpito", insurance: "Vakuutus", tax: "Kiinteistövero", management: "Hallinnointi", other: "Muu" },
  },
  GR: {
    country: "GR", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 24, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "2 μήνες",
    capitalGainsTax: { rate: 15 },
    deductibleCategories: ["insurance", "maintenance", "tax", "management"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Ενοίκιο", charges: "Κοινόχρηστα", deposit: "Εγγύηση", maintenance: "Συντήρηση", insurance: "Ασφάλεια", tax: "ΕΝΦΙΑ", management: "Διαχείριση", other: "Άλλο" },
  },
  CZ: {
    country: "CZ", fiscalYearStart: "01-01", currency: "CZK", currencySymbol: "Kč",
    vatApplicable: false, vatRates: { standard: 21, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 15 }, depositCap: "3 měsíce",
    capitalGainsTax: { rate: 15, exemptionYears: 5 },
    deductibleCategories: ["insurance", "maintenance", "tax", "management", "depreciation"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Nájem", charges: "Poplatky", deposit: "Kauce", maintenance: "Údržba", insurance: "Pojištění", tax: "Daň z nemovitostí", management: "Správa", other: "Ostatní" },
  },
  HU: {
    country: "HU", fiscalYearStart: "01-01", currency: "HUF", currencySymbol: "Ft",
    vatApplicable: false, vatRates: { standard: 27, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 15 },
    capitalGainsTax: { rate: 15 },
    deductibleCategories: ["maintenance", "insurance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Bérleti díj", charges: "Közös költség", deposit: "Kaució", maintenance: "Karbantartás", insurance: "Biztosítás", tax: "Ingatlanadó", management: "Kezelés", other: "Egyéb" },
  },
  RO: {
    country: "RO", fiscalYearStart: "01-01", currency: "RON", currencySymbol: "lei",
    vatApplicable: false, vatRates: { standard: 19, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 10 }, depositCap: "3 luni",
    capitalGainsTax: { rate: 10 },
    deductibleCategories: ["insurance", "maintenance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Chirie", charges: "Cheltuieli", deposit: "Garanție", maintenance: "Întreținere", insurance: "Asigurare", tax: "Impozit imobil", management: "Administrare", other: "Altele" },
  },
  BG: {
    country: "BG", fiscalYearStart: "01-01", currency: "BGN", currencySymbol: "лв",
    vatApplicable: false, vatRates: { standard: 20, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 10 },
    capitalGainsTax: { rate: 10 },
    deductibleCategories: ["maintenance", "insurance"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Наем", charges: "Такси", deposit: "Депозит", maintenance: "Поддръжка", insurance: "Застраховка", tax: "Данък имот", management: "Управление", other: "Друго" },
  },
  HR: {
    country: "HR", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 25, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 10 },
    capitalGainsTax: { rate: 10 },
    deductibleCategories: ["maintenance", "insurance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Najamnina", charges: "Režije", deposit: "Polog", maintenance: "Održavanje", insurance: "Osiguranje", tax: "Porez na nekretnine", management: "Upravljanje", other: "Ostalo" },
  },
  IE: {
    country: "IE", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 23, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "1 month",
    capitalGainsTax: { rate: 33 },
    deductibleCategories: ["insurance", "maintenance", "management", "interest"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Charges", deposit: "Deposit", maintenance: "Repairs", insurance: "Insurance", tax: "LPT", management: "Management", other: "Other" },
  },
  CA: {
    country: "CA", fiscalYearStart: "01-01", currency: "CAD", currencySymbol: "C$",
    vatApplicable: false, vatRates: { standard: 5, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "Varies by province",
    capitalGainsTax: { rate: 25 },
    deductibleCategories: ["insurance", "maintenance", "management", "tax", "interest", "depreciation", "utilities"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent/Loyer", charges: "Fees", deposit: "Deposit", maintenance: "Repairs", insurance: "Insurance", tax: "Property tax", management: "Management", other: "Other" },
  },
  MX: {
    country: "MX", fiscalYearStart: "01-01", currency: "MXN", currencySymbol: "MX$",
    vatApplicable: false, vatRates: { standard: 16, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "1 mes",
    capitalGainsTax: { rate: 35 },
    deductibleCategories: ["insurance", "maintenance", "tax", "management"],
    propertyTax: true, invoiceRequired: true, reportingFrequency: "monthly",
    categoryLabels: { rent: "Renta", charges: "Gastos", deposit: "Depósito", maintenance: "Mantenimiento", insurance: "Seguro", tax: "Predial", management: "Administración", other: "Otro" },
  },
  ZA: {
    country: "ZA", fiscalYearStart: "03-01", currency: "ZAR", currencySymbol: "R",
    vatApplicable: false, vatRates: { standard: 15, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "2 months",
    capitalGainsTax: { rate: 18 },
    deductibleCategories: ["insurance", "maintenance", "management", "tax", "interest"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Levies", deposit: "Deposit", maintenance: "Repairs", insurance: "Insurance", tax: "Rates & taxes", management: "Management", other: "Other" },
  },
  NG: {
    country: "NG", fiscalYearStart: "01-01", currency: "NGN", currencySymbol: "₦",
    vatApplicable: false, vatRates: { standard: 7.5, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "1-2 years",
    capitalGainsTax: { rate: 10 },
    deductibleCategories: ["maintenance", "insurance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Service charges", deposit: "Caution fee", maintenance: "Maintenance", insurance: "Insurance", tax: "Tenement rate", management: "Management", other: "Other" },
  },
  KR: {
    country: "KR", fiscalYearStart: "01-01", currency: "KRW", currencySymbol: "₩",
    vatApplicable: false, vatRates: { standard: 10, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "전세 보증금",
    capitalGainsTax: { rate: 6 },
    deductibleCategories: ["insurance", "maintenance", "tax", "management", "depreciation"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "월세", charges: "관리비", deposit: "보증금", maintenance: "수선비", insurance: "보험", tax: "재산세", management: "관리", other: "기타" },
  },
  CN: {
    country: "CN", fiscalYearStart: "01-01", currency: "CNY", currencySymbol: "¥",
    vatApplicable: true, vatRates: { standard: 13, rental: 5 },
    rentalIncomeTax: { type: "flat", rate: 20 },
    capitalGainsTax: { rate: 20 },
    deductibleCategories: ["maintenance", "tax", "management"],
    propertyTax: true, invoiceRequired: true, reportingFrequency: "monthly",
    categoryLabels: { rent: "租金", charges: "物业费", deposit: "押金", maintenance: "维修", insurance: "保险", tax: "房产税", management: "管理费", other: "其他" },
  },
  EG: {
    country: "EG", fiscalYearStart: "01-01", currency: "EGP", currencySymbol: "E£",
    vatApplicable: false, vatRates: { standard: 14, rental: 0 },
    rentalIncomeTax: { type: "progressive" },
    capitalGainsTax: { rate: 2.5 },
    deductibleCategories: ["maintenance", "insurance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Charges", deposit: "Deposit", maintenance: "Maintenance", insurance: "Insurance", tax: "Property tax", management: "Management", other: "Other" },
  },
  IL: {
    country: "IL", fiscalYearStart: "01-01", currency: "ILS", currencySymbol: "₪",
    vatApplicable: true, vatRates: { standard: 17, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 10, bracket: "Exempt under ₪5,471/month" },
    capitalGainsTax: { rate: 25 },
    deductibleCategories: ["maintenance", "insurance", "depreciation", "management"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "שכר דירה", charges: "ועד בית", deposit: "ערבון", maintenance: "תחזוקה", insurance: "ביטוח", tax: "ארנונה", management: "ניהול", other: "אחר" },
  },
  QA: {
    country: "QA", fiscalYearStart: "01-01", currency: "QAR", currencySymbol: "QAR",
    vatApplicable: false, vatRates: { standard: 0, rental: 0 },
    rentalIncomeTax: { type: "exempt" },
    capitalGainsTax: { rate: 0 },
    deductibleCategories: ["maintenance", "management"],
    propertyTax: false, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Fees", deposit: "Deposit", maintenance: "Maintenance", management: "Management", other: "Other" },
  },
  KW: {
    country: "KW", fiscalYearStart: "01-01", currency: "KWD", currencySymbol: "KD",
    vatApplicable: false, vatRates: { standard: 0, rental: 0 },
    rentalIncomeTax: { type: "exempt" },
    capitalGainsTax: { rate: 0 },
    deductibleCategories: ["maintenance", "management"],
    propertyTax: false, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Fees", deposit: "Deposit", maintenance: "Maintenance", management: "Management", other: "Other" },
  },
  PH: {
    country: "PH", fiscalYearStart: "01-01", currency: "PHP", currencySymbol: "₱",
    vatApplicable: true, vatRates: { standard: 12, rental: 12 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "2 months",
    capitalGainsTax: { rate: 6 },
    deductibleCategories: ["insurance", "maintenance", "tax", "management", "depreciation"],
    propertyTax: true, invoiceRequired: true, reportingFrequency: "quarterly",
    categoryLabels: { rent: "Rent", charges: "Dues", deposit: "Security deposit", maintenance: "Repairs", insurance: "Insurance", tax: "Real property tax", management: "Management", other: "Other" },
  },
  TH: {
    country: "TH", fiscalYearStart: "01-01", currency: "THB", currencySymbol: "฿",
    vatApplicable: false, vatRates: { standard: 7, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "2 months",
    capitalGainsTax: { rate: 0 },
    deductibleCategories: ["maintenance", "insurance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "ค่าเช่า", charges: "ค่าส่วนกลาง", deposit: "เงินประกัน", maintenance: "ซ่อมบำรุง", insurance: "ประกันภัย", tax: "ภาษีที่ดิน", management: "ค่าบริหาร", other: "อื่นๆ" },
  },
  VN: {
    country: "VN", fiscalYearStart: "01-01", currency: "VND", currencySymbol: "₫",
    vatApplicable: false, vatRates: { standard: 8, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 5 },
    capitalGainsTax: { rate: 2 },
    deductibleCategories: ["maintenance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Tiền thuê", charges: "Phí dịch vụ", deposit: "Tiền đặt cọc", maintenance: "Bảo trì", tax: "Thuế", management: "Quản lý", other: "Khác" },
  },
  MY: {
    country: "MY", fiscalYearStart: "01-01", currency: "MYR", currencySymbol: "RM",
    vatApplicable: false, vatRates: { standard: 0, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "2-3 months",
    capitalGainsTax: { rate: 30, exemptionYears: 5 },
    deductibleCategories: ["insurance", "maintenance", "tax", "interest", "management"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Sewa", charges: "Caj", deposit: "Deposit", maintenance: "Penyelenggaraan", insurance: "Insurans", tax: "Cukai pintu", management: "Pengurusan", other: "Lain-lain" },
  },
  ID: {
    country: "ID", fiscalYearStart: "01-01", currency: "IDR", currencySymbol: "Rp",
    vatApplicable: true, vatRates: { standard: 11, rental: 10 },
    rentalIncomeTax: { type: "flat", rate: 10 },
    capitalGainsTax: { rate: 2.5 },
    deductibleCategories: ["maintenance", "tax", "management"],
    propertyTax: true, invoiceRequired: true, reportingFrequency: "monthly",
    categoryLabels: { rent: "Sewa", charges: "Biaya", deposit: "Deposit", maintenance: "Pemeliharaan", insurance: "Asuransi", tax: "PBB", management: "Manajemen", other: "Lain-lain" },
  },
  UA: {
    country: "UA", fiscalYearStart: "01-01", currency: "UAH", currencySymbol: "₴",
    vatApplicable: false, vatRates: { standard: 20, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 18 }, socialCharges: 1.5,
    capitalGainsTax: { rate: 18 },
    deductibleCategories: ["maintenance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Оренда", charges: "Комунальні", deposit: "Застава", maintenance: "Ремонт", insurance: "Страхування", tax: "Податок", management: "Управління", other: "Інше" },
  },
  SK: {
    country: "SK", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 20, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 19 },
    capitalGainsTax: { rate: 19 },
    deductibleCategories: ["insurance", "maintenance", "tax", "depreciation"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Nájomné", charges: "Poplatky", deposit: "Kaucia", maintenance: "Údržba", insurance: "Poistenie", tax: "Daň z nehnuteľností", management: "Správa", other: "Ostatné" },
  },
  LU: {
    country: "LU", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 17, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "3 mois",
    capitalGainsTax: { rate: 0, exemptionYears: 2 },
    deductibleCategories: ["insurance", "maintenance", "management", "interest", "depreciation"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Loyer", charges: "Charges", deposit: "Caution", maintenance: "Entretien", insurance: "Assurance", tax: "Impôt foncier", management: "Gestion", other: "Autre" },
  },
  NZ: {
    country: "NZ", fiscalYearStart: "04-01", currency: "NZD", currencySymbol: "NZ$",
    vatApplicable: false, vatRates: { standard: 15, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "4 weeks' rent",
    capitalGainsTax: { rate: 0 },
    deductibleCategories: ["insurance", "maintenance", "management", "tax", "interest"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Rates", deposit: "Bond", maintenance: "Repairs", insurance: "Insurance", tax: "Council rates", management: "Property management", other: "Other" },
  },
  // ── Americas ──
  AR: {
    country: "AR", fiscalYearStart: "01-01", currency: "ARS", currencySymbol: "$",
    vatApplicable: false, vatRates: { standard: 21, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "1 mes",
    capitalGainsTax: { rate: 15 },
    deductibleCategories: ["insurance", "maintenance", "tax", "management"],
    propertyTax: true, invoiceRequired: true, reportingFrequency: "annual",
    categoryLabels: { rent: "Alquiler", charges: "Expensas", deposit: "Depósito", maintenance: "Reparaciones", insurance: "Seguro", tax: "ABL / Impuestos", management: "Administración", other: "Otros" },
  },
  CL: {
    country: "CL", fiscalYearStart: "01-01", currency: "CLP", currencySymbol: "$",
    vatApplicable: false, vatRates: { standard: 19, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "1 mes",
    capitalGainsTax: { rate: 10 },
    deductibleCategories: ["insurance", "maintenance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Arriendo", charges: "Gastos comunes", deposit: "Garantía", maintenance: "Mantención", insurance: "Seguro", tax: "Contribuciones", management: "Administración", other: "Otros" },
  },
  CO: {
    country: "CO", fiscalYearStart: "01-01", currency: "COP", currencySymbol: "$",
    vatApplicable: false, vatRates: { standard: 19, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "2 meses",
    capitalGainsTax: { rate: 10 },
    deductibleCategories: ["insurance", "maintenance", "tax", "management"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Canon de arrendamiento", charges: "Administración", deposit: "Depósito", maintenance: "Reparaciones", insurance: "Seguro", tax: "Predial", management: "Gestión", other: "Otros" },
  },
  PE: {
    country: "PE", fiscalYearStart: "01-01", currency: "PEN", currencySymbol: "S/",
    vatApplicable: false, vatRates: { standard: 18, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 5, bracket: "Renta de 1ra categoría" },
    capitalGainsTax: { rate: 5 },
    deductibleCategories: ["maintenance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "monthly",
    categoryLabels: { rent: "Alquiler", charges: "Gastos", deposit: "Garantía", maintenance: "Mantenimiento", insurance: "Seguro", tax: "Impuesto predial", management: "Administración", other: "Otros" },
  },
  // ── Africa ──
  TN: {
    country: "TN", fiscalYearStart: "01-01", currency: "TND", currencySymbol: "DT",
    vatApplicable: false, vatRates: { standard: 19, rental: 0 },
    rentalIncomeTax: { type: "progressive" }, depositCap: "3 mois",
    deductibleCategories: ["maintenance", "insurance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Loyer", charges: "Charges", deposit: "Caution", maintenance: "Entretien", insurance: "Assurance", tax: "Taxe foncière", management: "Gestion", other: "Autre" },
  },
  DZ: {
    country: "DZ", fiscalYearStart: "01-01", currency: "DZD", currencySymbol: "DA",
    vatApplicable: false, vatRates: { standard: 19, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 7, bracket: "IRG locatif" },
    deductibleCategories: ["maintenance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Loyer", charges: "Charges", deposit: "Caution", maintenance: "Entretien", insurance: "Assurance", tax: "Impôt foncier", management: "Gestion", other: "Autre" },
  },
  SN: {
    country: "SN", fiscalYearStart: "01-01", currency: "XOF", currencySymbol: "FCFA",
    vatApplicable: false, vatRates: { standard: 18, rental: 0 },
    rentalIncomeTax: { type: "progressive" },
    deductibleCategories: ["maintenance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Loyer", charges: "Charges", deposit: "Caution", maintenance: "Entretien", insurance: "Assurance", tax: "Contribution foncière", management: "Gestion", other: "Autre" },
  },
  CI: {
    country: "CI", fiscalYearStart: "01-01", currency: "XOF", currencySymbol: "FCFA",
    vatApplicable: false, vatRates: { standard: 18, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 15, bracket: "Impôt foncier" },
    deductibleCategories: ["maintenance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Loyer", charges: "Charges", deposit: "Caution", maintenance: "Entretien", insurance: "Assurance", tax: "Impôt foncier", management: "Gestion", other: "Autre" },
  },
  CM: {
    country: "CM", fiscalYearStart: "01-01", currency: "XAF", currencySymbol: "FCFA",
    vatApplicable: false, vatRates: { standard: 19.25, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 15 },
    deductibleCategories: ["maintenance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Loyer", charges: "Charges", deposit: "Caution", maintenance: "Entretien", insurance: "Assurance", tax: "Impôt foncier", management: "Gestion", other: "Autre" },
  },
  KE: {
    country: "KE", fiscalYearStart: "01-01", currency: "KES", currencySymbol: "KSh",
    vatApplicable: false, vatRates: { standard: 16, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 10, bracket: "Residential rental income tax" },
    capitalGainsTax: { rate: 5 },
    deductibleCategories: ["insurance", "maintenance", "management"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Service charge", deposit: "Deposit", maintenance: "Repairs", insurance: "Insurance", tax: "Land rates", management: "Management", other: "Other" },
  },
  GH: {
    country: "GH", fiscalYearStart: "01-01", currency: "GHS", currencySymbol: "GH₵",
    vatApplicable: false, vatRates: { standard: 15, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 8 },
    capitalGainsTax: { rate: 15 },
    deductibleCategories: ["maintenance", "insurance"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Charges", deposit: "Deposit", maintenance: "Maintenance", insurance: "Insurance", tax: "Property rate", management: "Management", other: "Other" },
  },
  MU: {
    country: "MU", fiscalYearStart: "07-01", currency: "MUR", currencySymbol: "Rs",
    vatApplicable: false, vatRates: { standard: 15, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 15 },
    capitalGainsTax: { rate: 0 },
    deductibleCategories: ["insurance", "maintenance", "management"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Loyer", charges: "Charges", deposit: "Caution", maintenance: "Entretien", insurance: "Assurance", tax: "Taxe municipale", management: "Gestion", other: "Autre" },
  },
  // ── Middle East ──
  BH: {
    country: "BH", fiscalYearStart: "01-01", currency: "BHD", currencySymbol: "BD",
    vatApplicable: false, vatRates: { standard: 10, rental: 0 },
    rentalIncomeTax: { type: "exempt" },
    capitalGainsTax: { rate: 0 },
    deductibleCategories: ["maintenance", "management"],
    propertyTax: false, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Fees", deposit: "Deposit", maintenance: "Maintenance", management: "Management", other: "Other" },
  },
  OM: {
    country: "OM", fiscalYearStart: "01-01", currency: "OMR", currencySymbol: "OMR",
    vatApplicable: true, vatRates: { standard: 5, rental: 0 },
    rentalIncomeTax: { type: "exempt" },
    capitalGainsTax: { rate: 0 },
    deductibleCategories: ["maintenance", "management"],
    propertyTax: false, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Fees", deposit: "Deposit", maintenance: "Maintenance", management: "Management", other: "Other" },
  },
  JO: {
    country: "JO", fiscalYearStart: "01-01", currency: "JOD", currencySymbol: "JD",
    vatApplicable: true, vatRates: { standard: 16, rental: 0 },
    rentalIncomeTax: { type: "progressive" },
    capitalGainsTax: { rate: 0 },
    deductibleCategories: ["maintenance", "insurance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Fees", deposit: "Deposit", maintenance: "Maintenance", insurance: "Insurance", tax: "Property tax", management: "Management", other: "Other" },
  },
  LB: {
    country: "LB", fiscalYearStart: "01-01", currency: "LBP", currencySymbol: "LL",
    vatApplicable: true, vatRates: { standard: 11, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 5 },
    capitalGainsTax: { rate: 15 },
    deductibleCategories: ["maintenance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Loyer", charges: "Charges", deposit: "Caution", maintenance: "Entretien", tax: "Impôt foncier", management: "Gestion", other: "Autre" },
  },
  IQ: {
    country: "IQ", fiscalYearStart: "01-01", currency: "IQD", currencySymbol: "IQD",
    vatApplicable: false, vatRates: { standard: 0, rental: 0 },
    rentalIncomeTax: { type: "progressive" },
    capitalGainsTax: { rate: 0 },
    deductibleCategories: ["maintenance"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Fees", deposit: "Deposit", maintenance: "Maintenance", management: "Management", other: "Other" },
  },
  // ── Europe missing ──
  SI: {
    country: "SI", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 22, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 25 },
    capitalGainsTax: { rate: 25 },
    deductibleCategories: ["insurance", "maintenance", "tax", "management"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Najemnina", charges: "Stroški", deposit: "Varščina", maintenance: "Vzdrževanje", insurance: "Zavarovanje", tax: "Davek", management: "Upravljanje", other: "Ostalo" },
  },
  LT: {
    country: "LT", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 21, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 15 },
    capitalGainsTax: { rate: 15 },
    deductibleCategories: ["maintenance", "insurance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Nuoma", charges: "Mokesčiai", deposit: "Užstatas", maintenance: "Remontas", insurance: "Draudimas", tax: "Turto mokestis", management: "Valdymas", other: "Kita" },
  },
  LV: {
    country: "LV", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 21, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 10 },
    capitalGainsTax: { rate: 20 },
    deductibleCategories: ["maintenance", "insurance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Īre", charges: "Maksājumi", deposit: "Depozīts", maintenance: "Uzturēšana", insurance: "Apdrošināšana", tax: "Nekustamā īpašuma nodoklis", management: "Pārvaldība", other: "Cits" },
  },
  EE: {
    country: "EE", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 22, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 20 },
    capitalGainsTax: { rate: 20 },
    deductibleCategories: ["maintenance", "insurance"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Üür", charges: "Kommunaalkulud", deposit: "Tagatisraha", maintenance: "Hooldus", insurance: "Kindlustus", tax: "Maamaks", management: "Haldus", other: "Muu" },
  },
  CY: {
    country: "CY", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 19, rental: 0 },
    rentalIncomeTax: { type: "progressive" },
    capitalGainsTax: { rate: 20 },
    deductibleCategories: ["insurance", "maintenance", "management", "interest"],
    propertyTax: false, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Fees", deposit: "Deposit", maintenance: "Repairs", insurance: "Insurance", tax: "Taxes", management: "Management", other: "Other" },
  },
  MT: {
    country: "MT", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
    vatApplicable: false, vatRates: { standard: 18, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 15, bracket: "Final withholding tax" },
    capitalGainsTax: { rate: 8 },
    deductibleCategories: ["maintenance", "insurance"],
    propertyTax: false, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Fees", deposit: "Deposit", maintenance: "Repairs", insurance: "Insurance", management: "Management", other: "Other" },
  },
  // ── Asia-Pacific missing ──
  TW: {
    country: "TW", fiscalYearStart: "01-01", currency: "TWD", currencySymbol: "NT$",
    vatApplicable: false, vatRates: { standard: 5, rental: 0 },
    rentalIncomeTax: { type: "progressive" },
    capitalGainsTax: { rate: 45 },
    deductibleCategories: ["insurance", "maintenance", "tax", "depreciation"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "租金", charges: "管理費", deposit: "押金", maintenance: "修繕費", insurance: "保險", tax: "房屋稅", management: "管理", other: "其他" },
  },
  HK: {
    country: "HK", fiscalYearStart: "04-01", currency: "HKD", currencySymbol: "HK$",
    vatApplicable: false, vatRates: { standard: 0, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 15, bracket: "Property tax" },
    capitalGainsTax: { rate: 0 },
    deductibleCategories: ["maintenance"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Management fees", deposit: "Deposit", maintenance: "Repairs", tax: "Rates", management: "Management", other: "Other" },
  },
  PK: {
    country: "PK", fiscalYearStart: "07-01", currency: "PKR", currencySymbol: "Rs",
    vatApplicable: false, vatRates: { standard: 18, rental: 0 },
    rentalIncomeTax: { type: "progressive" },
    capitalGainsTax: { rate: 15 },
    deductibleCategories: ["maintenance", "tax", "insurance"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Charges", deposit: "Security deposit", maintenance: "Repairs", insurance: "Insurance", tax: "Property tax", management: "Management", other: "Other" },
  },
  BD: {
    country: "BD", fiscalYearStart: "07-01", currency: "BDT", currencySymbol: "৳",
    vatApplicable: false, vatRates: { standard: 15, rental: 0 },
    rentalIncomeTax: { type: "progressive" },
    capitalGainsTax: { rate: 15 },
    deductibleCategories: ["maintenance", "tax", "insurance"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Charges", deposit: "Deposit", maintenance: "Repairs", insurance: "Insurance", tax: "Property tax", management: "Management", other: "Other" },
  },
  LK: {
    country: "LK", fiscalYearStart: "04-01", currency: "LKR", currencySymbol: "Rs",
    vatApplicable: false, vatRates: { standard: 18, rental: 0 },
    rentalIncomeTax: { type: "progressive" },
    capitalGainsTax: { rate: 10 },
    deductibleCategories: ["maintenance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Charges", deposit: "Deposit", maintenance: "Repairs", tax: "Rates", management: "Management", other: "Other" },
  },
  KH: {
    country: "KH", fiscalYearStart: "01-01", currency: "KHR", currencySymbol: "៛",
    vatApplicable: true, vatRates: { standard: 10, rental: 10 },
    rentalIncomeTax: { type: "flat", rate: 10 },
    capitalGainsTax: { rate: 20 },
    deductibleCategories: ["maintenance"],
    propertyTax: true, invoiceRequired: true, reportingFrequency: "monthly",
    categoryLabels: { rent: "Rent", charges: "Charges", deposit: "Deposit", maintenance: "Repairs", tax: "Tax on immovable property", management: "Management", other: "Other" },
  },
  NP: {
    country: "NP", fiscalYearStart: "07-01", currency: "NPR", currencySymbol: "Rs",
    vatApplicable: false, vatRates: { standard: 13, rental: 0 },
    rentalIncomeTax: { type: "flat", rate: 10 },
    capitalGainsTax: { rate: 5 },
    deductibleCategories: ["maintenance", "tax"],
    propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
    categoryLabels: { rent: "Rent", charges: "Charges", deposit: "Deposit", maintenance: "Repairs", tax: "Property tax", management: "Management", other: "Other" },
  },
};
// Fallback: if country not found, return a generic international set
const DEFAULT_RULES: CountryAccountingRules = {
  country: "INT", fiscalYearStart: "01-01", currency: "EUR", currencySymbol: "€",
  vatApplicable: false, vatRates: { standard: 0, rental: 0 },
  rentalIncomeTax: { type: "progressive" },
  deductibleCategories: ["insurance", "maintenance", "management", "tax", "utilities"],
  propertyTax: true, invoiceRequired: false, reportingFrequency: "annual",
  categoryLabels: { rent: "Rent", charges: "Charges", deposit: "Deposit", maintenance: "Maintenance", insurance: "Insurance", tax: "Taxes", utilities: "Utilities", management: "Management", booking: "Short-term", other: "Other" },
};

export function getAccountingRules(countryCode: string): CountryAccountingRules {
  return rules[countryCode] || DEFAULT_RULES;
}

export function getAllAccountingRules(): Record<string, CountryAccountingRules> {
  return rules;
}
