type Locale = "fr" | "en" | "es" | "de" | "it" | "pt" | "nl" | "pl" | "tr" | "ar" | "ja" | "ko" | "zh" | "hi" | "th" | "vi" | "id" | "ms" | "sv" | "da" | "nb" | "fi" | "el" | "cs" | "hu" | "ro" | "hr" | "bg" | "sk" | "he" | "uk" | "fa" | "bn" | "sw" | "tl" | "ur" | "am" | "ha" | "yo" | "wo" | "ru" | "sl" | "lt" | "lv" | "et";

const keys: Record<string, Record<Locale, string>> = {
  "islamic.title": {
    fr: "Section Islamique", en: "Islamic Section", es: "Sección Islámica", de: "Islamischer Bereich", it: "Sezione Islamica", pt: "Seção Islâmica", nl: "Islamitische Sectie", pl: "Sekcja Islamska", tr: "İslami Bölüm", ar: "القسم الإسلامي", ja: "イスラムセクション", ko: "이슬람 섹션", zh: "伊斯兰板块", hi: "इस्लामी अनुभाग", th: "ส่วนอิสลาม", vi: "Mục Hồi giáo", id: "Bagian Islam", ms: "Bahagian Islam", sv: "Islamisk Sektion", da: "Islamisk Sektion", nb: "Islamsk seksjon", fi: "Islamilainen osio", el: "Ισλαμικό Τμήμα", cs: "Islámská sekce", hu: "Iszlám rész", ro: "Secțiunea Islamică", hr: "Islamski odjeljak", bg: "Ислямски раздел", sk: "Islamská sekcia", he: "מדור אסלאמי", uk: "Ісламський розділ", fa: "بخش اسلامی", bn: "ইসলামিক বিভাগ", sw: "Sehemu ya Kiislamu", tl: "Seksyong Islamiko", ur: "اسلامی سیکشن", am: "እስላማዊ ክፍል", ha: "Sashen Musulunci", yo: "Apá Islam", wo: "Xët bu Islaam", ru: "Исламский раздел", sl: "Islamski razdelek", lt: "Islamo skyrius", lv: "Islāma sadaļa", et: "Islami jaotis",
  },
  "islamic.seo_desc": {
    fr: "Horaires de prière, Coran, Qibla, Duas, Tasbih, Zakat et plus.", en: "Prayer times, Quran, Qibla, Duas, Tasbih, Zakat and more.", es: "Horarios de oración, Corán, Qibla, Duas, Tasbih, Zakat y más.", de: "Gebetszeiten, Koran, Qibla, Duas, Tasbih, Zakat und mehr.", it: "Orari di preghiera, Corano, Qibla, Duas, Tasbih, Zakat e altro.", pt: "Horários de oração, Alcorão, Qibla, Duas, Tasbih, Zakat e mais.", nl: "Gebedstijden, Koran, Qibla, Duas, Tasbih, Zakat en meer.", pl: "Godziny modlitw, Koran, Qibla, Duas, Tasbih, Zakat i więcej.", tr: "Namaz vakitleri, Kur'an, Kıble, Dualar, Tesbih, Zekat ve daha fazlası.", ar: "مواقيت الصلاة، القرآن، القبلة، الأدعية، التسبيح، الزكاة والمزيد.", ja: "礼拝時間、クルアーン、キブラ、ドゥアー、タスビーフ、ザカートなど。", ko: "예배 시간, 꾸란, 키블라, 두아, 타스비흐, 자카트 등.", zh: "祈祷时间、古兰经、朝向、杜阿、念珠、天课等。", hi: "नमाज़ के समय, क़ुरान, क़िबला, दुआएँ, तस्बीह, ज़कात और अधिक।", th: "เวลาละหมาด อัลกุรอาน กิบลัต ดุอาอ์ ตัสบีห์ ซะกาต และอื่นๆ", vi: "Giờ cầu nguyện, Kinh Quran, Qibla, Dua, Tasbih, Zakat và hơn nữa.", id: "Waktu shalat, Al-Quran, Kiblat, Doa, Tasbih, Zakat dan lainnya.", ms: "Waktu solat, Al-Quran, Kiblat, Doa, Tasbih, Zakat dan lagi.", sv: "Bönetider, Koranen, Qibla, Duas, Tasbih, Zakat och mer.", da: "Bønnestider, Koranen, Qibla, Duas, Tasbih, Zakat og mere.", nb: "Bønnetider, Koranen, Qibla, Duas, Tasbih, Zakat og mer.", fi: "Rukousajat, Koraani, Qibla, Duas, Tasbih, Zakat ja muuta.", el: "Ώρες προσευχής, Κοράνι, Κιβλά, Ντουά, Τασμπίχ, Ζακάτ και άλλα.", cs: "Časy modliteb, Korán, Qibla, Duas, Tasbíh, Zakát a další.", hu: "Imarendek, Korán, Qibla, Duas, Tasbih, Zakat és több.", ro: "Orele de rugăciune, Coranul, Qibla, Duas, Tasbih, Zakat și altele.", hr: "Vremena molitve, Kur'an, Kibla, Dove, Tespih, Zekat i više.", bg: "Молитвени часове, Коран, Кибла, Дуи, Тасбих, Зекят и още.", sk: "Časy modlitieb, Korán, Qibla, Duas, Tasbíh, Zakát a ďalšie.", he: "זמני תפילה, קוראן, קיבלה, דועא, תסביח, זכאת ועוד.", uk: "Часи молитов, Коран, Кібла, Дуа, Тасбіх, Закят та інше.", fa: "اوقات نماز، قرآن، قبله، دعاها، تسبیح، زکات و بیشتر.", bn: "নামাজের সময়, কুরআন, কিবলা, দোয়া, তাসবীহ, যাকাত এবং আরও।", sw: "Nyakati za swala, Qurani, Qibla, Dua, Tasbih, Zakat na zaidi.", tl: "Oras ng panalangin, Quran, Qibla, Duas, Tasbih, Zakat at higit pa.", ur: "نماز کے اوقات، قرآن، قبلہ، دعائیں، تسبیح، زکوٰۃ اور مزید۔", am: "የጸሎት ሰዓታት፣ ቁርኣን፣ ቂብላ፣ ዱዓ፣ ተስቢሕ፣ ዘካት እና ተጨማሪ።", ha: "Lokutan sallah, Alqur'ani, Alqibla, Addu'o'i, Tasbih, Zakka da ƙari.", yo: "Àkókò ìjọsìn, Al-Qur'an, Qibla, Duas, Tasbih, Zakat àti diẹ̀ sí i.", wo: "Waxtu julli, Alxuraan, Qibla, Duas, Tasbih, Zakat ak yeneen.", ru: "Времена молитв, Коран, Кибла, Дуа, Тасбих, Закят и многое другое.", sl: "Molitveni časi, Koran, Kibla, Dove, Tasbih, Zakat in več.", lt: "Maldos laikai, Koranas, Kibla, Dua, Tasbih, Zakat ir daugiau.", lv: "Lūgšanu laiki, Korāns, Kibla, Dua, Tasbih, Zakat un vairāk.", et: "Palveajad, Koraan, Qibla, Duas, Tasbih, Zakat ja muud.",
  },
  "islamic.tab.prayers": {
    fr: "Prières", en: "Prayers", es: "Oraciones", de: "Gebete", it: "Preghiere", pt: "Orações", nl: "Gebeden", pl: "Modlitwy", tr: "Namazlar", ar: "الصلوات", ja: "礼拝", ko: "예배", zh: "祈祷", hi: "नमाज़", th: "ละหมาด", vi: "Cầu nguyện", id: "Shalat", ms: "Solat", sv: "Böner", da: "Bønner", nb: "Bønner", fi: "Rukoukset", el: "Προσευχές", cs: "Modlitby", hu: "Imák", ro: "Rugăciuni", hr: "Molitve", bg: "Молитви", sk: "Modlitby", he: "תפילות", uk: "Молитви", fa: "نمازها", bn: "নামাজ", sw: "Swala", tl: "Dasal", ur: "نمازیں", am: "ጸሎቶች", ha: "Salloli", yo: "Àdúrà", wo: "Julli", ru: "Молитвы", sl: "Molitve", lt: "Maldos", lv: "Lūgšanas", et: "Palved",
  },
  "islamic.tab.mosques": {
    fr: "Mosquées", en: "Mosques", es: "Mezquitas", de: "Moscheen", it: "Moschee", pt: "Mesquitas", nl: "Moskeeën", pl: "Meczety", tr: "Camiler", ar: "المساجد", ja: "モスク", ko: "모스크", zh: "清真寺", hi: "मस्जिदें", th: "มัสยิด", vi: "Thánh đường", id: "Masjid", ms: "Masjid", sv: "Moskéer", da: "Moskéer", nb: "Moskeer", fi: "Moskeijat", el: "Τζαμιά", cs: "Mešity", hu: "Mecsetek", ro: "Moschei", hr: "Džamije", bg: "Джамии", sk: "Mešity", he: "מסגדים", uk: "Мечеті", fa: "مساجد", bn: "মসজিদ", sw: "Misikiti", tl: "Moske", ur: "مساجد", am: "መስጊዶች", ha: "Masallatai", yo: "Mọ́ṣáláṣí", wo: "Jaaka", ru: "Мечети", sl: "Mošeje", lt: "Mečetės", lv: "Mošejas", et: "Mošeed",
  },
  "islamic.tab.qibla": {
    fr: "Qibla", en: "Qibla", es: "Qibla", de: "Qibla", it: "Qibla", pt: "Qibla", nl: "Qibla", pl: "Qibla", tr: "Kıble", ar: "القبلة", ja: "キブラ", ko: "키블라", zh: "朝向", hi: "क़िबला", th: "กิบลัต", vi: "Qibla", id: "Kiblat", ms: "Kiblat", sv: "Qibla", da: "Qibla", nb: "Qibla", fi: "Qibla", el: "Κιβλά", cs: "Qibla", hu: "Qibla", ro: "Qibla", hr: "Kibla", bg: "Кибла", sk: "Qibla", he: "קיבלה", uk: "Кібла", fa: "قبله", bn: "কিবলা", sw: "Qibla", tl: "Qibla", ur: "قبلہ", am: "ቂብላ", ha: "Alqibla", yo: "Qibla", wo: "Qibla", ru: "Кибла", sl: "Kibla", lt: "Kibla", lv: "Kibla", et: "Qibla",
  },
  "islamic.tab.calendar": {
    fr: "Calendrier", en: "Calendar", es: "Calendario", de: "Kalender", it: "Calendario", pt: "Calendário", nl: "Kalender", pl: "Kalendarz", tr: "Takvim", ar: "التقويم", ja: "カレンダー", ko: "달력", zh: "日历", hi: "कैलेंडर", th: "ปฏิทิน", vi: "Lịch", id: "Kalender", ms: "Kalendar", sv: "Kalender", da: "Kalender", nb: "Kalender", fi: "Kalenteri", el: "Ημερολόγιο", cs: "Kalendář", hu: "Naptár", ro: "Calendar", hr: "Kalendar", bg: "Календар", sk: "Kalendár", he: "לוח שנה", uk: "Календар", fa: "تقویم", bn: "ক্যালেন্ডার", sw: "Kalenda", tl: "Kalendaryo", ur: "کیلنڈر", am: "ቀን መቁጠሪያ", ha: "Kalanda", yo: "Kàlẹ́ndà", wo: "Kalàndiriyee", ru: "Календарь", sl: "Koledar", lt: "Kalendorius", lv: "Kalendārs", et: "Kalender",
  },
  "islamic.tab.ramadan": {
    fr: "Ramadan", en: "Ramadan", es: "Ramadán", de: "Ramadan", it: "Ramadan", pt: "Ramadã", nl: "Ramadan", pl: "Ramadan", tr: "Ramazan", ar: "رمضان", ja: "ラマダン", ko: "라마단", zh: "斋月", hi: "रमज़ान", th: "รอมฎอน", vi: "Ramadan", id: "Ramadan", ms: "Ramadan", sv: "Ramadan", da: "Ramadan", nb: "Ramadan", fi: "Ramadan", el: "Ραμαζάνι", cs: "Ramadán", hu: "Ramadán", ro: "Ramadan", hr: "Ramazan", bg: "Рамадан", sk: "Ramadán", he: "רמדאן", uk: "Рамадан", fa: "رمضان", bn: "রমজান", sw: "Ramadhani", tl: "Ramadan", ur: "رمضان", am: "ረመዳን", ha: "Ramadan", yo: "Ramadan", wo: "Ramadan", ru: "Рамадан", sl: "Ramadan", lt: "Ramadanas", lv: "Ramadāns", et: "Ramadan",
  },
  "islamic.tab.hijri": {
    fr: "Hijri", en: "Hijri", es: "Hijri", de: "Hidschri", it: "Hijri", pt: "Hijri", nl: "Hijri", pl: "Hijri", tr: "Hicri", ar: "هجري", ja: "ヒジュラ", ko: "히즈라", zh: "伊历", hi: "हिज्री", th: "ฮิจเราะห์", vi: "Hijri", id: "Hijriah", ms: "Hijrah", sv: "Hijri", da: "Hijri", nb: "Hijri", fi: "Hijri", el: "Χίτζρα", cs: "Hidžra", hu: "Hidzsra", ro: "Hijri", hr: "Hidžra", bg: "Хиджра", sk: "Hidžra", he: "היג'רי", uk: "Хіджра", fa: "هجری", bn: "হিজরি", sw: "Hijra", tl: "Hijri", ur: "ہجری", am: "ሂጅሪ", ha: "Hijira", yo: "Hijri", wo: "Hijri", ru: "Хиджра", sl: "Hidžra", lt: "Hidžra", lv: "Hidžra", et: "Hidžra",
  },
  "islamic.tab.quran": {
    fr: "Coran", en: "Quran", es: "Corán", de: "Koran", it: "Corano", pt: "Alcorão", nl: "Koran", pl: "Koran", tr: "Kur'an", ar: "القرآن", ja: "クルアーン", ko: "꾸란", zh: "古兰经", hi: "क़ुरान", th: "อัลกุรอาน", vi: "Kinh Quran", id: "Al-Quran", ms: "Al-Quran", sv: "Koranen", da: "Koranen", nb: "Koranen", fi: "Koraani", el: "Κοράνι", cs: "Korán", hu: "Korán", ro: "Coranul", hr: "Kur'an", bg: "Коран", sk: "Korán", he: "קוראן", uk: "Коран", fa: "قرآن", bn: "কুরআন", sw: "Qurani", tl: "Quran", ur: "قرآن", am: "ቁርኣን", ha: "Alqur'ani", yo: "Al-Qur'an", wo: "Alxuraan", ru: "Коран", sl: "Koran", lt: "Koranas", lv: "Korāns", et: "Koraan",
  },
  "islamic.tab.hadith": {
    fr: "Hadith", en: "Hadith", es: "Hadiz", de: "Hadith", it: "Hadith", pt: "Hadith", nl: "Hadith", pl: "Hadis", tr: "Hadis", ar: "الحديث", ja: "ハディース", ko: "하디스", zh: "圣训", hi: "हदीस", th: "หะดีษ", vi: "Hadith", id: "Hadits", ms: "Hadis", sv: "Hadith", da: "Hadith", nb: "Hadith", fi: "Hadith", el: "Χαντίθ", cs: "Hadís", hu: "Hadísz", ro: "Hadith", hr: "Hadis", bg: "Хадис", sk: "Hadís", he: "חדית'", uk: "Хадіс", fa: "حدیث", bn: "হাদিস", sw: "Hadithi", tl: "Hadith", ur: "حدیث", am: "ሐዲስ", ha: "Hadisi", yo: "Hadith", wo: "Hadis", ru: "Хадис", sl: "Hadis", lt: "Hadisas", lv: "Hadiss", et: "Hadiith",
  },
  "islamic.tab.duas": {
    fr: "Duas", en: "Duas", es: "Duas", de: "Duas", it: "Duas", pt: "Duas", nl: "Duas", pl: "Duas", tr: "Dualar", ar: "الأدعية", ja: "ドゥアー", ko: "두아", zh: "杜阿", hi: "दुआएँ", th: "ดุอาอ์", vi: "Dua", id: "Doa", ms: "Doa", sv: "Duas", da: "Duas", nb: "Duas", fi: "Duas", el: "Ντουά", cs: "Duas", hu: "Duas", ro: "Duas", hr: "Dove", bg: "Дуи", sk: "Duas", he: "דועא", uk: "Дуа", fa: "دعاها", bn: "দোয়া", sw: "Dua", tl: "Duas", ur: "دعائیں", am: "ዱዓ", ha: "Addu'o'i", yo: "Àdúrà", wo: "Du'a", ru: "Дуа", sl: "Dove", lt: "Dua", lv: "Dua", et: "Duaad",
  },
  "islamic.tab.tasbih": {
    fr: "Tasbih", en: "Tasbih", es: "Tasbih", de: "Tasbih", it: "Tasbih", pt: "Tasbih", nl: "Tasbih", pl: "Tasbih", tr: "Tesbih", ar: "التسبيح", ja: "タスビーフ", ko: "타스비흐", zh: "念珠", hi: "तस्बीह", th: "ตัสบีห์", vi: "Tasbih", id: "Tasbih", ms: "Tasbih", sv: "Tasbih", da: "Tasbih", nb: "Tasbih", fi: "Tasbih", el: "Τασμπίχ", cs: "Tasbíh", hu: "Tasbih", ro: "Tasbih", hr: "Tespih", bg: "Тасбих", sk: "Tasbíh", he: "תסביח", uk: "Тасбіх", fa: "تسبیح", bn: "তাসবীহ", sw: "Tasbih", tl: "Tasbih", ur: "تسبیح", am: "ተስቢሕ", ha: "Tasbih", yo: "Tasbih", wo: "Tasbih", ru: "Тасбих", sl: "Tasbih", lt: "Tasbih", lv: "Tasbih", et: "Tasbih",
  },
  "islamic.tab.names": {
    fr: "99 Noms", en: "99 Names", es: "99 Nombres", de: "99 Namen", it: "99 Nomi", pt: "99 Nomes", nl: "99 Namen", pl: "99 Imion", tr: "99 İsim", ar: "٩٩ اسمًا", ja: "99の名前", ko: "99개 이름", zh: "99个尊名", hi: "99 नाम", th: "99 พระนาม", vi: "99 Tên", id: "99 Nama", ms: "99 Nama", sv: "99 Namn", da: "99 Navne", nb: "99 Navn", fi: "99 Nimeä", el: "99 Ονόματα", cs: "99 Jmen", hu: "99 Név", ro: "99 Nume", hr: "99 Imena", bg: "99 Имена", sk: "99 Mien", he: "99 שמות", uk: "99 Імен", fa: "۹۹ نام", bn: "৯৯টি নাম", sw: "Majina 99", tl: "99 Pangalan", ur: "99 نام", am: "99 ስሞች", ha: "Sunaye 99", yo: "Orúkọ 99", wo: "99 Tur", ru: "99 Имён", sl: "99 Imen", lt: "99 Vardai", lv: "99 Vārdi", et: "99 Nime",
  },
  "islamic.tab.zakat": {
    fr: "Zakat", en: "Zakat", es: "Zakat", de: "Zakat", it: "Zakat", pt: "Zakat", nl: "Zakat", pl: "Zakat", tr: "Zekat", ar: "الزكاة", ja: "ザカート", ko: "자카트", zh: "天课", hi: "ज़कात", th: "ซะกาต", vi: "Zakat", id: "Zakat", ms: "Zakat", sv: "Zakat", da: "Zakat", nb: "Zakat", fi: "Zakat", el: "Ζακάτ", cs: "Zakát", hu: "Zakat", ro: "Zakat", hr: "Zekat", bg: "Зекят", sk: "Zakát", he: "זכאת", uk: "Закят", fa: "زکات", bn: "যাকাত", sw: "Zakat", tl: "Zakat", ur: "زکوٰۃ", am: "ዘካት", ha: "Zakka", yo: "Zakat", wo: "Zakat", ru: "Закят", sl: "Zakat", lt: "Zakat", lv: "Zakat", et: "Zakat",
  },
  "islamic.back": {
    fr: "Retour", en: "Back", es: "Volver", de: "Zurück", it: "Indietro", pt: "Voltar", nl: "Terug", pl: "Powrót", tr: "Geri", ar: "رجوع", ja: "戻る", ko: "뒤로", zh: "返回", hi: "वापस", th: "กลับ", vi: "Quay lại", id: "Kembali", ms: "Kembali", sv: "Tillbaka", da: "Tilbage", nb: "Tilbake", fi: "Takaisin", el: "Πίσω", cs: "Zpět", hu: "Vissza", ro: "Înapoi", hr: "Natrag", bg: "Назад", sk: "Späť", he: "חזרה", uk: "Назад", fa: "بازگشت", bn: "পিছনে", sw: "Rudi", tl: "Bumalik", ur: "واپس", am: "ተመለስ", ha: "Koma", yo: "Padà", wo: "Dellu", ru: "Назад", sl: "Nazaj", lt: "Atgal", lv: "Atpakaļ", et: "Tagasi",
  },
  "islamic.loading": {
    fr: "Chargement...", en: "Loading...", es: "Cargando...", de: "Laden...", it: "Caricamento...", pt: "Carregando...", nl: "Laden...", pl: "Ładowanie...", tr: "Yükleniyor...", ar: "جارٍ التحميل...", ja: "読み込み中...", ko: "로딩 중...", zh: "加载中...", hi: "लोड हो रहा है...", th: "กำลังโหลด...", vi: "Đang tải...", id: "Memuat...", ms: "Memuatkan...", sv: "Laddar...", da: "Indlæser...", nb: "Laster...", fi: "Ladataan...", el: "Φόρτωση...", cs: "Načítání...", hu: "Betöltés...", ro: "Se încarcă...", hr: "Učitavanje...", bg: "Зареждане...", sk: "Načítava sa...", he: "...טוען", uk: "Завантаження...", fa: "...در حال بارگذاری", bn: "লোড হচ্ছে...", sw: "Inapakia...", tl: "Naglo-load...", ur: "...لوڈ ہو رہا ہے", am: "በመጫን ላይ...", ha: "Ana lodawa...", yo: "Ń gbé kalẹ̀...", wo: "Yàgg nañu...", ru: "Загрузка...", sl: "Nalaganje...", lt: "Kraunama...", lv: "Ielādē...", et: "Laadimine...",
  },
  "islamic.retry": {
    fr: "Réessayer", en: "Retry", es: "Reintentar", de: "Erneut versuchen", it: "Riprova", pt: "Tentar novamente", nl: "Opnieuw proberen", pl: "Ponów", tr: "Tekrar dene", ar: "إعادة المحاولة", ja: "再試行", ko: "다시 시도", zh: "重试", hi: "पुनः प्रयास करें", th: "ลองอีกครั้ง", vi: "Thử lại", id: "Coba lagi", ms: "Cuba lagi", sv: "Försök igen", da: "Prøv igen", nb: "Prøv igjen", fi: "Yritä uudelleen", el: "Επανάληψη", cs: "Zkusit znovu", hu: "Újra", ro: "Reîncearcă", hr: "Pokušaj ponovo", bg: "Опитай отново", sk: "Skúsiť znova", he: "נסה שוב", uk: "Повторити", fa: "تلاش مجدد", bn: "আবার চেষ্টা করুন", sw: "Jaribu tena", tl: "Subukan muli", ur: "دوبارہ کوشش کریں", am: "እንደገና ሞክር", ha: "Sake gwadawa", yo: "Tún gbìyànjú", wo: "Jéemaatal", ru: "Повторить", sl: "Poskusi znova", lt: "Bandyti dar kartą", lv: "Mēģināt vēlreiz", et: "Proovi uuesti",
  },
  "islamic.copy": {
    fr: "Copier", en: "Copy", es: "Copiar", de: "Kopieren", it: "Copia", pt: "Copiar", nl: "Kopiëren", pl: "Kopiuj", tr: "Kopyala", ar: "نسخ", ja: "コピー", ko: "복사", zh: "复制", hi: "कॉपी करें", th: "คัดลอก", vi: "Sao chép", id: "Salin", ms: "Salin", sv: "Kopiera", da: "Kopier", nb: "Kopier", fi: "Kopioi", el: "Αντιγραφή", cs: "Kopírovat", hu: "Másolás", ro: "Copiază", hr: "Kopiraj", bg: "Копирай", sk: "Kopírovať", he: "העתק", uk: "Копіювати", fa: "کپی", bn: "কপি", sw: "Nakili", tl: "Kopyahin", ur: "کاپی", am: "ቅዳ", ha: "Kwafi", yo: "Ṣe ẹ̀da", wo: "Koppi", ru: "Копировать", sl: "Kopiraj", lt: "Kopijuoti", lv: "Kopēt", et: "Kopeeri",
  },
  "islamic.share": {
    fr: "Partager", en: "Share", es: "Compartir", de: "Teilen", it: "Condividi", pt: "Compartilhar", nl: "Delen", pl: "Udostępnij", tr: "Paylaş", ar: "مشاركة", ja: "共有", ko: "공유", zh: "分享", hi: "शेयर करें", th: "แชร์", vi: "Chia sẻ", id: "Bagikan", ms: "Kongsi", sv: "Dela", da: "Del", nb: "Del", fi: "Jaa", el: "Κοινοποίηση", cs: "Sdílet", hu: "Megosztás", ro: "Distribuie", hr: "Podijeli", bg: "Сподели", sk: "Zdieľať", he: "שתף", uk: "Поділитися", fa: "اشتراک‌گذاری", bn: "শেয়ার", sw: "Shiriki", tl: "Ibahagi", ur: "شیئر", am: "አጋራ", ha: "Raba", yo: "Pín", wo: "Séddal", ru: "Поделиться", sl: "Deli", lt: "Dalintis", lv: "Dalīties", et: "Jaga",
  },
  "islamic.copied": {
    fr: "Copié", en: "Copied", es: "Copiado", de: "Kopiert", it: "Copiato", pt: "Copiado", nl: "Gekopieerd", pl: "Skopiowano", tr: "Kopyalandı", ar: "تم النسخ", ja: "コピーしました", ko: "복사됨", zh: "已复制", hi: "कॉपी हुआ", th: "คัดลอกแล้ว", vi: "Đã sao chép", id: "Disalin", ms: "Disalin", sv: "Kopierat", da: "Kopieret", nb: "Kopiert", fi: "Kopioitu", el: "Αντιγράφηκε", cs: "Zkopírováno", hu: "Másolva", ro: "Copiat", hr: "Kopirano", bg: "Копирано", sk: "Skopírované", he: "הועתק", uk: "Скопійовано", fa: "کپی شد", bn: "কপি হয়েছে", sw: "Imenakiliwa", tl: "Nakopya", ur: "کاپی ہوگیا", am: "ተቀድቷል", ha: "An kwafa", yo: "Ti ṣe ẹ̀da", wo: "Koppi nañu", ru: "Скопировано", sl: "Kopirano", lt: "Nukopijuota", lv: "Nokopēts", et: "Kopeeritud",
  },
  "islamic.copy_error": {
    fr: "Impossible de copier", en: "Unable to copy", es: "No se pudo copiar", de: "Kopieren fehlgeschlagen", it: "Impossibile copiare", pt: "Não foi possível copiar", nl: "Kan niet kopiëren", pl: "Nie można skopiować", tr: "Kopyalanamadı", ar: "تعذر النسخ", ja: "コピーできません", ko: "복사할 수 없습니다", zh: "无法复制", hi: "कॉपी नहीं हो सका", th: "ไม่สามารถคัดลอกได้", vi: "Không thể sao chép", id: "Tidak bisa menyalin", ms: "Tidak dapat menyalin", sv: "Kan inte kopiera", da: "Kan ikke kopiere", nb: "Kan ikke kopiere", fi: "Ei voi kopioida", el: "Αδυναμία αντιγραφής", cs: "Nelze zkopírovat", hu: "Nem sikerült másolni", ro: "Nu se poate copia", hr: "Nije moguće kopirati", bg: "Не може да се копира", sk: "Nepodarilo sa skopírovať", he: "לא ניתן להעתיק", uk: "Не вдалося скопіювати", fa: "کپی ناموفق", bn: "কপি করা যায়নি", sw: "Haiwezi kunakili", tl: "Hindi makopya", ur: "کاپی نہیں ہو سکا", am: "መቅዳት አልተቻለም", ha: "Ba a iya kwafewa", yo: "Kò ṣe é ṣe ẹ̀da", wo: "Mën naa koppi", ru: "Не удалось скопировать", sl: "Ni mogoče kopirati", lt: "Nepavyko nukopijuoti", lv: "Nevar nokopēt", et: "Ei saa kopeerida",
  },
  "islamic.favorite": {
    fr: "Favori", en: "Favorite", es: "Favorito", de: "Favorit", it: "Preferito", pt: "Favorito", nl: "Favoriet", pl: "Ulubione", tr: "Favori", ar: "مفضلة", ja: "お気に入り", ko: "즐겨찾기", zh: "收藏", hi: "पसंदीदा", th: "รายการโปรด", vi: "Yêu thích", id: "Favorit", ms: "Kegemaran", sv: "Favorit", da: "Favorit", nb: "Favoritt", fi: "Suosikki", el: "Αγαπημένο", cs: "Oblíbené", hu: "Kedvenc", ro: "Favorit", hr: "Omiljeno", bg: "Любимо", sk: "Obľúbené", he: "מועדף", uk: "Улюблене", fa: "علاقه‌مندی", bn: "প্রিয়", sw: "Kipendwa", tl: "Paborito", ur: "پسندیدہ", am: "ተወዳጅ", ha: "Abin so", yo: "Àyànfẹ́", wo: "Mën la bëgg", ru: "Избранное", sl: "Priljubljeno", lt: "Mėgstamas", lv: "Izlase", et: "Lemmik",
  },
  "islamic.remove": {
    fr: "Retirer", en: "Remove", es: "Quitar", de: "Entfernen", it: "Rimuovi", pt: "Remover", nl: "Verwijderen", pl: "Usuń", tr: "Kaldır", ar: "إزالة", ja: "削除", ko: "제거", zh: "移除", hi: "हटाएं", th: "ลบ", vi: "Xóa", id: "Hapus", ms: "Buang", sv: "Ta bort", da: "Fjern", nb: "Fjern", fi: "Poista", el: "Αφαίρεση", cs: "Odebrat", hu: "Eltávolítás", ro: "Elimină", hr: "Ukloni", bg: "Премахни", sk: "Odstrániť", he: "הסר", uk: "Видалити", fa: "حذف", bn: "সরান", sw: "Ondoa", tl: "Alisin", ur: "ہٹائیں", am: "አስወግድ", ha: "Cire", yo: "Yọ kúrò", wo: "Génn", ru: "Удалить", sl: "Odstrani", lt: "Pašalinti", lv: "Noņemt", et: "Eemalda",
  },
  "islamic.no_favorites": {
    fr: "Aucun favori", en: "No favorites", es: "Sin favoritos", de: "Keine Favoriten", it: "Nessun preferito", pt: "Sem favoritos", nl: "Geen favorieten", pl: "Brak ulubionych", tr: "Favori yok", ar: "لا مفضلات", ja: "お気に入りなし", ko: "즐겨찾기 없음", zh: "没有收藏", hi: "कोई पसंदीदा नहीं", th: "ไม่มีรายการโปรด", vi: "Không có mục yêu thích", id: "Tidak ada favorit", ms: "Tiada kegemaran", sv: "Inga favoriter", da: "Ingen favoritter", nb: "Ingen favoritter", fi: "Ei suosikkeja", el: "Χωρίς αγαπημένα", cs: "Žádné oblíbené", hu: "Nincsenek kedvencek", ro: "Fără favorite", hr: "Nema omiljenih", bg: "Няма любими", sk: "Žiadne obľúbené", he: "אין מועדפים", uk: "Немає улюблених", fa: "بدون علاقه‌مندی", bn: "কোনো প্রিয় নেই", sw: "Hakuna vipendwa", tl: "Walang paborito", ur: "کوئی پسندیدہ نہیں", am: "ምንም ተወዳጆች የሉም", ha: "Babu abin so", yo: "Kò sí àyànfẹ́", wo: "Amul benn ci bëgg yi", ru: "Нет избранного", sl: "Ni priljubljenih", lt: "Nėra mėgstamų", lv: "Nav izlases", et: "Lemmikuid pole",
  },
  "islamic.search_placeholder": {
    fr: "Rechercher...", en: "Search...", es: "Buscar...", de: "Suchen...", it: "Cerca...", pt: "Pesquisar...", nl: "Zoeken...", pl: "Szukaj...", tr: "Ara...", ar: "...بحث", ja: "検索...", ko: "검색...", zh: "搜索...", hi: "खोजें...", th: "ค้นหา...", vi: "Tìm kiếm...", id: "Cari...", ms: "Cari...", sv: "Sök...", da: "Søg...", nb: "Søk...", fi: "Etsi...", el: "Αναζήτηση...", cs: "Hledat...", hu: "Keresés...", ro: "Caută...", hr: "Traži...", bg: "Търси...", sk: "Hľadať...", he: "...חיפוש", uk: "Пошук...", fa: "...جستجو", bn: "অনুসন্ধান...", sw: "Tafuta...", tl: "Maghanap...", ur: "...تلاش", am: "ፍለጋ...", ha: "Bincika...", yo: "Wá...", wo: "Seet...", ru: "Поиск...", sl: "Išči...", lt: "Ieškoti...", lv: "Meklēt...", et: "Otsi...",
  },
  "islamic.next_prayer": {
    fr: "Prochaine prière", en: "Next prayer", es: "Próxima oración", de: "Nächstes Gebet", it: "Prossima preghiera", pt: "Próxima oração", nl: "Volgend gebed", pl: "Następna modlitwa", tr: "Sonraki namaz", ar: "الصلاة التالية", ja: "次の礼拝", ko: "다음 예배", zh: "下次祈祷", hi: "अगली नमाज़", th: "ละหมาดถัดไป", vi: "Giờ cầu nguyện tiếp theo", id: "Shalat berikutnya", ms: "Solat seterusnya", sv: "Nästa bön", da: "Næste bøn", nb: "Neste bønn", fi: "Seuraava rukous", el: "Επόμενη προσευχή", cs: "Další modlitba", hu: "Következő ima", ro: "Următoarea rugăciune", hr: "Sljedeća molitva", bg: "Следваща молитва", sk: "Ďalšia modlitba", he: "התפילה הבאה", uk: "Наступна молитва", fa: "نماز بعدی", bn: "পরবর্তী নামাজ", sw: "Swala inayofuata", tl: "Susunod na dasal", ur: "اگلی نماز", am: "ቀጣይ ጸሎት", ha: "Salla mai zuwa", yo: "Àdúrà tó kàn", wo: "Julli bi ci topp", ru: "Следующая молитва", sl: "Naslednja molitev", lt: "Kita malda", lv: "Nākamā lūgšana", et: "Järgmine palve",
  },
  "islamic.next": {
    fr: "Prochaine", en: "Next", es: "Siguiente", de: "Nächste", it: "Prossima", pt: "Próxima", nl: "Volgende", pl: "Następna", tr: "Sonraki", ar: "التالية", ja: "次", ko: "다음", zh: "下一个", hi: "अगला", th: "ถัดไป", vi: "Tiếp theo", id: "Berikutnya", ms: "Seterusnya", sv: "Nästa", da: "Næste", nb: "Neste", fi: "Seuraava", el: "Επόμενη", cs: "Další", hu: "Következő", ro: "Următoare", hr: "Sljedeća", bg: "Следваща", sk: "Ďalšia", he: "הבא", uk: "Наступна", fa: "بعدی", bn: "পরবর্তী", sw: "Inayofuata", tl: "Susunod", ur: "اگلا", am: "ቀጣይ", ha: "Mai zuwa", yo: "Tó kàn", wo: "Bi ci topp", ru: "Следующая", sl: "Naslednja", lt: "Kita", lv: "Nākamā", et: "Järgmine",
  },
  "islamic.in_time": {
    fr: "dans", en: "in", es: "en", de: "in", it: "tra", pt: "em", nl: "over", pl: "za", tr: "sonra", ar: "بعد", ja: "後", ko: "후", zh: "后", hi: "में", th: "ใน", vi: "trong", id: "dalam", ms: "dalam", sv: "om", da: "om", nb: "om", fi: "kuluttua", el: "σε", cs: "za", hu: "múlva", ro: "peste", hr: "za", bg: "след", sk: "za", he: "בעוד", uk: "через", fa: "تا", bn: "পরে", sw: "katika", tl: "sa", ur: "میں", am: "በ", ha: "cikin", yo: "ní", wo: "ci", ru: "через", sl: "čez", lt: "po", lv: "pēc", et: "pärast",
  },
  "islamic.today_times": {
    fr: "Horaires du Jour", en: "Today's Times", es: "Horarios del Día", de: "Heutige Zeiten", it: "Orari di Oggi", pt: "Horários de Hoje", nl: "Tijden van Vandaag", pl: "Dzisiejsze Godziny", tr: "Bugünün Vakitleri", ar: "أوقات اليوم", ja: "本日の時刻", ko: "오늘의 시간", zh: "今日时间", hi: "आज के समय", th: "เวลาวันนี้", vi: "Giờ Hôm Nay", id: "Waktu Hari Ini", ms: "Waktu Hari Ini", sv: "Dagens Tider", da: "Dagens Tider", nb: "Dagens Tider", fi: "Päivän Ajat", el: "Σημερινές Ώρες", cs: "Dnešní Časy", hu: "Mai Időpontok", ro: "Orele de Astăzi", hr: "Današnja Vremena", bg: "Днешни Часове", sk: "Dnešné Časy", he: "שעות היום", uk: "Час сьогодні", fa: "اوقات امروز", bn: "আজকের সময়", sw: "Nyakati za Leo", tl: "Oras Ngayon", ur: "آج کے اوقات", am: "የዛሬ ሰዓታት", ha: "Lokutan Yau", yo: "Àkókò Òní", wo: "Waxtu tey", ru: "Сегодня", sl: "Današnji časi", lt: "Šiandienos laikai", lv: "Šodienas laiki", et: "Tänased ajad",
  },
  "islamic.calculation_method": {
    fr: "Méthode de calcul", en: "Calculation Method", es: "Método de Cálculo", de: "Berechnungsmethode", it: "Metodo di Calcolo", pt: "Método de Cálculo", nl: "Berekeningsmethode", pl: "Metoda Obliczeń", tr: "Hesaplama Yöntemi", ar: "طريقة الحساب", ja: "計算方法", ko: "계산 방법", zh: "计算方法", hi: "गणना विधि", th: "วิธีคำนวณ", vi: "Phương Pháp Tính", id: "Metode Perhitungan", ms: "Kaedah Pengiraan", sv: "Beräkningsmetod", da: "Beregningsmetode", nb: "Beregningsmetode", fi: "Laskentamenetelmä", el: "Μέθοδος Υπολογισμού", cs: "Metoda Výpočtu", hu: "Számítási Módszer", ro: "Metodă de Calcul", hr: "Metoda Izračuna", bg: "Метод на Изчисление", sk: "Metóda Výpočtu", he: "שיטת חישוב", uk: "Метод Розрахунку", fa: "روش محاسبه", bn: "হিসাবের পদ্ধতি", sw: "Njia ya Kukokotoa", tl: "Paraan ng Pagkalkula", ur: "حساب کا طریقہ", am: "የስሌት ዘዴ", ha: "Hanyar Lissafi", yo: "Ọ̀nà Ìṣírò", wo: "Yoonu xam-xam", ru: "Метод расчёта", sl: "Metoda izračuna", lt: "Skaičiavimo metodas", lv: "Aprēķina metode", et: "Arvutusmeetod",
  },
  "islamic.asr_calculation": {
    fr: "Calcul Asr", en: "Asr Calculation", es: "Cálculo del Asr", de: "Asr-Berechnung", it: "Calcolo Asr", pt: "Cálculo do Asr", nl: "Asr-berekening", pl: "Obliczenie Asr", tr: "İkindi Hesabı", ar: "حساب العصر", ja: "アスル計算", ko: "아스르 계산", zh: "阿斯尔计算", hi: "अस्र गणना", th: "การคำนวณอัศรฺ", vi: "Tính Asr", id: "Perhitungan Ashar", ms: "Kiraan Asar", sv: "Asr-beräkning", da: "Asr-beregning", nb: "Asr-beregning", fi: "Asr-laskenta", el: "Υπολογισμός Asr", cs: "Výpočet Asr", hu: "Asr számítás", ro: "Calcul Asr", hr: "Izračun Asr", bg: "Изчисление на Аср", sk: "Výpočet Asr", he: "חישוב עצר", uk: "Розрахунок Аср", fa: "محاسبه عصر", bn: "আসর হিসাব", sw: "Hesabu ya Alasiri", tl: "Pagkalkula ng Asr", ur: "عصر کا حساب", am: "የዐስር ስሌት", ha: "Lissafin Asr", yo: "Ìṣírò Asr", wo: "Xam-xam Asr", ru: "Расчёт Аср", sl: "Izračun Asr", lt: "Asr skaičiavimas", lv: "Asr aprēķins", et: "Asr arvutus",
  },
  "islamic.adhan_notifications": {
    fr: "Notifications Adhan", en: "Adhan Notifications", es: "Notificaciones del Adhan", de: "Adhan-Benachrichtigungen", it: "Notifiche Adhan", pt: "Notificações do Adhan", nl: "Adhan-meldingen", pl: "Powiadomienia Adhan", tr: "Ezan Bildirimleri", ar: "إشعارات الأذان", ja: "アザーン通知", ko: "아잔 알림", zh: "唤礼通知", hi: "अज़ान सूचनाएं", th: "การแจ้งเตือนอาซาน", vi: "Thông báo Adhan", id: "Notifikasi Adzan", ms: "Pemberitahuan Azan", sv: "Adhan-notiser", da: "Adhan-notifikationer", nb: "Adhan-varsler", fi: "Adhan-ilmoitukset", el: "Ειδοποιήσεις Αζάν", cs: "Oznámení Adhán", hu: "Adhan értesítések", ro: "Notificări Adhan", hr: "Obavijesti za Ezan", bg: "Известия за Езан", sk: "Oznámenia Adhán", he: "התראות אזאן", uk: "Сповіщення Азан", fa: "اعلان‌های اذان", bn: "আযান বিজ্ঞপ্তি", sw: "Arifa za Adhana", tl: "Mga Abiso ng Adhan", ur: "اذان کی اطلاعات", am: "የአዛን ማስታወቂያዎች", ha: "Sanarwar Azumi", yo: "Ìfitọ́nilétí Adhan", wo: "Xibaar yi Azan", ru: "Уведомления Азан", sl: "Obvestila Ezan", lt: "Adhan pranešimai", lv: "Adhan paziņojumi", et: "Adhan teavitused",
  },
  "islamic.reminders_enabled": {
    fr: "Rappels activés", en: "Reminders enabled", es: "Recordatorios activados", de: "Erinnerungen aktiviert", it: "Promemoria attivati", pt: "Lembretes ativados", nl: "Herinneringen ingeschakeld", pl: "Przypomnienia włączone", tr: "Hatırlatmalar açık", ar: "التذكيرات مفعّلة", ja: "リマインダー有効", ko: "알림 활성화됨", zh: "提醒已启用", hi: "रिमाइंडर सक्रिय", th: "เปิดการแจ้งเตือนแล้ว", vi: "Đã bật nhắc nhở", id: "Pengingat diaktifkan", ms: "Peringatan diaktifkan", sv: "Påminnelser aktiverade", da: "Påmindelser aktiveret", nb: "Påminnelser aktivert", fi: "Muistutukset käytössä", el: "Υπενθυμίσεις ενεργοποιημένες", cs: "Připomínky zapnuty", hu: "Emlékeztetők bekapcsolva", ro: "Mementouri activate", hr: "Podsjetnici omogućeni", bg: "Напомняния включени", sk: "Pripomienky zapnuté", he: "תזכורות פעילות", uk: "Нагадування увімкнено", fa: "یادآوری‌ها فعال", bn: "রিমাইন্ডার সক্রিয়", sw: "Vikumbusho vimewashwa", tl: "Mga paalala naka-enable", ur: "یاد دہانیاں فعال", am: "ማስታወሻዎች ነቅተዋል", ha: "An kunna tunaɗarwa", yo: "Ìrántí ti ṣiṣẹ́", wo: "Tukkeem yi dañu dëkk", ru: "Напоминания включены", sl: "Opomniki vklopljeni", lt: "Priminimai įjungti", lv: "Atgādinājumi ieslēgti", et: "Meeldetuletused lubatud",
  },
  "islamic.enable_reminders": {
    fr: "Activez les rappels", en: "Enable reminders", es: "Activar recordatorios", de: "Erinnerungen aktivieren", it: "Attiva promemoria", pt: "Ativar lembretes", nl: "Herinneringen inschakelen", pl: "Włącz przypomnienia", tr: "Hatırlatmaları aç", ar: "تفعيل التذكيرات", ja: "リマインダーを有効にする", ko: "알림 활성화", zh: "启用提醒", hi: "रिमाइंडर सक्रिय करें", th: "เปิดการแจ้งเตือน", vi: "Bật nhắc nhở", id: "Aktifkan pengingat", ms: "Aktifkan peringatan", sv: "Aktivera påminnelser", da: "Aktivér påmindelser", nb: "Aktiver påminnelser", fi: "Ota muistutukset käyttöön", el: "Ενεργοποίηση υπενθυμίσεων", cs: "Zapnout připomínky", hu: "Emlékeztetők bekapcsolása", ro: "Activează mementouri", hr: "Omogući podsjetnike", bg: "Включи напомняния", sk: "Zapnúť pripomienky", he: "הפעל תזכורות", uk: "Увімкнути нагадування", fa: "فعال‌سازی یادآوری", bn: "রিমাইন্ডার সক্রিয় করুন", sw: "Washa vikumbusho", tl: "I-enable ang paalala", ur: "یاد دہانیاں فعال کریں", am: "ማስታወሻዎችን አንቃ", ha: "Kunna tunaɗarwa", yo: "Mú ìrántí ṣiṣẹ́", wo: "Def tukkeem yi", ru: "Включить напоминания", sl: "Vklopi opomnike", lt: "Įjungti priminimus", lv: "Ieslēgt atgādinājumus", et: "Luba meeldetuletused",
  },
  "islamic.prayer_journal": {
    fr: "Journal de Prière", en: "Prayer Journal", es: "Diario de Oración", de: "Gebetstagebuch", it: "Diario di Preghiera", pt: "Diário de Oração", nl: "Gebedsdagboek", pl: "Dziennik Modlitw", tr: "Namaz Günlüğü", ar: "سجل الصلاة", ja: "礼拝日記", ko: "예배 일지", zh: "祈祷日记", hi: "नमाज़ डायरी", th: "สมุดบันทึกละหมาด", vi: "Nhật Ký Cầu Nguyện", id: "Jurnal Shalat", ms: "Jurnal Solat", sv: "Bönejournal", da: "Bønnejournal", nb: "Bønnejournal", fi: "Rukouspäiväkirja", el: "Ημερολόγιο Προσευχής", cs: "Deník Modliteb", hu: "Imanapló", ro: "Jurnal de Rugăciune", hr: "Dnevnik Molitve", bg: "Дневник на Молитвите", sk: "Denník Modlitieb", he: "יומן תפילה", uk: "Щоденник Молитов", fa: "دفتر نماز", bn: "নামাজ ডায়েরি", sw: "Jarida ya Swala", tl: "Talaarawan ng Dasal", ur: "نماز ڈائری", am: "የጸሎት ማስታወሻ", ha: "Littafin Salla", yo: "Ìwé Àdúrà", wo: "Kàrne Julli", ru: "Дневник Молитв", sl: "Dnevnik Molitev", lt: "Maldų Dienoraštis", lv: "Lūgšanu Dienasgrāmata", et: "Palvepäevik",
  },
  "islamic.days_streak": {
    fr: "jours de suite", en: "day streak", es: "días seguidos", de: "Tage in Folge", it: "giorni consecutivi", pt: "dias seguidos", nl: "dagen op rij", pl: "dni z rzędu", tr: "gün üst üste", ar: "أيام متتالية", ja: "日連続", ko: "일 연속", zh: "天连续", hi: "दिन लगातार", th: "วันติดต่อกัน", vi: "ngày liên tiếp", id: "hari berturut-turut", ms: "hari berturut-turut", sv: "dagar i rad", da: "dage i træk", nb: "dager på rad", fi: "päivää peräkkäin", el: "μέρες στη σειρά", cs: "dní v řadě", hu: "napja egymás után", ro: "zile consecutive", hr: "dana zaredom", bg: "дни подред", sk: "dní v rade", he: "ימים ברצף", uk: "днів поспіль", fa: "روز پیاپی", bn: "দিন একটানা", sw: "siku mfululizo", tl: "araw sunud-sunod", ur: "دن مسلسل", am: "ተከታታይ ቀናት", ha: "kwanaki a jere", yo: "ọjọ́ lẹ́sẹẹsẹ", wo: "fan ci biir", ru: "дней подряд", sl: "dni zapored", lt: "dienų iš eilės", lv: "dienas pēc kārtas", et: "päeva järjest",
  },
  "islamic.prayers_logged_today": {
    fr: "prières enregistrées aujourd'hui", en: "prayers logged today", es: "oraciones registradas hoy", de: "Gebete heute aufgezeichnet", it: "preghiere registrate oggi", pt: "orações registradas hoje", nl: "gebeden vandaag geregistreerd", pl: "modlitwy zarejestrowane dziś", tr: "bugün kaydedilen namazlar", ar: "صلوات مسجلة اليوم", ja: "本日記録された礼拝", ko: "오늘 기록된 예배", zh: "今日已记录的祈祷", hi: "आज दर्ज की गई नमाज़ें", th: "ละหมาดที่บันทึกวันนี้", vi: "cầu nguyện ghi nhận hôm nay", id: "shalat tercatat hari ini", ms: "solat dicatat hari ini", sv: "böner registrerade idag", da: "bønner registreret i dag", nb: "bønner registrert i dag", fi: "rukous kirjattu tänään", el: "προσευχές καταγράφηκαν σήμερα", cs: "modlitby zaznamenané dnes", hu: "ima rögzítve ma", ro: "rugăciuni înregistrate azi", hr: "molitvi zabilježeno danas", bg: "молитви записани днес", sk: "modlitby zaznamenané dnes", he: "תפילות שנרשמו היום", uk: "молитов записано сьогодні", fa: "نمازهای ثبت‌شده امروز", bn: "আজ নামাজ রেকর্ড করা হয়েছে", sw: "swala zilizorekodiwa leo", tl: "dasal na naitala ngayon", ur: "آج ریکارڈ شدہ نمازیں", am: "ዛሬ የተመዘገቡ ጸሎቶች", ha: "sallolli da aka rubuta yau", yo: "àdúrà tí a forúkọ lónìí", wo: "julli yi ñu bindee tey", ru: "молитв записано сегодня", sl: "molitev zabeleženih danes", lt: "maldos užregistruotos šiandien", lv: "lūgšanas reģistrētas šodien", et: "palveid registreeritud täna",
  },
  "islamic.show_history": {
    fr: "Voir l'historique", en: "Show history", es: "Ver historial", de: "Verlauf anzeigen", it: "Mostra cronologia", pt: "Ver histórico", nl: "Geschiedenis tonen", pl: "Pokaż historię", tr: "Geçmişi göster", ar: "عرض السجل", ja: "履歴を表示", ko: "기록 보기", zh: "查看历史", hi: "इतिहास दिखाएं", th: "แสดงประวัติ", vi: "Xem lịch sử", id: "Tampilkan riwayat", ms: "Tunjukkan sejarah", sv: "Visa historik", da: "Vis historik", nb: "Vis historikk", fi: "Näytä historia", el: "Εμφάνιση ιστορικού", cs: "Zobrazit historii", hu: "Előzmények megtekintése", ro: "Afișează istoricul", hr: "Prikaži povijest", bg: "Покажи история", sk: "Zobraziť históriu", he: "הצג היסטוריה", uk: "Показати історію", fa: "نمایش تاریخچه", bn: "ইতিহাস দেখুন", sw: "Onyesha historia", tl: "Ipakita ang kasaysayan", ur: "ہسٹری دکھائیں", am: "ታሪክ አሳይ", ha: "Nuna tarihi", yo: "Fi ìtàn hàn", wo: "Wone taariix bi", ru: "Показать историю", sl: "Prikaži zgodovino", lt: "Rodyti istoriją", lv: "Rādīt vēsturi", et: "Näita ajalugu",
  },
  "islamic.hide_history": {
    fr: "Masquer l'historique", en: "Hide history", es: "Ocultar historial", de: "Verlauf ausblenden", it: "Nascondi cronologia", pt: "Ocultar histórico", nl: "Geschiedenis verbergen", pl: "Ukryj historię", tr: "Geçmişi gizle", ar: "إخفاء السجل", ja: "履歴を非表示", ko: "기록 숨기기", zh: "隐藏历史", hi: "इतिहास छुपाएं", th: "ซ่อนประวัติ", vi: "Ẩn lịch sử", id: "Sembunyikan riwayat", ms: "Sembunyikan sejarah", sv: "Dölj historik", da: "Skjul historik", nb: "Skjul historikk", fi: "Piilota historia", el: "Απόκρυψη ιστορικού", cs: "Skrýt historii", hu: "Előzmények elrejtése", ro: "Ascunde istoricul", hr: "Sakrij povijest", bg: "Скрий история", sk: "Skryť históriu", he: "הסתר היסטוריה", uk: "Сховати історію", fa: "پنهان کردن تاریخچه", bn: "ইতিহাস লুকান", sw: "Ficha historia", tl: "Itago ang kasaysayan", ur: "ہسٹری چھپائیں", am: "ታሪክ ደብቅ", ha: "Ɓoye tarihi", yo: "Fi ìtàn pamọ́", wo: "Nëbb taariix bi", ru: "Скрыть историю", sl: "Skrij zgodovino", lt: "Slėpti istoriją", lv: "Slēpt vēsturi", et: "Peida ajalugu",
  },
  "islamic.quran.title": {
    fr: "Le Saint Coran", en: "The Holy Quran", es: "El Sagrado Corán", de: "Der Heilige Koran", it: "Il Sacro Corano", pt: "O Sagrado Alcorão", nl: "De Heilige Koran", pl: "Święty Koran", tr: "Kur'an-ı Kerim", ar: "القرآن الكريم", ja: "聖クルアーン", ko: "성 꾸란", zh: "古兰经", hi: "पवित्र क़ुरान", th: "อัลกุรอานอันศักดิ์สิทธิ์", vi: "Kinh Quran Thánh", id: "Al-Quran Al-Karim", ms: "Al-Quran Al-Karim", sv: "Den Heliga Koranen", da: "Den Hellige Koran", nb: "Den Hellige Koranen", fi: "Pyhä Koraani", el: "Το Ιερό Κοράνι", cs: "Svatý Korán", hu: "A Szent Korán", ro: "Sfântul Coran", hr: "Sveti Kur'an", bg: "Свещеният Коран", sk: "Svätý Korán", he: "הקוראן הקדוש", uk: "Священний Коран", fa: "قرآن مجید", bn: "পবিত্র কুরআন", sw: "Qurani Tukufu", tl: "Ang Banal na Quran", ur: "قرآن مجید", am: "ቅዱስ ቁርኣን", ha: "Alqur'ani Mai Girma", yo: "Al-Qur'an Mímọ́", wo: "Alxuraan Wu Teddu", ru: "Священный Коран", sl: "Sveti Koran", lt: "Šventasis Koranas", lv: "Svētais Korāns", et: "Püha Koraan",
  },
  "islamic.quran.subtitle": {
    fr: "114 Sourates · 30 Juz — Texte arabe, traduction & audio", en: "114 Surahs · 30 Juz — Arabic text, translation & audio", es: "114 Suras · 30 Juz — Texto árabe, traducción y audio", de: "114 Suren · 30 Dschuz — Arabischer Text, Übersetzung & Audio", it: "114 Sure · 30 Juz — Testo arabo, traduzione e audio", pt: "114 Suras · 30 Juz — Texto árabe, tradução e áudio", nl: "114 Soera's · 30 Juz — Arabische tekst, vertaling & audio", pl: "114 Sur · 30 Dżuz — Tekst arabski, tłumaczenie i audio", tr: "114 Sure · 30 Cüz — Arapça metin, çeviri ve ses", ar: "١١٤ سورة · ٣٠ جزءًا — النص العربي والترجمة والصوت", ja: "114章 · 30ジュズ — アラビア語テキスト、翻訳、音声", ko: "114 수라 · 30 주즈 — 아랍어 텍스트, 번역 및 오디오", zh: "114章 · 30卷 — 阿拉伯文、译文和音频", hi: "114 सूरतें · 30 जुज़ — अरबी पाठ, अनुवाद और ऑडियो", th: "114 ซูเราะฮ์ · 30 ญุซ — ข้อความอาหรับ การแปล และเสียง", vi: "114 Surah · 30 Juz — Văn bản Ả Rập, bản dịch & âm thanh", id: "114 Surah · 30 Juz — Teks Arab, terjemahan & audio", ms: "114 Surah · 30 Juz — Teks Arab, terjemahan & audio", sv: "114 Suror · 30 Juz — Arabisk text, översättning & ljud", da: "114 Suraer · 30 Juz — Arabisk tekst, oversættelse & lyd", nb: "114 Suraer · 30 Juz — Arabisk tekst, oversettelse og lyd", fi: "114 Suuraa · 30 Juzia — arabiankielinen teksti, käännös ja ääni", el: "114 Σούρες · 30 Τζουζ — Αραβικό κείμενο, μετάφραση & ήχος", cs: "114 Súr · 30 Džuzů — Arabský text, překlad a audio", hu: "114 Szúra · 30 Dzsuz — Arab szöveg, fordítás és hang", ro: "114 Sure · 30 Juz — Text arab, traducere și audio", hr: "114 Sura · 30 Džuzova — Arapski tekst, prijevod i audio", bg: "114 Сури · 30 Джуза — Арабски текст, превод и аудио", sk: "114 Súr · 30 Džuzov — Arabský text, preklad a audio", he: "114 סורות · 30 ג'וז — טקסט ערבי, תרגום ואודיו", uk: "114 Сур · 30 Джузів — арабський текст, переклад і аудіо", fa: "۱۱۴ سوره · ۳۰ جزء — متن عربی، ترجمه و صوت", bn: "১১৪ সূরা · ৩০ জুয — আরবি পাঠ, অনুবাদ ও অডিও", sw: "Sura 114 · Juz 30 — Maandishi ya Kiarabu, tafsiri na sauti", tl: "114 Surah · 30 Juz — Tekstong Arabe, salin at audio", ur: "114 سورتیں · 30 پارے — عربی متن، ترجمہ اور آڈیو", am: "114 ሱራዎች · 30 ጁዝ — ዐረብኛ ጽሑፍ፣ ትርጉም እና ድምጽ", ha: "Surori 114 · Juzu 30 — Rubutu na Larabci, fassara da sautin", yo: "Sura 114 · Juzu 30 — Ọ̀rọ̀ Lárúbáwá, ìtumọ̀ àti ohùn", wo: "114 Surat · 30 Juz — Kàddu arab, tekki ak audio", ru: "114 Сур · 30 Джузов — арабский текст, перевод и аудио", sl: "114 Sur · 30 Džuzov — Arabsko besedilo, prevod in zvok", lt: "114 Surų · 30 Džuzų — Arabiškas tekstas, vertimas ir garsas", lv: "114 Sūras · 30 Džuzi — Arābu teksts, tulkojums un audio", et: "114 Suurat · 30 Džuzi — Araabia tekst, tõlge ja heli",
  },
  "islamic.quran.translation_language": {
    fr: "Langue de traduction", en: "Translation language", es: "Idioma de traducción", de: "Übersetzungssprache", it: "Lingua di traduzione", pt: "Idioma de tradução", nl: "Vertaaltaal", pl: "Język tłumaczenia", tr: "Çeviri dili", ar: "لغة الترجمة", ja: "翻訳言語", ko: "번역 언어", zh: "翻译语言", hi: "अनुवाद भाषा", th: "ภาษาแปล", vi: "Ngôn ngữ dịch", id: "Bahasa terjemahan", ms: "Bahasa terjemahan", sv: "Översättningsspråk", da: "Oversættelsessprog", nb: "Oversettelsesspråk", fi: "Käännöskieli", el: "Γλώσσα μετάφρασης", cs: "Jazyk překladu", hu: "Fordítás nyelve", ro: "Limba de traducere", hr: "Jezik prijevoda", bg: "Език на превода", sk: "Jazyk prekladu", he: "שפת תרגום", uk: "Мова перекладу", fa: "زبان ترجمه", bn: "অনুবাদ ভাষা", sw: "Lugha ya tafsiri", tl: "Wika ng pagsasalin", ur: "ترجمے کی زبان", am: "የትርጉም ቋንቋ", ha: "Harshen fassara", yo: "Èdè ìtumọ̀", wo: "Làkk tekki", ru: "Язык перевода", sl: "Jezik prevoda", lt: "Vertimo kalba", lv: "Tulkojuma valoda", et: "Tõlkekeel",
  },
  "islamic.quran.audio_player": {
    fr: "Lecteur Audio", en: "Audio Player", es: "Reproductor de Audio", de: "Audioplayer", it: "Lettore Audio", pt: "Reprodutor de Áudio", nl: "Audiospeler", pl: "Odtwarzacz Audio", tr: "Ses Oynatıcı", ar: "مشغل الصوت", ja: "オーディオプレーヤー", ko: "오디오 플레이어", zh: "音频播放器", hi: "ऑडियो प्लेयर", th: "เครื่องเล่นเสียง", vi: "Trình phát âm thanh", id: "Pemutar Audio", ms: "Pemain Audio", sv: "Ljudspelare", da: "Lydafspiller", nb: "Lydavspiller", fi: "Äänisoitin", el: "Αναπαραγωγέας Ήχου", cs: "Přehrávač zvuku", hu: "Hanglejátszó", ro: "Player Audio", hr: "Audio Player", bg: "Аудио плейър", sk: "Prehrávač zvuku", he: "נגן שמע", uk: "Аудіоплеєр", fa: "پخش‌کننده صوتی", bn: "অডিও প্লেয়ার", sw: "Kicheza Sauti", tl: "Audio Player", ur: "آڈیو پلیئر", am: "ድምጽ ማጫወቻ", ha: "Mai Kunna Sauti", yo: "Ẹ̀rọ Ohùn", wo: "Jàpp Audio", ru: "Аудиоплеер", sl: "Predvajalnik zvoka", lt: "Garso grotuvas", lv: "Audio atskaņotājs", et: "Helipleier",
  },
  "islamic.quran.stop": {
    fr: "Arrêter", en: "Stop", es: "Detener", de: "Stoppen", it: "Ferma", pt: "Parar", nl: "Stoppen", pl: "Zatrzymaj", tr: "Durdur", ar: "إيقاف", ja: "停止", ko: "중지", zh: "停止", hi: "रोकें", th: "หยุด", vi: "Dừng", id: "Berhenti", ms: "Berhenti", sv: "Stoppa", da: "Stop", nb: "Stopp", fi: "Pysäytä", el: "Διακοπή", cs: "Zastavit", hu: "Leállítás", ro: "Oprește", hr: "Zaustavi", bg: "Спри", sk: "Zastaviť", he: "עצור", uk: "Зупинити", fa: "توقف", bn: "থামান", sw: "Simama", tl: "Itigil", ur: "روکیں", am: "አቁም", ha: "Tsaya", yo: "Dúró", wo: "Taxaw", ru: "Остановить", sl: "Ustavi", lt: "Sustabdyti", lv: "Apturēt", et: "Peata",
  },
  "islamic.quran.verse_copied": {
    fr: "Verset copié", en: "Verse copied", es: "Versículo copiado", de: "Vers kopiert", it: "Versetto copiato", pt: "Versículo copiado", nl: "Vers gekopieerd", pl: "Werset skopiowany", tr: "Ayet kopyalandı", ar: "تم نسخ الآية", ja: "節がコピーされました", ko: "구절 복사됨", zh: "经文已复制", hi: "आयत कॉपी की गई", th: "คัดลอกอายะฮ์แล้ว", vi: "Đã sao chép câu", id: "Ayat disalin", ms: "Ayat disalin", sv: "Vers kopierad", da: "Vers kopieret", nb: "Vers kopiert", fi: "Jae kopioitu", el: "Εδάφιο αντιγράφηκε", cs: "Verš zkopírován", hu: "Vers másolva", ro: "Verset copiat", hr: "Ajet kopiran", bg: "Стихът е копиран", sk: "Verš skopírovaný", he: "פסוק הועתק", uk: "Аят скопійовано", fa: "آیه کپی شد", bn: "আয়াত কপি হয়েছে", sw: "Aya imenakiliwa", tl: "Talata na-kopya", ur: "آیت کاپی ہوگئی", am: "አንቀጽ ተቀድቷል", ha: "An kwafa aya", yo: "Ti ṣe ẹ̀da aya", wo: "Koppi nañu aya bi", ru: "Аят скопирован", sl: "Ajet kopiran", lt: "Ajatas nukopijuotas", lv: "Pants nokopēts", et: "Värss kopeeritud",
  },
  "islamic.quran.favorites": {
    fr: "Versets Favoris", en: "Favorite Verses", es: "Versículos Favoritos", de: "Lieblingsverse", it: "Versetti Preferiti", pt: "Versículos Favoritos", nl: "Favoriete Verzen", pl: "Ulubione Wersety", tr: "Favori Ayetler", ar: "الآيات المفضلة", ja: "お気に入りの節", ko: "즐겨찾기 구절", zh: "收藏的经文", hi: "पसंदीदा आयतें", th: "อายะฮ์ที่ชื่นชอบ", vi: "Câu Yêu Thích", id: "Ayat Favorit", ms: "Ayat Kegemaran", sv: "Favoritverser", da: "Favoritvers", nb: "Favorittvers", fi: "Suosikkijakeet", el: "Αγαπημένα Εδάφια", cs: "Oblíbené Verše", hu: "Kedvenc Versek", ro: "Versete Favorite", hr: "Omiljeni Ajeti", bg: "Любими Стихове", sk: "Obľúbené Verše", he: "פסוקים מועדפים", uk: "Улюблені Аяти", fa: "آیات مورد علاقه", bn: "প্রিয় আয়াত", sw: "Aya Zipendwa", tl: "Mga Paboritong Talata", ur: "پسندیدہ آیات", am: "ተወዳጅ አንቀጾች", ha: "Ayoyin Da Aka Fi So", yo: "Àwọn Aya Àyànfẹ́", wo: "Aya yi ngën la bëgg", ru: "Избранные Аяты", sl: "Priljubljeni Ajeti", lt: "Mėgstami Aatai", lv: "Izlases Panti", et: "Lemmikvärsid",
  },
  "islamic.quran.bookmarks": {
    fr: "Marque-pages", en: "Bookmarks", es: "Marcadores", de: "Lesezeichen", it: "Segnalibri", pt: "Marcadores", nl: "Bladwijzers", pl: "Zakładki", tr: "Yer İmleri", ar: "علامات مرجعية", ja: "ブックマーク", ko: "북마크", zh: "书签", hi: "बुकमार्क", th: "บุ๊กมาร์ก", vi: "Dấu trang", id: "Penanda", ms: "Penanda Buku", sv: "Bokmärken", da: "Bogmærker", nb: "Bokmerker", fi: "Kirjanmerkit", el: "Σελιδοδείκτες", cs: "Záložky", hu: "Könyvjelzők", ro: "Marcaje", hr: "Oznake", bg: "Отметки", sk: "Záložky", he: "סימניות", uk: "Закладки", fa: "نشانک‌ها", bn: "বুকমার্ক", sw: "Alama", tl: "Mga Bookmark", ur: "بُک مارکس", am: "ምልክቶች", ha: "Alamomi", yo: "Àmì ìkà", wo: "Markë", ru: "Закладки", sl: "Zaznamki", lt: "Žymės", lv: "Grāmatzīmes", et: "Järjehoidjad",
  },
  "islamic.quran.bookmark_added": {
    fr: "Marque-page ajouté", en: "Bookmark added", es: "Marcador añadido", de: "Lesezeichen hinzugefügt", it: "Segnalibro aggiunto", pt: "Marcador adicionado", nl: "Bladwijzer toegevoegd", pl: "Zakładka dodana", tr: "Yer imi eklendi", ar: "تمت إضافة علامة", ja: "ブックマークを追加しました", ko: "북마크 추가됨", zh: "书签已添加", hi: "बुकमार्क जोड़ा गया", th: "เพิ่มบุ๊กมาร์กแล้ว", vi: "Đã thêm dấu trang", id: "Penanda ditambahkan", ms: "Penanda buku ditambahkan", sv: "Bokmärke tillagt", da: "Bogmærke tilføjet", nb: "Bokmerke lagt til", fi: "Kirjanmerkki lisätty", el: "Σελιδοδείκτης προστέθηκε", cs: "Záložka přidána", hu: "Könyvjelző hozzáadva", ro: "Marcaj adăugat", hr: "Oznaka dodana", bg: "Отметката е добавена", sk: "Záložka pridaná", he: "סימנייה נוספה", uk: "Закладку додано", fa: "نشانک اضافه شد", bn: "বুকমার্ক যোগ হয়েছে", sw: "Alama imeongezwa", tl: "Bookmark na-idag", ur: "بُک مارک شامل ہوگیا", am: "ምልክት ተጨምሯል", ha: "An ƙara alama", yo: "Àmì ti fi kún", wo: "Markë bi dañu ko tàmbali", ru: "Закладка добавлена", sl: "Zaznamek dodan", lt: "Žymė pridėta", lv: "Grāmatzīme pievienota", et: "Järjehoidja lisatud",
  },
  "islamic.quran.bookmark_removed": {
    fr: "Marque-page retiré", en: "Bookmark removed", es: "Marcador eliminado", de: "Lesezeichen entfernt", it: "Segnalibro rimosso", pt: "Marcador removido", nl: "Bladwijzer verwijderd", pl: "Zakładka usunięta", tr: "Yer imi kaldırıldı", ar: "تمت إزالة العلامة", ja: "ブックマークを削除しました", ko: "북마크 제거됨", zh: "书签已移除", hi: "बुकमार्क हटाया गया", th: "ลบบุ๊กมาร์กแล้ว", vi: "Đã xóa dấu trang", id: "Penanda dihapus", ms: "Penanda buku dibuang", sv: "Bokmärke borttaget", da: "Bogmærke fjernet", nb: "Bokmerke fjernet", fi: "Kirjanmerkki poistettu", el: "Σελιδοδείκτης αφαιρέθηκε", cs: "Záložka odstraněna", hu: "Könyvjelző eltávolítva", ro: "Marcaj eliminat", hr: "Oznaka uklonjena", bg: "Отметката е премахната", sk: "Záložka odstránená", he: "סימנייה הוסרה", uk: "Закладку видалено", fa: "نشانک حذف شد", bn: "বুকমার্ক সরানো হয়েছে", sw: "Alama imeondolewa", tl: "Bookmark na-alis", ur: "بُک مارک ہٹا دیا گیا", am: "ምልክት ተወግዷል", ha: "An cire alama", yo: "Àmì ti yọ kúrò", wo: "Markë bi dañu ko génn", ru: "Закладка удалена", sl: "Zaznamek odstranjen", lt: "Žymė pašalinta", lv: "Grāmatzīme noņemta", et: "Järjehoidja eemaldatud",
  },
  "islamic.quran.audio_error": {
    fr: "Erreur audio", en: "Audio error", es: "Error de audio", de: "Audiofehler", it: "Errore audio", pt: "Erro de áudio", nl: "Audiofout", pl: "Błąd audio", tr: "Ses hatası", ar: "خطأ في الصوت", ja: "オーディオエラー", ko: "오디오 오류", zh: "音频错误", hi: "ऑडियो त्रुटि", th: "ข้อผิดพลาดเสียง", vi: "Lỗi âm thanh", id: "Kesalahan audio", ms: "Ralat audio", sv: "Ljudfel", da: "Lydfejl", nb: "Lydfeil", fi: "Äänivirhe", el: "Σφάλμα ήχου", cs: "Chyba zvuku", hu: "Hanghiba", ro: "Eroare audio", hr: "Audio greška", bg: "Грешка на звука", sk: "Chyba zvuku", he: "שגיאת שמע", uk: "Помилка аудіо", fa: "خطای صوتی", bn: "অডিও ত্রুটি", sw: "Hitilafu ya sauti", tl: "Error sa audio", ur: "آڈیو خرابی", am: "የድምጽ ስህተት", ha: "Kuskuren sauti", yo: "Àṣìṣe ohùn", wo: "Njumte audio", ru: "Ошибка аудио", sl: "Napaka zvoka", lt: "Garso klaida", lv: "Audio kļūda", et: "Heli viga",
  },
  "islamic.quran.audio_unavailable": {
    fr: "Audio non disponible", en: "Audio unavailable", es: "Audio no disponible", de: "Audio nicht verfügbar", it: "Audio non disponibile", pt: "Áudio indisponível", nl: "Audio niet beschikbaar", pl: "Audio niedostępne", tr: "Ses mevcut değil", ar: "الصوت غير متاح", ja: "オーディオは利用できません", ko: "오디오를 사용할 수 없습니다", zh: "音频不可用", hi: "ऑडियो उपलब्ध नहीं", th: "ไม่มีเสียง", vi: "Không có âm thanh", id: "Audio tidak tersedia", ms: "Audio tidak tersedia", sv: "Ljud inte tillgängligt", da: "Lyd ikke tilgængelig", nb: "Lyd utilgjengelig", fi: "Ääni ei ole saatavilla", el: "Ήχος μη διαθέσιμος", cs: "Zvuk není k dispozici", hu: "Hang nem elérhető", ro: "Audio indisponibil", hr: "Audio nedostupan", bg: "Звукът не е наличен", sk: "Zvuk nie je k dispozícii", he: "שמע לא זמין", uk: "Аудіо недоступне", fa: "صوت در دسترس نیست", bn: "অডিও পাওয়া যাচ্ছে না", sw: "Sauti haipatikani", tl: "Audio hindi available", ur: "آڈیو دستیاب نہیں", am: "ድምጽ አይገኝም", ha: "Sauti ba ya samuwa", yo: "Ohùn kò sí", wo: "Audio bi amul", ru: "Аудио недоступно", sl: "Zvok ni na voljo", lt: "Garsas nepasiekiamas", lv: "Audio nav pieejams", et: "Heli pole saadaval",
  },
  "islamic.duas.title": {
    fr: "Duas & Adhkar", en: "Duas & Adhkar", es: "Duas y Adhkar", de: "Duas & Adhkar", it: "Duas e Adhkar", pt: "Duas e Adhkar", nl: "Duas & Adhkar", pl: "Duas i Adhkar", tr: "Dualar ve Zikirler", ar: "الأدعية والأذكار", ja: "ドゥアーとアズカール", ko: "두아와 아즈카르", zh: "杜阿与念词", hi: "दुआएँ और अज़कार", th: "ดุอาอ์และอัซการ์", vi: "Dua và Adhkar", id: "Doa dan Dzikir", ms: "Doa dan Zikir", sv: "Duas & Adhkar", da: "Duas & Adhkar", nb: "Duas & Adhkar", fi: "Duas & Adhkar", el: "Ντουά & Αζκάρ", cs: "Duas a Adhkar", hu: "Duas és Adhkar", ro: "Duas și Adhkar", hr: "Dove i Zikrovi", bg: "Дуи и Азкар", sk: "Duas a Adhkar", he: "דועא ואזכאר", uk: "Дуа та Азкар", fa: "دعاها و اذکار", bn: "দোয়া ও আযকার", sw: "Dua na Adhkar", tl: "Duas at Adhkar", ur: "دعائیں اور اذکار", am: "ዱዓ እና አዝካር", ha: "Addu'o'i da Azkar", yo: "Àdúrà àti Àdísíkà", wo: "Du'a ak Adhkar", ru: "Дуа и Азкар", sl: "Dove in Azkar", lt: "Dua ir Azkar", lv: "Dua un Azkar", et: "Duaad ja Azkar",
  },
  "islamic.duas.subtitle": {
    fr: "Invocations quotidiennes", en: "Daily invocations", es: "Invocaciones diarias", de: "Tägliche Anrufungen", it: "Invocazioni quotidiane", pt: "Invocações diárias", nl: "Dagelijkse aanroepingen", pl: "Codzienne inwokacje", tr: "Günlük dualar", ar: "أذكار يومية", ja: "日々の祈り", ko: "일일 기도", zh: "每日祈愿", hi: "दैनिक दुआएँ", th: "ดุอาอ์ประจำวัน", vi: "Lời cầu nguyện hàng ngày", id: "Doa harian", ms: "Doa harian", sv: "Dagliga åkallanden", da: "Daglige påkaldelser", nb: "Daglige bønner", fi: "Päivittäiset rukoukset", el: "Καθημερινές επικλήσεις", cs: "Denní prosby", hu: "Napi fohászok", ro: "Invocații zilnice", hr: "Dnevne dove", bg: "Ежедневни молитви", sk: "Denné prosby", he: "תפילות יומיות", uk: "Щоденні молитви", fa: "اذکار روزانه", bn: "দৈনিক দোয়া", sw: "Dua za kila siku", tl: "Pang-araw-araw na panalangin", ur: "روزانہ کی دعائیں", am: "ዕለታዊ ዱዓዎች", ha: "Addu'o'in yau da kullum", yo: "Àdúrà ojoojúmọ́", wo: "Du'a bu bés bu", ru: "Ежедневные мольбы", sl: "Dnevne prošnje", lt: "Kasdieniai maldavimai", lv: "Ikdienas lūgšanas", et: "Igapäevased palved",
  },
  "islamic.names.title": {
    fr: "Asma ul-Husna", en: "Asma ul-Husna", es: "Asma ul-Husna", de: "Asma ul-Husna", it: "Asma ul-Husna", pt: "Asma ul-Husna", nl: "Asma ul-Husna", pl: "Asma ul-Husna", tr: "Esmâül Hüsnâ", ar: "أسماء الله الحسنى", ja: "アスマ・ウル・フスナー", ko: "아스마 울 후스나", zh: "至美之名", hi: "अस्माउल हुस्ना", th: "อัสมาอุลฮุสนา", vi: "Asma ul-Husna", id: "Asmaul Husna", ms: "Asmaul Husna", sv: "Asma ul-Husna", da: "Asma ul-Husna", nb: "Asma ul-Husna", fi: "Asma ul-Husna", el: "Ασμά ουλ-Χούσνα", cs: "Asma ul-Husna", hu: "Aszmá ul-Huszná", ro: "Asma ul-Husna", hr: "Esmaul-husna", bg: "Асма ул-Хусна", sk: "Asma ul-Husna", he: "אסמא אול-חוסנא", uk: "Асма уль-Хусна", fa: "اسماء الحسنی", bn: "আসমাউল হুসনা", sw: "Asma ul-Husna", tl: "Asma ul-Husna", ur: "اسماء الحسنیٰ", am: "አስማኡል ሑስና", ha: "Asma'ul Husna", yo: "Asma ul-Husna", wo: "Asma ul-Husna", ru: "Асма уль-Хусна", sl: "Asma ul-Husna", lt: "Asma ul-Husna", lv: "Asma ul-Husna", et: "Asma ul-Husna",
  },
  "islamic.names.subtitle": {
    fr: "Les 99 Noms d'Allah", en: "The 99 Names of Allah", es: "Los 99 Nombres de Allah", de: "Die 99 Namen Allahs", it: "I 99 Nomi di Allah", pt: "Os 99 Nomes de Allah", nl: "De 99 Namen van Allah", pl: "99 Imion Allaha", tr: "Allah'ın 99 İsmi", ar: "أسماء الله الحسنى ال٩٩", ja: "アッラーの99の名前", ko: "알라의 99가지 이름", zh: "安拉的99个尊名", hi: "अल्लाह के 99 नाम", th: "99 พระนามของอัลลอฮ์", vi: "99 Tên của Allah", id: "99 Nama Allah", ms: "99 Nama Allah", sv: "Allahs 99 Namn", da: "Allahs 99 Navne", nb: "Allahs 99 Navn", fi: "Allahin 99 Nimeä", el: "Τα 99 Ονόματα του Αλλάχ", cs: "99 Jmen Alláha", hu: "Allah 99 Neve", ro: "Cele 99 de Nume ale lui Allah", hr: "99 Allahovih Imena", bg: "99-те Имена на Аллах", sk: "99 Mien Alláha", he: "99 השמות של אללה", uk: "99 Імен Аллага", fa: "۹۹ نام خداوند", bn: "আল্লাহর ৯৯টি নাম", sw: "Majina 99 ya Allah", tl: "Ang 99 na Pangalan ng Allah", ur: "اللہ کے 99 نام", am: "የአላህ 99 ስሞች", ha: "Sunaye 99 na Allah", yo: "Orúkọ 99 ti Allahu", wo: "99 Tur yi Yàlla", ru: "99 Имён Аллаха", sl: "99 Imen Allaha", lt: "99 Alacho Vardai", lv: "99 Allāha Vārdi", et: "99 Allahi Nime",
  },
  "islamic.tasbih.title": {
    fr: "Compteur Tasbih", en: "Tasbih Counter", es: "Contador de Tasbih", de: "Tasbih-Zähler", it: "Contatore Tasbih", pt: "Contador Tasbih", nl: "Tasbih Teller", pl: "Licznik Tasbih", tr: "Tesbih Sayacı", ar: "عداد التسبيح", ja: "タスビーフカウンター", ko: "타스비흐 카운터", zh: "念珠计数器", hi: "तस्बीह काउंटर", th: "ตัวนับตัสบีห์", vi: "Bộ đếm Tasbih", id: "Penghitung Tasbih", ms: "Kaunter Tasbih", sv: "Tasbih Räknare", da: "Tasbih Tæller", nb: "Tasbih Teller", fi: "Tasbih-laskuri", el: "Μετρητής Τασμπίχ", cs: "Počítadlo Tasbíh", hu: "Tasbih Számláló", ro: "Contor Tasbih", hr: "Tespih Brojač", bg: "Тасбих Брояч", sk: "Počítadlo Tasbíh", he: "מונה תסביח", uk: "Лічильник Тасбіх", fa: "شمارنده تسبیح", bn: "তাসবীহ কাউন্টার", sw: "Kihesabu cha Tasbih", tl: "Tasbih Counter", ur: "تسبیح کاؤنٹر", am: "ተስቢሕ ቆጣሪ", ha: "Kidayar Tasbih", yo: "Iye Tasbih", wo: "Compteur Tasbih", ru: "Счётчик Тасбих", sl: "Števec Tasbih", lt: "Tasbih Skaitiklis", lv: "Tasbih Skaitītājs", et: "Tasbih Loendur",
  },
  "islamic.tasbih.add": {
    fr: "Ajouter", en: "Add", es: "Añadir", de: "Hinzufügen", it: "Aggiungi", pt: "Adicionar", nl: "Toevoegen", pl: "Dodaj", tr: "Ekle", ar: "إضافة", ja: "追加", ko: "추가", zh: "添加", hi: "जोड़ें", th: "เพิ่ม", vi: "Thêm", id: "Tambah", ms: "Tambah", sv: "Lägg till", da: "Tilføj", nb: "Legg til", fi: "Lisää", el: "Προσθήκη", cs: "Přidat", hu: "Hozzáadás", ro: "Adaugă", hr: "Dodaj", bg: "Добави", sk: "Pridať", he: "הוסף", uk: "Додати", fa: "افزودن", bn: "যোগ করুন", sw: "Ongeza", tl: "Idagdag", ur: "شامل کریں", am: "ጨምር", ha: "Ƙara", yo: "Fi kún", wo: "Yokk", ru: "Добавить", sl: "Dodaj", lt: "Pridėti", lv: "Pievienot", et: "Lisa",
  },
  "islamic.tasbih.add_dhikr": {
    fr: "Ajouter un dhikr", en: "Add a dhikr", es: "Añadir un dhikr", de: "Einen Dhikr hinzufügen", it: "Aggiungi un dhikr", pt: "Adicionar um dhikr", nl: "Een dhikr toevoegen", pl: "Dodaj dhikr", tr: "Zikir ekle", ar: "إضافة ذكر", ja: "ズィクルを追加", ko: "지크르 추가", zh: "添加念词", hi: "ज़िक्र जोड़ें", th: "เพิ่มซิกร์", vi: "Thêm dhikr", id: "Tambah dzikir", ms: "Tambah zikir", sv: "Lägg till dhikr", da: "Tilføj dhikr", nb: "Legg til dhikr", fi: "Lisää dhikr", el: "Προσθήκη dhikr", cs: "Přidat dhikr", hu: "Dhikr hozzáadása", ro: "Adaugă un dhikr", hr: "Dodaj zikr", bg: "Добави зикр", sk: "Pridať dhikr", he: "הוסף זיכר", uk: "Додати зікр", fa: "افزودن ذکر", bn: "যিকির যোগ করুন", sw: "Ongeza dhikr", tl: "Magdagdag ng dhikr", ur: "ذکر شامل کریں", am: "ዚክር ጨምር", ha: "Ƙara ambato", yo: "Fi dhikr kún", wo: "Yokk dhikr", ru: "Добавить зикр", sl: "Dodaj zikr", lt: "Pridėti dhikr", lv: "Pievienot dhikr", et: "Lisa dhikr",
  },
  "islamic.tasbih.no_sessions": {
    fr: "Aucune session enregistrée.", en: "No sessions recorded.", es: "Sin sesiones registradas.", de: "Keine Sitzungen aufgezeichnet.", it: "Nessuna sessione registrata.", pt: "Nenhuma sessão registrada.", nl: "Geen sessies geregistreerd.", pl: "Brak zarejestrowanych sesji.", tr: "Kayıtlı oturum yok.", ar: "لا توجد جلسات مسجلة.", ja: "記録されたセッションはありません。", ko: "기록된 세션이 없습니다.", zh: "没有记录的会话。", hi: "कोई सत्र दर्ज नहीं।", th: "ไม่มีเซสชันที่บันทึกไว้", vi: "Không có phiên nào được ghi.", id: "Tidak ada sesi tercatat.", ms: "Tiada sesi direkodkan.", sv: "Inga sessioner registrerade.", da: "Ingen sessioner registreret.", nb: "Ingen økter registrert.", fi: "Ei tallennettuja istuntoja.", el: "Δεν καταγράφηκαν συνεδρίες.", cs: "Žádné zaznamenané relace.", hu: "Nincs rögzített munkamenet.", ro: "Nicio sesiune înregistrată.", hr: "Nema zabilježenih sesija.", bg: "Няма записани сесии.", sk: "Žiadne zaznamenané relácie.", he: "לא נרשמו הפעלות.", uk: "Немає записаних сесій.", fa: "هیچ جلسه‌ای ثبت نشده.", bn: "কোনো সেশন রেকর্ড করা হয়নি।", sw: "Hakuna vipindi vilivyorekodiwa.", tl: "Walang naitatalang sesyon.", ur: "کوئی سیشن ریکارڈ نہیں ہوا۔", am: "ምንም ክፍለ ጊዜ አልተመዘገበም።", ha: "Babu zaman da aka rubuta.", yo: "Kò sí ìgbà tí a forúkọ.", wo: "Amul xew bu ñu binddoon.", ru: "Нет записанных сессий.", sl: "Ni zabeleženih sej.", lt: "Nėra įrašytų sesijų.", lv: "Nav ierakstītu sesiju.", et: "Salvestatud seansse pole.",
  },
  "islamic.zakat.title": {
    fr: "Calculateur de Zakat", en: "Zakat Calculator", es: "Calculadora de Zakat", de: "Zakat-Rechner", it: "Calcolatore di Zakat", pt: "Calculadora de Zakat", nl: "Zakat-calculator", pl: "Kalkulator Zakat", tr: "Zekat Hesaplayıcı", ar: "حاسبة الزكاة", ja: "ザカート計算機", ko: "자카트 계산기", zh: "天课计算器", hi: "ज़कात कैलकुलेटर", th: "เครื่องคำนวณซะกาต", vi: "Máy tính Zakat", id: "Kalkulator Zakat", ms: "Kalkulator Zakat", sv: "Zakat-kalkylator", da: "Zakat-beregner", nb: "Zakat-kalkulator", fi: "Zakat-laskuri", el: "Υπολογιστής Ζακάτ", cs: "Kalkulátor Zakát", hu: "Zakat Kalkulátor", ro: "Calculator Zakat", hr: "Kalkulator Zekat", bg: "Калкулатор за Зекят", sk: "Kalkulátor Zakát", he: "מחשבון זכאת", uk: "Калькулятор Закят", fa: "محاسبه‌گر زکات", bn: "যাকাত ক্যালকুলেটর", sw: "Kikokotoo cha Zakat", tl: "Zakat Calculator", ur: "زکوٰۃ کیلکولیٹر", am: "ዘካት ካልኩሌተር", ha: "Na'urar Lissafin Zakka", yo: "Ẹ̀rọ Ìṣírò Zakat", wo: "Calculateur Zakat", ru: "Калькулятор Закят", sl: "Kalkulator Zakat", lt: "Zakat Skaičiuoklė", lv: "Zakat Kalkulators", et: "Zakat Kalkulaator",
  },
  "islamic.zakat.subtitle": {
    fr: "Zakat al-Mal & Zakat al-Fitr", en: "Zakat al-Mal & Zakat al-Fitr", es: "Zakat al-Mal y Zakat al-Fitr", de: "Zakat al-Mal & Zakat al-Fitr", it: "Zakat al-Mal e Zakat al-Fitr", pt: "Zakat al-Mal e Zakat al-Fitr", nl: "Zakat al-Mal & Zakat al-Fitr", pl: "Zakat al-Mal i Zakat al-Fitr", tr: "Zekat-ül Mal ve Zekat-ül Fıtır", ar: "زكاة المال وزكاة الفطر", ja: "ザカート・アル・マールとフィトル", ko: "자카트 알말 & 자카트 알피트르", zh: "财产天课和开斋天课", hi: "ज़कात अल-माल और ज़कात अल-फ़ित्र", th: "ซะกาตอัลมาลและซะกาตอัลฟิตร์", vi: "Zakat al-Mal & Zakat al-Fitr", id: "Zakat Mal & Zakat Fitrah", ms: "Zakat Harta & Zakat Fitrah", sv: "Zakat al-Mal & Zakat al-Fitr", da: "Zakat al-Mal & Zakat al-Fitr", nb: "Zakat al-Mal & Zakat al-Fitr", fi: "Zakat al-Mal & Zakat al-Fitr", el: "Ζακάτ αλ-Μαλ & Ζακάτ αλ-Φιτρ", cs: "Zakát al-Mal a Zakát al-Fitr", hu: "Zakat al-Mal és Zakat al-Fitr", ro: "Zakat al-Mal și Zakat al-Fitr", hr: "Zekat al-Mal i Zekat al-Fitr", bg: "Зекят ал-Мал и Зекят ал-Фитр", sk: "Zakát al-Mal a Zakát al-Fitr", he: "זכאת אל-מאל וזכאת אל-פיטר", uk: "Закят аль-Маль та Закят аль-Фітр", fa: "زکات مال و زکات فطره", bn: "যাকাত আল-মাল ও যাকাত আল-ফিতর", sw: "Zakat al-Mal na Zakat al-Fitr", tl: "Zakat al-Mal at Zakat al-Fitr", ur: "زکوٰۃ المال اور زکوٰۃ الفطر", am: "ዘካት አል-ማል እና ዘካት አል-ፊጥር", ha: "Zakkar Dukiya da Zakkar Fitira", yo: "Zakat al-Mal àti Zakat al-Fitr", wo: "Zakat al-Mal ak Zakat al-Fitr", ru: "Закят аль-Маль и Закят аль-Фитр", sl: "Zakat al-Mal in Zakat al-Fitr", lt: "Zakat al-Mal ir Zakat al-Fitr", lv: "Zakat al-Mal un Zakat al-Fitr", et: "Zakat al-Mal ja Zakat al-Fitr",
  },
  "islamic.zakat.currency": {
    fr: "Devise", en: "Currency", es: "Moneda", de: "Währung", it: "Valuta", pt: "Moeda", nl: "Valuta", pl: "Waluta", tr: "Para birimi", ar: "العملة", ja: "通貨", ko: "통화", zh: "货币", hi: "मुद्रा", th: "สกุลเงิน", vi: "Tiền tệ", id: "Mata uang", ms: "Mata wang", sv: "Valuta", da: "Valuta", nb: "Valuta", fi: "Valuutta", el: "Νόμισμα", cs: "Měna", hu: "Pénznem", ro: "Moneda", hr: "Valuta", bg: "Валута", sk: "Mena", he: "מטבע", uk: "Валюта", fa: "ارز", bn: "মুদ্রা", sw: "Sarafu", tl: "Pera", ur: "کرنسی", am: "ገንዘብ", ha: "Kuɗi", yo: "Owó", wo: "Xaalis", ru: "Валюта", sl: "Valuta", lt: "Valiuta", lv: "Valūta", et: "Valuuta",
  },
  "islamic.zakat.calculate": {
    fr: "Calculer la Zakat", en: "Calculate Zakat", es: "Calcular el Zakat", de: "Zakat berechnen", it: "Calcola Zakat", pt: "Calcular Zakat", nl: "Zakat berekenen", pl: "Oblicz Zakat", tr: "Zekat Hesapla", ar: "احسب الزكاة", ja: "ザカートを計算", ko: "자카트 계산", zh: "计算天课", hi: "ज़कात की गणना करें", th: "คำนวณซะกาต", vi: "Tính Zakat", id: "Hitung Zakat", ms: "Kira Zakat", sv: "Beräkna Zakat", da: "Beregn Zakat", nb: "Beregn Zakat", fi: "Laske Zakat", el: "Υπολόγισε Ζακάτ", cs: "Vypočítat Zakát", hu: "Zakat kiszámítása", ro: "Calculează Zakat", hr: "Izračunaj Zekat", bg: "Изчисли Зекят", sk: "Vypočítať Zakát", he: "חשב זכאת", uk: "Обчислити Закят", fa: "محاسبه زکات", bn: "যাকাত গণনা করুন", sw: "Kokotoa Zakat", tl: "Kalkulahin ang Zakat", ur: "زکوٰۃ حساب کریں", am: "ዘካት አስላ", ha: "Ƙididdige Zakka", yo: "Ṣe Ìṣírò Zakat", wo: "Xam-xam Zakat", ru: "Рассчитать Закят", sl: "Izračunaj Zakat", lt: "Apskaičiuoti Zakat", lv: "Aprēķināt Zakat", et: "Arvuta Zakat",
  },
  "islamic.qibla.compass": {
    fr: "Boussole Qibla", en: "Qibla Compass", es: "Brújula Qibla", de: "Qibla-Kompass", it: "Bussola Qibla", pt: "Bússola Qibla", nl: "Qibla Kompas", pl: "Kompas Qibla", tr: "Kıble Pusulası", ar: "بوصلة القبلة", ja: "キブラコンパス", ko: "키블라 나침반", zh: "朝向指南针", hi: "क़िबला कम्पास", th: "เข็มทิศกิบลัต", vi: "La bàn Qibla", id: "Kompas Kiblat", ms: "Kompas Kiblat", sv: "Qibla Kompass", da: "Qibla Kompas", nb: "Qibla Kompass", fi: "Qibla-kompassi", el: "Πυξίδα Κιβλά", cs: "Kompas Qibla", hu: "Qibla Iránytű", ro: "Busolă Qibla", hr: "Kibla Kompas", bg: "Компас за Кибла", sk: "Kompas Qibla", he: "מצפן קיבלה", uk: "Компас Кібла", fa: "قطب‌نمای قبله", bn: "কিবলা কম্পাস", sw: "Dira ya Qibla", tl: "Qibla Compass", ur: "قبلہ کمپاس", am: "ቂብላ ኮምፓስ", ha: "Kamfas na Alqibla", yo: "Kọ́mpásì Qibla", wo: "Boussole Qibla", ru: "Компас Киблы", sl: "Kompas Kibla", lt: "Kiblos Kompasas", lv: "Kiblas Kompass", et: "Qibla Kompass",
  },
  "islamic.qibla.direction": {
    fr: "Direction de la Mecque (Kaaba)", en: "Direction of Mecca (Kaaba)", es: "Dirección de La Meca (Kaaba)", de: "Richtung Mekka (Kaaba)", it: "Direzione della Mecca (Kaaba)", pt: "Direção de Meca (Kaaba)", nl: "Richting Mekka (Kaaba)", pl: "Kierunek Mekki (Kaaba)", tr: "Mekke (Kabe) Yönü", ar: "اتجاه مكة (الكعبة)", ja: "メッカ（カアバ）の方角", ko: "메카(카바) 방향", zh: "麦加（天房）方向", hi: "मक्का (काबा) की दिशा", th: "ทิศทางมักกะฮ์ (กะอ์บะฮ์)", vi: "Hướng Mecca (Kaaba)", id: "Arah Mekkah (Kabah)", ms: "Arah Mekah (Kaabah)", sv: "Riktning Mecka (Kaaba)", da: "Retning Mekka (Kaaba)", nb: "Retning Mekka (Kaaba)", fi: "Mekan (Kaaba) suunta", el: "Κατεύθυνση Μέκκα (Κάαμπα)", cs: "Směr Mekky (Kaaba)", hu: "Mekka (Kába) iránya", ro: "Direcția Mecca (Kaaba)", hr: "Smjer Meke (Kabe)", bg: "Посока Мека (Кааба)", sk: "Smer Mekky (Kaaba)", he: "כיוון מכה (כעבה)", uk: "Напрямок Мекки (Кааба)", fa: "جهت مکه (کعبه)", bn: "মক্কার (কাবা) দিক", sw: "Mwelekeo wa Makka (Kaaba)", tl: "Direksyon ng Mecca (Kaaba)", ur: "مکہ (کعبہ) کی سمت", am: "ወደ መካ (ካዕባ) አቅጣጫ", ha: "Alkiblar Makka (Ka'aba)", yo: "Ìtọ́sọ́nà Mekka (Kaaba)", wo: "Yoon Mekka (Kaaba)", ru: "Направление Мекки (Кааба)", sl: "Smer Meke (Kaba)", lt: "Mekos (Kaabos) kryptis", lv: "Mekas (Kaabas) virziens", et: "Meka (Kaaba) suund",
  },
  "islamic.qibla.geo_unavailable": {
    fr: "Géolocalisation non disponible.", en: "Geolocation unavailable.", es: "Geolocalización no disponible.", de: "Geolokalisierung nicht verfügbar.", it: "Geolocalizzazione non disponibile.", pt: "Geolocalização indisponível.", nl: "Geolocatie niet beschikbaar.", pl: "Geolokalizacja niedostępna.", tr: "Konum bulunamıyor.", ar: "الموقع الجغرافي غير متاح.", ja: "位置情報が利用できません。", ko: "위치 정보를 사용할 수 없습니다.", zh: "地理定位不可用。", hi: "जियोलोकेशन उपलब्ध नहीं।", th: "ไม่สามารถระบุตำแหน่งได้", vi: "Vị trí không khả dụng.", id: "Geolokasi tidak tersedia.", ms: "Geolokasi tidak tersedia.", sv: "Geolokalisering otillgänglig.", da: "Geolokalisering utilgængelig.", nb: "Geolokalisering utilgjengelig.", fi: "Paikannus ei ole käytettävissä.", el: "Γεωτοποθεσία μη διαθέσιμη.", cs: "Geolokace není dostupná.", hu: "Helymeghatározás nem elérhető.", ro: "Geolocalizare indisponibilă.", hr: "Geolokacija nedostupna.", bg: "Геолокацията не е налична.", sk: "Geolokácia nie je k dispozícii.", he: "מיקום גיאוגרפי אינו זמין.", uk: "Геолокація недоступна.", fa: "موقعیت جغرافیایی در دسترس نیست.", bn: "জিওলোকেশন পাওয়া যাচ্ছে না।", sw: "Eneo halipatikani.", tl: "Hindi available ang geolocation.", ur: "جیو لوکیشن دستیاب نہیں۔", am: "ጂኦሎኬሽን አይገኝም።", ha: "Ba a sami wurin ba.", yo: "Ipo agbègbè kò sí.", wo: "Géolocalisation bi amul.", ru: "Геолокация недоступна.", sl: "Geolokacija ni na voljo.", lt: "Geolokacija neprieinama.", lv: "Ģeolokācija nav pieejama.", et: "Asukoht pole saadaval.",
  },
  "islamic.qibla.enable_geo": {
    fr: "Activez la géolocalisation pour voir la Qibla.", en: "Enable geolocation to see the Qibla.", es: "Active la geolocalización para ver la Qibla.", de: "Aktivieren Sie die Geolokalisierung, um die Qibla zu sehen.", it: "Attiva la geolocalizzazione per vedere la Qibla.", pt: "Ative a geolocalização para ver a Qibla.", nl: "Schakel geolocatie in om de Qibla te zien.", pl: "Włącz geolokalizację, aby zobaczyć Qiblę.", tr: "Kıbleyi görmek için konumu açın.", ar: "فعّل الموقع الجغرافي لرؤية القبلة.", ja: "キブラを見るには位置情報を有効にしてください。", ko: "키블라를 보려면 위치를 활성화하세요.", zh: "启用地理定位以查看朝向。", hi: "क़िबला देखने के लिए जियोलोकेशन सक्रिय करें।", th: "เปิดการระบุตำแหน่งเพื่อดูกิบลัต", vi: "Bật vị trí để xem Qibla.", id: "Aktifkan lokasi untuk melihat Kiblat.", ms: "Aktifkan lokasi untuk melihat Kiblat.", sv: "Aktivera geolokalisering för att se Qibla.", da: "Aktivér geolokalisering for at se Qibla.", nb: "Aktiver geolokalisering for å se Qibla.", fi: "Ota paikannus käyttöön nähdäksesi Qibla.", el: "Ενεργοποιήστε τη γεωτοποθεσία για να δείτε την Κιβλά.", cs: "Zapněte geolokaci pro zobrazení Qibly.", hu: "Engedélyezze a helymeghatározást a Qibla megtekintéséhez.", ro: "Activați geolocalizarea pentru a vedea Qibla.", hr: "Omogućite geolokaciju za prikaz Kible.", bg: "Включете геолокацията, за да видите Кибла.", sk: "Zapnite geolokáciu na zobrazenie Qibly.", he: "הפעל מיקום כדי לראות את הקיבלה.", uk: "Увімкніть геолокацію, щоб побачити Кіблу.", fa: "برای مشاهده قبله مکان‌یابی را فعال کنید.", bn: "কিবলা দেখতে জিওলোকেশন সক্রিয় করুন।", sw: "Washa eneo kuona Qibla.", tl: "I-enable ang lokasyon para makita ang Qibla.", ur: "قبلہ دیکھنے کے لیے لوکیشن فعال کریں۔", am: "ቂብላን ለማየት ጂኦሎኬሽን ያንቁ።", ha: "Kunna wuri don ganin Alqibla.", yo: "Mú ipò ṣiṣẹ́ láti rí Qibla.", wo: "Def géolocalisation ngir gis Qibla.", ru: "Включите геолокацию, чтобы увидеть Киблу.", sl: "Vklopite geolokacijo za prikaz Kible.", lt: "Įjunkite geolokaciją, kad matytumėte Kiblą.", lv: "Ieslēdziet ģeolokāciju, lai redzētu Kiblu.", et: "Lülitage asukoht sisse, et näha Qiblat.",
  },
  "islamic.qibla.detecting": {
    fr: "Détection de votre position...", en: "Detecting your position...", es: "Detectando su posición...", de: "Position wird ermittelt...", it: "Rilevamento della posizione...", pt: "Detectando sua posição...", nl: "Positie detecteren...", pl: "Wykrywanie pozycji...", tr: "Konumunuz belirleniyor...", ar: "جارٍ تحديد موقعك...", ja: "位置を検出中...", ko: "위치 감지 중...", zh: "正在检测您的位置...", hi: "आपकी स्थिति पता लगाई जा रही है...", th: "กำลังตรวจจับตำแหน่งของคุณ...", vi: "Đang xác định vị trí của bạn...", id: "Mendeteksi posisi Anda...", ms: "Mengesan kedudukan anda...", sv: "Detekterar din position...", da: "Registrerer din position...", nb: "Oppdager posisjonen din...", fi: "Paikannusta haetaan...", el: "Εντοπισμός θέσης...", cs: "Zjišťování vaší polohy...", hu: "Pozíció meghatározása...", ro: "Se detectează poziția dvs....", hr: "Otkrivanje vaše pozicije...", bg: "Определяне на позицията...", sk: "Zisťovanie vašej polohy...", he: "...מאתר את מיקומך", uk: "Визначення вашої позиції...", fa: "...در حال شناسایی موقعیت شما", bn: "আপনার অবস্থান সনাক্ত করা হচ্ছে...", sw: "Inatafuta nafasi yako...", tl: "Tinutukoy ang iyong posisyon...", ur: "...آپ کی پوزیشن کا پتا لگایا جا رہا ہے", am: "ቦታዎን በመለየት ላይ...", ha: "Ana gano matsayinku...", yo: "Wíwá ipò rẹ...", wo: "Yàgg nañu séet sa bopp...", ru: "Определение вашей позиции...", sl: "Zaznavanje vaše lokacije...", lt: "Nustatoma jūsų padėtis...", lv: "Nosakām jūsu atrašanās vietu...", et: "Teie asukoha tuvastamine...",
  },
  "islamic.qibla.angle": {
    fr: "Angle Qibla", en: "Qibla Angle", es: "Ángulo Qibla", de: "Qibla-Winkel", it: "Angolo Qibla", pt: "Ângulo Qibla", nl: "Qibla Hoek", pl: "Kąt Qibla", tr: "Kıble Açısı", ar: "زاوية القبلة", ja: "キブラ角度", ko: "키블라 각도", zh: "朝向角度", hi: "क़िबला कोण", th: "มุมกิบลัต", vi: "Góc Qibla", id: "Sudut Kiblat", ms: "Sudut Kiblat", sv: "Qibla Vinkel", da: "Qibla Vinkel", nb: "Qibla Vinkel", fi: "Qibla-kulma", el: "Γωνία Κιβλά", cs: "Úhel Qibla", hu: "Qibla Szög", ro: "Unghi Qibla", hr: "Kut Kible", bg: "Ъгъл на Кибла", sk: "Uhol Qibla", he: "זווית קיבלה", uk: "Кут Кібли", fa: "زاویه قبله", bn: "কিবলা কোণ", sw: "Pembe ya Qibla", tl: "Anggulo ng Qibla", ur: "قبلہ زاویہ", am: "ቂብላ ማዕዘን", ha: "Kusurwar Alqibla", yo: "Ìgun Qibla", wo: "Angle Qibla", ru: "Угол Киблы", sl: "Kot Kible", lt: "Kiblos Kampas", lv: "Kiblas Leņķis", et: "Qibla Nurk",
  },
  "islamic.qibla.distance": {
    fr: "Distance", en: "Distance", es: "Distancia", de: "Entfernung", it: "Distanza", pt: "Distância", nl: "Afstand", pl: "Odległość", tr: "Mesafe", ar: "المسافة", ja: "距離", ko: "거리", zh: "距离", hi: "दूरी", th: "ระยะทาง", vi: "Khoảng cách", id: "Jarak", ms: "Jarak", sv: "Avstånd", da: "Afstand", nb: "Avstand", fi: "Etäisyys", el: "Απόσταση", cs: "Vzdálenost", hu: "Távolság", ro: "Distanță", hr: "Udaljenost", bg: "Разстояние", sk: "Vzdialenosť", he: "מרחק", uk: "Відстань", fa: "فاصله", bn: "দূরত্ব", sw: "Umbali", tl: "Distansya", ur: "فاصلہ", am: "ርቀት", ha: "Nisa", yo: "Ọ̀nà", wo: "Ànd", ru: "Расстояние", sl: "Razdalja", lt: "Atstumas", lv: "Attālums", et: "Kaugus",
  },
  "islamic.ramadan.suhoor_iftar": {
    fr: "Horaires Suhoor & Iftar", en: "Suhoor & Iftar Times", es: "Horarios de Suhoor e Iftar", de: "Suhoor- & Iftar-Zeiten", it: "Orari Suhoor & Iftar", pt: "Horários de Suhoor e Iftar", nl: "Suhoor & Iftar Tijden", pl: "Godziny Suhoor i Iftar", tr: "Sahur & İftar Vakitleri", ar: "أوقات السحور والإفطار", ja: "サフールとイフタールの時間", ko: "수후르 & 이프타르 시간", zh: "封斋与开斋时间", hi: "सहरी और इफ्तार के समय", th: "เวลาซะฮูรและอิฟตาร", vi: "Giờ Suhoor & Iftar", id: "Waktu Sahur & Buka Puasa", ms: "Waktu Sahur & Berbuka", sv: "Suhoor- & Iftartider", da: "Suhoor- & Iftartider", nb: "Suhoor- & Iftartider", fi: "Suhoor- ja Iftar-ajat", el: "Ώρες Σουχούρ & Ιφτάρ", cs: "Časy Suhoor a Iftar", hu: "Szuhúr és Iftar időpontok", ro: "Orele Suhoor și Iftar", hr: "Suhur i Iftar Vremena", bg: "Часове за Сухур и Ифтар", sk: "Časy Suhoor a Iftar", he: "זמני סוחור ואיפטאר", uk: "Часи Сухуру та Іфтару", fa: "اوقات سحر و افطار", bn: "সাহরি ও ইফতারের সময়", sw: "Nyakati za Daku na Futari", tl: "Oras ng Suhoor at Iftar", ur: "سحری اور افطار کے اوقات", am: "የሰሑር እና ኢፍጣር ሰዓቶች", ha: "Lokacin Sahur da Buda-baki", yo: "Àkókò Suhoor àti Iftar", wo: "Waxtu Suhoor ak Iftar", ru: "Время Сухура и Ифтара", sl: "Časi Suhura in Iftara", lt: "Suhoor ir Iftar laikai", lv: "Suhoor un Iftar laiki", et: "Suhoor & Iftar ajad",
  },
  "islamic.ramadan.not_active": {
    fr: "Le Ramadan n'est pas en cours", en: "Ramadan is not currently active", es: "El Ramadán no está en curso", de: "Der Ramadan ist derzeit nicht aktiv", it: "Il Ramadan non è attualmente in corso", pt: "O Ramadã não está ativo atualmente", nl: "Ramadan is momenteel niet actief", pl: "Ramadan nie jest aktywny", tr: "Ramazan şu anda aktif değil", ar: "رمضان ليس جاريًا حاليًا", ja: "現在ラマダンではありません", ko: "현재 라마단이 아닙니다", zh: "斋月目前不在进行中", hi: "रमज़ान अभी जारी नहीं है", th: "ขณะนี้ไม่ใช่เดือนรอมฎอน", vi: "Ramadan hiện không diễn ra", id: "Ramadan saat ini tidak aktif", ms: "Ramadan tidak aktif sekarang", sv: "Ramadan pågår inte för närvarande", da: "Ramadan er ikke aktiv i øjeblikket", nb: "Ramadan er ikke aktiv nå", fi: "Ramadan ei ole käynnissä", el: "Το Ραμαζάνι δεν είναι ενεργό αυτή τη στιγμή", cs: "Ramadán momentálně neprobíhá", hu: "A Ramadán jelenleg nem aktív", ro: "Ramadanul nu este activ în prezent", hr: "Ramazan trenutno nije aktivan", bg: "Рамаданът в момента не е активен", sk: "Ramadán momentálne neprebieha", he: "רמדאן אינו פעיל כרגע", uk: "Рамадан наразі не активний", fa: "رمضان در حال حاضر فعال نیست", bn: "রমজান এখন চলছে না", sw: "Ramadhani haipo sasa hivi", tl: "Hindi kasalukuyang aktibo ang Ramadan", ur: "رمضان ابھی جاری نہیں ہے", am: "ረመዳን አሁን አይሄድም", ha: "Ramadan bai fara ba yanzu", yo: "Ramadan kò ti bẹ̀rẹ̀", wo: "Ramadan dafa dul jëm", ru: "Рамадан сейчас не идёт", sl: "Ramadan trenutno ni aktiven", lt: "Ramadanas šiuo metu nevyksta", lv: "Ramadāns pašlaik nav aktīvs", et: "Ramadan ei ole praegu aktiivne",
  },
  "islamic.hadith.title": {
    fr: "Hadiths", en: "Hadiths", es: "Hadices", de: "Hadithe", it: "Hadith", pt: "Hadiths", nl: "Hadiths", pl: "Hadisy", tr: "Hadisler", ar: "الأحاديث", ja: "ハディース", ko: "하디스", zh: "圣训集", hi: "हदीसें", th: "หะดีษ", vi: "Hadith", id: "Hadits", ms: "Hadis", sv: "Hadither", da: "Hadither", nb: "Hadither", fi: "Hadithit", el: "Χαντίθ", cs: "Hadísy", hu: "Hadíszok", ro: "Hadith-uri", hr: "Hadisi", bg: "Хадиси", sk: "Hadísy", he: "חדיתים", uk: "Хадіси", fa: "احادیث", bn: "হাদিসসমূহ", sw: "Hadithi", tl: "Mga Hadith", ur: "احادیث", am: "ሐዲሶች", ha: "Hadisai", yo: "Àwọn Hadith", wo: "Hadis yi", ru: "Хадисы", sl: "Hadisi", lt: "Hadisai", lv: "Hadisi", et: "Hadiithid",
  },
  "islamic.hadith.subtitle": {
    fr: "Les 6 recueils authentiques (Kutub al-Sittah)", en: "The 6 authentic collections (Kutub al-Sittah)", es: "Las 6 colecciones auténticas (Kutub al-Sittah)", de: "Die 6 authentischen Sammlungen (Kutub al-Sittah)", it: "Le 6 collezioni autentiche (Kutub al-Sittah)", pt: "As 6 coleções autênticas (Kutub al-Sittah)", nl: "De 6 authentieke verzamelingen (Kutub al-Sittah)", pl: "6 autentycznych zbiorów (Kutub al-Sittah)", tr: "6 sahih koleksiyon (Kütüb-i Sitte)", ar: "الكتب الستة الصحيحة", ja: "6つの真正なコレクション（クトゥブ・アッシッタ）", ko: "6개의 정본 모음집 (쿠투브 앗싯타)", zh: "六大圣训集", hi: "6 प्रामाणिक संग्रह (कुतुब अस-सित्तह)", th: "6 บันทึกที่แท้จริง (กุตุบ อัสสิตตะฮ์)", vi: "6 bộ sưu tập chính thống (Kutub al-Sittah)", id: "6 koleksi autentik (Kutub al-Sittah)", ms: "6 koleksi sahih (Kutub al-Sittah)", sv: "De 6 autentiska samlingarna (Kutub al-Sittah)", da: "De 6 autentiske samlinger (Kutub al-Sittah)", nb: "De 6 autentiske samlingene (Kutub al-Sittah)", fi: "6 autenttista kokoelmaa (Kutub al-Sittah)", el: "Οι 6 αυθεντικές συλλογές (Κουτούμπ αλ-Σίττα)", cs: "6 autentických sbírek (Kutub al-Sittah)", hu: "A 6 hiteles gyűjtemény (Kutub asz-Szitta)", ro: "Cele 6 colecții autentice (Kutub al-Sittah)", hr: "6 autentičnih zbirki (Kutub al-Sittah)", bg: "6-те автентични сбирки (Кутуб ал-Ситта)", sk: "6 autentických zbierok (Kutub al-Sittah)", he: "6 האוספים האותנטיים (כותב אל-סיטה)", uk: "6 достовірних збірок (Кутуб ас-Сітта)", fa: "۶ مجموعه معتبر (کتب سته)", bn: "৬টি প্রামাণ্য সংকলন (কুতুব আস-সিত্তাহ)", sw: "Makusanyo 6 ya kweli (Kutub al-Sittah)", tl: "6 na autentikong koleksyon (Kutub al-Sittah)", ur: "6 مستند مجموعے (کتب ستہ)", am: "6 ትክክለኛ ስብስቦች (ኩቱብ አል-ሲታ)", ha: "Littattafai 6 masu inganci (Kutub al-Sittah)", yo: "Àkójọpọ̀ 6 tó jẹ́ mímọ́ (Kutub al-Sittah)", wo: "6 Jëriñ yi dëgg (Kutub al-Sittah)", ru: "6 достоверных сборников (Кутуб ас-Ситта)", sl: "6 avtentičnih zbirk (Kutub al-Sittah)", lt: "6 autentiškos kolekcijos (Kutub al-Sittah)", lv: "6 autentiskas kolekcijas (Kutub al-Sittah)", et: "6 autentset kogu (Kutub al-Sittah)",
  },
  "islamic.hadith.copied": {
    fr: "Hadith copié", en: "Hadith copied", es: "Hadiz copiado", de: "Hadith kopiert", it: "Hadith copiato", pt: "Hadith copiado", nl: "Hadith gekopieerd", pl: "Hadis skopiowany", tr: "Hadis kopyalandı", ar: "تم نسخ الحديث", ja: "ハディースをコピーしました", ko: "하디스 복사됨", zh: "圣训已复制", hi: "हदीस कॉपी की गई", th: "คัดลอกหะดีษแล้ว", vi: "Đã sao chép hadith", id: "Hadits disalin", ms: "Hadis disalin", sv: "Hadith kopierad", da: "Hadith kopieret", nb: "Hadith kopiert", fi: "Hadith kopioitu", el: "Χαντίθ αντιγράφηκε", cs: "Hadís zkopírován", hu: "Hadísz másolva", ro: "Hadith copiat", hr: "Hadis kopiran", bg: "Хадисът е копиран", sk: "Hadís skopírovaný", he: "חדית' הועתק", uk: "Хадіс скопійовано", fa: "حدیث کپی شد", bn: "হাদিস কপি হয়েছে", sw: "Hadithi imenakiliwa", tl: "Hadith na-kopya", ur: "حدیث کاپی ہوگئی", am: "ሐዲስ ተቀድቷል", ha: "An kwafa hadisi", yo: "Ti ṣe ẹ̀da hadith", wo: "Koppi nañu hadis bi", ru: "Хадис скопирован", sl: "Hadis kopiran", lt: "Hadisas nukopijuotas", lv: "Hadiss nokopēts", et: "Hadiith kopeeritud",
  },
  "islamic.hadith.collections": {
    fr: "Collections", en: "Collections", es: "Colecciones", de: "Sammlungen", it: "Collezioni", pt: "Coleções", nl: "Verzamelingen", pl: "Kolekcje", tr: "Koleksiyonlar", ar: "المجموعات", ja: "コレクション", ko: "컬렉션", zh: "集合", hi: "संग्रह", th: "คอลเลกชัน", vi: "Bộ sưu tập", id: "Koleksi", ms: "Koleksi", sv: "Samlingar", da: "Samlinger", nb: "Samlinger", fi: "Kokoelmat", el: "Συλλογές", cs: "Sbírky", hu: "Gyűjtemények", ro: "Colecții", hr: "Zbirke", bg: "Сбирки", sk: "Zbierky", he: "אוספים", uk: "Збірки", fa: "مجموعه‌ها", bn: "সংকলন", sw: "Makusanyo", tl: "Mga Koleksyon", ur: "مجموعے", am: "ስብስቦች", ha: "Tarin", yo: "Àkójọpọ̀", wo: "Jëriñ", ru: "Сборники", sl: "Zbirke", lt: "Kolekcijos", lv: "Kolekcijas", et: "Kogud",
  },
  "islamic.ramadan.calendar_title": {
    fr: "Calendrier complet du Ramadan", en: "Full Ramadan Calendar", es: "Calendario completo del Ramadán", de: "Vollständiger Ramadan-Kalender", it: "Calendario completo del Ramadan", pt: "Calendário completo do Ramadã", nl: "Volledig Ramadan Kalender", pl: "Pełny kalendarz Ramadanu", tr: "Tam Ramazan Takvimi", ar: "تقويم رمضان الكامل", ja: "ラマダン全日程", ko: "전체 라마단 달력", zh: "完整的斋月日历", hi: "पूरा रमज़ान कैलेंडर", th: "ปฏิทินรอมฎอนเต็ม", vi: "Lịch Ramadan đầy đủ", id: "Kalender Ramadan Lengkap", ms: "Kalendar Ramadan Penuh", sv: "Fullständig Ramadan-kalender", da: "Fuld Ramadan-kalender", nb: "Fullstendig Ramadan-kalender", fi: "Täydellinen Ramadan-kalenteri", el: "Πλήρες Ημερολόγιο Ραμαζανιού", cs: "Kompletní kalendář Ramadánu", hu: "Teljes Ramadán naptár", ro: "Calendar complet Ramadan", hr: "Potpuni kalendar Ramazana", bg: "Пълен календар на Рамадан", sk: "Kompletný kalendár Ramadánu", he: "לוח שנה מלא של רמדאן", uk: "Повний календар Рамадану", fa: "تقویم کامل رمضان", bn: "সম্পূর্ণ রমজান ক্যালেন্ডার", sw: "Kalenda kamili ya Ramadhani", tl: "Kumpletong Kalendaryo ng Ramadan", ur: "مکمل رمضان کیلنڈر", am: "ሙሉ ረመዳን ቀን መቁጠሪያ", ha: "Cikakken Kalandar na Ramadan", yo: "Kàlẹ́ndà Ramadan Ní Kíkún", wo: "Kalàndiriye Ramadan bi mat", ru: "Полный календарь Рамадана", sl: "Celoten koledar Ramadana", lt: "Pilnas Ramadano kalendorius", lv: "Pilnais Ramadāna kalendārs", et: "Täielik Ramadani kalender",
  },
  "islamic.ramadan.day": {
    fr: "Jour", en: "Day", es: "Día", de: "Tag", it: "Giorno", pt: "Dia", nl: "Dag", pl: "Dzień", tr: "Gün", ar: "يوم", ja: "日", ko: "일", zh: "天", hi: "दिन", th: "วัน", vi: "Ngày", id: "Hari", ms: "Hari", sv: "Dag", da: "Dag", nb: "Dag", fi: "Päivä", el: "Ημέρα", cs: "Den", hu: "Nap", ro: "Zi", hr: "Dan", bg: "Ден", sk: "Deň", he: "יום", uk: "День", fa: "روز", bn: "দিন", sw: "Siku", tl: "Araw", ur: "دن", am: "ቀን", ha: "Rana", yo: "Ọjọ́", wo: "Fan", ru: "День", sl: "Dan", lt: "Diena", lv: "Diena", et: "Päev",
  },
  "islamic.ramadan.date": {
    fr: "Date", en: "Date", es: "Fecha", de: "Datum", it: "Data", pt: "Data", nl: "Datum", pl: "Data", tr: "Tarih", ar: "التاريخ", ja: "日付", ko: "날짜", zh: "日期", hi: "तारीख", th: "วันที่", vi: "Ngày", id: "Tanggal", ms: "Tarikh", sv: "Datum", da: "Dato", nb: "Dato", fi: "Päivämäärä", el: "Ημερομηνία", cs: "Datum", hu: "Dátum", ro: "Dată", hr: "Datum", bg: "Дата", sk: "Dátum", he: "תאריך", uk: "Дата", fa: "تاریخ", bn: "তারিখ", sw: "Tarehe", tl: "Petsa", ur: "تاریخ", am: "ቀን", ha: "Kwanan", yo: "Ọjọ́", wo: "Bés", ru: "Дата", sl: "Datum", lt: "Data", lv: "Datums", et: "Kuupäev",
  },
  "islamic.ramadan.fast": {
    fr: "Jeûne", en: "Fast", es: "Ayuno", de: "Fasten", it: "Digiuno", pt: "Jejum", nl: "Vasten", pl: "Post", tr: "Oruç", ar: "صيام", ja: "断食", ko: "단식", zh: "斋戒", hi: "रोज़ा", th: "ถือศีลอด", vi: "Nhịn ăn", id: "Puasa", ms: "Puasa", sv: "Fasta", da: "Faste", nb: "Faste", fi: "Paasto", el: "Νηστεία", cs: "Půst", hu: "Böjt", ro: "Post", hr: "Post", bg: "Пост", sk: "Pôst", he: "צום", uk: "Піст", fa: "روزه", bn: "রোজা", sw: "Saumu", tl: "Pag-aayuno", ur: "روزہ", am: "ጾም", ha: "Azumi", yo: "Àwẹ̀", wo: "Ñaari", ru: "Пост", sl: "Post", lt: "Pasninkas", lv: "Gavēnis", et: "Paast",
  },
  "islamic.ramadan.fasted": {
    fr: "Jeûné", en: "Fasted", es: "Ayunado", de: "Gefastet", it: "Digiunato", pt: "Jejuado", nl: "Gevast", pl: "Poszczono", tr: "Tutuldu", ar: "تم الصيام", ja: "断食済み", ko: "단식 완료", zh: "已斋戒", hi: "रोज़ा रखा", th: "ถือศีลอดแล้ว", vi: "Đã nhịn ăn", id: "Berpuasa", ms: "Berpuasa", sv: "Fastat", da: "Fastet", nb: "Fastet", fi: "Paastottu", el: "Νήστεψε", cs: "Postil", hu: "Böjtölt", ro: "Postit", hr: "Postio", bg: "Постил", sk: "Postil", he: "צם", uk: "Постив", fa: "روزه گرفته", bn: "রোজা রেখেছে", sw: "Amefunga", tl: "Nag-ayuno", ur: "روزہ رکھا", am: "ጾመ", ha: "Ya yi azumi", yo: "Ó gbàwẹ̀", wo: "Ñaari nañu", ru: "Постился", sl: "Postil", lt: "Pasninkavo", lv: "Gavēja", et: "Paastus",
  },
  "islamic.ramadan.missed": {
    fr: "Manqué", en: "Missed", es: "Faltó", de: "Verpasst", it: "Mancato", pt: "Perdido", nl: "Gemist", pl: "Opuszczony", tr: "Kaçırıldı", ar: "فائت", ja: "欠席", ko: "놓침", zh: "错过", hi: "छूट गया", th: "พลาด", vi: "Bỏ lỡ", id: "Terlewat", ms: "Tertinggal", sv: "Missat", da: "Misset", nb: "Savnet", fi: "Ohitettu", el: "Χαμένη", cs: "Vynechaný", hu: "Kihagyott", ro: "Ratat", hr: "Propušteno", bg: "Пропуснат", sk: "Vynechaný", he: "פוספס", uk: "Пропущено", fa: "از دست رفته", bn: "মিস হয়েছে", sw: "Imekosa", tl: "Na-miss", ur: "چھوٹ گیا", am: "ጠፍቷል", ha: "An rasa", yo: "Padànù", wo: "Dañu ko fay", ru: "Пропущено", sl: "Zamujeno", lt: "Praleistas", lv: "Nokavēts", et: "Puudus",
  },
  "islamic.ramadan.makeup": {
    fr: "Rattrapé", en: "Made up", es: "Recuperado", de: "Nachgeholt", it: "Recuperato", pt: "Compensado", nl: "Ingehaald", pl: "Odrobiony", tr: "Kaza edildi", ar: "تم القضاء", ja: "取り戻し", ko: "보충", zh: "补回", hi: "क़ज़ा किया", th: "ถือทดแทน", vi: "Bù lại", id: "Diqadha", ms: "Diqadha", sv: "Ikapptat", da: "Indhentet", nb: "Tatt igjen", fi: "Korvattu", el: "Αναπληρώθηκε", cs: "Nahrazeno", hu: "Pótolva", ro: "Recuperat", hr: "Nadoknađeno", bg: "Навакъсан", sk: "Nahradený", he: "הושלם", uk: "Відпрацьовано", fa: "قضا شده", bn: "কাজা করা হয়েছে", sw: "Imerudishwa", tl: "Na-bawi", ur: "قضا کیا", am: "ተካክሏል", ha: "An rama", yo: "Ti ṣe àtúnṣe", wo: "Dañu ko jot", ru: "Восполнено", sl: "Nadoknajeno", lt: "Atlikta", lv: "Atgūts", et: "Järele tehtud",
  },
  "islamic.export_csv": {
    fr: "Exporter CSV", en: "Export CSV", es: "Exportar CSV", de: "CSV exportieren", it: "Esporta CSV", pt: "Exportar CSV", nl: "CSV exporteren", pl: "Eksportuj CSV", tr: "CSV Dışa Aktar", ar: "تصدير CSV", ja: "CSVエクスポート", ko: "CSV 내보내기", zh: "导出CSV", hi: "CSV निर्यात करें", th: "ส่งออก CSV", vi: "Xuất CSV", id: "Ekspor CSV", ms: "Eksport CSV", sv: "Exportera CSV", da: "Eksporter CSV", nb: "Eksporter CSV", fi: "Vie CSV", el: "Εξαγωγή CSV", cs: "Exportovat CSV", hu: "CSV exportálása", ro: "Exportă CSV", hr: "Izvezi CSV", bg: "Експортирай CSV", sk: "Exportovať CSV", he: "ייצוא CSV", uk: "Експортувати CSV", fa: "خروجی CSV", bn: "CSV রপ্তানি", sw: "Hamisha CSV", tl: "I-export CSV", ur: "CSV ایکسپورٹ", am: "CSV ላክ", ha: "Fitar CSV", yo: "Gbe CSV jáde", wo: "Export CSV", ru: "Экспорт CSV", sl: "Izvozi CSV", lt: "Eksportuoti CSV", lv: "Eksportēt CSV", et: "Ekspordi CSV",
  },
  "islamic.list": {
    fr: "Liste", en: "List", es: "Lista", de: "Liste", it: "Elenco", pt: "Lista", nl: "Lijst", pl: "Lista", tr: "Liste", ar: "قائمة", ja: "リスト", ko: "목록", zh: "列表", hi: "सूची", th: "รายการ", vi: "Danh sách", id: "Daftar", ms: "Senarai", sv: "Lista", da: "Liste", nb: "Liste", fi: "Luettelo", el: "Λίστα", cs: "Seznam", hu: "Lista", ro: "Listă", hr: "Popis", bg: "Списък", sk: "Zoznam", he: "רשימה", uk: "Список", fa: "فهرست", bn: "তালিকা", sw: "Orodha", tl: "Listahan", ur: "فہرست", am: "ዝርዝር", ha: "Jerin", yo: "Àtòjọ", wo: "Lëst", ru: "Список", sl: "Seznam", lt: "Sąrašas", lv: "Saraksts", et: "Nimekiri",
  },
  "islamic.grid": {
    fr: "Grille", en: "Grid", es: "Cuadrícula", de: "Raster", it: "Griglia", pt: "Grade", nl: "Raster", pl: "Siatka", tr: "Izgara", ar: "شبكة", ja: "グリッド", ko: "그리드", zh: "网格", hi: "ग्रिड", th: "กริด", vi: "Lưới", id: "Grid", ms: "Grid", sv: "Rutnät", da: "Gitter", nb: "Rutenett", fi: "Ruudukko", el: "Πλέγμα", cs: "Mřížka", hu: "Rács", ro: "Grilă", hr: "Rešetka", bg: "Решетка", sk: "Mriežka", he: "רשת", uk: "Сітка", fa: "شبکه", bn: "গ্রিড", sw: "Gridi", tl: "Grid", ur: "گرڈ", am: "ግሪድ", ha: "Grid", yo: "Grid", wo: "Grid", ru: "Сетка", sl: "Mreža", lt: "Tinklelis", lv: "Režģis", et: "Võrgustik",
  },
  "islamic.previous": {
    fr: "Précédent", en: "Previous", es: "Anterior", de: "Vorherige", it: "Precedente", pt: "Anterior", nl: "Vorige", pl: "Poprzedni", tr: "Önceki", ar: "السابق", ja: "前へ", ko: "이전", zh: "上一页", hi: "पिछला", th: "ก่อนหน้า", vi: "Trước", id: "Sebelumnya", ms: "Sebelumnya", sv: "Föregående", da: "Forrige", nb: "Forrige", fi: "Edellinen", el: "Προηγούμενο", cs: "Předchozí", hu: "Előző", ro: "Anterior", hr: "Prethodno", bg: "Предишен", sk: "Predchádzajúci", he: "הקודם", uk: "Попередній", fa: "قبلی", bn: "পূর্ববর্তী", sw: "Iliyotangulia", tl: "Nakaraan", ur: "پچھلا", am: "ያለፈው", ha: "Na baya", yo: "Ṣáájú", wo: "Bi weesu", ru: "Предыдущий", sl: "Prejšnji", lt: "Ankstesnis", lv: "Iepriekšējais", et: "Eelmine",
  },
  "islamic.page": {
    fr: "Page", en: "Page", es: "Página", de: "Seite", it: "Pagina", pt: "Página", nl: "Pagina", pl: "Strona", tr: "Sayfa", ar: "صفحة", ja: "ページ", ko: "페이지", zh: "页面", hi: "पृष्ठ", th: "หน้า", vi: "Trang", id: "Halaman", ms: "Halaman", sv: "Sida", da: "Side", nb: "Side", fi: "Sivu", el: "Σελίδα", cs: "Stránka", hu: "Oldal", ro: "Pagină", hr: "Stranica", bg: "Страница", sk: "Stránka", he: "עמוד", uk: "Сторінка", fa: "صفحه", bn: "পৃষ্ঠা", sw: "Ukurasa", tl: "Pahina", ur: "صفحہ", am: "ገጽ", ha: "Shafi", yo: "Ojú-ìwé", wo: "Xët", ru: "Страница", sl: "Stran", lt: "Puslapis", lv: "Lapa", et: "Leht",
  },
  "islamic.nisab_threshold": {
    fr: "Seuil Nisab actuel", en: "Current Nisab Threshold", es: "Umbral Nisab actual", de: "Aktueller Nisab-Schwellenwert", it: "Soglia Nisab attuale", pt: "Limiar Nisab atual", nl: "Huidige Nisab-drempel", pl: "Aktualny próg Nisab", tr: "Güncel Nisab Eşiği", ar: "نصاب الزكاة الحالي", ja: "現在のニサーブ基準", ko: "현재 니사브 기준", zh: "当前尼萨布门槛", hi: "वर्तमान निसाब सीमा", th: "เกณฑ์นิศอบปัจจุบัน", vi: "Ngưỡng Nisab hiện tại", id: "Ambang Batas Nisab Saat Ini", ms: "Ambang Nisab Semasa", sv: "Aktuell Nisab-tröskel", da: "Aktuel Nisab-tærskel", nb: "Nåværende Nisab-grense", fi: "Nykyinen Nisab-raja", el: "Τρέχον Όριο Νισάμπ", cs: "Aktuální práh Nisab", hu: "Jelenlegi Niszáb-küszöb", ro: "Pragul Nisab actual", hr: "Trenutni prag Nisab", bg: "Текущ праг Нисаб", sk: "Aktuálny prah Nisab", he: "סף ניסאב נוכחי", uk: "Поточний поріг Нісаб", fa: "نصاب فعلی", bn: "বর্তমান নিসাব সীমা", sw: "Kiwango cha Nisab cha Sasa", tl: "Kasalukuyang Nisab Threshold", ur: "موجودہ نصاب حد", am: "የአሁኑ ኒሳብ ደረጃ", ha: "Iyakar Nisab na yanzu", yo: "Ìwọ̀n Nisab lọ́wọ́lọ́wọ́", wo: "Seuil Nisab bu tey", ru: "Текущий порог Нисаб", sl: "Trenutni prag Nisab", lt: "Dabartinė Nisab riba", lv: "Pašreizējais Nisab slieksnis", et: "Praegune Nisab lävi",
  },
  "islamic.total_wealth": {
    fr: "Patrimoine total", en: "Total Wealth", es: "Patrimonio total", de: "Gesamtvermögen", it: "Patrimonio totale", pt: "Patrimônio total", nl: "Totaal vermogen", pl: "Łączny majątek", tr: "Toplam Servet", ar: "إجمالي الثروة", ja: "総資産", ko: "총 자산", zh: "总资产", hi: "कुल संपत्ति", th: "ความมั่งคั่งรวม", vi: "Tổng tài sản", id: "Total Kekayaan", ms: "Jumlah Kekayaan", sv: "Totalt Förmögenhet", da: "Samlet Formue", nb: "Total Formue", fi: "Kokonaisvarallisuus", el: "Συνολικός Πλούτος", cs: "Celkový majetek", hu: "Teljes vagyon", ro: "Patrimoniu total", hr: "Ukupno bogatstvo", bg: "Общо богатство", sk: "Celkový majetok", he: "עושר כולל", uk: "Загальне багатство", fa: "مجموع دارایی", bn: "মোট সম্পদ", sw: "Utajiri Wote", tl: "Kabuuang Kayamanan", ur: "کل دولت", am: "ጠቅላላ ሀብት", ha: "Jimlar dukiya", yo: "Àpapọ̀ Ohun-ìní", wo: "Alal lépp", ru: "Общее состояние", sl: "Skupno premoženje", lt: "Bendras turtas", lv: "Kopējā bagātība", et: "Kogu vara",
  },
  "islamic.debts": {
    fr: "Dettes", en: "Debts", es: "Deudas", de: "Schulden", it: "Debiti", pt: "Dívidas", nl: "Schulden", pl: "Długi", tr: "Borçlar", ar: "الديون", ja: "債務", ko: "부채", zh: "债务", hi: "क़र्ज़", th: "หนี้สิน", vi: "Nợ", id: "Utang", ms: "Hutang", sv: "Skulder", da: "Gæld", nb: "Gjeld", fi: "Velat", el: "Χρέη", cs: "Dluhy", hu: "Adósságok", ro: "Datorii", hr: "Dugovi", bg: "Дългове", sk: "Dlhy", he: "חובות", uk: "Борги", fa: "بدهی‌ها", bn: "ঋণ", sw: "Madeni", tl: "Mga Utang", ur: "قرضے", am: "ዕዳዎች", ha: "Bashin kuɗi", yo: "Gbèsè", wo: "Baaj", ru: "Долги", sl: "Dolgovi", lt: "Skolos", lv: "Parādi", et: "Võlad",
  },
  "islamic.net_wealth": {
    fr: "Patrimoine net", en: "Net Wealth", es: "Patrimonio neto", de: "Nettovermögen", it: "Patrimonio netto", pt: "Patrimônio líquido", nl: "Netto vermogen", pl: "Majątek netto", tr: "Net Servet", ar: "صافي الثروة", ja: "純資産", ko: "순 자산", zh: "净资产", hi: "शुद्ध संपत्ति", th: "ความมั่งคั่งสุทธิ", vi: "Tài sản ròng", id: "Kekayaan Bersih", ms: "Kekayaan Bersih", sv: "Nettoförmögenhet", da: "Nettoformue", nb: "Nettoformue", fi: "Nettovarallisuus", el: "Καθαρός Πλούτος", cs: "Čistý majetek", hu: "Nettó vagyon", ro: "Patrimoniu net", hr: "Neto bogatstvo", bg: "Нетно богатство", sk: "Čistý majetok", he: "עושר נטו", uk: "Чисте багатство", fa: "دارایی خالص", bn: "নিট সম্পদ", sw: "Utajiri Halisi", tl: "Netong Kayamanan", ur: "خالص دولت", am: "ንጹህ ሀብት", ha: "Tsabtar dukiya", yo: "Àpapọ̀ gidi", wo: "Alal bu set", ru: "Чистое состояние", sl: "Neto premoženje", lt: "Grynasis turtas", lv: "Neto bagātība", et: "Puhas vara",
  },
  "islamic.subject_to_zakat": {
    fr: "Assujetti ?", en: "Subject to Zakat?", es: "¿Sujeto al Zakat?", de: "Zakatpflichtig?", it: "Soggetto a Zakat?", pt: "Sujeito ao Zakat?", nl: "Zakatplichtig?", pl: "Podlega Zakatowi?", tr: "Zekat gerekli mi?", ar: "هل تجب الزكاة؟", ja: "ザカート対象？", ko: "자카트 대상？", zh: "需缴天课？", hi: "ज़कात लागू？", th: "ต้องจ่ายซะกาต？", vi: "Phải đóng Zakat?", id: "Wajib Zakat?", ms: "Wajib Zakat?", sv: "Zakatpliktigt?", da: "Zakatpligtigt?", nb: "Zakatpliktig?", fi: "Zakat-velvollinen?", el: "Υποκείμενο σε Ζακάτ;", cs: "Podléhá Zakátu?", hu: "Zakat-köteles?", ro: "Supus Zakat-ului?", hr: "Podliježe Zekatu?", bg: "Подлежи на Зекят?", sk: "Podlieha Zakátu?", he: "חייב בזכאת?", uk: "Підлягає Закяту?", fa: "مشمول زکات؟", bn: "যাকাত প্রযোজ্য？", sw: "Inapaswa Zakat?", tl: "Nararapat sa Zakat?", ur: "زکوٰۃ واجب？", am: "ዘካት ይገባዋል？", ha: "Ana buƙatar Zakka?", yo: "Ṣe Zakat jẹ́ dandan?", wo: "Ndax Zakat waral?", ru: "Подлежит Закяту?", sl: "Podvržen Zakatu?", lt: "Zakat privalomas?", lv: "Vai jāmaksā Zakat?", et: "Zakat kohustuslik?",
  },
  "islamic.yes": {
    fr: "Oui", en: "Yes", es: "Sí", de: "Ja", it: "Sì", pt: "Sim", nl: "Ja", pl: "Tak", tr: "Evet", ar: "نعم", ja: "はい", ko: "예", zh: "是", hi: "हाँ", th: "ใช่", vi: "Có", id: "Ya", ms: "Ya", sv: "Ja", da: "Ja", nb: "Ja", fi: "Kyllä", el: "Ναι", cs: "Ano", hu: "Igen", ro: "Da", hr: "Da", bg: "Да", sk: "Áno", he: "כן", uk: "Так", fa: "بله", bn: "হ্যাঁ", sw: "Ndiyo", tl: "Oo", ur: "ہاں", am: "አዎ", ha: "Eh", yo: "Bẹ́ẹ̀ni", wo: "Waaw", ru: "Да", sl: "Da", lt: "Taip", lv: "Jā", et: "Jah",
  },
  "islamic.no": {
    fr: "Non", en: "No", es: "No", de: "Nein", it: "No", pt: "Não", nl: "Nee", pl: "Nie", tr: "Hayır", ar: "لا", ja: "いいえ", ko: "아니요", zh: "否", hi: "नहीं", th: "ไม่", vi: "Không", id: "Tidak", ms: "Tidak", sv: "Nej", da: "Nej", nb: "Nei", fi: "Ei", el: "Όχι", cs: "Ne", hu: "Nem", ro: "Nu", hr: "Ne", bg: "Не", sk: "Nie", he: "לא", uk: "Ні", fa: "خیر", bn: "না", sw: "Hapana", tl: "Hindi", ur: "نہیں", am: "አይ", ha: "A'a", yo: "Bẹ́ẹ̀kọ́", wo: "Déedéet", ru: "Нет", sl: "Ne", lt: "Ne", lv: "Nē", et: "Ei",
  },
  "islamic.total_zakat": {
    fr: "Total Zakat à verser", en: "Total Zakat Due", es: "Total de Zakat a pagar", de: "Zakat-Gesamtbetrag", it: "Totale Zakat da versare", pt: "Total de Zakat a pagar", nl: "Totaal verschuldigde Zakat", pl: "Łączny Zakat do zapłaty", tr: "Toplam Zekat Tutarı", ar: "إجمالي الزكاة المستحقة", ja: "ザカート支払い総額", ko: "납부해야 할 자카트 총액", zh: "应缴天课总额", hi: "कुल ज़कात देय", th: "ยอดซะกาตรวม", vi: "Tổng Zakat phải trả", id: "Total Zakat yang Harus Dibayar", ms: "Jumlah Zakat yang Perlu Dibayar", sv: "Totalt Zakat att betala", da: "Samlet Zakat at betale", nb: "Total Zakat å betale", fi: "Maksettava Zakat yhteensä", el: "Συνολική Ζακάτ οφειλόμενη", cs: "Celkový splatný Zakát", hu: "Fizetendő Zakat összesen", ro: "Total Zakat de plătit", hr: "Ukupni Zekat za uplatu", bg: "Общ дължим Зекят", sk: "Celkový splatný Zakát", he: "סה\"כ זכאת לתשלום", uk: "Загальний Закят до сплати", fa: "مجموع زکات قابل پرداخت", bn: "মোট যাকাত প্রদেয়", sw: "Jumla ya Zakat ya Kulipwa", tl: "Kabuuang Zakat na Dapat Bayaran", ur: "کل واجب الادا زکوٰۃ", am: "ጠቅላላ ዘካት ለመክፈል", ha: "Jimlar Zakka da za a biya", yo: "Àpapọ̀ Zakat láti san", wo: "Toltalitee Zakat bu ñu war fay", ru: "Общая сумма Закята к оплате", sl: "Skupni dolgovani Zakat", lt: "Bendra mokėtina Zakat suma", lv: "Kopējais maksājamais Zakat", et: "Tasumisele kuuluv Zakat kokku",
  },
  "islamic.calculation_result": {
    fr: "Résultat du calcul", en: "Calculation Result", es: "Resultado del cálculo", de: "Berechnungsergebnis", it: "Risultato del calcolo", pt: "Resultado do cálculo", nl: "Berekeningsresultaat", pl: "Wynik obliczeń", tr: "Hesaplama Sonucu", ar: "نتيجة الحساب", ja: "計算結果", ko: "계산 결과", zh: "计算结果", hi: "गणना परिणाम", th: "ผลการคำนวณ", vi: "Kết quả tính toán", id: "Hasil Perhitungan", ms: "Keputusan Pengiraan", sv: "Beräkningsresultat", da: "Beregningsresultat", nb: "Beregningsresultat", fi: "Laskentatulos", el: "Αποτέλεσμα Υπολογισμού", cs: "Výsledek výpočtu", hu: "Számítás eredménye", ro: "Rezultatul calculului", hr: "Rezultat izračuna", bg: "Резултат от изчислението", sk: "Výsledok výpočtu", he: "תוצאת חישוב", uk: "Результат розрахунку", fa: "نتیجه محاسبه", bn: "হিসাবের ফলাফল", sw: "Matokeo ya Kukokotoa", tl: "Resulta ng Pagkalkula", ur: "حساب کا نتیجہ", am: "የስሌት ውጤት", ha: "Sakamakon lissafi", yo: "Èsì ìṣírò", wo: "Boppu xam-xam bi", ru: "Результат расчёта", sl: "Rezultat izračuna", lt: "Skaičiavimo rezultatas", lv: "Aprēķina rezultāts", et: "Arvutuse tulemus",
  },
  "islamic.number_of_persons": {
    fr: "Nombre de personnes", en: "Number of persons", es: "Número de personas", de: "Anzahl der Personen", it: "Numero di persone", pt: "Número de pessoas", nl: "Aantal personen", pl: "Liczba osób", tr: "Kişi sayısı", ar: "عدد الأشخاص", ja: "人数", ko: "인원수", zh: "人数", hi: "व्यक्तियों की संख्या", th: "จำนวนคน", vi: "Số người", id: "Jumlah orang", ms: "Bilangan orang", sv: "Antal personer", da: "Antal personer", nb: "Antall personer", fi: "Henkilöiden lukumäärä", el: "Αριθμός ατόμων", cs: "Počet osob", hu: "Személyek száma", ro: "Număr de persoane", hr: "Broj osoba", bg: "Брой хора", sk: "Počet osôb", he: "מספר אנשים", uk: "Кількість осіб", fa: "تعداد افراد", bn: "ব্যক্তির সংখ্যা", sw: "Idadi ya watu", tl: "Bilang ng mga tao", ur: "افراد کی تعداد", am: "የሰዎች ብዛት", ha: "Adadin mutane", yo: "Iye ènìyàn", wo: "Limu nit ñi", ru: "Количество человек", sl: "Število oseb", lt: "Asmenų skaičius", lv: "Personu skaits", et: "Isikute arv",
  },
  "islamic.exchange_rate_loading": {
    fr: "Chargement du taux de change...", en: "Loading exchange rate...", es: "Cargando tipo de cambio...", de: "Wechselkurs wird geladen...", it: "Caricamento tasso di cambio...", pt: "Carregando taxa de câmbio...", nl: "Wisselkoers laden...", pl: "Ładowanie kursu wymiany...", tr: "Döviz kuru yükleniyor...", ar: "جارٍ تحميل سعر الصرف...", ja: "為替レートを読み込み中...", ko: "환율 로딩 중...", zh: "加载汇率中...", hi: "विनिमय दर लोड हो रही है...", th: "กำลังโหลดอัตราแลกเปลี่ยน...", vi: "Đang tải tỷ giá...", id: "Memuat kurs...", ms: "Memuatkan kadar pertukaran...", sv: "Laddar växelkurs...", da: "Indlæser valutakurs...", nb: "Laster valutakurs...", fi: "Ladataan vaihtokurssia...", el: "Φόρτωση συναλλαγματικής ισοτιμίας...", cs: "Načítání směnného kurzu...", hu: "Árfolyam betöltése...", ro: "Se încarcă cursul valutar...", hr: "Učitavanje tečaja...", bg: "Зареждане на обменния курс...", sk: "Načítava sa výmenný kurz...", he: "...טוען שער חליפין", uk: "Завантаження курсу обміну...", fa: "...در حال بارگذاری نرخ ارز", bn: "বিনিময় হার লোড হচ্ছে...", sw: "Inapakia kiwango cha kubadilisha...", tl: "Nilo-load ang exchange rate...", ur: "...شرح مبادلہ لوڈ ہو رہی ہے", am: "የምንዛሪ ተመን እየጫነ ነው...", ha: "Ana lodawan farashin musaya...", yo: "Ń gbé owó pàṣípààrọ̀ kalẹ̀...", wo: "Yàgg nañu jëfandiku kursu bi...", ru: "Загрузка курса валют...", sl: "Nalaganje menjalnega tečaja...", lt: "Kraunamas valiutos kursas...", lv: "Ielādē valūtas kursu...", et: "Vahetuskursi laadimine...",
  },
};

export const ISLAMIC_TRANSLATIONS: Record<string, Record<string, string>> = {};

for (const [key, locales] of Object.entries(keys)) {
  for (const [locale, value] of Object.entries(locales)) {
    if (!ISLAMIC_TRANSLATIONS[locale]) ISLAMIC_TRANSLATIONS[locale] = {};
    ISLAMIC_TRANSLATIONS[locale][key] = value;
  }
}
