import type { DataSource } from "./types";
import { FALLBACK_STORIES } from "@/data/fallback-stories";
import { FALLBACK_PROPERTIES } from "@/data/fallback-properties";
import { FALLBACK_HOTELS } from "@/data/fallback-hotels";
import { FALLBACK_RESTAURANTS, FALLBACK_MENUS } from "@/data/fallback-restaurants";
import { FALLBACK_SHOPS, FALLBACK_GROCERY } from "@/data/fallback-shops";
import { FALLBACK_SERVICES, FALLBACK_SERVICE_ITEMS } from "@/data/fallback-services";

export function buildSourceInventory(): DataSource[] {
  return [
    {
      name: "FALLBACK_STORIES",
      path: "src/data/fallback-stories.ts",
      type: "fallback_static",
      runtimeConsumers: ["story-feed", "dashboard", "search-index", "story-taxonomy"],
      verticalsAffected: ["property", "stay", "food", "grocery", "utility", "mobility", "shops", "services"],
      status: "fallback",
      risk: "medium",
      entityCount: FALLBACK_STORIES.length,
      safeToMutate: true,
      shouldExist: true,
      actionNeeded: "Audit taxonomy, media, cross-vertical purity",
    },
    {
      name: "FALLBACK_PROPERTIES",
      path: "src/data/fallback-properties.ts",
      type: "fallback_static",
      runtimeConsumers: ["search-index", "property-hub", "dashboard"],
      verticalsAffected: ["property"],
      status: "fallback",
      risk: "low",
      entityCount: FALLBACK_PROPERTIES.length,
      safeToMutate: true,
      shouldExist: true,
      actionNeeded: "Validate taxonomy, field completeness",
    },
    {
      name: "FALLBACK_HOTELS",
      path: "src/data/fallback-hotels.ts",
      type: "fallback_static",
      runtimeConsumers: ["search-index", "stay-hub", "dashboard"],
      verticalsAffected: ["stay"],
      status: "fallback",
      risk: "low",
      entityCount: FALLBACK_HOTELS.length,
      safeToMutate: true,
      shouldExist: true,
      actionNeeded: "Validate taxonomy, room references, media",
    },
    {
      name: "FALLBACK_RESTAURANTS",
      path: "src/data/fallback-restaurants.ts",
      type: "fallback_static",
      runtimeConsumers: ["search-index", "food-hub", "dashboard"],
      verticalsAffected: ["food"],
      status: "fallback",
      risk: "low",
      entityCount: FALLBACK_RESTAURANTS.length,
      safeToMutate: true,
      shouldExist: true,
      actionNeeded: "Validate taxonomy, menu references, media",
    },
    {
      name: "FALLBACK_MENUS",
      path: "src/data/fallback-restaurants.ts",
      type: "fallback_static",
      runtimeConsumers: ["food-hub", "storefront"],
      verticalsAffected: ["food"],
      status: "fallback",
      risk: "low",
      entityCount: Object.values(FALLBACK_MENUS).flat().length,
      safeToMutate: true,
      shouldExist: true,
      actionNeeded: "Validate shop_id references, media, field completeness",
    },
    {
      name: "FALLBACK_SHOPS",
      path: "src/data/fallback-shops.ts",
      type: "fallback_static",
      runtimeConsumers: ["search-index", "shops-hub", "dashboard"],
      verticalsAffected: ["shops"],
      status: "fallback",
      risk: "low",
      entityCount: FALLBACK_SHOPS.length,
      safeToMutate: true,
      shouldExist: true,
      actionNeeded: "Validate taxonomy, media, field completeness",
    },
    {
      name: "FALLBACK_GROCERY",
      path: "src/data/fallback-shops.ts",
      type: "fallback_static",
      runtimeConsumers: ["search-index", "grocery-hub", "dashboard"],
      verticalsAffected: ["grocery"],
      status: "fallback",
      risk: "low",
      entityCount: FALLBACK_GROCERY.length,
      safeToMutate: true,
      shouldExist: true,
      actionNeeded: "Validate taxonomy, media, field completeness",
    },
    {
      name: "FALLBACK_SERVICES",
      path: "src/data/fallback-services.ts",
      type: "fallback_static",
      runtimeConsumers: ["search-index", "services-hub", "dashboard"],
      verticalsAffected: ["services"],
      status: "fallback",
      risk: "low",
      entityCount: FALLBACK_SERVICES.length,
      safeToMutate: true,
      shouldExist: true,
      actionNeeded: "Validate taxonomy, media, service item references",
    },
    {
      name: "FALLBACK_SERVICE_ITEMS",
      path: "src/data/fallback-services.ts",
      type: "fallback_static",
      runtimeConsumers: ["services-hub", "storefront"],
      verticalsAffected: ["services"],
      status: "fallback",
      risk: "low",
      entityCount: FALLBACK_SERVICE_ITEMS.length,
      safeToMutate: true,
      shouldExist: true,
      actionNeeded: "Validate provider_id references, media, field completeness",
    },
  ];
}
