import type { DataSource } from "./types";
import { FALLBACK_STORIES } from "@/data/fallback-stories";
import { FALLBACK_PROPERTIES } from "@/data/fallback-properties";
import { FALLBACK_HOTELS } from "@/data/fallback-hotels";
import { FALLBACK_RESTAURANTS, FALLBACK_MENUS } from "@/data/fallback-restaurants";
import { FALLBACK_SHOPS, FALLBACK_GROCERY } from "@/data/fallback-shops";
import { FALLBACK_SERVICES, FALLBACK_SERVICE_ITEMS } from "@/data/fallback-services";

export function buildSourceInventory(): DataSource[] {
  return [
    {
      name: "FALLBACK_STORIES",
      path: "src/data/fallback-stories.ts",
      type: "fallback_static",
      runtimeConsumers: ["story-feed", "dashboard", "search-index", "story-taxonomy"],
      verticalsAffected: ["property", "stay", "food", "grocery", "utility", "mobility", "shops", "services"],
      status: "fallback",
      risk: "medium",
      entityCount: FALLBACK_STORIES.length,
      safeToMutate: true,
      shouldExist: true,
      actionNeeded: "Audit taxonomy, media, cross-vertical purity",
      trustScore: 70,
      mutationPolicy: "safe_auto",
      visibilityPolicy: "fallback_only",
      mayFeedLiveSurfaces: true,
      requiresSanitization: true,
    },
    {
      name: "FALLBACK_PROPERTIES",
      path: "src/data/fallback-properties.ts",
      type: "fallback_static",
      runtimeConsumers: ["search-index", "property-hub", "dashboard"],
      verticalsAffected: ["property"],
      status: "fallback",
      risk: "low",
      entityCount: FALLBACK_PROPERTIES.length,
      safeToMutate: true,
      shouldExist: true,
      actionNeeded: "Validate taxonomy, field completeness",
      trustScore: 80,
      mutationPolicy: "safe_auto",
      visibilityPolicy: "fallback_only",
      mayFeedLiveSurfaces: true,
      requiresSanitization: false,
    },
    {
      name: "FALLBACK_HOTELS",
      path: "src/data/fallback-hotels.ts",
      type: "fallback_static",
      runtimeConsumers: ["search-index", "stay-hub", "dashboard"],
      verticalsAffected: ["stay"],
      status: "fallback",
      risk: "low",
      entityCount: FALLBACK_HOTELS.length,
      safeToMutate: true,
      shouldExist: true,
      actionNeeded: "Validate taxonomy, room references, media",
      trustScore: 80,
      mutationPolicy: "safe_auto",
      visibilityPolicy: "fallback_only",
      mayFeedLiveSurfaces: true,
      requiresSanitization: false,
    },
    {
      name: "FALLBACK_RESTAURANTS",
      path: "src/data/fallback-restaurants.ts",
      type: "fallback_static",
      runtimeConsumers: ["search-index", "food-hub", "dashboard"],
      verticalsAffected: ["food"],
      status: "fallback",
      risk: "low",
      entityCount: FALLBACK_RESTAURANTS.length,
      safeToMutate: true,
      shouldExist: true,
      actionNeeded: "Validate taxonomy, menu references, media",
      trustScore: 85,
      mutationPolicy: "safe_auto",
      visibilityPolicy: "fallback_only",
      mayFeedLiveSurfaces: true,
      requiresSanitization: false,
    },
    {
      name: "FALLBACK_MENUS",
      path: "src/data/fallback-restaurants.ts",
      type: "fallback_static",
      runtimeConsumers: ["food-hub", "storefront"],
      verticalsAffected: ["food"],
      status: "fallback",
      risk: "low",
      entityCount: Object.values(FALLBACK_MENUS).flat().length,
      safeToMutate: true,
      shouldExist: true,
      actionNeeded: "Validate shop_id references, media, field completeness",
      trustScore: 85,
      mutationPolicy: "safe_auto",
      visibilityPolicy: "fallback_only",
      mayFeedLiveSurfaces: true,
      requiresSanitization: false,
    },
    {
      name: "FALLBACK_SHOPS",
      path: "src/data/fallback-shops.ts",
      type: "fallback_static",
      runtimeConsumers: ["search-index", "shops-hub", "dashboard"],
      verticalsAffected: ["shops"],
      status: "fallback",
      risk: "low",
      entityCount: FALLBACK_SHOPS.length,
      safeToMutate: true,
      shouldExist: true,
      actionNeeded: "Validate taxonomy, media, field completeness",
      trustScore: 80,
      mutationPolicy: "safe_auto",
      visibilityPolicy: "fallback_only",
      mayFeedLiveSurfaces: true,
      requiresSanitization: false,
    },
    {
      name: "FALLBACK_GROCERY",
      path: "src/data/fallback-shops.ts",
      type: "fallback_static",
      runtimeConsumers: ["search-index", "grocery-hub", "dashboard"],
      verticalsAffected: ["grocery"],
      status: "fallback",
      risk: "low",
      entityCount: FALLBACK_GROCERY.length,
      safeToMutate: true,
      shouldExist: true,
      actionNeeded: "Validate taxonomy, media, field completeness",
      trustScore: 80,
      mutationPolicy: "safe_auto",
      visibilityPolicy: "fallback_only",
      mayFeedLiveSurfaces: true,
      requiresSanitization: false,
    },
    {
      name: "FALLBACK_SERVICES",
      path: "src/data/fallback-services.ts",
      type: "fallback_static",
      runtimeConsumers: ["search-index", "services-hub", "dashboard"],
      verticalsAffected: ["services"],
      status: "fallback",
      risk: "low",
      entityCount: FALLBACK_SERVICES.length,
      safeToMutate: true,
      shouldExist: true,
      actionNeeded: "Validate taxonomy, media, service item references",
      trustScore: 80,
      mutationPolicy: "safe_auto",
      visibilityPolicy: "fallback_only",
      mayFeedLiveSurfaces: true,
      requiresSanitization: false,
    },
    {
      name: "FALLBACK_SERVICE_ITEMS",
      path: "src/data/fallback-services.ts",
      type: "fallback_static",
      runtimeConsumers: ["services-hub", "storefront"],
      verticalsAffected: ["services"],
      status: "fallback",
      risk: "low",
      entityCount: FALLBACK_SERVICE_ITEMS.length,
      safeToMutate: true,
      shouldExist: true,
      actionNeeded: "Validate provider_id references, media, field completeness",
      trustScore: 75,
      mutationPolicy: "safe_auto",
      visibilityPolicy: "fallback_only",
      mayFeedLiveSurfaces: true,
      requiresSanitization: false,
    },
  ];
}

export function getSourceTrustSummary() {
  const sources = buildSourceInventory();
  return {
    totalSources: sources.length,
    sources: sources.map((s) => ({
      name: s.name,
      type: s.type,
      trustScore: s.trustScore,
      mutationPolicy: s.mutationPolicy,
      visibilityPolicy: s.visibilityPolicy,
      mayFeedLiveSurfaces: s.mayFeedLiveSurfaces,
      requiresSanitization: s.requiresSanitization,
      risk: s.risk,
      entityCount: s.entityCount,
    })),
    byType: sources.reduce<Record<string, number>>((acc, s) => {
      acc[s.type] = (acc[s.type] ?? 0) + 1;
      return acc;
    }, {}),
    averageTrust: sources.reduce((sum, s) => sum + s.trustScore, 0) / sources.length,
    sanitizationRequired: sources.filter((s) => s.requiresSanitization).map((s) => s.name),
    dangerousSources: sources.filter((s) => s.visibilityPolicy === "dangerous" || s.risk === "critical").map((s) => s.name),
  };
}
