#!/usr/bin/env -S npx tsx
/**
 * Edge Functions — security posture inventory.
 *
 * Ground-truth classification lives in `supabase/functions/_manifest.ts`.
 * This script cross-checks the manifest against what is actually on disk
 * (config.toml verify_jwt flags + source files) and emits a report that:
 *   1. lists every manifest entry with its declared auth/rate-limit posture,
 *   2. flags any function present on disk but missing from the manifest
 *      (these are treated as unclassified and block the "zero public
 *      unauthenticated" goal),
 *   3. flags any mismatch between the manifest's `rateLimit: true` claim
 *      and the actual presence of `withRateLimit(` in the handler source
 *      (so false assurances are caught).
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { pathToFileURL } from "node:url";

const ROOT = path.resolve(import.meta.dirname, "..");
const FUNCTIONS_DIR = path.join(ROOT, "supabase", "functions");
const CONFIG_FILE = path.join(ROOT, "supabase", "config.toml");
const MANIFEST_FILE = path.join(FUNCTIONS_DIR, "_manifest.ts");
const OUTPUT = path.join(ROOT, "docs", "security", "edge-functions-auth-inventory.md");

type Auth = "jwt" | "service_role" | "signature" | "token" | "public";
interface Entry { auth: Auth; rateLimit: boolean; reason?: string }

function readConfigJwtFlags(): Map<string, "true" | "false"> {
  const out = new Map<string, "true" | "false">();
  if (!fs.existsSync(CONFIG_FILE)) return out;
  const text = fs.readFileSync(CONFIG_FILE, "utf8");
  const re = /\[functions\.([^\]]+)\]\s*\n\s*verify_jwt\s*=\s*(true|false)/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text))) out.set(m[1], m[2] as "true" | "false");
  return out;
}

function sourceOf(name: string): string {
  const idx = path.join(FUNCTIONS_DIR, name, "index.ts");
  try { return fs.readFileSync(idx, "utf8"); } catch { return ""; }
}

async function loadManifest(): Promise<Record<string, Entry>> {
  const mod = await import(pathToFileURL(MANIFEST_FILE).href);
  return mod.EDGE_FUNCTION_MANIFEST as Record<string, Entry>;
}

function hasRateLimitWrapper(src: string): boolean {
  // The inventory trusts only the explicit wrapper — not keyword matches.
  return /withRateLimit\s*\(/.test(src);
}

async function main() {
  const manifest = await loadManifest();
  const jwtFlags = readConfigJwtFlags();
  const onDisk = fs
    .readdirSync(FUNCTIONS_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !e.name.startsWith("_"))
    .map((e) => e.name)
    .sort();

  const unclassified = onDisk.filter((n) => !(n in manifest));
  const declaredNotOnDisk = Object.keys(manifest).filter((n) => !onDisk.includes(n));

  interface Mismatch { name: string; kind: string; detail: string }
  const mismatches: Mismatch[] = [];

  for (const [name, entry] of Object.entries(manifest)) {
    const src = sourceOf(name);
    const rlActual = hasRateLimitWrapper(src);
    if (entry.rateLimit && !rlActual) {
      mismatches.push({ name, kind: "rate-limit claimed but wrapper missing", detail: `_manifest says rateLimit=true but index.ts has no withRateLimit(` });
    }
    if (!entry.rateLimit && rlActual) {
      mismatches.push({ name, kind: "rate-limit present but manifest says no", detail: `index.ts has withRateLimit( but _manifest has rateLimit=false` });
    }
    const jwt = jwtFlags.get(name);
    if (entry.auth === "public" && jwt !== "false") {
      mismatches.push({ name, kind: "config drift", detail: `manifest auth=public but config.toml verify_jwt=${jwt ?? "unset"}` });
    }
    if (entry.auth === "signature" && jwt !== "false") {
      mismatches.push({ name, kind: "config drift", detail: `manifest auth=signature requires verify_jwt=false; current=${jwt ?? "unset"}` });
    }
  }

  const byAuth = { jwt: 0, service_role: 0, signature: 0, token: 0, public: 0 } as Record<Auth, number>;
  let rateLimited = 0;
  for (const e of Object.values(manifest)) {
    byAuth[e.auth]++;
    if (e.rateLimit) rateLimited++;
  }

  const L: string[] = [];
  L.push("# Edge Functions — Auth & Rate-Limit Inventory");
  L.push("");
  L.push("> Generated by `scripts/security-inventory-edge-functions.ts`. Source of truth is `supabase/functions/_manifest.ts`. Re-run after any manifest / config / handler change.");
  L.push("");
  L.push(`On disk: **${onDisk.length}** function directories · manifested: **${Object.keys(manifest).length}** · unclassified: **${unclassified.length}**`);
  L.push("");
  L.push("## Posture (manifested functions only)");
  L.push("");
  L.push("| Auth | Count |");
  L.push("| --- | ---: |");
  L.push(`| JWT (inside domain router) | ${byAuth.jwt} |`);
  L.push(`| Service role (internal / cron) | ${byAuth.service_role} |`);
  L.push(`| Signature verify (webhook) | ${byAuth.signature} |`);
  L.push(`| Per-request token | ${byAuth.token} |`);
  L.push(`| Public (no auth) | ${byAuth.public} |`);
  L.push("");
  L.push(`Rate-limit wrapper: **${rateLimited} / ${Object.keys(manifest).length}** manifested functions.`);
  L.push("");

  if (unclassified.length) {
    L.push("## ⚠ Unclassified functions on disk");
    L.push("");
    L.push("Each of these must be added to `_manifest.ts` with an explicit `auth` and a one-line `reason`. Until they are, the overall goal of \"zéro Edge Function publique non authentifiée\" cannot be declared met.");
    L.push("");
    for (const n of unclassified) {
      const jwt = jwtFlags.get(n) ?? "unset (default verify_jwt=true)";
      const src = sourceOf(n);
      L.push(`- \`${n}\` (verify_jwt=${jwt}, rate-limit wrapper ${hasRateLimitWrapper(src) ? "present" : "missing"})`);
    }
    L.push("");
    L.push(`Total unclassified: **${unclassified.length}**`);
    L.push("");
  }

  if (declaredNotOnDisk.length) {
    L.push("## ⚠ Manifest entries not present on disk");
    L.push("");
    for (const n of declaredNotOnDisk) L.push(`- \`${n}\``);
    L.push("");
  }

  if (mismatches.length) {
    L.push("## ⚠ Manifest ↔ code mismatches");
    L.push("");
    for (const m of mismatches) {
      L.push(`- \`${m.name}\` — ${m.kind}: ${m.detail}`);
    }
    L.push("");
  }

  L.push("## Manifest (ground truth)");
  L.push("");
  L.push("| Function | Auth | Rate-limit | Reason |");
  L.push("| --- | --- | :-: | --- |");
  for (const [name, e] of Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b))) {
    L.push(`| \`${name}\` | ${e.auth} | ${e.rateLimit ? "✓" : ""} | ${e.reason ?? ""} |`);
  }
  L.push("");

  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, L.join("\n"), "utf8");
  console.log(`Wrote ${OUTPUT}`);
  console.log(
    `onDisk=${onDisk.length} manifested=${Object.keys(manifest).length} unclassified=${unclassified.length} mismatches=${mismatches.length}`,
  );

  // Hard gate: mismatches always fail. Unclassified count must never
  // increase past the baseline committed in docs/security/unclassified-baseline.json.
  // This is a one-way ratchet: the number can only shrink as functions are
  // added to `_manifest.ts` with an explicit auth + rateLimit + reason, until
  // it reaches zero.
  if (mismatches.length > 0) {
    console.error(`\n${mismatches.length} manifest/code mismatch(es) — see inventory report.`);
    process.exit(2);
  }

  const BASELINE_FILE = path.join(ROOT, "docs", "security", "unclassified-baseline.json");
  let baseline = Number.POSITIVE_INFINITY;
  try {
    const raw = JSON.parse(fs.readFileSync(BASELINE_FILE, "utf8"));
    if (typeof raw.count === "number") baseline = raw.count;
  } catch { /* first run */ }

  if (unclassified.length > baseline) {
    console.error(
      `\n${unclassified.length} unclassified edge functions — baseline is ${baseline}.\n` +
        `Add each new function to supabase/functions/_manifest.ts with an explicit\n` +
        `auth mode + rateLimit flag + reason. The ratchet never moves backwards.`,
    );
    process.exit(3);
  }

  if (unclassified.length < baseline) {
    fs.writeFileSync(
      BASELINE_FILE,
      JSON.stringify({ count: unclassified.length, updatedAt: new Date().toISOString() }, null, 2) + "\n",
      "utf8",
    );
    console.log(`Ratchet: unclassified count decreased from ${baseline} to ${unclassified.length}. Baseline updated.`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
