import type { DocumentTemplate } from "../types";

export const frPVAGO: DocumentTemplate = {
  id: "fr-pv-ago",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "pv-ago",
  label: "PV d'Assemblée Générale Ordinaire",
  description: "Procès-verbal d'assemblée générale ordinaire annuelle.",
  legalBasis: "Code de commerce, art. L225-100 et suivants",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "companyName", label: "Dénomination sociale", type: "text", required: true },
    { key: "companyForm", label: "Forme juridique", type: "select", required: true, options: [
      { value: "SAS", label: "SAS" }, { value: "SARL", label: "SARL" }, { value: "SCI", label: "SCI" },
    ] },
    { key: "registeredOffice", label: "Siège social", type: "text", required: true },
    { key: "siret", label: "SIRET", type: "text", required: true },
    { key: "capital", label: "Capital social (€)", type: "number", required: true, validation: { min: 1 } },
    { key: "meetingDate", label: "Date de l'assemblée", type: "date", required: true },
    { key: "meetingPlace", label: "Lieu de l'assemblée", type: "text", required: true },
    { key: "presidentName", label: "Président de séance", type: "text", required: true },
    { key: "attendees", label: "Associés présents", type: "textarea", required: true, placeholder: "M. Dupont (500 parts)\nMme Martin (300 parts)" },
    { key: "agenda", label: "Ordre du jour", type: "textarea", required: true, placeholder: "1. Approbation des comptes\n2. Affectation du résultat\n3. Questions diverses" },
    { key: "resolutions", label: "Résolutions votées", type: "textarea", required: true },
  ],
  clauses: [
    { id: "header", label: "En-tête", required: true, text: "PROCÈS-VERBAL DE L'ASSEMBLÉE GÉNÉRALE ORDINAIRE\n\n{companyName} — {companyForm}\nCapital : {capital} €\nSiège : {registeredOffice}\nSIRET : {siret}\n\nRéunie le {meetingDate} à {meetingPlace}" },
    { id: "attendance", label: "Feuille de présence", required: true, text: "Associés présents ou représentés :\n{attendees}\n\nLa présidence de séance est assurée par {presidentName}." },
    { id: "agenda-clause", label: "Ordre du jour", required: true, text: "Ordre du jour :\n{agenda}" },
    { id: "resolutions-clause", label: "Résolutions", required: true, text: "Résolutions :\n{resolutions}" },
  ],
};

export const frAccountsApproval: DocumentTemplate = {
  id: "fr-accounts-approval",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "accounts-approval",
  label: "Approbation des comptes annuels",
  description: "PV d'approbation des comptes et affectation du résultat.",
  legalBasis: "Code de commerce, art. L232-1",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "companyName", label: "Dénomination sociale", type: "text", required: true },
    { key: "companyForm", label: "Forme juridique", type: "select", required: true, options: [
      { value: "SAS", label: "SAS" }, { value: "SARL", label: "SARL" }, { value: "SCI", label: "SCI" },
    ] },
    { key: "siret", label: "SIRET", type: "text", required: true },
    { key: "registeredOffice", label: "Siège social", type: "text", required: true },
    { key: "fiscalYear", label: "Exercice clos le", type: "date", required: true },
    { key: "revenue", label: "Chiffre d'affaires (€)", type: "number", required: true },
    { key: "netResult", label: "Résultat net (€)", type: "number", required: true },
    { key: "resultAllocation", label: "Affectation du résultat", type: "select", required: true, options: [
      { value: "report", label: "Report à nouveau" },
      { value: "dividends", label: "Distribution de dividendes" },
      { value: "reserves", label: "Mise en réserves" },
    ] },
    { key: "meetingDate", label: "Date de l'assemblée", type: "date", required: true },
    { key: "presidentName", label: "Président de séance", type: "text", required: true },
  ],
  clauses: [
    { id: "approval", label: "Approbation", required: true, text: "L'assemblée approuve les comptes de l'exercice clos le {fiscalYear} présentant un chiffre d'affaires de {revenue} € et un résultat net de {netResult} €." },
    { id: "allocation", label: "Affectation", required: true, text: "L'assemblée décide d'affecter le résultat de {netResult} € en {resultAllocation}." },
    { id: "quitus", label: "Quitus", required: true, text: "L'assemblée donne quitus à {presidentName} de sa gestion au titre de l'exercice écoulé." },
  ],
};

export const frShareTransfer: DocumentTemplate = {
  id: "fr-share-transfer",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "share-transfer",
  label: "Cession de parts sociales",
  description: "Acte de cession de parts sociales entre associés ou à un tiers.",
  legalBasis: "Code de commerce ; Code civil, art. 1589 et suivants",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "companyName", label: "Dénomination sociale", type: "text", required: true },
    { key: "companyForm", label: "Forme juridique", type: "select", required: true, options: [
      { value: "SAS", label: "SAS" }, { value: "SARL", label: "SARL" }, { value: "SCI", label: "SCI" },
    ] },
    { key: "siret", label: "SIRET", type: "text", required: true },
    { key: "capital", label: "Capital social (€)", type: "number", required: true },
    { key: "sellerName", label: "Cédant (nom)", type: "text", required: true },
    { key: "sellerAddress", label: "Adresse du cédant", type: "text", required: true },
    { key: "buyerName", label: "Cessionnaire (nom)", type: "text", required: true },
    { key: "buyerAddress", label: "Adresse du cessionnaire", type: "text", required: true },
    { key: "sharesCount", label: "Nombre de parts cédées", type: "number", required: true, validation: { min: 1 } },
    { key: "sharePrice", label: "Prix de cession par part (€)", type: "number", required: true, validation: { min: 0 } },
    { key: "transferDate", label: "Date de cession", type: "date", required: true },
  ],
  clauses: [
    { id: "transfer", label: "Cession", required: true, text: "ACTE DE CESSION DE PARTS SOCIALES\n\n{companyName} — {companyForm}\nCapital : {capital} €\nSIRET : {siret}\n\n{sellerName}, demeurant au {sellerAddress} (ci-après le « Cédant »), cède à {buyerName}, demeurant au {buyerAddress} (ci-après le « Cessionnaire »), {sharesCount} parts sociales au prix unitaire de {sharePrice} €, soit un prix total de cession à calculer.\n\nDate d'effet : {transferDate}" },
    { id: "conditions", label: "Conditions", required: true, text: "Le cessionnaire déclare avoir pris connaissance des statuts de la société et s'engage à en respecter toutes les dispositions. La cession sera opposable à la société après dépôt au greffe." },
  ],
};

export const frCapitalIncrease: DocumentTemplate = {
  id: "fr-capital-increase",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "capital-increase",
  label: "Augmentation de capital",
  description: "PV de décision d'augmentation du capital social.",
  legalBasis: "Code de commerce",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "companyName", label: "Dénomination sociale", type: "text", required: true },
    { key: "companyForm", label: "Forme juridique", type: "select", required: true, options: [
      { value: "SAS", label: "SAS" }, { value: "SARL", label: "SARL" }, { value: "SCI", label: "SCI" },
    ] },
    { key: "siret", label: "SIRET", type: "text", required: true },
    { key: "currentCapital", label: "Capital actuel (€)", type: "number", required: true, validation: { min: 1 } },
    { key: "increaseAmount", label: "Montant de l'augmentation (€)", type: "number", required: true, validation: { min: 1 } },
    { key: "method", label: "Modalité", type: "select", required: true, options: [
      { value: "numeraire", label: "Apport en numéraire" },
      { value: "nature", label: "Apport en nature" },
      { value: "incorporation", label: "Incorporation de réserves" },
    ] },
    { key: "decisionDate", label: "Date de la décision", type: "date", required: true },
    { key: "presidentName", label: "Président de séance", type: "text", required: true },
  ],
  clauses: [
    { id: "resolution", label: "Résolution", required: true, text: "L'assemblée des associés de {companyName} ({companyForm}), SIRET {siret}, décide d'augmenter le capital social de {increaseAmount} €, le portant de {currentCapital} € à un nouveau montant.\n\nModalité : {method}\n\nLes statuts sont modifiés en conséquence." },
  ],
};

export const frDissolution: DocumentTemplate = {
  id: "fr-dissolution",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "dissolution",
  label: "Dissolution amiable",
  description: "PV de décision de dissolution anticipée amiable de la société.",
  legalBasis: "Code de commerce ; Code civil, art. 1844-7",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "companyName", label: "Dénomination sociale", type: "text", required: true },
    { key: "companyForm", label: "Forme juridique", type: "select", required: true, options: [
      { value: "SAS", label: "SAS" }, { value: "SARL", label: "SARL" }, { value: "SCI", label: "SCI" },
    ] },
    { key: "siret", label: "SIRET", type: "text", required: true },
    { key: "registeredOffice", label: "Siège social", type: "text", required: true },
    { key: "capital", label: "Capital social (€)", type: "number", required: true },
    { key: "dissolutionDate", label: "Date de dissolution", type: "date", required: true },
    { key: "liquidatorName", label: "Nom du liquidateur", type: "text", required: true },
    { key: "liquidatorAddress", label: "Adresse du liquidateur", type: "text", required: true },
    { key: "decisionDate", label: "Date de la décision", type: "date", required: true },
  ],
  clauses: [
    { id: "dissolution", label: "Dissolution", required: true, text: "L'assemblée des associés de {companyName} ({companyForm}), SIRET {siret}, au capital de {capital} €, siège au {registeredOffice}, décide la dissolution anticipée amiable de la société à compter du {dissolutionDate}." },
    { id: "liquidator", label: "Liquidateur", required: true, text: "Est nommé(e) liquidateur amiable : {liquidatorName}, demeurant au {liquidatorAddress}.\n\nLe liquidateur disposera des pouvoirs les plus étendus pour réaliser les opérations de liquidation, conformément aux statuts et à la loi." },
    { id: "publication", label: "Publicité", required: true, text: "La publication de la dissolution sera effectuée dans un journal d'annonces légales du département du siège social et le dossier sera déposé au greffe du tribunal de commerce compétent." },
  ],
};

// ——— NEW TEMPLATES ———

export const frPVAGE: DocumentTemplate = {
  id: "fr-pv-age",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "pv-age",
  label: "PV d'Assemblée Générale Extraordinaire",
  description: "Procès-verbal d'assemblée générale extraordinaire pour modification des statuts.",
  legalBasis: "Code de commerce, art. L225-96 et suivants",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "companyName", label: "Dénomination sociale", type: "text", required: true },
    { key: "companyForm", label: "Forme juridique", type: "select", required: true, options: [
      { value: "SAS", label: "SAS" }, { value: "SARL", label: "SARL" }, { value: "SCI", label: "SCI" },
    ] },
    { key: "registeredOffice", label: "Siège social", type: "text", required: true },
    { key: "siret", label: "SIRET", type: "text", required: true },
    { key: "capital", label: "Capital social (€)", type: "number", required: true, validation: { min: 1 } },
    { key: "meetingDate", label: "Date de l'assemblée", type: "date", required: true },
    { key: "meetingPlace", label: "Lieu de l'assemblée", type: "text", required: true },
    { key: "presidentName", label: "Président de séance", type: "text", required: true },
    { key: "secretaryName", label: "Secrétaire de séance", type: "text", required: false },
    { key: "attendees", label: "Associés présents / représentés", type: "textarea", required: true, placeholder: "M. Dupont (500 parts)\nMme Martin (300 parts)" },
    { key: "totalShares", label: "Nombre total de parts représentées", type: "number", required: true, validation: { min: 1 } },
    { key: "quorumPercent", label: "Quorum atteint (%)", type: "number", required: true, validation: { min: 0, max: 100 } },
    { key: "agenda", label: "Ordre du jour", type: "textarea", required: true, placeholder: "1. Modification de l'objet social\n2. Transfert de siège social\n3. Pouvoirs" },
    { key: "resolutions", label: "Résolutions votées", type: "textarea", required: true, placeholder: "Première résolution : …\nDeuxième résolution : …" },
    { key: "majorityDetails", label: "Conditions de majorité", type: "text", required: false, placeholder: "Majorité des 2/3 des voix" },
  ],
  clauses: [
    { id: "header", label: "En-tête", required: true, text: "PROCÈS-VERBAL DE L'ASSEMBLÉE GÉNÉRALE EXTRAORDINAIRE\n\n{companyName} — {companyForm}\nCapital : {capital} €\nSiège : {registeredOffice}\nSIRET : {siret}\n\nRéunie le {meetingDate} à {meetingPlace}" },
    { id: "attendance", label: "Feuille de présence", required: true, text: "Associés présents ou représentés :\n{attendees}\n\nNombre total de parts représentées : {totalShares}\nQuorum : {quorumPercent} %\n\nLa présidence de séance est assurée par {presidentName}." },
    { id: "secretary", label: "Secrétaire", required: false, text: "Le secrétaire de séance désigné est {secretaryName}.", conditional: (d) => !!d.secretaryName },
    { id: "agenda-clause", label: "Ordre du jour", required: true, text: "Ordre du jour :\n{agenda}" },
    { id: "resolutions-clause", label: "Résolutions", required: true, text: "L'assemblée, statuant aux conditions de majorité requises pour les décisions extraordinaires, adopte les résolutions suivantes :\n\n{resolutions}" },
    { id: "majority", label: "Majorité", required: false, text: "Conditions de majorité appliquées : {majorityDetails}.", conditional: (d) => !!d.majorityDetails },
    { id: "powers", label: "Pouvoirs", required: true, text: "Tous pouvoirs sont conférés au porteur d'un original ou d'une copie des présentes pour accomplir toutes formalités de publicité et de dépôt." },
  ],
};

export const frActeCession: DocumentTemplate = {
  id: "fr-acte-cession",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "acte-cession",
  label: "Acte de cession de parts sociales",
  description: "Acte de cession de parts sociales complet avec agrément, garanties et formalités.",
  legalBasis: "Code de commerce, art. L221-13 (SARL) ; Code civil, art. 1589 et suivants",
  needsLegalReview: true,
  active: true,
  fields: [
    { key: "companyName", label: "Dénomination sociale", type: "text", required: true },
    { key: "companyForm", label: "Forme juridique", type: "select", required: true, options: [
      { value: "SAS", label: "SAS" }, { value: "SARL", label: "SARL" }, { value: "SCI", label: "SCI" },
    ] },
    { key: "siret", label: "SIRET", type: "text", required: true },
    { key: "rcs", label: "RCS (ville)", type: "text", required: true, placeholder: "Paris" },
    { key: "capital", label: "Capital social (€)", type: "number", required: true, validation: { min: 1 } },
    { key: "totalShares", label: "Nombre total de parts", type: "number", required: true, validation: { min: 1 } },
    { key: "shareNominalValue", label: "Valeur nominale d'une part (€)", type: "number", required: true, validation: { min: 0.01 } },
    { key: "sellerCivility", label: "Civilité du cédant", type: "select", required: true, options: [
      { value: "M.", label: "Monsieur" }, { value: "Mme", label: "Madame" },
    ] },
    { key: "sellerName", label: "Nom et prénom du cédant", type: "text", required: true },
    { key: "sellerBirthDate", label: "Date de naissance du cédant", type: "date", required: true },
    { key: "sellerBirthPlace", label: "Lieu de naissance du cédant", type: "text", required: true },
    { key: "sellerAddress", label: "Adresse du cédant", type: "text", required: true },
    { key: "sellerSharesBefore", label: "Parts détenues par le cédant avant cession", type: "number", required: true, validation: { min: 1 } },
    { key: "buyerCivility", label: "Civilité du cessionnaire", type: "select", required: true, options: [
      { value: "M.", label: "Monsieur" }, { value: "Mme", label: "Madame" },
    ] },
    { key: "buyerName", label: "Nom et prénom du cessionnaire", type: "text", required: true },
    { key: "buyerBirthDate", label: "Date de naissance du cessionnaire", type: "date", required: true },
    { key: "buyerBirthPlace", label: "Lieu de naissance du cessionnaire", type: "text", required: true },
    { key: "buyerAddress", label: "Adresse du cessionnaire", type: "text", required: true },
    { key: "sharesCount", label: "Nombre de parts cédées", type: "number", required: true, validation: { min: 1 } },
    { key: "sharePrice", label: "Prix unitaire de cession (€)", type: "number", required: true, validation: { min: 0.01 } },
    { key: "transferDate", label: "Date d'effet de la cession", type: "date", required: true },
    { key: "approvalDate", label: "Date de l'agrément", type: "date", required: false },
    { key: "approvalDetails", label: "Détails de l'agrément", type: "textarea", required: false, placeholder: "Agréé par décision collective des associés du …" },
    { key: "paymentMethod", label: "Mode de paiement", type: "select", required: true, options: [
      { value: "virement", label: "Virement bancaire" }, { value: "cheque", label: "Chèque" }, { value: "especes", label: "Espèces" },
    ] },
  ],
  clauses: [
    { id: "parties", label: "Les parties", required: true, text: "ACTE DE CESSION DE PARTS SOCIALES\n\nENTRE :\n\n{sellerCivility} {sellerName}, né(e) le {sellerBirthDate} à {sellerBirthPlace}, demeurant au {sellerAddress}, ci-après dénommé(e) le « Cédant »,\n\nET :\n\n{buyerCivility} {buyerName}, né(e) le {buyerBirthDate} à {buyerBirthPlace}, demeurant au {buyerAddress}, ci-après dénommé(e) le « Cessionnaire »." },
    { id: "company-info", label: "La société", required: true, text: "IL A ÉTÉ PRÉALABLEMENT EXPOSÉ :\n\n{companyName}, {companyForm} au capital de {capital} €, divisé en {totalShares} parts sociales de {shareNominalValue} € chacune, immatriculée au RCS de {rcs} sous le numéro SIRET {siret}.\n\nLe Cédant détient actuellement {sellerSharesBefore} parts sociales de ladite société." },
    { id: "approval", label: "Agrément", required: false, text: "AGRÉMENT :\n\nLa cession a été agréée le {approvalDate}.\n{approvalDetails}", conditional: (d) => !!d.approvalDate },
    { id: "transfer", label: "Cession", required: true, text: "CELA EXPOSÉ, IL A ÉTÉ CONVENU CE QUI SUIT :\n\nLe Cédant cède au Cessionnaire, qui accepte, {sharesCount} parts sociales de la société {companyName} au prix unitaire de {sharePrice} €.\n\nPrix total de la cession : à calculer ({sharesCount} × {sharePrice} €).\n\nMode de paiement : {paymentMethod}.\n\nDate d'effet : {transferDate}." },
    { id: "warranties", label: "Garanties", required: true, text: "DÉCLARATIONS ET GARANTIES :\n\nLe Cédant déclare :\n- être propriétaire des parts cédées, libres de tout nantissement, gage ou privilège ;\n- que les parts sont entièrement libérées ;\n- qu'il n'existe aucun pacte d'associés ou convention restreignant la cessibilité desdites parts, autre que les dispositions statutaires.\n\nLe Cessionnaire déclare avoir pris connaissance des statuts de la société et des comptes des trois derniers exercices." },
    { id: "formalities", label: "Formalités", required: true, text: "FORMALITÉS :\n\nLa présente cession sera :\n1. Signifiée à la société par voie d'huissier ou acceptée par elle dans un acte authentique (art. 1690 du Code civil) ;\n2. Déposée au greffe du tribunal de commerce compétent ;\n3. Enregistrée auprès du service des impôts dans le délai d'un mois.\n\nLes droits d'enregistrement sont à la charge du Cessionnaire." },
  ],
};

export const frRapportGestion: DocumentTemplate = {
  id: "fr-rapport-gestion",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "rapport-gestion",
  label: "Rapport de gestion annuel",
  description: "Rapport de gestion du dirigeant à l'assemblée générale annuelle.",
  legalBasis: "Code de commerce, art. L232-1 ; L225-100",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "companyName", label: "Dénomination sociale", type: "text", required: true },
    { key: "companyForm", label: "Forme juridique", type: "select", required: true, options: [
      { value: "SAS", label: "SAS" }, { value: "SARL", label: "SARL" }, { value: "SCI", label: "SCI" },
    ] },
    { key: "siret", label: "SIRET", type: "text", required: true },
    { key: "registeredOffice", label: "Siège social", type: "text", required: true },
    { key: "capital", label: "Capital social (€)", type: "number", required: true },
    { key: "presidentName", label: "Dirigeant / Président", type: "text", required: true },
    { key: "fiscalYearStart", label: "Début de l'exercice", type: "date", required: true },
    { key: "fiscalYearEnd", label: "Fin de l'exercice", type: "date", required: true },
    { key: "revenue", label: "Chiffre d'affaires HT (€)", type: "number", required: true },
    { key: "previousRevenue", label: "CA exercice précédent (€)", type: "number", required: false },
    { key: "expenses", label: "Total des charges (€)", type: "number", required: true },
    { key: "netResult", label: "Résultat net (€)", type: "number", required: true },
    { key: "activitySummary", label: "Résumé de l'activité", type: "textarea", required: true, placeholder: "Décrivez les faits marquants de l'exercice…" },
    { key: "significantEvents", label: "Événements significatifs", type: "textarea", required: false, placeholder: "Investissements, embauches, contrats importants…" },
    { key: "outlook", label: "Perspectives", type: "textarea", required: true, placeholder: "Orientations et projets pour l'exercice à venir…" },
    { key: "resultAllocation", label: "Affectation du résultat proposée", type: "select", required: true, options: [
      { value: "report", label: "Report à nouveau" },
      { value: "dividends", label: "Distribution de dividendes" },
      { value: "reserves", label: "Mise en réserves" },
      { value: "mixed", label: "Mixte (réserves + dividendes)" },
    ] },
    { key: "dividendAmount", label: "Montant des dividendes (€)", type: "number", required: false, validation: { min: 0 } },
    { key: "employeeCount", label: "Effectif moyen", type: "number", required: false },
  ],
  clauses: [
    { id: "header", label: "En-tête", required: true, text: "RAPPORT DE GESTION\nExercice du {fiscalYearStart} au {fiscalYearEnd}\n\n{companyName} — {companyForm}\nCapital : {capital} €\nSiège : {registeredOffice}\nSIRET : {siret}\n\nPrésenté par {presidentName}, en sa qualité de dirigeant." },
    { id: "activity", label: "Activité de l'exercice", required: true, text: "I. ACTIVITÉ DE L'EXERCICE\n\n{activitySummary}" },
    { id: "events", label: "Événements significatifs", required: false, text: "II. ÉVÉNEMENTS SIGNIFICATIFS\n\n{significantEvents}", conditional: (d) => !!d.significantEvents },
    { id: "financials", label: "Résultats financiers", required: true, text: "III. RÉSULTATS FINANCIERS\n\nChiffre d'affaires HT : {revenue} €\nTotal des charges : {expenses} €\nRésultat net : {netResult} €" },
    { id: "comparison", label: "Comparaison N-1", required: false, text: "Le chiffre d'affaires de l'exercice précédent s'élevait à {previousRevenue} €.", conditional: (d) => !!d.previousRevenue },
    { id: "employees", label: "Effectifs", required: false, text: "L'effectif moyen au cours de l'exercice s'est établi à {employeeCount} salarié(s).", conditional: (d) => !!d.employeeCount },
    { id: "allocation", label: "Affectation du résultat", required: true, text: "IV. AFFECTATION DU RÉSULTAT\n\nNous vous proposons d'affecter le résultat net de {netResult} € en : {resultAllocation}." },
    { id: "dividends", label: "Dividendes", required: false, text: "Le montant des dividendes proposé s'élève à {dividendAmount} €.", conditional: (d) => !!d.dividendAmount && Number(d.dividendAmount) > 0 },
    { id: "outlook-clause", label: "Perspectives", required: true, text: "V. PERSPECTIVES\n\n{outlook}" },
    { id: "conclusion", label: "Conclusion", required: true, text: "VI. CONCLUSION\n\nNous vous demandons de bien vouloir approuver les comptes de l'exercice clos le {fiscalYearEnd} tels qu'ils vous sont présentés, et de donner quitus au dirigeant de sa gestion." },
  ],
};