import type { DocumentTemplate } from "../types";

export const frCompanySAS: DocumentTemplate = {
  id: "fr-company-sas",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "company-sas",
  label: "Création SAS — Projet de statuts",
  description: "Projet de statuts pour une Société par Actions Simplifiée (SAS).",
  legalBasis: "Code de commerce, art. L227-1 et suivants",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "companyName", label: "Dénomination sociale", type: "text", required: true },
    { key: "companyObject", label: "Objet social", type: "textarea", required: true, validation: { minLength: 10, maxLength: 2000 } },
    { key: "registeredOffice", label: "Siège social", type: "text", required: true },
    { key: "capital", label: "Capital social (€)", type: "number", required: true, validation: { min: 1 } },
    { key: "presidentName", label: "Nom du Président", type: "text", required: true },
    { key: "presidentAddress", label: "Adresse du Président", type: "text", required: true },
    { key: "presidentBirthDate", label: "Date de naissance du Président", type: "date", required: true },
    { key: "presidentBirthPlace", label: "Lieu de naissance du Président", type: "text", required: true },
    { key: "presidentNationality", label: "Nationalité du Président", type: "text", required: true, defaultValue: "Française" },
    { key: "duration", label: "Durée (années)", type: "number", required: true, validation: { min: 1, max: 99 }, defaultValue: 99 },
    { key: "fiscalYearEnd", label: "Clôture exercice (JJ/MM)", type: "text", required: true, defaultValue: "31/12" },
    { key: "sharesCount", label: "Nombre d'actions", type: "number", required: true, validation: { min: 1 } },
  ],
  clauses: [
    { id: "form", label: "Article 1 — Forme", required: true, text: "Il est constitué une Société par Actions Simplifiée (SAS) régie par les articles L227-1 et suivants du Code de commerce et les présents statuts." },
    { id: "name", label: "Article 2 — Dénomination", required: true, text: "La société prend la dénomination : {companyName}.\n\nDans tous les actes et documents émanant de la société, la dénomination sociale doit être précédée ou suivie des mots « Société par Actions Simplifiée » ou des initiales « SAS » et de l'énonciation du capital social." },
    { id: "object", label: "Article 3 — Objet", required: true, text: "La société a pour objet, en France et à l'étranger :\n\n{companyObject}\n\nEt plus généralement, toutes opérations industrielles, commerciales, financières, civiles, mobilières ou immobilières, pouvant se rattacher directement ou indirectement à l'objet social." },
    { id: "office", label: "Article 4 — Siège social", required: true, text: "Le siège social est fixé au {registeredOffice}.\n\nIl pourra être transféré en tout autre endroit par décision du Président, sous réserve de ratification par la collectivité des associés." },
    { id: "duration-clause", label: "Article 5 — Durée", required: true, text: "La durée de la société est fixée à {duration} ans à compter de son immatriculation au Registre du Commerce et des Sociétés, sauf dissolution anticipée ou prorogation." },
    { id: "capital-clause", label: "Article 6 — Capital social", required: true, text: "Le capital social est fixé à {capital} €, divisé en {sharesCount} actions de valeur nominale égale, entièrement libérées et de même catégorie." },
    { id: "president", label: "Article 7 — Président", required: true, text: "Est nommé(e) premier(ère) Président(e) de la société :\n\n{presidentName}\nNé(e) le {presidentBirthDate} à {presidentBirthPlace}\nNationalité : {presidentNationality}\nDemeurant au {presidentAddress}\n\nLe Président est nommé pour une durée indéterminée. Il représente la société à l'égard des tiers." },
    { id: "decisions", label: "Article 8 — Décisions collectives", required: true, text: "Les décisions collectives des associés sont prises en assemblée générale ou par consultation écrite. Chaque action donne droit à une voix." },
    { id: "fiscal-year", label: "Article 9 — Exercice social", required: true, text: "L'exercice social commence le 1er janvier et se termine le {fiscalYearEnd} de chaque année." },
    { id: "dissolution-clause", label: "Article 10 — Dissolution", required: true, text: "La société sera dissoute à l'expiration de sa durée, sauf prorogation, ou par décision de l'assemblée des associés statuant dans les conditions prévues par la loi." },
  ],
};

export const frCompanySARL: DocumentTemplate = {
  id: "fr-company-sarl",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "company-sarl",
  label: "Création SARL — Projet de statuts",
  description: "Projet de statuts pour une Société à Responsabilité Limitée (SARL).",
  legalBasis: "Code de commerce, art. L223-1 et suivants",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "companyName", label: "Dénomination sociale", type: "text", required: true },
    { key: "companyObject", label: "Objet social", type: "textarea", required: true, validation: { minLength: 10 } },
    { key: "registeredOffice", label: "Siège social", type: "text", required: true },
    { key: "capital", label: "Capital social (€)", type: "number", required: true, validation: { min: 1 } },
    { key: "managerName", label: "Nom du Gérant", type: "text", required: true },
    { key: "managerAddress", label: "Adresse du Gérant", type: "text", required: true },
    { key: "managerBirthDate", label: "Date de naissance du Gérant", type: "date", required: true },
    { key: "managerBirthPlace", label: "Lieu de naissance du Gérant", type: "text", required: true },
    { key: "managerNationality", label: "Nationalité du Gérant", type: "text", required: true, defaultValue: "Française" },
    { key: "duration", label: "Durée (années)", type: "number", required: true, validation: { min: 1, max: 99 }, defaultValue: 99 },
    { key: "associatesCount", label: "Nombre d'associés", type: "number", required: true, validation: { min: 1, max: 100 } },
    { key: "sharesCount", label: "Nombre de parts sociales", type: "number", required: true, validation: { min: 1 } },
    { key: "fiscalYearEnd", label: "Clôture exercice (JJ/MM)", type: "text", required: true, defaultValue: "31/12" },
  ],
  clauses: [
    { id: "form", label: "Article 1 — Forme", required: true, text: "Il est constitué une Société à Responsabilité Limitée (SARL) régie par les articles L223-1 et suivants du Code de commerce et les présents statuts." },
    { id: "name", label: "Article 2 — Dénomination", required: true, text: "La société prend la dénomination : {companyName}.\n\nDans tous les actes, la dénomination sociale doit être précédée ou suivie des mots « Société à Responsabilité Limitée » ou des initiales « SARL » et de l'énonciation du capital social." },
    { id: "object", label: "Article 3 — Objet", required: true, text: "La société a pour objet :\n\n{companyObject}\n\nEt plus généralement, toutes opérations pouvant se rattacher directement ou indirectement à l'objet social." },
    { id: "office", label: "Article 4 — Siège", required: true, text: "Le siège social est fixé au {registeredOffice}." },
    { id: "capital-clause", label: "Article 5 — Capital", required: true, text: "Le capital social est fixé à {capital} €, divisé en {sharesCount} parts sociales de valeur nominale égale, réparties entre {associatesCount} associé(s)." },
    { id: "manager", label: "Article 6 — Gérance", required: true, text: "Est nommé(e) premier(ère) Gérant(e) :\n\n{managerName}\nNé(e) le {managerBirthDate} à {managerBirthPlace}\nNationalité : {managerNationality}\nDemeurant au {managerAddress}\n\nLe Gérant est nommé pour une durée indéterminée." },
    { id: "decisions", label: "Article 7 — Décisions collectives", required: true, text: "Les décisions collectives sont prises en assemblée générale. Chaque part donne droit à une voix." },
    { id: "fiscal-year", label: "Article 8 — Exercice social", required: true, text: "L'exercice social commence le 1er janvier et se termine le {fiscalYearEnd} de chaque année." },
  ],
};

export const frCompanyEURL: DocumentTemplate = {
  id: "fr-company-eurl",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "company-eurl",
  label: "Création EURL — Projet de statuts",
  description: "Projet de statuts pour une Entreprise Unipersonnelle à Responsabilité Limitée (EURL).",
  legalBasis: "Code de commerce, art. L223-1 et suivants",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "companyName", label: "Dénomination sociale", type: "text", required: true },
    { key: "companyObject", label: "Objet social", type: "textarea", required: true, validation: { minLength: 10 } },
    { key: "registeredOffice", label: "Siège social", type: "text", required: true },
    { key: "capital", label: "Capital social (€)", type: "number", required: true, validation: { min: 1 } },
    { key: "associateName", label: "Nom de l'associé unique", type: "text", required: true },
    { key: "associateAddress", label: "Adresse de l'associé unique", type: "text", required: true },
    { key: "associateBirthDate", label: "Date de naissance", type: "date", required: true },
    { key: "associateBirthPlace", label: "Lieu de naissance", type: "text", required: true },
    { key: "associateNationality", label: "Nationalité", type: "text", required: true, defaultValue: "Française" },
    { key: "isManagerAssociate", label: "L'associé est-il gérant ?", type: "select", required: true, options: [
      { value: "oui", label: "Oui" },
      { value: "non", label: "Non — Gérant tiers" },
    ] },
    { key: "managerName", label: "Nom du Gérant (si tiers)", type: "text", required: false },
    { key: "managerAddress", label: "Adresse du Gérant (si tiers)", type: "text", required: false },
    { key: "duration", label: "Durée (années)", type: "number", required: true, validation: { min: 1, max: 99 }, defaultValue: 99 },
    { key: "sharesCount", label: "Nombre de parts sociales", type: "number", required: true, validation: { min: 1 } },
    { key: "fiscalYearEnd", label: "Clôture exercice (JJ/MM)", type: "text", required: true, defaultValue: "31/12" },
  ],
  clauses: [
    { id: "form", label: "Article 1 — Forme", required: true, text: "Il est constitué une Entreprise Unipersonnelle à Responsabilité Limitée (EURL), société à responsabilité limitée à associé unique, régie par les articles L223-1 et suivants du Code de commerce." },
    { id: "name", label: "Article 2 — Dénomination", required: true, text: "La société prend la dénomination : {companyName}." },
    { id: "object", label: "Article 3 — Objet", required: true, text: "La société a pour objet :\n\n{companyObject}\n\nEt plus généralement, toutes opérations pouvant se rattacher directement ou indirectement à l'objet social." },
    { id: "office", label: "Article 4 — Siège social", required: true, text: "Le siège social est fixé au {registeredOffice}." },
    { id: "duration-clause", label: "Article 5 — Durée", required: true, text: "La durée de la société est fixée à {duration} ans à compter de son immatriculation au Registre du Commerce et des Sociétés." },
    { id: "capital-clause", label: "Article 6 — Capital social", required: true, text: "Le capital social est fixé à {capital} €, divisé en {sharesCount} parts sociales de valeur nominale égale, toutes souscrites et entièrement libérées par l'associé unique." },
    { id: "associate", label: "Article 7 — Associé unique", required: true, text: "L'associé unique est :\n\n{associateName}\nNé(e) le {associateBirthDate} à {associateBirthPlace}\nNationalité : {associateNationality}\nDemeurant au {associateAddress}\n\nL'associé unique détient l'intégralité des {sharesCount} parts sociales." },
    { id: "manager", label: "Article 8 — Gérance", required: true, text: "Le Gérant de la société est l'associé unique lui-même, sauf disposition contraire.\n\nLe Gérant représente la société à l'égard des tiers et est investi des pouvoirs les plus étendus pour agir en toute circonstance au nom de la société." },
    { id: "decisions", label: "Article 9 — Décisions de l'associé unique", required: true, text: "L'associé unique exerce les pouvoirs dévolus à l'assemblée des associés. Ses décisions sont consignées dans un registre." },
    { id: "fiscal-year", label: "Article 10 — Exercice social", required: true, text: "L'exercice social commence le 1er janvier et se termine le {fiscalYearEnd} de chaque année." },
  ],
};

export const frMicroEntrepreneur: DocumentTemplate = {
  id: "fr-micro-entrepreneur",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "micro-entrepreneur",
  label: "Micro-entrepreneur — Déclaration d'activité",
  description: "Guide complet et checklist pour la déclaration d'activité en micro-entreprise.",
  legalBasis: "Code de commerce ; Code général des impôts, art. 293 B",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "fullName", label: "Nom complet", type: "text", required: true },
    { key: "address", label: "Adresse du domicile / siège", type: "text", required: true },
    { key: "birthDate", label: "Date de naissance", type: "date", required: true },
    { key: "birthPlace", label: "Lieu de naissance", type: "text", required: true },
    { key: "nationality", label: "Nationalité", type: "text", required: true, defaultValue: "Française" },
    { key: "activity", label: "Description de l'activité", type: "textarea", required: true },
    { key: "activityCategory", label: "Catégorie d'activité", type: "select", required: true, options: [
      { value: "commerciale", label: "Commerciale (BIC)" },
      { value: "artisanale", label: "Artisanale (BIC)" },
      { value: "liberale", label: "Libérale (BNC)" },
    ] },
    { key: "startDate", label: "Date de début d'activité", type: "date", required: true },
    { key: "versementLiberatoire", label: "Versement libératoire", type: "select", required: true, options: [
      { value: "oui", label: "Oui — Versement libératoire de l'IR" },
      { value: "non", label: "Non — Régime classique" },
    ] },
    { key: "acreEligible", label: "Éligible à l'ACRE ?", type: "select", required: true, options: [
      { value: "oui", label: "Oui" },
      { value: "non", label: "Non" },
      { value: "ne-sais-pas", label: "Je ne sais pas" },
    ] },
  ],
  clauses: [
    { id: "identity", label: "Identité", required: true, text: "DÉCLARATION DE DÉBUT D'ACTIVITÉ — MICRO-ENTREPRENEUR\n\nNom : {fullName}\nNé(e) le {birthDate} à {birthPlace}\nNationalité : {nationality}\nAdresse : {address}" },
    { id: "activity-clause", label: "Activité", required: true, text: "Activité exercée : {activity}\nCatégorie : {activityCategory}\nDate de début : {startDate}" },
    { id: "fiscal", label: "Options fiscales", required: true, text: "Versement libératoire de l'impôt sur le revenu : {versementLiberatoire}\nDemande ACRE : {acreEligible}" },
    { id: "checklist", label: "Checklist de création", required: true, text: "✅ CHECKLIST DE CRÉATION\n\n1. Inscription sur le guichet unique (formalites.entreprises.gouv.fr)\n2. Pièce d'identité en cours de validité\n3. Justificatif de domicile de moins de 3 mois\n4. Déclaration de non-condamnation et de filiation\n5. Choix du régime fiscal (versement libératoire ou non)\n6. Demande ACRE si éligible\n7. Ouverture d'un compte bancaire dédié (obligatoire si CA > 10 000 €/an pendant 2 ans)\n8. Souscription assurance RC Pro si nécessaire\n9. Déclaration de chiffre d'affaires (mensuelle ou trimestrielle)\n10. Affiliation à l'URSSAF pour les cotisations sociales" },
  ],
};

// ── Annonce légale de constitution ──

export const frLegalNotice: DocumentTemplate = {
  id: "fr-legal-notice",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "legal-notice",
  label: "Annonce légale de constitution",
  description: "Avis de constitution à publier dans un journal d'annonces légales (JAL).",
  legalBasis: "Code de commerce, art. R210-4 ; Décret 2012-928",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "companyForm", label: "Forme juridique", type: "select", required: true, options: [
      { value: "SAS", label: "SAS" },
      { value: "SARL", label: "SARL" },
      { value: "EURL", label: "EURL" },
    ] },
    { key: "companyName", label: "Dénomination sociale", type: "text", required: true },
    { key: "companyObject", label: "Objet social (résumé)", type: "textarea", required: true, validation: { minLength: 10, maxLength: 500 } },
    { key: "registeredOffice", label: "Siège social", type: "text", required: true },
    { key: "capital", label: "Capital social (€)", type: "number", required: true, validation: { min: 1 } },
    { key: "duration", label: "Durée (années)", type: "number", required: true, defaultValue: 99 },
    { key: "directorTitle", label: "Titre du dirigeant", type: "select", required: true, options: [
      { value: "Président", label: "Président (SAS)" },
      { value: "Gérant", label: "Gérant (SARL/EURL)" },
    ] },
    { key: "directorName", label: "Nom du dirigeant", type: "text", required: true },
    { key: "directorAddress", label: "Adresse du dirigeant", type: "text", required: true },
    { key: "rcsCity", label: "Ville du RCS (greffe)", type: "text", required: true, placeholder: "Paris, Lyon, Marseille…" },
    { key: "constitutionDate", label: "Date de signature des statuts", type: "date", required: true },
  ],
  clauses: [
    { id: "notice", label: "Avis de constitution", required: true, text: "AVIS DE CONSTITUTION\n\nAux termes d'un acte sous seing privé en date du {constitutionDate}, il a été constitué une société présentant les caractéristiques suivantes :\n\nForme : {companyForm}\nDénomination : {companyName}\nSiège social : {registeredOffice}\nCapital : {capital} €\nObjet : {companyObject}\nDurée : {duration} ans\n\n{directorTitle} : {directorName}, demeurant au {directorAddress}\n\nImmatriculation : la société sera immatriculée au Registre du Commerce et des Sociétés de {rcsCity}.\n\nPour avis." },
  ],
};

// ── Formulaire M0 (SAS/SARL/EURL) ──

export const frFormM0: DocumentTemplate = {
  id: "fr-form-m0",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "form-m0",
  label: "Formulaire M0 — Déclaration de création société",
  description: "Récapitulatif des informations nécessaires au formulaire M0 (Cerfa 13959) pour l'immatriculation.",
  legalBasis: "Code de commerce ; Cerfa 13959*09",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "companyForm", label: "Forme juridique", type: "select", required: true, options: [
      { value: "SAS", label: "SAS" },
      { value: "SARL", label: "SARL" },
      { value: "EURL", label: "EURL" },
    ] },
    { key: "companyName", label: "Dénomination sociale", type: "text", required: true },
    { key: "tradeName", label: "Nom commercial (si différent)", type: "text", required: false },
    { key: "companyObject", label: "Activité principale", type: "textarea", required: true },
    { key: "registeredOffice", label: "Adresse du siège social", type: "text", required: true },
    { key: "capital", label: "Capital social (€)", type: "number", required: true, validation: { min: 1 } },
    { key: "capitalType", label: "Type de capital", type: "select", required: true, options: [
      { value: "fixe", label: "Capital fixe" },
      { value: "variable", label: "Capital variable" },
    ] },
    { key: "constitutionDate", label: "Date de début d'activité", type: "date", required: true },
    { key: "fiscalYearEnd", label: "Date de clôture du 1er exercice", type: "text", required: true, defaultValue: "31/12" },
    { key: "directorName", label: "Nom du dirigeant principal", type: "text", required: true },
    { key: "directorBirthDate", label: "Date de naissance", type: "date", required: true },
    { key: "directorBirthPlace", label: "Lieu de naissance", type: "text", required: true },
    { key: "directorNationality", label: "Nationalité", type: "text", required: true, defaultValue: "Française" },
    { key: "directorAddress", label: "Adresse personnelle", type: "text", required: true },
    { key: "employeesCount", label: "Effectif salarié prévu", type: "number", required: true, defaultValue: 0, validation: { min: 0 } },
    { key: "originActivity", label: "Origine du fonds / activité", type: "select", required: true, options: [
      { value: "creation", label: "Création" },
      { value: "achat", label: "Achat" },
      { value: "apport", label: "Apport" },
      { value: "location-gerance", label: "Location-gérance" },
    ] },
  ],
  clauses: [
    { id: "recap-societe", label: "Cadre 1 — Identification de la société", required: true, text: "FORMULAIRE M0 — RÉCAPITULATIF DE DÉCLARATION\n\nForme juridique : {companyForm}\nDénomination sociale : {companyName}\nNom commercial : {tradeName}\nAdresse du siège : {registeredOffice}\n\nCapital social : {capital} € ({capitalType})\nDate de début d'activité : {constitutionDate}\nClôture du 1er exercice : {fiscalYearEnd}\nOrigine : {originActivity}" },
    { id: "recap-activite", label: "Cadre 2 — Activité", required: true, text: "Activité principale exercée :\n{companyObject}\n\nEffectif salarié prévu : {employeesCount}" },
    { id: "recap-dirigeant", label: "Cadre 3 — Dirigeant", required: true, text: "Dirigeant principal :\n\nNom : {directorName}\nNé(e) le {directorBirthDate} à {directorBirthPlace}\nNationalité : {directorNationality}\nAdresse : {directorAddress}" },
    { id: "pieces", label: "Pièces à joindre", required: true, text: "📋 PIÈCES À JOINDRE AU DOSSIER M0\n\n1. Formulaire M0 (Cerfa 13959) rempli et signé\n2. Deux exemplaires des statuts signés, paraphés et datés\n3. Attestation de dépôt des fonds (capital)\n4. Attestation de parution de l'annonce légale (JAL)\n5. Copie de la pièce d'identité du dirigeant\n6. Déclaration de non-condamnation et de filiation du dirigeant\n7. Justificatif de jouissance des locaux du siège social\n8. Si activité réglementée : autorisation ou diplôme requis" },
  ],
};

// ── Formulaire P0 (Micro-entrepreneur) ──

export const frFormP0: DocumentTemplate = {
  id: "fr-form-p0",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "form-p0",
  label: "Formulaire P0 — Déclaration micro-entrepreneur",
  description: "Récapitulatif des informations nécessaires au formulaire P0 (Cerfa 15253) pour la déclaration de micro-entreprise.",
  legalBasis: "Code de commerce ; Cerfa 15253*09",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "fullName", label: "Nom et prénom", type: "text", required: true },
    { key: "birthDate", label: "Date de naissance", type: "date", required: true },
    { key: "birthPlace", label: "Lieu de naissance", type: "text", required: true },
    { key: "nationality", label: "Nationalité", type: "text", required: true, defaultValue: "Française" },
    { key: "address", label: "Adresse du domicile", type: "text", required: true },
    { key: "businessAddress", label: "Adresse d'exercice (si différente)", type: "text", required: false },
    { key: "activity", label: "Description de l'activité", type: "textarea", required: true },
    { key: "activityCategory", label: "Catégorie", type: "select", required: true, options: [
      { value: "commerciale", label: "Commerciale (BIC)" },
      { value: "artisanale", label: "Artisanale (BIC)" },
      { value: "liberale", label: "Libérale (BNC)" },
    ] },
    { key: "startDate", label: "Date de début d'activité", type: "date", required: true },
    { key: "versementLiberatoire", label: "Option versement libératoire IR", type: "select", required: true, options: [
      { value: "oui", label: "Oui" },
      { value: "non", label: "Non" },
    ] },
    { key: "acreRequest", label: "Demande d'ACRE", type: "select", required: true, options: [
      { value: "oui", label: "Oui" },
      { value: "non", label: "Non" },
    ] },
  ],
  clauses: [
    { id: "recap-identity", label: "Cadre 1 — Identité", required: true, text: "FORMULAIRE P0 — RÉCAPITULATIF\n\nNom : {fullName}\nNé(e) le {birthDate} à {birthPlace}\nNationalité : {nationality}\nDomicile : {address}\nAdresse d'exercice : {businessAddress}" },
    { id: "recap-activity", label: "Cadre 2 — Activité", required: true, text: "Activité : {activity}\nCatégorie : {activityCategory}\nDate de début : {startDate}" },
    { id: "recap-fiscal", label: "Cadre 3 — Options fiscales et sociales", required: true, text: "Versement libératoire IR : {versementLiberatoire}\nDemande ACRE : {acreRequest}" },
    { id: "pieces-p0", label: "Pièces à joindre", required: true, text: "📋 PIÈCES À JOINDRE AU DOSSIER P0\n\n1. Formulaire P0 Micro-entrepreneur (Cerfa 15253) rempli et signé\n2. Copie de la pièce d'identité recto-verso\n3. Justificatif de domicile de moins de 3 mois\n4. Déclaration de non-condamnation et de filiation\n5. Si activité artisanale : justificatif de qualification (diplôme, CAP…)\n6. Si activité réglementée : autorisation ou diplôme requis\n7. Si demande ACRE : justificatif d'éligibilité" },
  ],
};
