import type { DocumentTemplate } from "../types";

/* ─── Statuts SAS ─── */
export const frStatutsSAS: DocumentTemplate = {
  id: "fr-statuts-sas",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "statuts-sas",
  label: "Statuts de SAS",
  description: "Modèle complet de statuts pour une Société par Actions Simplifiée.",
  legalBasis: "Code de commerce, art. L227-1 et suivants",
  needsLegalReview: true,
  active: true,
  fields: [
    { key: "companyName", label: "Dénomination sociale", type: "text", required: true, group: "Société" },
    { key: "registeredOffice", label: "Siège social", type: "text", required: true, group: "Société" },
    { key: "activity", label: "Objet social", type: "textarea", required: true, validation: { minLength: 20 }, group: "Société" },
    { key: "duration", label: "Durée (années)", type: "number", required: true, defaultValue: 99, validation: { min: 1, max: 99 }, group: "Société" },
    { key: "shareCapital", label: "Capital social (€)", type: "number", required: true, validation: { min: 1 }, group: "Capital" },
    { key: "shareValue", label: "Valeur nominale par action (€)", type: "number", required: true, validation: { min: 1 }, defaultValue: 1, group: "Capital" },
    { key: "presidentName", label: "Nom du Président", type: "text", required: true, group: "Dirigeants" },
    { key: "presidentAddress", label: "Adresse du Président", type: "text", required: true, group: "Dirigeants" },
    { key: "presidentBirthDate", label: "Date de naissance du Président", type: "date", required: true, group: "Dirigeants" },
    { key: "presidentBirthPlace", label: "Lieu de naissance du Président", type: "text", required: true, group: "Dirigeants" },
    { key: "presidentNationality", label: "Nationalité du Président", type: "text", required: true, defaultValue: "Française", group: "Dirigeants" },
    { key: "dgName", label: "Nom du Directeur Général (optionnel)", type: "text", required: false, group: "Dirigeants" },
    { key: "associatesCount", label: "Nombre d'associés", type: "number", required: true, validation: { min: 1 }, defaultValue: 1, group: "Associés" },
    { key: "associatesList", label: "Liste des associés et répartition", type: "textarea", required: true, placeholder: "M. Dupont : 500 actions (50%)\nMme Martin : 500 actions (50%)", group: "Associés" },
    { key: "fiscalYearEnd", label: "Date de clôture de l'exercice", type: "text", required: true, defaultValue: "31 décembre", placeholder: "31 décembre", group: "Société" },
    { key: "constitutionDate", label: "Date de constitution", type: "date", required: true },
  ],
  clauses: [
    { id: "titre", label: "Titre", required: true, text: "STATUTS DE LA SOCIÉTÉ {companyName}\nSociété par Actions Simplifiée au capital de {shareCapital} €\nSiège social : {registeredOffice}" },
    { id: "forme", label: "Article 1 — Forme", required: true, text: "Il est constitué entre les soussignés une Société par Actions Simplifiée (SAS) régie par les articles L. 227-1 et suivants du Code de commerce et par les présents statuts." },
    { id: "objet", label: "Article 2 — Objet", required: true, text: "La société a pour objet :\n{activity}\n\nEt plus généralement, toutes opérations industrielles, commerciales, financières, mobilières ou immobilières se rattachant directement ou indirectement à l'objet ci-dessus." },
    { id: "siege", label: "Article 3 — Siège social", required: true, text: "Le siège social est fixé au {registeredOffice}. Il pourra être transféré en tout autre lieu par décision du Président." },
    { id: "duree", label: "Article 4 — Durée", required: true, text: "La durée de la société est fixée à {duration} années à compter de son immatriculation au RCS." },
    { id: "capital", label: "Article 5 — Capital social", required: true, text: "Le capital social est fixé à {shareCapital} €, divisé en {shareCapital}/{shareValue} actions de {shareValue} € chacune, entièrement souscrites et libérées.\n\nRépartition :\n{associatesList}" },
    { id: "president", label: "Article 6 — Président", required: true, text: "Est nommé(e) en qualité de Président(e) pour une durée illimitée :\n{presidentName}, né(e) le {presidentBirthDate} à {presidentBirthPlace}, de nationalité {presidentNationality}, demeurant au {presidentAddress}.\n\nLe Président représente la société à l'égard des tiers." },
    { id: "exercice", label: "Article 7 — Exercice social", required: true, text: "L'exercice social commence le 1er janvier et se termine le {fiscalYearEnd} de chaque année." },
    { id: "decisions", label: "Article 8 — Décisions collectives", required: true, text: "Les décisions collectives des associés sont prises en assemblée générale ou par consultation écrite. Les décisions ordinaires sont adoptées à la majorité simple, les décisions extraordinaires à la majorité des 2/3." },
    { id: "cession", label: "Article 9 — Cession d'actions", required: true, text: "Les cessions d'actions entre associés sont libres. Les cessions à des tiers sont soumises à l'agrément préalable de la collectivité des associés statuant à la majorité." },
    { id: "dissolution", label: "Article 10 — Dissolution", required: true, text: "La dissolution de la société peut être décidée par la collectivité des associés statuant dans les conditions de l'article 8." },
  ],
};

/* ─── Statuts SARL ─── */
export const frStatutsSARL: DocumentTemplate = {
  id: "fr-statuts-sarl",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "statuts-sarl",
  label: "Statuts de SARL",
  description: "Modèle complet de statuts pour une Société à Responsabilité Limitée.",
  legalBasis: "Code de commerce, art. L223-1 et suivants",
  needsLegalReview: true,
  active: true,
  fields: [
    { key: "companyName", label: "Dénomination sociale", type: "text", required: true, group: "Société" },
    { key: "registeredOffice", label: "Siège social", type: "text", required: true, group: "Société" },
    { key: "activity", label: "Objet social", type: "textarea", required: true, validation: { minLength: 20 }, group: "Société" },
    { key: "duration", label: "Durée (années)", type: "number", required: true, defaultValue: 99, validation: { min: 1, max: 99 }, group: "Société" },
    { key: "shareCapital", label: "Capital social (€)", type: "number", required: true, validation: { min: 1 }, group: "Capital" },
    { key: "shareValue", label: "Valeur nominale par part (€)", type: "number", required: true, validation: { min: 1 }, defaultValue: 1, group: "Capital" },
    { key: "gerantName", label: "Nom du Gérant", type: "text", required: true, group: "Gérant" },
    { key: "gerantAddress", label: "Adresse du Gérant", type: "text", required: true, group: "Gérant" },
    { key: "gerantBirthDate", label: "Date de naissance du Gérant", type: "date", required: true, group: "Gérant" },
    { key: "gerantBirthPlace", label: "Lieu de naissance du Gérant", type: "text", required: true, group: "Gérant" },
    { key: "gerantNationality", label: "Nationalité du Gérant", type: "text", required: true, defaultValue: "Française", group: "Gérant" },
    { key: "associatesList", label: "Liste des associés et répartition", type: "textarea", required: true, placeholder: "M. Dupont : 500 parts (50%)\nMme Martin : 500 parts (50%)", group: "Associés" },
    { key: "fiscalYearEnd", label: "Date de clôture de l'exercice", type: "text", required: true, defaultValue: "31 décembre", group: "Société" },
    { key: "constitutionDate", label: "Date de constitution", type: "date", required: true },
  ],
  clauses: [
    { id: "titre", label: "Titre", required: true, text: "STATUTS DE LA SOCIÉTÉ {companyName}\nSociété à Responsabilité Limitée au capital de {shareCapital} €\nSiège social : {registeredOffice}" },
    { id: "forme", label: "Article 1 — Forme", required: true, text: "Il est constitué entre les soussignés une Société à Responsabilité Limitée (SARL) régie par les articles L. 223-1 et suivants du Code de commerce et par les présents statuts." },
    { id: "objet", label: "Article 2 — Objet", required: true, text: "La société a pour objet :\n{activity}\n\nEt plus généralement, toutes opérations se rattachant directement ou indirectement à l'objet ci-dessus." },
    { id: "siege", label: "Article 3 — Siège social", required: true, text: "Le siège social est fixé au {registeredOffice}." },
    { id: "duree", label: "Article 4 — Durée", required: true, text: "La durée de la société est fixée à {duration} années à compter de son immatriculation au RCS." },
    { id: "capital", label: "Article 5 — Capital social", required: true, text: "Le capital social est fixé à {shareCapital} €, divisé en parts sociales de {shareValue} € chacune, entièrement souscrites et libérées.\n\nRépartition :\n{associatesList}" },
    { id: "gerant", label: "Article 6 — Gérance", required: true, text: "Est nommé(e) Gérant(e) pour une durée illimitée :\n{gerantName}, né(e) le {gerantBirthDate} à {gerantBirthPlace}, de nationalité {gerantNationality}, demeurant au {gerantAddress}." },
    { id: "ago", label: "Article 7 — Assemblées", required: true, text: "Les décisions collectives ordinaires sont prises à la majorité des parts sociales. Les décisions extraordinaires modifiant les statuts sont prises à la majorité des 2/3." },
    { id: "cession", label: "Article 8 — Cession de parts", required: true, text: "Les parts sociales sont librement cessibles entre associés. Toute cession à un tiers est soumise à l'agrément de la majorité des associés représentant au moins la moitié des parts sociales." },
    { id: "exercice", label: "Article 9 — Exercice social", required: true, text: "L'exercice social commence le 1er janvier et se termine le {fiscalYearEnd} de chaque année." },
  ],
};

/* ─── Pacte d'associés ─── */
export const frPacteAssocies: DocumentTemplate = {
  id: "fr-pacte-associes",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "pacte-associes",
  label: "Pacte d'associés",
  description: "Convention extra-statutaire organisant les relations entre associés.",
  legalBasis: "Code civil, art. 1101 et suivants (liberté contractuelle)",
  needsLegalReview: true,
  active: true,
  fields: [
    { key: "companyName", label: "Dénomination sociale", type: "text", required: true, group: "Société" },
    { key: "companyForm", label: "Forme juridique", type: "select", required: true, options: [
      { value: "SAS", label: "SAS" },
      { value: "SARL", label: "SARL" },
      { value: "SA", label: "SA" },
    ], group: "Société" },
    { key: "registeredOffice", label: "Siège social", type: "text", required: true, group: "Société" },
    { key: "shareCapital", label: "Capital social (€)", type: "number", required: true, validation: { min: 1 }, group: "Société" },
    { key: "associatesList", label: "Associés signataires", type: "textarea", required: true, placeholder: "M. Dupont, 50% du capital\nMme Martin, 50% du capital", group: "Signataires" },
    { key: "nonCompeteDuration", label: "Durée de non-concurrence (mois)", type: "number", required: false, validation: { min: 0, max: 36 }, defaultValue: 12, group: "Clauses" },
    { key: "tagAlongThreshold", label: "Seuil de déclenchement du droit de sortie conjointe (%)", type: "number", required: false, validation: { min: 1, max: 100 }, defaultValue: 50, group: "Clauses" },
    { key: "lockupDuration", label: "Durée d'inaliénabilité (mois)", type: "number", required: false, validation: { min: 0, max: 60 }, defaultValue: 24, group: "Clauses" },
    { key: "pacteDate", label: "Date du pacte", type: "date", required: true },
    { key: "pacteDuration", label: "Durée du pacte (années)", type: "number", required: true, validation: { min: 1, max: 20 }, defaultValue: 5 },
  ],
  clauses: [
    { id: "preambule", label: "Préambule", required: true, text: "PACTE D'ASSOCIÉS\n\nEntre les soussignés, associés de la société {companyName} ({companyForm}), au capital de {shareCapital} €, dont le siège social est au {registeredOffice} :\n\n{associatesList}\n\nIl a été convenu ce qui suit :" },
    { id: "objet", label: "Article 1 — Objet", required: true, text: "Le présent pacte a pour objet d'organiser les relations entre les associés signataires, en complément des statuts de la société." },
    { id: "inalienabilite", label: "Article 2 — Inaliénabilité", required: true, text: "Les associés s'interdisent de céder tout ou partie de leurs titres pendant une durée de {lockupDuration} mois à compter de la signature du présent pacte." },
    { id: "preemption", label: "Article 3 — Droit de préemption", required: true, text: "En cas de projet de cession de titres par un associé, les autres associés bénéficient d'un droit de préemption aux mêmes conditions que celles proposées par le tiers acquéreur." },
    { id: "sortie-conjointe", label: "Article 4 — Droit de sortie conjointe (Tag Along)", required: true, text: "Si un associé détenant plus de {tagAlongThreshold}% du capital cède ses titres, les autres associés pourront exiger de céder leurs titres aux mêmes conditions (droit de sortie conjointe)." },
    { id: "non-concurrence", label: "Article 5 — Non-concurrence", required: true, text: "Chaque associé s'engage à ne pas exercer, directement ou indirectement, une activité concurrente à celle de la société pendant la durée du pacte et pendant {nonCompeteDuration} mois après la cessation de ses fonctions." },
    { id: "confidentialite", label: "Article 6 — Confidentialité", required: true, text: "Les associés s'engagent à maintenir la confidentialité du présent pacte et de toutes les informations relatives à la société." },
    { id: "duree", label: "Article 7 — Durée", required: true, text: "Le présent pacte est conclu pour une durée de {pacteDuration} années à compter du {pacteDate}." },
  ],
};

/* ─── Procès-verbal de nomination du commissaire aux comptes ─── */
export const frNominationCAC: DocumentTemplate = {
  id: "fr-nomination-cac",
  version: "1.0.0",
  country: "FR",
  category: "company",
  docType: "nomination-cac",
  label: "Nomination du Commissaire aux Comptes",
  description: "PV de nomination d'un commissaire aux comptes titulaire et suppléant.",
  legalBasis: "Code de commerce, art. L823-1 et suivants",
  needsLegalReview: true,
  active: true,
  fields: [
    { key: "companyName", label: "Dénomination sociale", type: "text", required: true, group: "Société" },
    { key: "companyForm", label: "Forme juridique", type: "select", required: true, options: [
      { value: "SAS", label: "SAS" }, { value: "SARL", label: "SARL" }, { value: "SA", label: "SA" },
    ], group: "Société" },
    { key: "registeredOffice", label: "Siège social", type: "text", required: true, group: "Société" },
    { key: "rcsNumber", label: "Numéro RCS", type: "text", required: true, group: "Société" },
    { key: "cacName", label: "Nom du CAC titulaire", type: "text", required: true, group: "CAC" },
    { key: "cacAddress", label: "Adresse du CAC titulaire", type: "text", required: true, group: "CAC" },
    { key: "cacSupplName", label: "Nom du CAC suppléant", type: "text", required: false, group: "CAC" },
    { key: "mandatDuration", label: "Durée du mandat (exercices)", type: "number", required: true, validation: { min: 3, max: 6 }, defaultValue: 6, group: "CAC" },
    { key: "assemblyDate", label: "Date de l'assemblée", type: "date", required: true },
  ],
  clauses: [
    { id: "pv", label: "Procès-verbal", required: true, text: "PROCÈS-VERBAL DE L'ASSEMBLÉE GÉNÉRALE ORDINAIRE\nDE LA SOCIÉTÉ {companyName} ({companyForm})\nRCS {rcsNumber}\nSiège social : {registeredOffice}\n\nRéunie le {assemblyDate}\n\nRÉSOLUTION : NOMINATION DU COMMISSAIRE AUX COMPTES\n\nL'assemblée décide de nommer en qualité de Commissaire aux Comptes titulaire :\n{cacName}, domicilié(e) au {cacAddress},\npour une durée de {mandatDuration} exercices." },
    { id: "suppleant", label: "CAC Suppléant", required: false, conditional: (data) => !!data.cacSupplName, text: "Est nommé(e) en qualité de Commissaire aux Comptes suppléant :\n{cacSupplName}." },
  ],
};
