import type { DocumentTemplate } from "../types";

export const frLeaseCommercial: DocumentTemplate = {
  id: "fr-lease-commercial",
  version: "2.0.0",
  country: "FR",
  category: "rental",
  docType: "lease-commercial",
  label: "Bail commercial (3-6-9)",
  description: "Bail commercial conforme au Code de commerce, avec clauses complètes.",
  legalBasis: "Code de commerce, art. L145-1 et suivants",
  needsLegalReview: false,
  active: true,
  fields: [
    // Bailleur
    { key: "landlordName", label: "Nom du bailleur", type: "text", required: true, group: "Bailleur" },
    { key: "landlordAddress", label: "Adresse du bailleur", type: "text", required: true, group: "Bailleur" },
    { key: "landlordSiret", label: "SIRET du bailleur", type: "text", required: false, group: "Bailleur" },
    // Preneur
    { key: "tenantName", label: "Nom / raison sociale du preneur", type: "text", required: true, group: "Preneur" },
    { key: "tenantSiret", label: "SIRET du preneur", type: "text", required: true, validation: { pattern: /^\d{14}$/, patternMessage: "Le SIRET doit contenir 14 chiffres." }, group: "Preneur" },
    { key: "tenantRCS", label: "Ville du RCS", type: "text", required: false, group: "Preneur" },
    { key: "tenantRepresentant", label: "Représentant légal", type: "text", required: false, group: "Preneur" },
    // Local
    { key: "propertyAddress", label: "Adresse du local", type: "text", required: true, group: "Le local" },
    { key: "activity", label: "Activité autorisée (destination)", type: "text", required: true, group: "Le local" },
    { key: "allActivities", label: "Clause tous commerces ?", type: "select", required: true, options: [
      { value: "non", label: "Non — activité spécifique" },
      { value: "oui", label: "Oui — tous commerces" },
    ], defaultValue: "non", group: "Le local" },
    { key: "surface", label: "Surface (m²)", type: "number", required: true, validation: { min: 1 }, group: "Le local" },
    { key: "localDescription", label: "Description détaillée du local", type: "textarea", required: false, placeholder: "RDC : boutique 60m², réserve 20m²\nSous-sol : cave 15m²", group: "Le local" },
    { key: "parkingSpaces", label: "Places de stationnement", type: "number", required: false, defaultValue: 0, group: "Le local" },
    // Financier
    { key: "rentAmount", label: "Loyer annuel HT (€)", type: "number", required: true, validation: { min: 1 }, group: "Conditions financières" },
    { key: "chargesAmount", label: "Charges annuelles (€)", type: "number", required: true, validation: { min: 0 }, defaultValue: 0, group: "Conditions financières" },
    { key: "taxeFonciere", label: "Quote-part taxe foncière (€)", type: "number", required: false, defaultValue: 0, group: "Conditions financières" },
    { key: "depositAmount", label: "Dépôt de garantie (€)", type: "number", required: true, validation: { min: 0 }, group: "Conditions financières" },
    { key: "indexationType", label: "Indice de révision", type: "select", required: true, options: [
      { value: "ILC", label: "ILC (Indice des Loyers Commerciaux)" },
      { value: "ILAT", label: "ILAT (Indice des Loyers des Activités Tertiaires)" },
      { value: "ICC", label: "ICC (Indice du Coût de la Construction)" },
    ], defaultValue: "ILC", group: "Conditions financières" },
    { key: "paymentFrequency", label: "Périodicité de paiement", type: "select", required: true, options: [
      { value: "trimestriel", label: "Trimestriel d'avance" },
      { value: "mensuel", label: "Mensuel d'avance" },
    ], defaultValue: "trimestriel", group: "Conditions financières" },
    { key: "tva", label: "Loyer soumis à TVA ?", type: "select", required: true, options: [
      { value: "non", label: "Non" },
      { value: "oui", label: "Oui (option TVA)" },
    ], defaultValue: "non", group: "Conditions financières" },
    // Droit au bail
    { key: "droitBail", label: "Droit au bail / Pas de porte (€)", type: "number", required: false, defaultValue: 0, group: "Conditions financières" },
    // Dates
    { key: "startDate", label: "Date d'effet", type: "date", required: true, group: "Durée" },
  ],
  clauses: [
    { id: "parties", label: "Article 1 — Parties", required: true,
      text: "ENTRE :\n\nLe bailleur : {landlordName}, SIRET {landlordSiret}, demeurant/siège au {landlordAddress}\n\nET :\n\nLe preneur : {tenantName}, SIRET {tenantSiret}, RCS {tenantRCS}, représenté par {tenantRepresentant}" },
    { id: "local", label: "Article 2 — Désignation des locaux", required: true,
      text: "Le bailleur donne à bail commercial au preneur les locaux situés au {propertyAddress}, d'une surface totale de {surface} m².\n\nDescription : {localDescription}\n\nPlaces de stationnement : {parkingSpaces}" },
    { id: "destination", label: "Article 3 — Destination", required: true,
      text: "Les lieux loués sont destinés exclusivement à l'exercice de l'activité suivante : {activity}.\n\nToute modification de l'activité nécessite l'accord préalable et écrit du bailleur (déspécialisation partielle) ou une procédure judiciaire (déspécialisation plénière, art. L145-47 et suivants du Code de commerce)." },
    { id: "all-activities", label: "Article 3 bis — Clause tous commerces", required: false,
      conditional: (data) => data.allActivities === "oui",
      text: "Par dérogation à l'article précédent, le preneur est autorisé à exercer dans les lieux toutes activités commerciales, sous réserve qu'elles soient conformes à la réglementation en vigueur et au règlement de copropriété." },
    { id: "duration", label: "Article 4 — Durée", required: true,
      text: "Le bail est consenti pour une durée de 9 ans à compter du {startDate}, avec faculté de résiliation triennale conformément à l'article L145-4 du Code de commerce.\n\nLe congé doit être donné 6 mois avant l'expiration de chaque période triennale par acte d'huissier ou lettre recommandée avec AR." },
    { id: "loyer", label: "Article 5 — Loyer", required: true,
      text: "Le loyer annuel HT est fixé à {rentAmount} €, payable {paymentFrequency}.\n\nRévision triennale : le loyer sera révisé à chaque période triennale en fonction de l'indice {indexationType} (art. L145-38 du Code de commerce).\n\nLe loyer révisé ne peut excéder la variation de l'indice de référence, sauf modification matérielle des facteurs locaux de commercialité." },
    { id: "tva-clause", label: "Article 5 bis — TVA", required: false,
      conditional: (data) => data.tva === "oui",
      text: "Le bailleur ayant opté pour l'assujettissement à la TVA, le loyer s'entend hors taxes. La TVA au taux en vigueur sera facturée en sus." },
    { id: "charges", label: "Article 6 — Charges et taxes", required: true,
      text: "Les charges annuelles s'élèvent à {chargesAmount} €.\n\nConformément à l'article L145-40-2 du Code de commerce et au décret du 3 novembre 2014, le bailleur communique au preneur un inventaire précis et limitatif des charges, impôts, taxes et redevances.\n\nQuote-part de taxe foncière à la charge du preneur : {taxeFonciere} €.\n\nUne régularisation annuelle sera effectuée sur justificatifs." },
    { id: "depot", label: "Article 7 — Dépôt de garantie", required: true,
      text: "Un dépôt de garantie de {depositAmount} € est versé à la signature.\n\nIl est restitué dans les deux mois suivant la restitution des locaux, déduction faite des sommes dues.\n\nSi le dépôt excède deux termes de loyer, il produit des intérêts au taux légal au profit du preneur." },
    { id: "droit-bail", label: "Article 8 — Droit au bail", required: false,
      conditional: (data) => Number(data.droitBail) > 0,
      text: "Le preneur verse au bailleur un droit au bail / pas de porte de {droitBail} € à la signature des présentes." },
    { id: "travaux", label: "Article 9 — Travaux", required: true,
      text: "Le bailleur prend en charge les grosses réparations (art. 606 du Code civil) : murs de soutènement, voûtes, planchers, couverture.\n\nLe preneur prend en charge toutes les réparations d'entretien et les travaux d'aménagement intérieur.\n\nLe preneur ne peut effectuer de travaux modifiant la structure sans l'accord écrit du bailleur." },
    { id: "cession", label: "Article 10 — Cession et sous-location", required: true,
      text: "Le preneur peut céder son droit au bail à l'acquéreur de son fonds de commerce (art. L145-16 du Code de commerce). Toute clause contraire est réputée non écrite.\n\nLa sous-location totale ou partielle est interdite sauf accord écrit du bailleur et sous réserve de l'appeler à concourir à l'acte (art. L145-31 et L145-32)." },
    { id: "renouvellement", label: "Article 11 — Renouvellement et indemnité d'éviction", required: true,
      text: "Le preneur bénéficie du droit au renouvellement de son bail (propriété commerciale, art. L145-8 et suivants).\n\nEn cas de refus de renouvellement sans motif grave et légitime, le bailleur devra verser au preneur une indemnité d'éviction compensant le préjudice subi (art. L145-14)." },
    { id: "assurance", label: "Article 12 — Assurance", required: true,
      text: "Le preneur doit s'assurer contre les risques locatifs, les risques liés à son activité et la responsabilité civile. Il justifie de cette assurance à la signature puis annuellement.\n\nLe bailleur s'assure pour sa part en tant que propriétaire non occupant." },
    { id: "resiliation", label: "Article 13 — Clause résolutoire", required: true,
      text: "Le bail sera résilié de plein droit un mois après commandement de payer demeuré infructueux (loyer, charges) ou en cas de cessation d'activité, de mise en liquidation judiciaire, ou d'infraction grave aux obligations du bail." },
  ],
};
