import type { DocumentTemplate } from "../types";

/* ─── Congé du bailleur ─── */
export const frCongesBailleur: DocumentTemplate = {
  id: "fr-conges-bailleur",
  version: "2.0.0",
  country: "FR",
  category: "rental",
  docType: "conges-bailleur",
  label: "Congé du bailleur",
  description: "Lettre de congé délivrée par le bailleur, conforme à l'article 15 de la loi du 6 juillet 1989.",
  legalBasis: "Loi n° 89-462 du 6 juillet 1989, art. 15 ; Loi ALUR du 24 mars 2014",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "landlordName", label: "Nom du bailleur", type: "text", required: true, group: "Bailleur" },
    { key: "landlordAddress", label: "Adresse du bailleur", type: "text", required: true, group: "Bailleur" },
    { key: "tenantName", label: "Nom du locataire", type: "text", required: true, group: "Locataire" },
    { key: "tenantAddress", label: "Adresse du locataire", type: "text", required: true, group: "Locataire" },
    { key: "tenantAge", label: "Âge du locataire (si + de 65 ans)", type: "number", required: false, group: "Locataire" },
    { key: "propertyAddress", label: "Adresse du logement", type: "text", required: true, group: "Bien" },
    { key: "leaseStartDate", label: "Date de début du bail", type: "date", required: true, group: "Bail" },
    { key: "leaseEndDate", label: "Date d'échéance du bail", type: "date", required: true, group: "Bail" },
    { key: "leaseType", label: "Type de bail", type: "select", required: true, options: [
      { value: "vide", label: "Non meublé (préavis 6 mois)" },
      { value: "meuble", label: "Meublé (préavis 3 mois)" },
    ], defaultValue: "vide", group: "Bail" },
    { key: "motif", label: "Motif du congé", type: "select", required: true, options: [
      { value: "reprise", label: "Reprise pour habiter" },
      { value: "vente", label: "Vente du logement" },
      { value: "motif-legitime", label: "Motif légitime et sérieux" },
    ], group: "Congé" },
    { key: "motifDetail", label: "Exposé détaillé du motif", type: "textarea", required: true, placeholder: "Précisez les circonstances justifiant le congé. En cas de reprise, indiquez l'identité du bénéficiaire.", validation: { minLength: 20 }, group: "Congé" },
    { key: "beneficiaireName", label: "Nom du bénéficiaire de la reprise", type: "text", required: false, group: "Reprise" },
    { key: "beneficiaireLink", label: "Lien de parenté avec le bénéficiaire", type: "text", required: false, placeholder: "Conjoint, ascendant, descendant…", group: "Reprise" },
    { key: "beneficiaireAddress", label: "Adresse actuelle du bénéficiaire", type: "text", required: false, group: "Reprise" },
    { key: "salePrice", label: "Prix de vente proposé (€)", type: "number", required: false, group: "Vente" },
    { key: "saleConditions", label: "Conditions de la vente", type: "textarea", required: false, placeholder: "Nombre de pièces, surface, DPE…", group: "Vente" },
    { key: "sendDate", label: "Date d'envoi", type: "date", required: true, group: "Dates" },
  ],
  clauses: [
    { id: "header", label: "En-tête", required: true,
      text: "LETTRE RECOMMANDÉE AVEC ACCUSÉ DE RÉCEPTION\n(ou signifiée par acte d'huissier de justice)\n\n{landlordName}\n{landlordAddress}\n\nÀ l'attention de {tenantName}\n{tenantAddress}\n\nFait le {sendDate}" },
    { id: "conge", label: "Notification du congé", required: true,
      text: "Objet : CONGÉ POUR {motif}\n\nMadame, Monsieur,\n\nConformément à l'article 15 de la loi n° 89-462 du 6 juillet 1989, tel que modifié par la loi ALUR du 24 mars 2014, j'ai l'honneur de vous notifier par la présente mon intention de ne pas renouveler le bail portant sur le logement situé au :\n\n{propertyAddress}\n\nBail conclu le {leaseStartDate}, arrivant à échéance le {leaseEndDate}." },
    { id: "motif-detail", label: "Motif détaillé", required: true,
      text: "MOTIF DU CONGÉ\n\n{motifDetail}" },
    { id: "reprise", label: "Bénéficiaire (reprise)", required: false,
      conditional: (data) => data.motif === "reprise",
      text: "DÉSIGNATION DU BÉNÉFICIAIRE DE LA REPRISE\n(Obligation légale : art. 15-I al. 1 de la loi du 6 juillet 1989)\n\nNom : {beneficiaireName}\nLien de parenté : {beneficiaireLink}\nAdresse actuelle : {beneficiaireAddress}\n\nLe bénéficiaire s'engage à occuper le logement à titre de résidence principale pendant une durée minimale d'un an à compter de l'expiration du délai de préavis.\n\nATTENTION : Conformément à l'article 15-I, le congé pour reprise ne peut être délivré si le locataire est âgé de plus de 65 ans et dispose de ressources inférieures au plafond en vigueur, sauf à lui proposer un relogement adapté." },
    { id: "vente", label: "Offre de vente (droit de préemption)", required: false,
      conditional: (data) => data.motif === "vente",
      text: "OFFRE DE VENTE — DROIT DE PRÉEMPTION DU LOCATAIRE\n(Article 15-II de la loi du 6 juillet 1989)\n\nConformément à la loi, le présent congé vaut offre de vente au profit du locataire aux conditions suivantes :\n\nPrix de vente proposé : {salePrice} €\nConditions : {saleConditions}\n\nVous disposez des deux premiers mois du préavis pour accepter ou refuser cette offre. En cas d'acceptation, vous disposerez d'un délai de deux mois pour réaliser la vente (quatre mois en cas de recours à un prêt immobilier).\n\nÀ défaut de réponse dans le délai, l'offre sera considérée comme refusée." },
    { id: "preavis", label: "Préavis légal", required: true,
      text: "DÉLAI DE PRÉAVIS\n\nCe congé prend effet à l'expiration du bail, soit le {leaseEndDate}, sous réserve du respect du délai de préavis légal de 6 mois (bail vide) ou 3 mois (bail meublé) avant l'échéance du bail.\n\nPendant le délai de préavis, le locataire est redevable du loyer et des charges jusqu'à la remise des clés, sauf si un nouveau locataire est agréé par le bailleur et prend possession des lieux avant la fin du préavis.\n\nRECOURS DU LOCATAIRE :\nEn cas de contestation, le locataire peut saisir la Commission Départementale de Conciliation ou le Tribunal judiciaire dans un délai de deux mois à compter de la réception du congé.\n\nVeuillez agréer, Madame, Monsieur, l'expression de mes salutations distinguées." },
  ],
};

/* ─── Congé du locataire ─── */
export const frCongesLocataire: DocumentTemplate = {
  id: "fr-conges-locataire",
  version: "2.0.0",
  country: "FR",
  category: "rental",
  docType: "conges-locataire",
  label: "Congé du locataire",
  description: "Lettre de congé donnée par le locataire au bailleur, conforme à l'article 15 de la loi du 6 juillet 1989.",
  legalBasis: "Loi n° 89-462 du 6 juillet 1989, art. 15-I",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "tenantName", label: "Nom du locataire", type: "text", required: true, group: "Locataire" },
    { key: "tenantAddress", label: "Adresse actuelle du locataire", type: "text", required: true, group: "Locataire" },
    { key: "landlordName", label: "Nom du bailleur", type: "text", required: true, group: "Bailleur" },
    { key: "landlordAddress", label: "Adresse du bailleur", type: "text", required: true, group: "Bailleur" },
    { key: "propertyAddress", label: "Adresse du logement loué", type: "text", required: true, group: "Bien" },
    { key: "leaseStartDate", label: "Date de début du bail", type: "date", required: true, group: "Bail" },
    { key: "preavisDuration", label: "Durée du préavis", type: "select", required: true, options: [
      { value: "3", label: "3 mois (bail vide — régime normal)" },
      { value: "1", label: "1 mois (bail meublé / zone tendue / motif réduit)" },
    ], defaultValue: "3", group: "Congé" },
    { key: "motifReduit", label: "Motif de préavis réduit (si 1 mois)", type: "select", required: false, options: [
      { value: "zone-tendue", label: "Logement en zone tendue" },
      { value: "mutation", label: "Mutation professionnelle" },
      { value: "perte-emploi", label: "Perte d'emploi involontaire" },
      { value: "nouvel-emploi", label: "Obtention d'un premier emploi" },
      { value: "rsa", label: "Bénéficiaire RSA ou AAH" },
      { value: "sante", label: "État de santé justifiant un changement (+ 60 ans)" },
      { value: "violence", label: "Violences conjugales (ordonnance de protection)" },
      { value: "meuble", label: "Bail meublé (préavis légal d'1 mois)" },
    ], group: "Congé" },
    { key: "newAddress", label: "Nouvelle adresse (si connue)", type: "text", required: false, group: "Congé" },
    { key: "departureDate", label: "Date de départ souhaitée", type: "date", required: true, group: "Congé" },
    { key: "sendDate", label: "Date d'envoi", type: "date", required: true, group: "Congé" },
  ],
  clauses: [
    { id: "header", label: "En-tête", required: true,
      text: "LETTRE RECOMMANDÉE AVEC ACCUSÉ DE RÉCEPTION\n\n{tenantName}\n{tenantAddress}\n\nÀ l'attention de {landlordName}\n{landlordAddress}\n\nFait le {sendDate}" },
    { id: "conge", label: "Congé", required: true,
      text: "Objet : Congé du locataire — Préavis de {preavisDuration} mois\n\nMadame, Monsieur,\n\nPar la présente lettre recommandée avec accusé de réception, je vous notifie ma décision de quitter le logement situé au :\n\n{propertyAddress}\n\nOccupé en vertu du bail signé le {leaseStartDate}.\n\nConformément à l'article 15-I de la loi n° 89-462 du 6 juillet 1989, je respecte un préavis de {preavisDuration} mois. Mon départ effectif est fixé au {departureDate}." },
    { id: "motif", label: "Motif de préavis réduit", required: false,
      conditional: (data) => data.preavisDuration === "1" && !!data.motifReduit,
      text: "JUSTIFICATION DU PRÉAVIS RÉDUIT À 1 MOIS\n\nCe préavis réduit est justifié par : {motifReduit}.\n\nConformément à la loi, je tiens les justificatifs correspondants à votre disposition et les joindrai à mon courrier si nécessaire." },
    { id: "new-address", label: "Nouvelle adresse", required: false,
      conditional: (data) => !!data.newAddress && String(data.newAddress).length > 3,
      text: "Ma nouvelle adresse sera la suivante (pour la restitution du dépôt de garantie) :\n{newAddress}" },
    { id: "demandes", label: "Demandes", required: true,
      text: "DEMANDES COMPLÉMENTAIRES\n\nJe vous prie de bien vouloir :\n\n• Convenir avec moi d'une date pour l'état des lieux de sortie ;\n• Procéder à la restitution du dépôt de garantie dans le délai légal d'un mois (état des lieux conforme) ou deux mois (différences constatées), conformément à l'article 22 de la loi du 6 juillet 1989 ;\n• M'adresser un solde de tout compte locatif.\n\nJe vous rappelle que le loyer sera dû jusqu'à la date effective de remise des clés, au prorata temporis pour le dernier mois.\n\nVeuillez agréer, Madame, Monsieur, l'expression de mes salutations distinguées." },
  ],
};

/* ─── Caution solidaire ─── */
export const frCautionSolidaire: DocumentTemplate = {
  id: "fr-caution-solidaire",
  version: "2.0.0",
  country: "FR",
  category: "rental",
  docType: "caution-solidaire",
  label: "Acte de cautionnement solidaire",
  description: "Engagement de caution solidaire conforme à la loi du 6 juillet 1989, art. 22-1.",
  legalBasis: "Code civil, art. 2288 et suivants ; Loi n° 89-462, art. 22-1 ; Loi ALUR",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "guarantorName", label: "Nom complet du garant", type: "text", required: true, group: "Garant" },
    { key: "guarantorAddress", label: "Adresse complète du garant", type: "text", required: true, group: "Garant" },
    { key: "guarantorBirthDate", label: "Date de naissance du garant", type: "date", required: true, group: "Garant" },
    { key: "guarantorBirthPlace", label: "Lieu de naissance du garant", type: "text", required: true, group: "Garant" },
    { key: "guarantorProfession", label: "Profession du garant", type: "text", required: false, group: "Garant" },
    { key: "tenantName", label: "Nom du locataire cautionné", type: "text", required: true, group: "Locataire" },
    { key: "landlordName", label: "Nom du bailleur", type: "text", required: true, group: "Bailleur" },
    { key: "landlordAddress", label: "Adresse du bailleur", type: "text", required: false, group: "Bailleur" },
    { key: "propertyAddress", label: "Adresse du logement", type: "text", required: true, group: "Bien" },
    { key: "rentAmount", label: "Loyer mensuel hors charges (€)", type: "number", required: true, validation: { min: 1 }, group: "Bail" },
    { key: "chargesAmount", label: "Charges mensuelles (€)", type: "number", required: true, validation: { min: 0 }, defaultValue: 0, group: "Bail" },
    { key: "leaseDuration", label: "Durée du bail cautionné", type: "select", required: true, options: [
      { value: "1", label: "1 an (bail meublé)" },
      { value: "3", label: "3 ans (bail vide — personne physique)" },
      { value: "6", label: "6 ans (bail vide — personne morale)" },
    ], defaultValue: "3", group: "Bail" },
    { key: "cautionDate", label: "Date de l'acte", type: "date", required: true, group: "Date" },
  ],
  clauses: [
    { id: "engagement", label: "Engagement de caution", required: true,
      text: "ACTE DE CAUTIONNEMENT SOLIDAIRE\n(Articles 2288 et suivants du Code civil — Article 22-1 de la loi du 6 juillet 1989)\n\nJe soussigné(e) {guarantorName},\nNé(e) le {guarantorBirthDate} à {guarantorBirthPlace},\nDemeurant au {guarantorAddress},\nProfession : {guarantorProfession},\n\nDéclare me porter caution solidaire et indivisible de {tenantName} au profit de {landlordName}, demeurant au {landlordAddress}, pour garantir le paiement du loyer, des charges locatives et de toutes sommes accessoires dues au titre du bail portant sur le logement situé au :\n\n{propertyAddress}" },
    { id: "montant", label: "Étendue de l'engagement", required: true,
      text: "ÉTENDUE DE L'ENGAGEMENT\n\nLe loyer mensuel hors charges s'élève à : {rentAmount} €\nLes charges mensuelles s'élèvent à : {chargesAmount} €\nSoit un total mensuel de : {total} €\n\nLe présent cautionnement couvre le paiement du loyer principal, des charges locatives, des réparations locatives, des indemnités d'occupation après résiliation du bail, des intérêts de retard, et des frais de procédure éventuels.\n\nIl est consenti pour toute la durée du bail de {leaseDuration} an(s), y compris les renouvellements ou reconductions tacites, conformément à l'article 22-1 de la loi du 6 juillet 1989.\n\nIMPORTANT : En cas de colocation, la caution cesse de plein droit au départ du colocataire cautionné, dans un délai de 6 mois suivant la date d'effet du congé (art. 8-1 de la loi du 6 juillet 1989)." },
    { id: "mention-manuscrite", label: "Mention manuscrite obligatoire", required: true,
      text: "MENTION MANUSCRITE OBLIGATOIRE\n(À recopier intégralement de la main de la caution — art. 22-1 de la loi du 6 juillet 1989)\n\n« En me portant caution de {tenantName}, je m'engage à rembourser au bailleur {landlordName} les loyers et charges impayés, en principal, intérêts et frais, au cas où le locataire ne les paierait pas lui-même.\n\nLe montant du loyer mensuel est de {rentAmount} € hors charges et de {chargesAmount} € de charges, soit un total de {total} € par mois à la date du présent acte.\n\nCet engagement court pour toute la durée du bail de {leaseDuration} an(s) et de ses renouvellements successifs.\n\nJe reconnais avoir pris connaissance de l'article 22-1 de la loi du 6 juillet 1989 reproduit ci-dessus et que mon engagement de caution pourra être invoqué même si le bail est renouvelé ou reconduit tacitement. »" },
    { id: "information", label: "Information du garant", required: true,
      text: "INFORMATION DU GARANT\n\nConformément à l'article 2293 du Code civil, le bailleur informe la caution de tout impayé dès le premier mois de retard.\n\nLa caution peut résilier son engagement à l'expiration du bail en cours par lettre recommandée avec accusé de réception.\n\nFait en deux exemplaires originaux à _____________, le {cautionDate}\n\nSignature du garant (précédée de la mention « Lu et approuvé, bon pour cautionnement solidaire ») :\n\n\n\nSignature du bailleur (bon pour acceptation) :" },
  ],
};

/* ─── Attestation d'hébergement ─── */
export const frAttestationHebergement: DocumentTemplate = {
  id: "fr-attestation-hebergement",
  version: "2.0.0",
  country: "FR",
  category: "rental",
  docType: "attestation-hebergement",
  label: "Attestation d'hébergement",
  description: "Attestation sur l'honneur d'hébergement à titre gratuit, conforme au Code pénal.",
  legalBasis: "Code pénal, art. 441-7 (faux et usage de faux)",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "hostName", label: "Nom complet de l'hébergeant", type: "text", required: true, group: "Hébergeant" },
    { key: "hostBirthDate", label: "Date de naissance", type: "date", required: true, group: "Hébergeant" },
    { key: "hostBirthPlace", label: "Lieu de naissance", type: "text", required: true, group: "Hébergeant" },
    { key: "hostAddress", label: "Adresse complète du logement", type: "text", required: true, group: "Hébergeant" },
    { key: "hostPostalCode", label: "Code postal", type: "postal-code", required: false, group: "Hébergeant" },
    { key: "hostCity", label: "Ville", type: "text", required: false, group: "Hébergeant" },
    { key: "guestName", label: "Nom complet de l'hébergé(e)", type: "text", required: true, group: "Hébergé" },
    { key: "guestBirthDate", label: "Date de naissance de l'hébergé(e)", type: "date", required: true, group: "Hébergé" },
    { key: "guestBirthPlace", label: "Lieu de naissance de l'hébergé(e)", type: "text", required: true, group: "Hébergé" },
    { key: "guestNationality", label: "Nationalité de l'hébergé(e)", type: "text", required: false, group: "Hébergé" },
    { key: "startDate", label: "Hébergé(e) depuis le", type: "date", required: true, group: "Informations" },
    { key: "purpose", label: "Destinataire de l'attestation", type: "text", required: false, placeholder: "Préfecture, banque, employeur…", group: "Informations" },
    { key: "attestationDate", label: "Date de l'attestation", type: "date", required: true, group: "Date" },
  ],
  clauses: [
    { id: "declaration", label: "Déclaration", required: true,
      text: "ATTESTATION D'HÉBERGEMENT À TITRE GRATUIT\n\nJe soussigné(e) {hostName},\nNé(e) le {hostBirthDate} à {hostBirthPlace},\n\nCertifie sur l'honneur héberger à mon domicile situé au :\n{hostAddress} {hostPostalCode} {hostCity}\n\nLa personne suivante :\n{guestName}, né(e) le {guestBirthDate} à {guestBirthPlace},\nNationalité : {guestNationality}\n\nCet hébergement est accordé à titre gratuit depuis le {startDate}.\n\nLe logement constitue la résidence principale de la personne hébergée." },
    { id: "pieces", label: "Pièces jointes", required: true,
      text: "PIÈCES JUSTIFICATIVES À JOINDRE\n\nLa présente attestation doit être accompagnée des documents suivants :\n• Photocopie de la pièce d'identité de l'hébergeant (recto/verso)\n• Justificatif de domicile récent de l'hébergeant (facture EDF, avis d'imposition…)\n• Photocopie de la pièce d'identité de l'hébergé(e)" },
    { id: "engagement", label: "Engagement", required: true,
      text: "ENGAGEMENT\n\nJe certifie sur l'honneur l'exactitude des informations ci-dessus et suis informé(e) que toute fausse déclaration m'expose aux sanctions pénales prévues par l'article 441-7 du Code pénal (un an d'emprisonnement et 15 000 euros d'amende).\n\nFait pour servir et valoir ce que de droit.\n\nFait à _____________, le {attestationDate}\n\nSignature de l'hébergeant\n(précédée de la mention manuscrite « Certifié sur l'honneur ») :" },
  ],
};

/* ─── Commandement de payer ─── */
export const frCommandementPayer: DocumentTemplate = {
  id: "fr-commandement-payer",
  version: "2.0.0",
  country: "FR",
  category: "rental",
  docType: "commandement-payer",
  label: "Commandement de payer (modèle)",
  description: "Modèle de commandement de payer visant la clause résolutoire. À faire signifier par huissier.",
  legalBasis: "Loi n° 89-462 du 6 juillet 1989, art. 24 ; Loi n° 2023-668 du 27 juillet 2023",
  needsLegalReview: true,
  active: true,
  fields: [
    { key: "landlordName", label: "Nom du bailleur", type: "text", required: true, group: "Bailleur" },
    { key: "landlordAddress", label: "Adresse du bailleur", type: "text", required: true, group: "Bailleur" },
    { key: "tenantName", label: "Nom du locataire", type: "text", required: true, group: "Locataire" },
    { key: "tenantAddress", label: "Adresse du locataire", type: "text", required: true, group: "Locataire" },
    { key: "propertyAddress", label: "Adresse du logement", type: "text", required: true, group: "Bien" },
    { key: "leaseDate", label: "Date du bail", type: "date", required: true, group: "Bail" },
    { key: "unpaidMonths", label: "Détail des mois impayés", type: "textarea", required: true, placeholder: "Janvier 2026 — Loyer : 750 € + Charges : 100 € = 850 €\nFévrier 2026 — Loyer : 750 € + Charges : 100 € = 850 €", group: "Impayés" },
    { key: "totalAmount", label: "Montant total de la dette (€)", type: "number", required: true, validation: { min: 1 }, group: "Impayés" },
    { key: "commandmentDate", label: "Date du commandement", type: "date", required: true, group: "Date" },
  ],
  clauses: [
    { id: "header", label: "En-tête", required: true,
      text: "COMMANDEMENT DE PAYER VISANT LA CLAUSE RÉSOLUTOIRE\n(Article 24 de la loi n° 89-462 du 6 juillet 1989)\n\n⚠️ Ce document est un MODÈLE. Le commandement de payer doit obligatoirement être signifié par un commissaire de justice (huissier).\n\nÀ la requête de : {landlordName}, demeurant au {landlordAddress}\n\nÀ : {tenantName}, demeurant au {tenantAddress}" },
    { id: "commandment", label: "Commandement", required: true,
      text: "En vertu du bail en date du {leaseDate} portant sur le logement situé au {propertyAddress}, et en application de la clause résolutoire inscrite audit bail ;\n\nConformément à l'article 24 de la loi du 6 juillet 1989 modifié par la loi n° 2023-668 du 27 juillet 2023 ;\n\nIl est fait COMMANDEMENT à {tenantName} d'avoir à payer dans un délai de SIX SEMAINES (42 jours) la somme de {totalAmount} € correspondant aux loyers, charges et accessoires impayés ci-après détaillés :\n\nDÉTAIL DE LA DETTE :\n{unpaidMonths}\n\n──────────────────────\nTOTAL DÛ : {totalAmount} €" },
    { id: "avertissement", label: "Avertissement légal", required: true,
      text: "AVERTISSEMENTS LÉGAUX OBLIGATOIRES\n\n1. CLAUSE RÉSOLUTOIRE : À défaut de paiement intégral dans le délai de six semaines, le bail sera résilié de plein droit et le locataire devra quitter les lieux.\n\n2. RECOURS DU LOCATAIRE : Vous pouvez :\n   • Solliciter des délais de paiement auprès du juge des contentieux de la protection ;\n   • Saisir le Fonds de Solidarité pour le Logement (FSL) de votre département ;\n   • Contacter les services sociaux de votre commune ou le CCAS ;\n   • Vous adresser à une association agréée d'aide aux locataires.\n\n3. SIGNALEMENT CCAPEX : Conformément à la loi, ce commandement est signalé à la Commission de Coordination des Actions de Prévention des Expulsions (CCAPEX) de votre département.\n\n4. TRÊVE HIVERNALE : Aucune expulsion ne peut être exécutée entre le 1er novembre et le 31 mars de l'année suivante (art. L412-6 du Code des procédures civiles d'exécution), sauf exceptions.\n\nFait le {commandmentDate}." },
  ],
};

/* ─── Restitution du dépôt de garantie ─── */
export const frRestitutionDepot: DocumentTemplate = {
  id: "fr-restitution-depot",
  version: "2.0.0",
  country: "FR",
  category: "rental",
  docType: "restitution-depot",
  label: "Restitution du dépôt de garantie",
  description: "Courrier de restitution (totale ou partielle) du dépôt de garantie, conforme à l'article 22.",
  legalBasis: "Loi n° 89-462 du 6 juillet 1989, art. 22",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "landlordName", label: "Nom du bailleur", type: "text", required: true, group: "Bailleur" },
    { key: "landlordAddress", label: "Adresse du bailleur", type: "text", required: true, group: "Bailleur" },
    { key: "landlordIBAN", label: "IBAN du bailleur (si virement)", type: "text", required: false, group: "Bailleur" },
    { key: "tenantName", label: "Nom du locataire", type: "text", required: true, group: "Locataire" },
    { key: "tenantNewAddress", label: "Nouvelle adresse du locataire", type: "text", required: true, group: "Locataire" },
    { key: "propertyAddress", label: "Adresse du logement quitté", type: "text", required: true, group: "Bien" },
    { key: "leaseDate", label: "Date du bail", type: "date", required: false, group: "Bail" },
    { key: "depositAmount", label: "Montant du dépôt initial (€)", type: "number", required: true, validation: { min: 0 }, group: "Montants" },
    { key: "retainedAmount", label: "Montant total retenu (€)", type: "number", required: true, validation: { min: 0 }, defaultValue: 0, group: "Montants" },
    { key: "retainedDetail", label: "Détail justifié des retenues", type: "textarea", required: false, placeholder: "Réparations locatives (peinture chambre) : 250 €\nRemplacement serrure cassée : 80 €\nLoyers impayés : 0 €\nRégularisation charges : 65 €\n\nTotal retenues : 395 €", group: "Montants" },
    { key: "edlConforme", label: "État des lieux de sortie conforme ?", type: "select", required: true, options: [
      { value: "oui", label: "Oui — conforme à l'entrée" },
      { value: "non", label: "Non — différences constatées" },
    ], defaultValue: "oui", group: "État des lieux" },
    { key: "exitDate", label: "Date de remise des clés", type: "date", required: true, group: "Dates" },
    { key: "sendDate", label: "Date du courrier", type: "date", required: true, group: "Dates" },
  ],
  clauses: [
    { id: "header", label: "En-tête", required: true,
      text: "{landlordName}\n{landlordAddress}\n\nÀ l'attention de {tenantName}\n{tenantNewAddress}\n\nFait le {sendDate}" },
    { id: "restitution", label: "Restitution du dépôt", required: true,
      text: "Objet : Restitution du dépôt de garantie\n\nMadame, Monsieur,\n\nSuite à votre départ du logement situé au {propertyAddress} et à la remise des clés effectuée le {exitDate}, je procède conformément à l'article 22 de la loi n° 89-462 du 6 juillet 1989 à la restitution de votre dépôt de garantie.\n\nDÉCOMPTE DE RESTITUTION :\n\n╔══════════════════════════════════════╗\n║ Dépôt de garantie initial  : {depositAmount} €\n║ Retenues justifiées        : {retainedAmount} €\n║ ────────────────────────────────────\n║ MONTANT RESTITUÉ           : [solde] €\n╚══════════════════════════════════════╝" },
    { id: "retenues-detail", label: "Détail des retenues", required: false,
      conditional: (data) => Number(data.retainedAmount) > 0,
      text: "DÉTAIL DES RETENUES (sur justificatifs) :\n\n{retainedDetail}\n\nLes pièces justificatives (devis, factures) sont jointes au présent courrier ou tenues à votre disposition." },
    { id: "delai-legal", label: "Délai légal", required: true,
      text: "RAPPEL DU CADRE LÉGAL\n\nConformément à l'article 22 de la loi du 6 juillet 1989 :\n\n• État des lieux conforme : le dépôt est restitué dans un délai d'un mois à compter de la remise des clés.\n• Différences constatées : le dépôt est restitué dans un délai de deux mois.\n• En cas de non-restitution dans les délais, le dépôt produit des intérêts de retard de 10 % du loyer mensuel par mois de retard.\n• Le bailleur peut retenir au maximum 20 % du dépôt de garantie en provision sur la régularisation annuelle des charges, à régulariser dans le mois suivant l'approbation des comptes de l'immeuble.\n\nLe solde vous sera versé par virement bancaire ou chèque dans les délais légaux.\n\nVeuillez agréer, Madame, Monsieur, l'expression de mes salutations distinguées." },
  ],
};
