import type { DocumentTemplate } from "../types";

export const frSwornStatement: DocumentTemplate = {
  id: "fr-sworn-statement",
  version: "2.0.0",
  country: "FR",
  category: "administrative",
  docType: "sworn-statement",
  label: "Attestation sur l'honneur",
  description: "Déclaration solennelle conforme à l'article 441-7 du Code pénal, utilisable pour diverses démarches.",
  legalBasis: "Article 441-7 du Code pénal ; Articles 202 et 200 du Code de procédure civile",
  needsLegalReview: false,
  active: true,
  fields: [
    { key: "fullName", label: "Nom et prénom(s) complet(s)", type: "text", required: true, validation: { minLength: 2, maxLength: 100 }, group: "Identité" },
    { key: "birthDate", label: "Date de naissance", type: "date", required: true, group: "Identité" },
    { key: "birthPlace", label: "Lieu de naissance (ville et département)", type: "text", required: true, group: "Identité" },
    { key: "nationality", label: "Nationalité", type: "text", required: false, defaultValue: "Française", group: "Identité" },
    { key: "address", label: "Adresse actuelle complète", type: "text", required: true, validation: { minLength: 5 }, group: "Domicile" },
    { key: "postalCode", label: "Code postal", type: "postal-code", required: false, group: "Domicile" },
    { key: "city", label: "Ville", type: "text", required: false, group: "Domicile" },
    { key: "attestationType", label: "Type d'attestation", type: "select", required: true, options: [
      { value: "domicile", label: "Attestation de domicile" },
      { value: "honneur", label: "Attestation sur l'honneur (libre)" },
      { value: "revenus", label: "Attestation de revenus" },
      { value: "hebergement", label: "Attestation d'hébergement" },
      { value: "perte", label: "Déclaration de perte" },
      { value: "autre", label: "Autre" },
    ], defaultValue: "honneur", group: "Déclaration" },
    { key: "statement", label: "Contenu de la déclaration", type: "textarea", required: true, placeholder: "Précisez l'objet de votre attestation…\n\nExemple : « Je certifie sur l'honneur que je réside à l'adresse ci-dessus depuis le 1er janvier 2025 et que cette adresse constitue ma résidence principale. »", validation: { minLength: 10, maxLength: 3000 }, group: "Déclaration" },
    { key: "purpose", label: "Destinataire / usage de l'attestation", type: "text", required: false, placeholder: "Ex: Préfecture, banque, administration fiscale…", group: "Déclaration" },
    { key: "attestationDate", label: "Date de l'attestation", type: "date", required: true, group: "Date" },
    { key: "attestationCity", label: "Fait à (ville)", type: "text", required: false, group: "Date" },
  ],
  clauses: [
    { id: "title", label: "Titre", required: true,
      text: "ATTESTATION SUR L'HONNEUR\n\n(Article 441-7 du Code pénal)" },
    { id: "declaration", label: "Déclaration d'identité", required: true,
      text: "Je soussigné(e) {fullName},\n\nNé(e) le {birthDate} à {birthPlace},\nNationalité : {nationality},\nDemeurant au {address} {postalCode} {city},\n\nAtteste sur l'honneur, en toute connaissance des sanctions pénales encourues en cas de fausse déclaration, que :\n\n{statement}" },
    { id: "purpose-clause", label: "Destination", required: false,
      conditional: (data) => !!data.purpose && String(data.purpose).length > 2,
      text: "La présente attestation est établie pour servir et valoir ce que de droit auprès de {purpose}." },
    { id: "penal-warning", label: "Avertissement pénal", required: true,
      text: "AVERTISSEMENT\n\nJe certifie sur l'honneur l'exactitude de la présente déclaration.\n\nJe suis informé(e) que :\n• Toute fausse attestation est passible d'un an d'emprisonnement et de 15 000 euros d'amende (article 441-7 du Code pénal).\n• L'usage de faux est passible de trois ans d'emprisonnement et de 45 000 euros d'amende (article 441-1 du Code pénal).\n• La présente attestation pourra être produite en justice et engage ma responsabilité civile et pénale." },
    { id: "signature-block", label: "Signature", required: true,
      text: "Fait pour servir et valoir ce que de droit.\n\nFait à {attestationCity}, le {attestationDate}\n\nSignature précédée de la mention manuscrite « Lu et approuvé, certifié sincère et véritable » :" },
  ],
};
