/**
 * Taxonomy Mapper — Maps raw source categories to canonical Family→Category→Subcategory.
 * Strict per-vertical rules. Zero ambiguity.
 */
import type { Vertical, TaxonomyNode, SourceEntityRecord } from "../types";

// ─── Family definitions per vertical ───
const VERTICAL_FAMILIES: Record<string, string> = {
  food: "food_beverage",
  grocery: "retail_grocery",
  stay: "hospitality",
  hotel: "hospitality",
  services: "professional_services",
  property: "real_estate",
  shops: "retail_shops",
  mobility: "transport",
  utility: "infrastructure",
  healthcare: "health_wellness",
  experiences: "entertainment_leisure",
};

// ─── Category mapping per vertical ───
const CATEGORY_MAP: Record<string, Record<string, { category: string; subcategory: string }>> = {
  food: {
    restaurant: { category: "restaurant", subcategory: "general" },
    fast_food: { category: "restaurant", subcategory: "fast_food" },
    pizza: { category: "restaurant", subcategory: "pizza" },
    burger: { category: "restaurant", subcategory: "burger" },
    sushi: { category: "restaurant", subcategory: "sushi" },
    shawarma: { category: "restaurant", subcategory: "shawarma" },
    fried_chicken: { category: "restaurant", subcategory: "fried_chicken" },
    cafe: { category: "cafe_bakery", subcategory: "cafe" },
    coffee: { category: "cafe_bakery", subcategory: "coffee" },
    bakery: { category: "cafe_bakery", subcategory: "bakery" },
    desserts: { category: "cafe_bakery", subcategory: "desserts" },
    beverages: { category: "cafe_bakery", subcategory: "beverages" },
    breakfast: { category: "restaurant", subcategory: "breakfast" },
    brunch: { category: "restaurant", subcategory: "brunch" },
    catering: { category: "catering", subcategory: "catering" },
    vietnamese: { category: "restaurant", subcategory: "vietnamese" },
    greek: { category: "restaurant", subcategory: "greek" },
    french: { category: "restaurant", subcategory: "french" },
    spanish: { category: "restaurant", subcategory: "spanish" },
    african: { category: "restaurant", subcategory: "african" },
    ethiopian: { category: "restaurant", subcategory: "ethiopian" },
    caribbean: { category: "restaurant", subcategory: "caribbean" },
    persian: { category: "restaurant", subcategory: "persian" },
    filipino: { category: "restaurant", subcategory: "filipino" },
    brazilian: { category: "restaurant", subcategory: "brazilian" },
    german: { category: "restaurant", subcategory: "german" },
    moroccan: { category: "restaurant", subcategory: "moroccan" },
    bbq: { category: "restaurant", subcategory: "bbq" },
    vegan: { category: "restaurant", subcategory: "vegan" },
    juice_bar: { category: "cafe_bakery", subcategory: "juice_bar" },
    food_truck: { category: "restaurant", subcategory: "food_truck" },
    ice_cream: { category: "cafe_bakery", subcategory: "ice_cream" },
    steakhouse: { category: "restaurant", subcategory: "steakhouse" },
    fine_dining: { category: "restaurant", subcategory: "fine_dining" },
    pakistani: { category: "restaurant", subcategory: "pakistani" },
    italian: { category: "restaurant", subcategory: "italian" },
    indian: { category: "restaurant", subcategory: "indian" },
    chinese: { category: "restaurant", subcategory: "chinese" },
    lebanese: { category: "restaurant", subcategory: "lebanese" },
    arabic: { category: "restaurant", subcategory: "arabic" },
    turkish: { category: "restaurant", subcategory: "turkish" },
    mexican: { category: "restaurant", subcategory: "mexican" },
    thai: { category: "restaurant", subcategory: "thai" },
    korean: { category: "restaurant", subcategory: "korean" },
    japanese: { category: "restaurant", subcategory: "japanese" },
    seafood: { category: "restaurant", subcategory: "seafood" },
    healthy: { category: "restaurant", subcategory: "healthy" },
    asian: { category: "restaurant", subcategory: "asian" },
    pasta: { category: "restaurant", subcategory: "pasta" },
  },
  grocery: {
    supermarket: { category: "grocery_store", subcategory: "supermarket" },
    mini_mart: { category: "grocery_store", subcategory: "mini_mart" },
    organic: { category: "grocery_store", subcategory: "organic" },
    organic_store: { category: "grocery_store", subcategory: "organic" },
    fruits_vegetables: { category: "fresh_market", subcategory: "fruits_vegetables" },
    butcher: { category: "fresh_market", subcategory: "butcher" },
    dairy: { category: "fresh_market", subcategory: "dairy" },
    beverages_store: { category: "grocery_store", subcategory: "beverages" },
    snacks: { category: "grocery_store", subcategory: "snacks" },
    frozen: { category: "grocery_store", subcategory: "frozen" },
    bakery_grocery: { category: "fresh_market", subcategory: "bakery_grocery" },
    baby_products: { category: "grocery_store", subcategory: "baby_products" },
    household: { category: "grocery_store", subcategory: "household" },
    personal_care: { category: "grocery_store", subcategory: "personal_care" },
    pet_food: { category: "grocery_store", subcategory: "pet_food" },
    fish_market: { category: "fresh_market", subcategory: "fish_market" },
    spices: { category: "grocery_store", subcategory: "spices" },
    health_food: { category: "grocery_store", subcategory: "health_food" },
    gourmet: { category: "grocery_store", subcategory: "gourmet" },
    water_delivery: { category: "grocery_store", subcategory: "water_delivery" },
  },
  hotel: {
    hotel: { category: "accommodation", subcategory: "hotel" },
    resort: { category: "accommodation", subcategory: "resort" },
    hostel: { category: "accommodation", subcategory: "hostel" },
    boutique_hotel: { category: "accommodation", subcategory: "boutique_hotel" },
    serviced_apartment: { category: "accommodation", subcategory: "serviced_apartment" },
    apart_hotel: { category: "accommodation", subcategory: "serviced_apartment" },
    holiday_rental: { category: "accommodation", subcategory: "holiday_rental" },
    short_stay: { category: "accommodation", subcategory: "short_stay" },
    motel: { category: "accommodation", subcategory: "motel" },
    bed_breakfast: { category: "accommodation", subcategory: "bed_breakfast" },
    glamping: { category: "accommodation", subcategory: "glamping" },
    eco_lodge: { category: "accommodation", subcategory: "eco_lodge" },
  },
  stay: {
    hotel: { category: "accommodation", subcategory: "hotel" },
    resort: { category: "accommodation", subcategory: "resort" },
    hostel: { category: "accommodation", subcategory: "hostel" },
    serviced_apartment: { category: "accommodation", subcategory: "serviced_apartment" },
    boutique_hotel: { category: "accommodation", subcategory: "boutique_hotel" },
    apart_hotel: { category: "accommodation", subcategory: "serviced_apartment" },
    holiday_rental: { category: "accommodation", subcategory: "holiday_rental" },
    short_stay: { category: "accommodation", subcategory: "short_stay" },
  },
  services: {
    salon: { category: "beauty", subcategory: "salon" },
    barber: { category: "beauty", subcategory: "barber" },
    spa: { category: "beauty", subcategory: "spa" },
    nails: { category: "beauty", subcategory: "nails" },
    makeup: { category: "beauty", subcategory: "makeup" },
    lashes: { category: "beauty", subcategory: "lashes" },
    tattoo: { category: "beauty", subcategory: "tattoo" },
    massage: { category: "beauty", subcategory: "massage" },
    cleaning: { category: "home_services", subcategory: "cleaning" },
    laundry: { category: "home_services", subcategory: "laundry" },
    plumbing: { category: "home_services", subcategory: "plumbing" },
    electrical: { category: "home_services", subcategory: "electrical" },
    ac_repair: { category: "home_services", subcategory: "ac_repair" },
    car_wash: { category: "auto_services", subcategory: "car_wash" },
    car_repair: { category: "auto_services", subcategory: "car_repair" },
    handyman: { category: "home_services", subcategory: "handyman" },
    pest_control: { category: "home_services", subcategory: "pest_control" },
    movers: { category: "home_services", subcategory: "movers" },
    tailoring: { category: "personal_services", subcategory: "tailoring" },
    tutoring: { category: "professional", subcategory: "tutoring" },
    legal: { category: "professional", subcategory: "legal" },
    fitness: { category: "wellness", subcategory: "fitness" },
    photography: { category: "professional", subcategory: "photography" },
    accounting: { category: "professional", subcategory: "accounting" },
    insurance: { category: "professional", subcategory: "insurance" },
    pet_grooming: { category: "home_services", subcategory: "pet_grooming" },
    gardening: { category: "home_services", subcategory: "gardening" },
    painting: { category: "home_services", subcategory: "painting" },
    interior_design: { category: "professional", subcategory: "interior_design" },
    key_cutting: { category: "home_services", subcategory: "key_cutting" },
    carpentry: { category: "home_services", subcategory: "carpentry" },
    it_support: { category: "professional", subcategory: "it_support" },
    mobile_repair: { category: "auto_services", subcategory: "mobile_repair" },
    printing: { category: "professional", subcategory: "printing" },
  },
  property: {
    rent: { category: "residential", subcategory: "rent" },
    sale: { category: "residential", subcategory: "sale" },
    short_stay: { category: "residential", subcategory: "short_stay" },
    commercial_lease: { category: "commercial", subcategory: "lease" },
    villa: { category: "residential", subcategory: "villa" },
    apartment: { category: "residential", subcategory: "apartment" },
    office: { category: "commercial", subcategory: "office" },
  },
  shops: {
    fashion: { category: "fashion", subcategory: "clothing" },
    electronics: { category: "electronics", subcategory: "gadgets" },
    jewelry: { category: "luxury", subcategory: "jewelry" },
    footwear: { category: "fashion", subcategory: "shoes" },
    home_decor: { category: "home", subcategory: "decor" },
    perfume: { category: "beauty", subcategory: "fragrance" },
    toys: { category: "family", subcategory: "toys" },
    sports: { category: "sports", subcategory: "equipment" },
    books: { category: "media", subcategory: "books" },
    general: { category: "retail", subcategory: "general" },
  },
  mobility: {
    taxi: { category: "rideshare", subcategory: "taxi" },
    chauffeur: { category: "rideshare", subcategory: "chauffeur" },
    rental: { category: "vehicle_rental", subcategory: "car" },
    bus: { category: "public_transport", subcategory: "bus" },
    metro: { category: "public_transport", subcategory: "metro" },
  },
  utility: {
    atm: { category: "finance", subcategory: "atm" },
    fuel: { category: "automotive", subcategory: "fuel" },
    pharmacy: { category: "health", subcategory: "pharmacy" },
    parking: { category: "automotive", subcategory: "parking" },
    ev_charger: { category: "automotive", subcategory: "ev_charger" },
  },
  healthcare: {
    hospital: { category: "medical", subcategory: "hospital" },
    clinic: { category: "medical", subcategory: "clinic" },
    dental: { category: "medical", subcategory: "dental" },
    pharmacy: { category: "medical", subcategory: "pharmacy" },
    lab: { category: "medical", subcategory: "lab" },
    optical: { category: "medical", subcategory: "optical" },
    physio: { category: "medical", subcategory: "physio" },
    dentist: { category: "medical", subcategory: "dental" },
  },
  experiences: {
    theme_park: { category: "entertainment", subcategory: "theme_park" },
    museum: { category: "culture", subcategory: "museum" },
    concert: { category: "events", subcategory: "concert" },
    desert_safari: { category: "adventure", subcategory: "safari" },
    water_sports: { category: "adventure", subcategory: "water_sports" },
    tour: { category: "tourism", subcategory: "city_tour" },
    cruise: { category: "tourism", subcategory: "cruise" },
    safari: { category: "adventure", subcategory: "safari" },
    diving: { category: "adventure", subcategory: "diving" },
    ski: { category: "adventure", subcategory: "ski" },
    hiking: { category: "adventure", subcategory: "hiking" },
    city_tour: { category: "tourism", subcategory: "city_tour" },
    flights: { category: "tourism", subcategory: "flights" },
    activities: { category: "entertainment", subcategory: "activities" },
    events: { category: "events", subcategory: "events" },
  },
};

// ─── Aliases for raw source categories ───
const CATEGORY_ALIASES: Record<string, string> = {
  "fast food": "fast_food",
  fastfood: "fast_food",
  "fried chicken": "fried_chicken",
  "coffee shop": "cafe",
  "ice cream": "ice_cream",
  gelato: "ice_cream",
  "frozen yogurt": "ice_cream",
  "mini mart": "mini_mart",
  convenience: "mini_mart",
  "convenience store": "mini_mart",
  "organic store": "organic_store",
  "car wash": "car_wash",
  "car repair": "car_repair",
  "ac repair": "ac_repair",
  "pest control": "pest_control",
  "short stay": "short_stay",
  "serviced apartment": "serviced_apartment",
  "boutique hotel": "boutique_hotel",
  "apart hotel": "apart_hotel",
  fruits: "fruits_vegetables",
  vegetables: "fruits_vegetables",
  repair: "handyman",
  maintenance: "handyman",
  "pho restaurant": "vietnamese",
  "pho": "vietnamese",
  "banh mi": "vietnamese",
  "gyros": "greek",
  "souvlaki": "greek",
  "tapas": "spanish",
  "paella": "spanish",
  "bistro": "french",
  "brasserie": "french",
  "patisserie": "french",
  "jollof": "african",
  "west african": "african",
  "east african": "african",
  "nigerian": "african",
  "ghanaian": "african",
  "senegalese": "african",
  "jerk chicken": "caribbean",
  "jamaican": "caribbean",
  "trinidadian": "caribbean",
  "iranian": "persian",
  "kebab": "persian",
  "churrasco": "brazilian",
  "bratwurst": "german",
  "schnitzel": "german",
  "tagine": "moroccan",
  "couscous": "moroccan",
  "north african": "moroccan",
  "tunisian": "moroccan",
  "barbecue": "bbq",
  "grill": "bbq",
  "grilled": "bbq",
  "smokehouse": "bbq",
  "plant based": "vegan",
  "plant_based": "vegan",
  vegetarian: "vegan",
  "raw food": "vegan",
  "smoothie bar": "juice_bar",
  "smoothie": "juice_bar",
  "juice": "juice_bar",
  "fresh juice": "juice_bar",
  "acai": "juice_bar",
  "street food": "food_truck",
  "food cart": "food_truck",
  "steak": "steakhouse",
  "steak house": "steakhouse",
  "gourmet burger": "burger",
  "fish and chips": "seafood",
  "fish & chips": "seafood",
  "ramen": "japanese",
  "noodles": "asian",
  "dim sum": "chinese",
  "dumpling": "chinese",
  "dumplings": "chinese",
  "taco": "mexican",
  "tacos": "mexican",
  "burrito": "mexican",
  "biryani": "indian",
  "curry": "indian",
  "tandoori": "indian",
  "falafel": "lebanese",
  "hummus": "lebanese",
  "manakeesh": "lebanese",
  "manoushe": "lebanese",
  "doner": "turkish",
  "lahmacun": "turkish",
  "pide": "turkish",
  "kbbq": "korean",
  "korean bbq": "korean",
  "bibimbap": "korean",
  "pad thai": "thai",
  croissant: "bakery",
  "donut": "desserts",
  "doughnut": "desserts",
  "cake": "desserts",
  "pastry": "bakery",
  tea: "cafe",
  "tea house": "cafe",
  "bubble tea": "cafe",
  "boba": "cafe",
  "fish market": "fish_market",
  fishmonger: "fish_market",
  "spice shop": "spices",
  "herb shop": "spices",
  "deli": "gourmet",
  delicatessen: "gourmet",
  "health store": "health_food",
  "supplement store": "health_food",
  "gnc": "health_food",
  "nail salon": "nails",
  manicure: "nails",
  pedicure: "nails",
  "makeup artist": "makeup",
  "mua": "makeup",
  "eyelash": "lashes",
  "eyebrow": "lashes",
  "brow bar": "lashes",
  "tattoo parlor": "tattoo",
  "tattoo studio": "tattoo",
  piercing: "tattoo",
  "body art": "tattoo",
  "massage therapy": "massage",
  "thai massage": "massage",
  "deep tissue": "massage",
  photographer: "photography",
  "photo studio": "photography",
  accountant: "accounting",
  "tax consultant": "accounting",
  bookkeeper: "accounting",
  "dog grooming": "pet_grooming",
  "pet salon": "pet_grooming",
  landscaping: "gardening",
  "lawn care": "gardening",
  "house painter": "painting",
  "wall painting": "painting",
  decorator: "interior_design",
  locksmith: "key_cutting",
  "key maker": "key_cutting",
  carpenter: "carpentry",
  "wood work": "carpentry",
  "computer repair": "it_support",
  "tech support": "it_support",
  "it services": "it_support",
  "bed and breakfast": "bed_breakfast",
  "bed & breakfast": "bed_breakfast",
  "b&b": "bed_breakfast",
  bnb: "bed_breakfast",
  guesthouse: "bed_breakfast",
  "guest house": "bed_breakfast",
  "desert safari": "safari",
  "wildlife": "safari",
  "scuba": "diving",
  snorkeling: "diving",
  "scuba diving": "diving",
  snowboard: "ski",
  skiing: "ski",
  "winter sports": "ski",
  trek: "hiking",
  trekking: "hiking",
  "mountain climbing": "hiking",
  "sightseeing": "city_tour",
  "guided tour": "city_tour",
  "bus tour": "city_tour",
  "amusement park": "theme_park",
  "water park": "theme_park",
  "live music": "concert",
  "live show": "concert",
  surf: "water_sports",
  surfing: "water_sports",
  kayak: "water_sports",
  "jet ski": "water_sports",
};

function normalizeKey(raw: string): string {
  return raw.toLowerCase().trim().replace(/[\s-]+/g, "_");
}

function resolveAlias(raw: string): string {
  const norm = normalizeKey(raw);
  return CATEGORY_ALIASES[norm] ?? norm;
}

/**
 * Map a source entity record to canonical taxonomy.
 */
export function mapToTaxonomy(record: SourceEntityRecord): TaxonomyNode {
  const vertical = record.vertical;
  const family = VERTICAL_FAMILIES[vertical] ?? "unknown";
  const verticalMap = CATEGORY_MAP[vertical] ?? {};

  // Try each raw category/subcategory
  const candidates = [
    ...(record.subcategories ?? []),
    ...(record.categories ?? []),
  ].map(resolveAlias);

  for (const key of candidates) {
    const match = verticalMap[key];
    if (match) {
      const wasAlias = key !== candidates[0];
      return {
        family,
        category: match.category,
        subcategory: match.subcategory,
        tags: [...new Set([...(record.categories ?? []), ...(record.subcategories ?? [])])],
        confidence: wasAlias ? 75 : 85,
      };
    }
  }

  // Fallback: use vertical defaults
  const defaultCategories: Record<string, { category: string; subcategory: string }> = {
    food: { category: "restaurant", subcategory: "general" },
    grocery: { category: "grocery_store", subcategory: "general" },
    stay: { category: "accommodation", subcategory: "hotel" },
    hotel: { category: "accommodation", subcategory: "hotel" },
    services: { category: "general_services", subcategory: "general" },
    property: { category: "listing", subcategory: "general" },
    shops: { category: "retail", subcategory: "general" },
    mobility: { category: "transport", subcategory: "taxi" },
    utility: { category: "utility", subcategory: "general" },
    healthcare: { category: "health", subcategory: "general" },
    experiences: { category: "entertainment", subcategory: "general" },
  };

  const fallback = defaultCategories[vertical] ?? { category: "general", subcategory: "general" };
  return {
    family,
    category: fallback.category,
    subcategory: fallback.subcategory,
    tags: [...new Set([...(record.categories ?? []), ...(record.subcategories ?? [])])],
    confidence: 30,
  };
}

/**
 * Validate taxonomy node completeness.
 */
export function isTaxonomyComplete(t: TaxonomyNode): boolean {
  return !!t.family && !!t.category && !!t.subcategory && t.confidence >= 50;
}
