/**
 * geo.city.resolve — Resolves city name with timezone/zone awareness.
 * ONE thing: clean and validate city name.
 */

const CITY_ZONES: Record<string, { zone: string; country: string }> = {
  dubai: { zone: "dubai", country: "AE" },
  "abu dhabi": { zone: "abu_dhabi", country: "AE" },
  sharjah: { zone: "sharjah", country: "AE" },
  ajman: { zone: "ajman", country: "AE" },
  riyadh: { zone: "riyadh", country: "SA" },
  jeddah: { zone: "jeddah", country: "SA" },
  makkah: { zone: "makkah", country: "SA" },
  madinah: { zone: "madinah", country: "SA" },
  cairo: { zone: "cairo", country: "EG" },
  alexandria: { zone: "alexandria", country: "EG" },
  casablanca: { zone: "casablanca", country: "MA" },
  marrakech: { zone: "marrakech", country: "MA" },
  paris: { zone: "paris", country: "FR" },
  lyon: { zone: "lyon", country: "FR" },
  marseille: { zone: "marseille", country: "FR" },
  london: { zone: "london", country: "GB" },
  istanbul: { zone: "istanbul", country: "TR" },
  ankara: { zone: "ankara", country: "TR" },
  doha: { zone: "doha", country: "QA" },
  muscat: { zone: "muscat", country: "OM" },
  manama: { zone: "manama", country: "BH" },
  amman: { zone: "amman", country: "JO" },
  berlin: { zone: "berlin", country: "DE" },
  munich: { zone: "munich", country: "DE" },
  madrid: { zone: "madrid", country: "ES" },
  barcelona: { zone: "barcelona", country: "ES" },
  rome: { zone: "rome", country: "IT" },
  milan: { zone: "milan", country: "IT" },
  lisbon: { zone: "lisbon", country: "PT" },
  amsterdam: { zone: "amsterdam", country: "NL" },
  brussels: { zone: "brussels", country: "BE" },
  "new york": { zone: "new_york", country: "US" },
  "los angeles": { zone: "los_angeles", country: "US" },
  toronto: { zone: "toronto", country: "CA" },
  "sao paulo": { zone: "sao_paulo", country: "BR" },
  "são paulo": { zone: "sao_paulo", country: "BR" },
  "rio de janeiro": { zone: "rio", country: "BR" },
  "mexico city": { zone: "mexico_city", country: "MX" },
  "buenos aires": { zone: "buenos_aires", country: "AR" },
  bogota: { zone: "bogota", country: "CO" },
  "bogotá": { zone: "bogota", country: "CO" },
  medellin: { zone: "medellin", country: "CO" },
  "medellín": { zone: "medellin", country: "CO" },
  lima: { zone: "lima", country: "PE" },
  santiago: { zone: "santiago", country: "CL" },
  mumbai: { zone: "mumbai", country: "IN" },
  delhi: { zone: "delhi", country: "IN" },
  "new delhi": { zone: "new_delhi", country: "IN" },
  bangalore: { zone: "bangalore", country: "IN" },
  bengaluru: { zone: "bangalore", country: "IN" },
  kolkata: { zone: "kolkata", country: "IN" },
  chennai: { zone: "chennai", country: "IN" },
  hyderabad: { zone: "hyderabad", country: "IN" },
  karachi: { zone: "karachi", country: "PK" },
  lahore: { zone: "lahore", country: "PK" },
  islamabad: { zone: "islamabad", country: "PK" },
  dhaka: { zone: "dhaka", country: "BD" },
  bangkok: { zone: "bangkok", country: "TH" },
  "ho chi minh": { zone: "ho_chi_minh", country: "VN" },
  hanoi: { zone: "hanoi", country: "VN" },
  "hà nội": { zone: "hanoi", country: "VN" },
  jakarta: { zone: "jakarta", country: "ID" },
  surabaya: { zone: "surabaya", country: "ID" },
  "kuala lumpur": { zone: "kuala_lumpur", country: "MY" },
  manila: { zone: "manila", country: "PH" },
  seoul: { zone: "seoul", country: "KR" },
  tokyo: { zone: "tokyo", country: "JP" },
  osaka: { zone: "osaka", country: "JP" },
  beijing: { zone: "beijing", country: "CN" },
  shanghai: { zone: "shanghai", country: "CN" },
  singapore: { zone: "singapore", country: "SG" },
  sydney: { zone: "sydney", country: "AU" },
  melbourne: { zone: "melbourne", country: "AU" },
  auckland: { zone: "auckland", country: "NZ" },
  lagos: { zone: "lagos", country: "NG" },
  abuja: { zone: "abuja", country: "NG" },
  nairobi: { zone: "nairobi", country: "KE" },
  mombasa: { zone: "mombasa", country: "KE" },
  accra: { zone: "accra", country: "GH" },
  johannesburg: { zone: "johannesburg", country: "ZA" },
  "cape town": { zone: "cape_town", country: "ZA" },
  "addis ababa": { zone: "addis_ababa", country: "ET" },
  "dar es salaam": { zone: "dar_es_salaam", country: "TZ" },
  dakar: { zone: "dakar", country: "SN" },
  abidjan: { zone: "abidjan", country: "CI" },
  douala: { zone: "douala", country: "CM" },
  moscow: { zone: "moscow", country: "RU" },
  "saint petersburg": { zone: "saint_petersburg", country: "RU" },
  kyiv: { zone: "kyiv", country: "UA" },
  tunis: { zone: "tunis", country: "TN" },
  algiers: { zone: "algiers", country: "DZ" },
  kuwait: { zone: "kuwait", country: "KW" },
  beirut: { zone: "beirut", country: "LB" },
};

export function resolveCity(raw: string | null | undefined): {
  city: string | null;
  zone: string | null;
  countryHint: string | null;
} {
  if (!raw?.trim()) return { city: null, zone: null, countryHint: null };
  const key = raw.trim().toLowerCase();
  const match = CITY_ZONES[key];
  if (match) {
    return {
      city: raw.trim().charAt(0).toUpperCase() + raw.trim().slice(1).toLowerCase(),
      zone: match.zone,
      countryHint: match.country,
    };
  }
  return {
    city: raw.trim(),
    zone: null,
    countryHint: null,
  };
}
