// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * Thrown when code tries to use the Supabase client without the required
 * environment variables being configured. Callers should catch this at the
 * boundary (e.g. `validateIntegrationsBoot()` in `main.tsx`) and surface a
 * real configuration error instead of a generic network failure.
 */
export class IntegrationsNotConfiguredError extends Error {
  readonly code = "INTEGRATIONS_NOT_CONFIGURED" as const;
  constructor(message: string) {
    super(message);
    this.name = "IntegrationsNotConfiguredError";
  }
}

function safeGetStorage() {
  try { return localStorage; } catch { return undefined; }
}

/**
 * Guarded proxy used when env vars are missing. Any property access or method
 * call throws `IntegrationsNotConfiguredError` — we deliberately DO NOT return
 * a fake working client that would issue fetches against a placeholder host
 * (phantom network errors, realtime websocket loops, masked root cause).
 *
 * Module evaluation remains safe: nothing throws until the client is actually
 * used, which gives `validateIntegrationsBoot()` a chance to surface a typed
 * configuration error to the user.
 */
function createUnconfiguredClient(): SupabaseClient<Database> {
  const message =
    "[Supabase] VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY is not defined. " +
    "Configure these environment variables before starting the app.";
  // Log once at module eval so developers see the failure even before the
  // first use. No network, no websocket, no localStorage access here.
  console.error(message);

  const fail = (prop: string | symbol): never => {
    throw new IntegrationsNotConfiguredError(
      `${message} (attempted to access supabase.${String(prop)})`,
    );
  };

  // A single Proxy where every property access or call throws. Callable so
  // that `supabase.auth()` style misuse also fails cleanly.
  const target = function () { /* noop */ } as unknown as SupabaseClient<Database>;
  return new Proxy(target, {
    get: (_t, prop) => fail(prop),
    apply: () => fail("(call)"),
    has: () => true,
  });
}

function createRealClient(): SupabaseClient<Database> {
  return createClient<Database>(SUPABASE_URL as string, SUPABASE_PUBLISHABLE_KEY as string, {
    auth: {
      storage: safeGetStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

function createSafeClient(): SupabaseClient<Database> {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    return createUnconfiguredClient();
  }
  // `createClient` can itself throw on malformed URLs. We still don't want
  // a module-eval crash blanking the screen before React mounts, so fall
  // back to the guarded proxy — the error surfaces on first use instead.
  try {
    return createRealClient();
  } catch (err) {
    console.error("[Supabase] createClient failed:", err);
    return createUnconfiguredClient();
  }
}

export const supabase = createSafeClient();