import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.2";
// @deno-types="npm:jspdf@2.5.2"
import { jsPDF } from "npm:jspdf@2.5.2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const log = (step: string, d?: unknown) =>
  console.log(`[RECEIPT-GEN] ${step}${d ? ` — ${JSON.stringify(d)}` : ""}`);

/** Country-specific receipt labels */
const COUNTRY_LABELS: Record<string, {
  title: string; landlord: string; tenant: string; property: string;
  period: string; rent: string; charges: string; total: string;
  paidOn: string; method: string; signature: string; legal: string;
}> = {
  FR: {
    title: "QUITTANCE DE LOYER",
    landlord: "Bailleur", tenant: "Locataire", property: "Bien loué",
    period: "Période", rent: "Loyer hors charges", charges: "Charges",
    total: "Total réglé", paidOn: "Date de paiement", method: "Mode de paiement",
    signature: "Fait pour servir de quittance",
    legal: "Conformément à la loi n° 89-462 du 6 juillet 1989, article 21.",
  },
  _default: {
    title: "RENT RECEIPT",
    landlord: "Landlord", tenant: "Tenant", property: "Property",
    period: "Period", rent: "Rent", charges: "Charges",
    total: "Total paid", paidOn: "Payment date", method: "Payment method",
    signature: "Issued as receipt of payment",
    legal: "",
  },
};

const PAYMENT_LABELS: Record<string, string> = {
  wallet: "Wallet", card: "Card", sepa_debit: "SEPA Direct Debit",
  bank_transfer: "Bank Transfer", manual: "Manual",
};

function fmtCurrency(amount: number, currency: string): string {
  try {
    return new Intl.NumberFormat("fr-FR", { style: "currency", currency }).format(amount);
  } catch {
    return `${amount.toFixed(2)} ${currency}`;
  }
}

function generateReceiptPDF(data: {
  country: string; month: string;
  landlordName: string; landlordAddress: string;
  tenantName: string; tenantAddress: string;
  propertyAddress: string; propertyLabel: string;
  rentAmount: number; chargesAmount: number; totalAmount: number;
  currency: string; paidDate: string; paymentMethod: string;
  receiptRef: string;
}): Uint8Array {
  const L = COUNTRY_LABELS[data.country] || COUNTRY_LABELS._default;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const w = doc.internal.pageSize.getWidth();
  let y = 20;

  // Title
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(L.title, w / 2, y, { align: "center" });
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Réf: ${data.receiptRef}`, w / 2, y, { align: "center" });
  y += 12;

  // Landlord
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(L.landlord, 20, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.text(data.landlordName, 20, y); y += 5;
  if (data.landlordAddress) { doc.text(data.landlordAddress, 20, y); y += 5; }
  y += 4;

  // Tenant
  doc.setFont("helvetica", "bold");
  doc.text(L.tenant, 20, y); y += 6;
  doc.setFont("helvetica", "normal");
  doc.text(data.tenantName, 20, y); y += 5;
  if (data.tenantAddress) { doc.text(data.tenantAddress, 20, y); y += 5; }
  y += 4;

  // Property
  doc.setFont("helvetica", "bold");
  doc.text(L.property, 20, y); y += 6;
  doc.setFont("helvetica", "normal");
  doc.text(data.propertyLabel || data.propertyAddress, 20, y); y += 5;
  doc.text(data.propertyAddress, 20, y); y += 8;

  // Separator
  doc.setDrawColor(200); doc.line(20, y, w - 20, y); y += 8;

  // Period
  doc.setFont("helvetica", "bold");
  doc.text(`${L.period}: ${data.month}`, 20, y); y += 8;

  // Amounts
  const col2 = w - 60;
  doc.setFont("helvetica", "normal");
  doc.text(L.rent, 20, y);
  doc.text(fmtCurrency(data.rentAmount, data.currency), col2, y, { align: "right" }); y += 6;
  doc.text(L.charges, 20, y);
  doc.text(fmtCurrency(data.chargesAmount, data.currency), col2, y, { align: "right" }); y += 6;
  doc.setDrawColor(100); doc.line(20, y, col2, y); y += 4;
  doc.setFont("helvetica", "bold");
  doc.text(L.total, 20, y);
  doc.text(fmtCurrency(data.totalAmount, data.currency), col2, y, { align: "right" }); y += 10;

  // Payment info
  doc.setFont("helvetica", "normal");
  doc.text(`${L.paidOn}: ${data.paidDate}`, 20, y); y += 6;
  doc.text(`${L.method}: ${PAYMENT_LABELS[data.paymentMethod] || data.paymentMethod || "—"}`, 20, y); y += 12;

  // Signature
  doc.setFont("helvetica", "italic");
  doc.text(L.signature, 20, y); y += 10;

  // Legal
  if (L.legal) {
    doc.setFontSize(8);
    doc.text(L.legal, 20, y, { maxWidth: w - 40 });
  }

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(150);
  doc.text("Generated by Easy-Locs", w / 2, 285, { align: "center" });

  return doc.output("arraybuffer") as unknown as Uint8Array;
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  const sb = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    { auth: { persistSession: false } }
  );

  try {
    const { rent_call_id } = await req.json();
    if (!rent_call_id) throw new Error("Missing rent_call_id");

    log("Processing", { rent_call_id });

    // Fetch rent_call with full context
    const { data: rc, error: rcErr } = await sb
      .from("rent_calls")
      .select("*")
      .eq("id", rent_call_id)
      .single();
    if (rcErr || !rc) throw new Error("Rent call not found");

    // Idempotency: receipt already exists
    if (rc.receipt_pdf_url) {
      log("Receipt already exists, skipping");
      return new Response(JSON.stringify({ ok: true, already_exists: true, url: rc.receipt_pdf_url }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Verify payment conditions
    if (rc.paid_amount < rc.total_amount) throw new Error("Payment incomplete");

    // Fetch lease, tenant, property, org
    const [leaseRes, tenantRes, propertyRes, orgRes] = await Promise.all([
      rc.lease_id ? sb.from("leases").select("country, property_id").eq("id", rc.lease_id).maybeSingle() : { data: null },
      sb.from("tenants").select("name, email, current_address").eq("id", rc.tenant_id).single(),
      rc.property_id ? sb.from("properties").select("label, address, city, postal_code, country").eq("id", rc.property_id).single() : { data: null },
      sb.from("orgs").select("name, address, city").eq("id", rc.org_id).single(),
    ]);

    const country = leaseRes.data?.country || propertyRes.data?.country || "FR";
    const currency = "EUR"; // TODO: derive from country
    const propertyAddr = propertyRes.data
      ? `${propertyRes.data.address || ""}, ${propertyRes.data.postal_code || ""} ${propertyRes.data.city || ""}`.trim()
      : "";

    const receiptRef = `REC-${rc.month.replace("-", "")}-${rent_call_id.slice(0, 8).toUpperCase()}`;

    // Generate PDF
    const pdfBytes = generateReceiptPDF({
      country,
      month: rc.month,
      landlordName: orgRes.data?.name || "Proprietaire",
      landlordAddress: orgRes.data?.address ? `${orgRes.data.address}, ${orgRes.data.city || ""}` : "",
      tenantName: tenantRes.data?.name || "Locataire",
      tenantAddress: tenantRes.data?.current_address || "",
      propertyAddress: propertyAddr,
      propertyLabel: propertyRes.data?.label || "",
      rentAmount: rc.rent_amount,
      chargesAmount: rc.charges_amount,
      totalAmount: rc.total_amount,
      currency,
      paidDate: rc.paid_date || new Date().toISOString().split("T")[0],
      paymentMethod: rc.payment_method || "",
      receiptRef,
    });

    // Upload to storage
    const filePath = `receipts/${rc.org_id}/${rc.month}/${receiptRef}.pdf`;
    const { error: uploadErr } = await sb.storage
      .from("rental-docs")
      .upload(filePath, pdfBytes, { contentType: "application/pdf", upsert: true });

    if (uploadErr) throw new Error(`Upload failed: ${uploadErr.message}`);

    const { data: urlData } = sb.storage.from("rental-docs").getPublicUrl(filePath);
    const publicUrl = urlData?.publicUrl || "";

    // Update rent_call with receipt URL
    await sb.from("rent_calls").update({
      receipt_pdf_url: publicUrl,
      receipt_validated: true,
      payment_reference: rc.payment_reference || receiptRef,
    }).eq("id", rent_call_id);

    // Create document record for visibility in landlord + tenant documents
    await sb.from("documents").insert({
      org_id: rc.org_id,
      tenant_id: rc.tenant_id,
      lease_id: rc.lease_id || null,
      title: `Quittance ${rc.month}`,
      doc_type: "rent-receipt",
      status: "signed",
      pdf_url: publicUrl,
    }).single();

    // Create notification for tenant
    if (tenantRes.data) {
      const { data: tenantUser } = await sb
        .from("tenants")
        .select("tenant_user_id")
        .eq("id", rc.tenant_id)
        .maybeSingle();

      if (tenantUser?.tenant_user_id) {
        await sb.from("notifications").insert({
          user_id: tenantUser.tenant_user_id,
          title: "Quittance disponible",
          message: `Votre quittance de loyer pour ${rc.month} est disponible.`,
          type: "document",
          link: "/tenant/receipts",
          metadata_json: { rent_call_id, month: rc.month, receipt_url: publicUrl },
        });
      }
    }

    log("Receipt generated", { receiptRef, url: publicUrl });

    return new Response(JSON.stringify({ ok: true, url: publicUrl, ref: receiptRef }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    log("ERROR", { message: msg });
    return new Response(JSON.stringify({ error: msg }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 500,
    });
  }
});
