/**
 * Explicit security manifest for edge functions.
 *
 * The inventory script (`scripts/security-inventory-edge-functions.ts`) uses
 * this as the ground-truth classification. Any function whose name does NOT
 * appear here is treated as "unclassified" and flagged in the inventory.
 *
 * Keep entries alphabetical per section. Every entry must state:
 *  - `auth`      how callers are authenticated (jwt, service_role, signature, token, public)
 *  - `rateLimit` whether the function wraps its handler with `withRateLimit`
 *  - `reason`    short justification, especially for `public` entries
 */

export type ManifestEntry = {
  auth: "jwt" | "service_role" | "signature" | "token" | "public";
  rateLimit: boolean;
  reason?: string;
  // ── All remaining functions (classified by auth posture) ────────────

  // ── Webhook / signature-verified functions ──
  "auth-callback": { auth: "jwt", rateLimit: false, reason: "Auth callback: provider signature verification (OAuth/PKCE)" },

  // ── Service-role / cron invocations ──
  "army-tick": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "auto-onboarding-cron": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "dispatch-cron": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "dld-sync-cron": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "engine-cron-server": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "gateway-cron-sync": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "integration-health-cron": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "rent-lifecycle-cron": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "run-engine-cron": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "sync-meilisearch-cron": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "watchdog-loop": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "watchdog-ping": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },

  // ── JWT-authenticated functions ──
  "admin-merge-conflict-recovery": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "admin-payout-approve": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "admin-payout-reject": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "admin-trigger": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "agent-heal": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "agent-kill": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "agent-spawn": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "agent-watchdog": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "ai-assistant": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "ai-content-enrichment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "ai-entity-enrichment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "ai-eval-runner": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "ai-rag": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "ai-recommendations": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "ai-shopping-chat": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "ai-web-search": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "alert-dispatcher": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "audit-export": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "auto-source-scrape": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "award-loyalty-points": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "aws-health-check": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "backup-storage": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "booking-approve": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "booking-complete": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "booking-create": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "booking-lifecycle": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "booking-reject": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "browser-user-repair-engine": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "cache-manager": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "captain-plan": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "capture-payment-intent": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "check-connect-status": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "check-subscription": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "chief-agent": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "classify-business": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "cleanup-expired-media": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "cleanup-expired-messages": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "cleanup-integration-health-logs": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "cleanup-orphan-media": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "collect-sepa-rents": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "command-center-api": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "command-email-parse": { auth: "jwt", rateLimit: true, reason: "JWT authentication via Supabase JWT middleware" },
  "commission-split": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-booking-payment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-checkout": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-checkout-session": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-concierge-payment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-connect-account": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-guest-checkout": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-legal-notice-payment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-listing-checkout": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-storefront-checkout": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-stripe-intent": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-subscription": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-wallet-topup": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "crypto-payment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "customer-portal": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "deep-scrape-build": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "deliveroo-dubai-food": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "dev-builder": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "dev-planner": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "disconnect-stripe": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "dispatch-delivery": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "dispatch-ride": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "dld-analytics": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "dlq-ingest": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "dlq-processor": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "email-enqueue": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "email-queue-process": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "esign-create-envelope": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "execution-loop": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "execution-runner-callback": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "expire-listings": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "expire-pending-referrals": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "export-ical": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "extract-article": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "food-audit": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "food-menu-builder": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "food-normalizer": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "food-publish": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "food-rescrape-monitor": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "food-visibility-gate": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "food-visual-clean": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "fx-rates": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "gateway-marketplace-sync": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "gateway-webhook-ingest": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "gdpr-delete-account": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "gdpr-deletion-processor": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "gdpr-export": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "general-route": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "generate-cv": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "generate-embeddings": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "generate-pdf": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "generate-rent-receipt": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "generate-seo": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "get-turn-credentials": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "goal-create": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "goal-planner": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "guest-session": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "health-check": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "incident-escalate": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "integration-health-monitor": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "job-queue-worker": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "job-runner": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "kyc-review": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "lambda-invoke-proxy": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "lc3-replan-trigger": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "lease-workflow": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "livekit-room-token": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "manage-subscription": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "master-runtime-qa-engine": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "media-processor": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "mobile-money-payment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "mux-upload": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "notification-dispatcher": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "notify-booking": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "omega-server-loop": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "ops-ai-chat": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "orbit-ai-support": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "orbit-payment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "orchestrator-dispatch": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "order-manage": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "payment-notification": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "payout-request-create": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "pipeline-worker": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "plaid-link-token": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "platform-recovery": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "prayer-times": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "presence-heartbeat": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "process-onboarding-media": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "process-referral-reward": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "process-refund": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "public-health": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "purchase-locs": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "qr-payment-session": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "redis-enqueue": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "redis-proxy": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "refund-admin": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "refund-process-booking": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "refund-request-booking": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "rent-create-payment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "rent-payment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "rent-reminders": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "repair-worker": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "reveal-contact": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "rss-proxy": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "run-ingestion-pipeline": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "run-scheduled-audit": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "runtime-control-plane": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "s3-upload-proxy": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "scrape-proxy": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "search-global": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "search-meilisearch": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "seller-kpi-snapshot": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "send-call-push": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "send-email": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "send-notification-email": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "send-otp": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "send-push": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "send-push-notification": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "send-sms": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "sentinel-server": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "sentinel-server-guards": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "shop-import-processor": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "social-preview": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "spatial-query": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "sqs-enqueue-proxy": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "storefront-description": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "stripe-connect-login": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "submit-review": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "subscription-portal": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "sync-ical": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "sync-meilisearch": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "tenant-signup": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "translate-message": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "trigger-github": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "tts-engine": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "uae-data-cleanup": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "uae-scrape-onboard": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "vector-embed": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "verify-guest-payment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "verify-otp": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "video-processor": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "voice-processing": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "voice-stt-token": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "voice-tts": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "wallet-ops": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "wallet-pin": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "wallet-transfer": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "webauthn-authentication-challenge": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "webauthn-authentication-verify": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "webauthn-begin-registration": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "webauthn-finish-registration": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "webauthn-login-challenge": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "webauthn-login-verify": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "webauthn-registration-challenge": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "webauthn-registration-verify": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "worker-execute": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "worker-report": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
};

export const EDGE_FUNCTION_MANIFEST: Record<string, ManifestEntry> = {
  // ── Public webhooks (third-party callers, no JWT) ────────────────────
  "stripe-webhook": { auth: "signature", rateLimit: true, reason: "Stripe sends ts+sig; verified with stripe.webhooks.constructEvent" },
  "ses-webhook": { auth: "signature", rateLimit: true, reason: "AWS SNS signature verification in handler" },
  "plaid-webhook": { auth: "signature", rateLimit: true, reason: "Plaid JWT signature" },
  "crypto-webhook": { auth: "signature", rateLimit: true, reason: "HMAC signature header" },
  "mobile-money-webhook": { auth: "signature", rateLimit: true, reason: "PSP HMAC signature" },
  "esign-webhook": { auth: "signature", rateLimit: true, reason: "eSign provider HMAC" },
  "dispatch-webhook": { auth: "signature", rateLimit: false, reason: "Dispatcher HMAC" },
  "command-github-webhook": { auth: "signature", rateLimit: true, reason: "GitHub X-Hub-Signature-256 HMAC SHA-256" },
  "command-email-intake": { auth: "signature", rateLimit: true, reason: "HMAC-SHA256 preferred (x-webhook-signature) or legacy shared secret (constant-time)" },
  "command-approval-webhook": { auth: "token", rateLimit: true, reason: "Per-request opaque tokens in the approval_requests table; JSON path uses constant-time shared secret" },
  "receive-email": { auth: "signature", rateLimit: true, reason: "SendGrid inbound shared secret, constant-time compare" },
  "inngest-handler": { auth: "signature", rateLimit: true, reason: "Inngest SDK verifies its own signing key" },

  // ── Cron dispatchers (called by pg_cron via pg_net) ──────────────────
  "autonomous-cron-dispatcher": { auth: "service_role", rateLimit: true, reason: "Invoked server-side via service-role header" },
  "prayer-push-cron": { auth: "service_role", rateLimit: true, reason: "pg_cron service-role invocation" },
  "command-monitoring-cron": { auth: "service_role", rateLimit: true, reason: "Internal secret header, constant-time compared" },
  "merge-conflict-recovery-alerts-cron": { auth: "service_role", rateLimit: true, reason: "Internal secret header, constant-time compared (task #973)" },

  // ── Public SEO / read APIs ───────────────────────────────────────────
  "public-api": { auth: "public", rateLimit: true, reason: "Read-only SEO / taxonomy endpoints; per-route RLS + rate limit" },
  "csp-report": { auth: "public", rateLimit: true, reason: "CSP report-uri collector; accepts application/csp-report from browsers, persists to security_csp_reports" },

  // ── Domain routers (JWT verified inside via edge-auth.ts) ────────────
  // rateLimit is currently false for routers: they do auth via edge-auth
  // but do not wrap with `withRateLimit`. Tracked in follow-up #772.
  "admin-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending (follow-up #772)" },
  "ai-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  "vector-similarity-search": { auth: "jwt", rateLimit: false, reason: "JWT verified via requireAuthenticatedUser; rate-limit wrapper pending follow-up #772" },
  "ai-proxy": { auth: "jwt", rateLimit: false, reason: "JWT verified inside proxy; rate-limit wrapper pending" },
  "booking-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  "commerce-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  "food-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  "gdpr-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  "identity-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  "infra-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  "logistics-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  "marketplace-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  "media-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  "notification-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  "orbit-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  "rent-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  "search-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  "stripe-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  "system-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  "voice-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  "wallet-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  "webauthn-router": { auth: "jwt", rateLimit: false, reason: "JWT verified inside router; rate-limit wrapper pending" },
  // ── All remaining functions (classified by auth posture) ────────────

  // ── Webhook / signature-verified functions ──
  "auth-callback": { auth: "jwt", rateLimit: false, reason: "Auth callback: provider signature verification (OAuth/PKCE)" },

  // ── Service-role / cron invocations ──
  "army-tick": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "auto-onboarding-cron": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "dispatch-cron": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "dld-sync-cron": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "engine-cron-server": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "gateway-cron-sync": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "integration-health-cron": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "rent-lifecycle-cron": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "run-engine-cron": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "sync-meilisearch-cron": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "watchdog-loop": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },
  "watchdog-ping": { auth: "service_role", rateLimit: false, reason: "Scheduled/background job via service-role invocation" },

  // ── JWT-authenticated functions ──
  "admin-merge-conflict-recovery": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "admin-payout-approve": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "admin-payout-reject": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "admin-trigger": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "agent-heal": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "agent-kill": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "agent-spawn": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "agent-watchdog": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "ai-assistant": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "ai-content-enrichment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "ai-entity-enrichment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "ai-eval-runner": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "ai-rag": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "ai-recommendations": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "ai-shopping-chat": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "ai-web-search": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "alert-dispatcher": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "audit-export": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "auto-source-scrape": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "award-loyalty-points": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "aws-health-check": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "backup-storage": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "booking-approve": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "booking-complete": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "booking-create": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "booking-lifecycle": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "booking-reject": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "browser-user-repair-engine": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "cache-manager": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "captain-plan": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "capture-payment-intent": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "check-connect-status": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "check-subscription": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "chief-agent": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "classify-business": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "cleanup-expired-media": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "cleanup-expired-messages": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "cleanup-integration-health-logs": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "cleanup-orphan-media": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "collect-sepa-rents": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "command-center-api": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "command-email-parse": { auth: "jwt", rateLimit: true, reason: "JWT authentication via Supabase JWT middleware" },
  "commission-split": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-booking-payment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-checkout": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-checkout-session": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-concierge-payment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-connect-account": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-guest-checkout": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-legal-notice-payment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-listing-checkout": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-storefront-checkout": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-stripe-intent": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-subscription": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "create-wallet-topup": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "crypto-payment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "customer-portal": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "deep-scrape-build": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "deliveroo-dubai-food": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "dev-builder": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "dev-planner": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "disconnect-stripe": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "dispatch-delivery": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "dispatch-ride": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "dld-analytics": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "dlq-ingest": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "dlq-processor": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "email-enqueue": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "email-queue-process": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "esign-create-envelope": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "execution-loop": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "execution-runner-callback": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "expire-listings": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "expire-pending-referrals": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "export-ical": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "extract-article": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "food-audit": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "food-menu-builder": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "food-normalizer": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "food-publish": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "food-rescrape-monitor": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "food-visibility-gate": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "food-visual-clean": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "fx-rates": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "gateway-marketplace-sync": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "gateway-webhook-ingest": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "gdpr-delete-account": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "gdpr-deletion-processor": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "gdpr-export": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "general-route": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "generate-cv": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "generate-embeddings": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "generate-pdf": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "generate-rent-receipt": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "generate-seo": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "get-turn-credentials": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "goal-create": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "goal-planner": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "guest-session": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "health-check": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "incident-escalate": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "integration-health-monitor": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "job-queue-worker": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "job-runner": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "kyc-review": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "lambda-invoke-proxy": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "lc3-replan-trigger": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "lease-workflow": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "livekit-room-token": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "manage-subscription": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "master-runtime-qa-engine": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "media-processor": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "mobile-money-payment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "mux-upload": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "notification-dispatcher": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "notify-booking": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "omega-server-loop": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "ops-ai-chat": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "orbit-ai-support": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "orbit-payment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "orchestrator-dispatch": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "order-manage": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "payment-notification": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "payout-request-create": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "pipeline-worker": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "plaid-link-token": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "platform-recovery": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "prayer-times": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "presence-heartbeat": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "process-onboarding-media": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "process-referral-reward": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "process-refund": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "public-health": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "purchase-locs": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "qr-payment-session": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "redis-enqueue": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "redis-proxy": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "refund-admin": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "refund-process-booking": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "refund-request-booking": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "rent-create-payment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "rent-payment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "rent-reminders": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "repair-worker": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "reveal-contact": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "rss-proxy": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "run-ingestion-pipeline": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "run-scheduled-audit": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "runtime-control-plane": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "s3-upload-proxy": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "scrape-proxy": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "search-global": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "search-meilisearch": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "seller-kpi-snapshot": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "send-call-push": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "send-email": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "send-notification-email": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "send-otp": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "send-push": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "send-push-notification": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "send-sms": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "sentinel-server": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "sentinel-server-guards": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "shop-import-processor": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "social-preview": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "spatial-query": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "sqs-enqueue-proxy": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "storefront-description": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "stripe-connect-login": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "submit-review": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "subscription-portal": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "sync-ical": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "sync-meilisearch": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "tenant-signup": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "translate-message": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "trigger-github": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "tts-engine": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "uae-data-cleanup": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "uae-scrape-onboard": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "vector-embed": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "verify-guest-payment": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "verify-otp": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "video-processor": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "voice-processing": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "voice-stt-token": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "voice-tts": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "wallet-ops": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "wallet-pin": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "wallet-transfer": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "webauthn-authentication-challenge": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "webauthn-authentication-verify": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "webauthn-begin-registration": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "webauthn-finish-registration": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "webauthn-login-challenge": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "webauthn-login-verify": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "webauthn-registration-challenge": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "webauthn-registration-verify": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "worker-execute": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
  "worker-report": { auth: "jwt", rateLimit: false, reason: "JWT authentication via Supabase JWT middleware" },
};
