import type jsPDF from "jspdf";
import { toast } from "sonner";

// ═══════════════════════════════════════════════════════════════
// WORLDWIDE INVOICE PDF GENERATOR — Easy-Locs® Marketplace
// Professional SaaS standard (Stripe / Airbnb level)
// ═══════════════════════════════════════════════════════════════

interface InvoiceData {
  booking: any;
  service: any;
  provider: any;
}

// ── Country → locale / date format / tax config ──
const COUNTRY_LOCALE: Record<string, string> = {
  FR: "fr-FR", DE: "de-DE", ES: "es-ES", IT: "it-IT", PT: "pt-PT",
  NL: "nl-NL", BE: "fr-BE", CH: "de-CH", AT: "de-AT", GB: "en-GB",
  IE: "en-IE", US: "en-US", CA: "en-CA", AU: "en-AU", NZ: "en-NZ",
  MA: "fr-MA", TN: "fr-TN", DZ: "fr-DZ", AE: "ar-AE", SA: "ar-SA",
  QA: "ar-QA", JP: "ja-JP", KR: "ko-KR", CN: "zh-CN", IN: "hi-IN",
  BR: "pt-BR", MX: "es-MX", TR: "tr-TR", PL: "pl-PL", CZ: "cs-CZ",
  SE: "sv-SE", NO: "nb-NO", DK: "da-DK", FI: "fi-FI", GR: "el-GR",
  RO: "ro-RO", HU: "hu-HU", BG: "bg-BG", HR: "hr-HR", SK: "sk-SK",
  ZA: "en-ZA", NG: "en-NG", KE: "en-KE", GH: "en-GH", EG: "ar-EG",
};

const TAX_LABEL_BY_COUNTRY: Record<string, string> = {
  FR: "TVA", DE: "MwSt.", ES: "IVA", IT: "IVA", PT: "IVA", NL: "BTW",
  BE: "TVA", CH: "MWST", AT: "USt.", GB: "VAT", IE: "VAT", US: "Sales Tax",
  CA: "GST/HST", AU: "GST", NZ: "GST", IN: "GST", JP: "消費税",
  AE: "VAT", SA: "VAT", MA: "TVA", TN: "TVA", DZ: "TVA", BR: "ICMS",
  MX: "IVA", TR: "KDV", ZA: "VAT", NG: "VAT", KE: "VAT", EG: "ض.ق.م",
};

const INVOICE_LABELS: Record<string, Record<string, string>> = {
  en: { invoice: "INVOICE", billTo: "BILL TO", description: "DESCRIPTION", qty: "QTY", unitPrice: "UNIT PRICE", total: "TOTAL", subtotal: "Subtotal", grandTotal: "TOTAL DUE", paymentStatus: "Payment Status", paidOn: "Paid on", paymentMethod: "Payment Method", bookingRef: "Booking Ref", location: "Location", bankDetails: "BANK DETAILS", holder: "Account Holder", bank: "Bank", date: "Date", thanks: "Thank you for your business.", generated: "Generated by Easy-Locs\u00AE Marketplace", footer2: "This invoice was automatically generated.", website: "www.easy-locs.com", paid: "PAID", pending: "PENDING" },
  fr: { invoice: "FACTURE", billTo: "FACTURER À", description: "DESCRIPTION", qty: "QTÉ", unitPrice: "PRIX UNIT.", total: "TOTAL", subtotal: "Sous-total", grandTotal: "TOTAL À PAYER", paymentStatus: "Statut du paiement", paidOn: "Payé le", paymentMethod: "Moyen de paiement", bookingRef: "Réf. réservation", location: "Lieu", bankDetails: "COORDONNÉES BANCAIRES", holder: "Titulaire", bank: "Banque", date: "Date", thanks: "Merci pour votre confiance.", generated: "Généré par Easy-Locs\u00AE Marketplace", footer2: "Cette facture a été générée automatiquement.", website: "www.easy-locs.com", paid: "PAYÉ", pending: "EN ATTENTE" },
  es: { invoice: "FACTURA", billTo: "FACTURAR A", description: "DESCRIPCIÓN", qty: "CANT.", unitPrice: "PRECIO UNIT.", total: "TOTAL", subtotal: "Subtotal", grandTotal: "TOTAL A PAGAR", paymentStatus: "Estado del pago", paidOn: "Pagado el", paymentMethod: "Método de pago", bookingRef: "Ref. reserva", location: "Ubicación", bankDetails: "DATOS BANCARIOS", holder: "Titular", bank: "Banco", date: "Date", thanks: "Gracias por su confianza.", generated: "Generado por Easy-Locs\u00AE Marketplace", footer2: "Esta factura fue generada automáticamente.", website: "www.easy-locs.com", paid: "PAGADO", pending: "PENDIENTE" },
  de: { invoice: "RECHNUNG", billTo: "RECHNUNGSEMPFÄNGER", description: "BESCHREIBUNG", qty: "MENGE", unitPrice: "EINZELPREIS", total: "GESAMT", subtotal: "Zwischensumme", grandTotal: "GESAMTBETRAG", paymentStatus: "Zahlungsstatus", paidOn: "Bezahlt am", paymentMethod: "Zahlungsart", bookingRef: "Buchungs-Nr.", location: "Standort", bankDetails: "BANKVERBINDUNG", holder: "Kontoinhaber", bank: "Bank", date: "Datum", thanks: "Vielen Dank für Ihr Vertrauen.", generated: "Erstellt von Easy-Locs\u00AE Marketplace", footer2: "Diese Rechnung wurde automatisch erstellt.", website: "www.easy-locs.com", paid: "BEZAHLT", pending: "AUSSTEHEND" },
  it: { invoice: "FATTURA", billTo: "INTESTATARIO", description: "DESCRIZIONE", qty: "Q.TÀ", unitPrice: "PREZZO UNIT.", total: "TOTALE", subtotal: "Subtotale", grandTotal: "TOTALE DOVUTO", paymentStatus: "Stato pagamento", paidOn: "Pagato il", paymentMethod: "Metodo di pagamento", bookingRef: "Rif. prenotazione", location: "Luogo", bankDetails: "DATI BANCARI", holder: "Intestatario conto", bank: "Banca", date: "Data", thanks: "Grazie per la fiducia.", generated: "Generato da Easy-Locs\u00AE Marketplace", footer2: "Questa fattura è stata generata automaticamente.", website: "www.easy-locs.com", paid: "PAGATO", pending: "IN ATTESA" },
  pt: { invoice: "FATURA", billTo: "FATURAR A", description: "DESCRIÇÃO", qty: "QTD.", unitPrice: "PREÇO UNIT.", total: "TOTAL", subtotal: "Subtotal", grandTotal: "TOTAL A PAGAR", paymentStatus: "Estado do pagamento", paidOn: "Pago em", paymentMethod: "Método de pagamento", bookingRef: "Ref. reserva", location: "Local", bankDetails: "DADOS BANCÁRIOS", holder: "Titular", bank: "Banco", date: "Data", thanks: "Obrigado pela sua confiança.", generated: "Gerado por Easy-Locs\u00AE Marketplace", footer2: "Esta fatura foi gerada automaticamente.", website: "www.easy-locs.com", paid: "PAGO", pending: "PENDENTE" },
  ar: { invoice: "فاتورة", billTo: "فاتورة إلى", description: "الوصف", qty: "الكمية", unitPrice: "سعر الوحدة", total: "المجموع", subtotal: "المجموع الفرعي", grandTotal: "المجموع المستحق", paymentStatus: "حالة الدفع", paidOn: "تم الدفع في", paymentMethod: "طريقة الدفع", bookingRef: "مرجع الحجز", location: "الموقع", bankDetails: "البيانات البنكية", holder: "صاحب الحساب", bank: "البنك", date: "التاريخ", thanks: "شكراً لتعاملكم معنا.", generated: "تم الإنشاء بواسطة Easy-Locs\u00AE", footer2: "تم إنشاء هذه الفاتورة تلقائياً.", website: "www.easy-locs.com", paid: "مدفوع", pending: "معلق" },
};

function getLabels(country: string): Record<string, string> {
  const langMap: Record<string, string> = {
    FR: "fr", BE: "fr", CH: "fr", MA: "fr", TN: "fr", DZ: "fr", LU: "fr",
    ES: "es", MX: "es", AR: "es", CL: "es", CO: "es",
    DE: "de", AT: "de",
    IT: "it",
    PT: "pt", BR: "pt",
    AE: "ar", SA: "ar", QA: "ar", EG: "ar",
  };
  return INVOICE_LABELS[langMap[country] || "en"] || INVOICE_LABELS.en;
}

function formatDate(date: Date, country: string): string {
  const locale = COUNTRY_LOCALE[country] || "en-GB";
  try {
    return new Intl.DateTimeFormat(locale, { day: "2-digit", month: "long", year: "numeric" }).format(date);
  } catch { return date.toLocaleDateString("en-GB"); }
}

function formatAmount(amount: number, currency: string, country: string): string {
  const locale = COUNTRY_LOCALE[country] || "en-US";
  try {
    return new Intl.NumberFormat(locale, { style: "currency", currency, minimumFractionDigits: 2 }).format(amount);
  } catch { return `${amount.toFixed(2)} ${currency}`; }
}

function loadLogoAsBase64(url: string): Promise<string | null> {
  return new Promise((resolve) => {
    if (!url) return resolve(null);
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      canvas.getContext("2d")?.drawImage(img, 0, 0);
      try { resolve(canvas.toDataURL("image/png")); } catch { resolve(null); }
    };
    img.onerror = () => resolve(null);
    img.src = url;
  });
}

// ═══════════════════════════════════════════════════════════════
// MAIN GENERATOR
// ═══════════════════════════════════════════════════════════════

export async function generateInvoicePdf(data: InvoiceData): Promise<Blob | null> {
  const { booking, service, provider } = data;

  if (!provider?.invoicing_enabled) {
    toast.error("Invoicing is not enabled. Activate it in your provider profile.");
    return null;
  }

  const { default: JsPDF } = await import("jspdf");
  const country = service?.country || provider?.country || booking?.country || "FR";
  const L = getLabels(country);
  const currency = booking.currency || "EUR";

  const doc = new JsPDF({ unit: "mm", format: "a4" });
  const PW = 210; // page width
  const M = 18;   // margin
  const W = PW - M * 2; // content width
  const RX = M + W;
  let y = M;

  // ── Colors ──
  const C = {
    brand:    [0, 71, 171]   as [number, number, number],   // deep blue
    brandBg:  [235, 243, 255] as [number, number, number],
    black:    [20, 20, 20]    as [number, number, number],
    dark:     [55, 55, 65]    as [number, number, number],
    mid:      [120, 120, 130] as [number, number, number],
    light:    [180, 180, 190] as [number, number, number],
    lineBg:   [247, 248, 250] as [number, number, number],
    white:    [255, 255, 255] as [number, number, number],
    green:    [16, 124, 65]   as [number, number, number],
    greenBg:  [230, 248, 237] as [number, number, number],
    red:      [200, 40, 40]   as [number, number, number],
  };

  const tc = (c: [number, number, number]) => doc.setTextColor(...c);
  const fc = (c: [number, number, number]) => doc.setFillColor(...c);
  const font = (style: "normal" | "bold", size: number) => { doc.setFont("helvetica", style); doc.setFontSize(size); };

  // ── Load logo ──
  let logo: string | null = null;
  if (provider.avatar_url) logo = await loadLogoAsBase64(provider.avatar_url);

  // ══════════════════════════════════════════════════════════════
  // HEADER — Left: Company Info / Right: Invoice Title
  // ══════════════════════════════════════════════════════════════

  const companyName = provider.invoice_company_name || provider.company_name || provider.display_name || "Provider";
  const headerRightX = RX;

  // Left side — logo + company info
  let lx = M;
  if (logo) {
    try { doc.addImage(logo, "PNG", M, y, 16, 16); lx = M + 20; } catch { /* skip */ }
  }

  font("bold", 13);
  tc(C.black);
  doc.text(companyName, lx, y + 5);

  font("normal", 8);
  tc(C.dark);
  let infoY = y + 10;
  if (provider.invoice_address) {
    const lines = provider.invoice_address.split("\n").map((l: string) => l.trim()).filter(Boolean);
    lines.forEach((line: string) => { doc.text(line, lx, infoY); infoY += 3.5; });
  }
  const contactParts: string[] = [];
  if (provider.email) contactParts.push(provider.email);
  if (provider.phone) contactParts.push(provider.phone);
  if (contactParts.length) { doc.text(contactParts.join("  |  "), lx, infoY); infoY += 3.5; }
  if (provider.invoice_tax_id) {
    font("normal", 7.5);
    tc(C.mid);
    doc.text(`Tax ID: ${provider.invoice_tax_id}`, lx, infoY);
  }

  // Right side — INVOICE title + number + date
  font("bold", 22);
  tc(C.brand);
  doc.text(L.invoice, headerRightX, y + 6, { align: "right" });

  font("normal", 9);
  tc(C.dark);
  const prefix = provider.invoice_prefix || "INV";
  const num = String(provider.invoice_next_number || 1).padStart(4, "0");
  const invoiceNumber = `${prefix}-${num}`;
  doc.text(`#${invoiceNumber}`, headerRightX, y + 12, { align: "right" });

  font("normal", 8.5);
  tc(C.mid);
  const invoiceDate = formatDate(new Date(), country);
  doc.text(`${L.date}: ${invoiceDate}`, headerRightX, y + 17, { align: "right" });

  // Country
  try {
    const countryName = new Intl.DisplayNames(["en"], { type: "region" }).of(country);
    if (countryName) {
      doc.text(countryName, headerRightX, y + 21.5, { align: "right" });
    }
  } catch { /* skip */ }

  y = Math.max(y + 28, infoY + 6);

  // ── Brand accent line ──
  doc.setDrawColor(...C.brand);
  doc.setLineWidth(0.8);
  doc.line(M, y, RX, y);
  y += 10;

  // ══════════════════════════════════════════════════════════════
  // BILL TO
  // ══════════════════════════════════════════════════════════════
  fc(C.lineBg);
  doc.roundedRect(M, y, W, 24, 2, 2, "F");

  font("bold", 7);
  tc(C.mid);
  doc.text(L.billTo, M + 6, y + 5);

  font("bold", 10.5);
  tc(C.black);
  doc.text(booking.booker_name || "Client", M + 6, y + 11);

  font("normal", 8);
  tc(C.dark);
  const clientParts: string[] = [];
  if (booking.booker_email) clientParts.push(booking.booker_email);
  if (booking.booker_phone) clientParts.push(booking.booker_phone);
  doc.text(clientParts.join("  •  "), M + 6, y + 16);

  // Client country
  if (booking.customer_country || booking.country) {
    font("normal", 7.5);
    tc(C.mid);
    try {
      const cName = new Intl.DisplayNames(["en"], { type: "region" }).of(booking.customer_country || booking.country);
      if (cName) doc.text(cName, M + 6, y + 20.5);
    } catch { /* skip */ }
  }

  y += 30;

  // ══════════════════════════════════════════════════════════════
  // SERVICE TABLE
  // ══════════════════════════════════════════════════════════════
  const colDesc = M + 5;
  const colQty = M + 102;
  const colUnit = M + 120;
  const colCur = M + 148;
  const colTotal = RX - 5;

  // Table header
  fc(C.brand);
  doc.roundedRect(M, y, W, 9, 1.5, 1.5, "F");
  font("bold", 7.5);
  tc(C.white);
  doc.text(L.description, colDesc, y + 6);
  doc.text(L.qty, colQty, y + 6);
  doc.text(L.unitPrice, colUnit, y + 6);
  doc.text(L.total, colTotal, y + 6, { align: "right" });
  y += 11;

  // Table row
  const title = service?.title || "Service";
  const qty = booking.quantity || 1;
  const subtotalPrice = Number(booking.total_price || 0);
  const unitPrice = service?.price || subtotalPrice / qty;

  // Row background
  fc(C.lineBg);
  const rowH = 16;
  doc.roundedRect(M, y - 1, W, rowH, 1, 1, "F");

  // Service title
  font("bold", 9);
  tc(C.black);
  doc.text(title, colDesc, y + 4.5);

  // Sub-info: location + dates
  font("normal", 7);
  tc(C.mid);
  const subInfoParts: string[] = [];
  if (service?.city) subInfoParts.push(service.city);
  if (service?.country) {
    try {
      const cn = new Intl.DisplayNames(["en"], { type: "region" }).of(service.country);
      if (cn) subInfoParts.push(cn);
    } catch { /* skip */ }
  }
  const dateInfo = booking.date_from && booking.date_to
    ? `${booking.date_from} → ${booking.date_to}`
    : booking.service_date || "";
  if (dateInfo) subInfoParts.push(dateInfo);
  if (booking.service_time) subInfoParts.push(booking.service_time);
  if (subInfoParts.length) {
    doc.text(subInfoParts.join("  •  "), colDesc, y + 9.5);
  }

  // Qty
  font("normal", 9);
  tc(C.dark);
  doc.text(String(qty), colQty, y + 4.5);

  // Unit price
  doc.text(formatAmount(unitPrice, currency, country), colUnit, y + 4.5);

  // Total
  font("bold", 9);
  tc(C.black);
  doc.text(formatAmount(subtotalPrice, currency, country), colTotal, y + 4.5, { align: "right" });

  y += rowH + 3;

  // Separator
  doc.setDrawColor(...C.light);
  doc.setLineWidth(0.15);
  doc.line(M, y, RX, y);
  y += 5;

  // ══════════════════════════════════════════════════════════════
  // TOTALS
  // ══════════════════════════════════════════════════════════════
  const taxRate = Number(provider.tax_rate || 0);
  const taxLabel = provider.tax_label || TAX_LABEL_BY_COUNTRY[country] || "VAT";
  const taxAmount = taxRate > 0 ? Math.round(subtotalPrice * taxRate) / 100 : 0;
  const grandTotal = subtotalPrice + taxAmount;

  const totalsLabelX = M + 100;
  const totalsValX = RX - 5;

  // Subtotal
  font("normal", 9);
  tc(C.dark);
  doc.text(L.subtotal, totalsLabelX, y + 4);
  doc.text(formatAmount(subtotalPrice, currency, country), totalsValX, y + 4, { align: "right" });
  y += 6;

  // Tax
  if (taxRate > 0) {
    doc.text(`${taxLabel} (${taxRate}%)`, totalsLabelX, y + 4);
    doc.text(formatAmount(taxAmount, currency, country), totalsValX, y + 4, { align: "right" });
    y += 6;
  }

  // Grand total box
  y += 2;
  fc(C.brandBg);
  doc.roundedRect(totalsLabelX - 5, y - 1, RX - totalsLabelX + 10, 13, 2, 2, "F");
  font("bold", 11.5);
  tc(C.brand);
  doc.text(L.grandTotal, totalsLabelX, y + 8);
  doc.text(formatAmount(grandTotal, currency, country), totalsValX, y + 8, { align: "right" });
  y += 19;

  // ══════════════════════════════════════════════════════════════
  // PAYMENT INFORMATION
  // ══════════════════════════════════════════════════════════════
  const isPaid = booking.payment_confirmed;

  // Payment status badge
  if (isPaid) {
    fc(C.greenBg);
    doc.roundedRect(M, y - 1, 22, 7, 1.5, 1.5, "F");
    font("bold", 7.5);
    tc(C.green);
    doc.text(L.paid, M + 3, y + 3.8);
  } else {
    font("bold", 7.5);
    tc(C.red);
    doc.text(`⏳ ${L.pending}`, M, y + 3.8);
  }

  // Payment details on right
  font("normal", 8);
  tc(C.dark);
  const payDetails: string[] = [];
  if (booking.payment_confirmed_at) {
    payDetails.push(`${L.paidOn}: ${formatDate(new Date(booking.payment_confirmed_at), country)}`);
  }
  if (booking.payment_method) {
    payDetails.push(`${L.paymentMethod}: ${booking.payment_method}`);
  }
  if (payDetails.length) {
    doc.text(payDetails.join("   •   "), M + 26, y + 3.8);
  }
  y += 9;

  // Booking ref + location
  font("normal", 7.5);
  tc(C.mid);
  const metaParts: string[] = [];
  if (booking.id) metaParts.push(`${L.bookingRef}: ${booking.id.slice(0, 8).toUpperCase()}`);
  if (service?.city) metaParts.push(`${L.location}: ${service.city}`);
  if (metaParts.length) {
    doc.text(metaParts.join("   •   "), M, y + 3);
    y += 5;
  }

  // Notes
  if (booking.notes) {
    font("normal", 7.5);
    tc(C.mid);
    doc.text(`Notes: ${booking.notes}`, M, y + 3);
    y += 5;
  }

  // ══════════════════════════════════════════════════════════════
  // BANK DETAILS
  // ══════════════════════════════════════════════════════════════
  if (provider.bank_iban || provider.bank_bic) {
    y += 3;
    doc.setDrawColor(...C.light);
    doc.setLineWidth(0.2);
    doc.line(M, y, RX, y);
    y += 6;

    font("bold", 8);
    tc(C.brand);
    doc.text(L.bankDetails, M, y);
    y += 5;

    font("normal", 8);
    tc(C.dark);
    if (provider.bank_holder) { doc.text(`${L.holder}: ${provider.bank_holder}`, M, y); y += 4; }
    if (provider.bank_iban) { doc.text(`IBAN: ${provider.bank_iban}`, M, y); y += 4; }
    if (provider.bank_bic) { doc.text(`BIC / SWIFT: ${provider.bank_bic}`, M, y); y += 4; }
    if (provider.bank_name) { doc.text(`${L.bank}: ${provider.bank_name}`, M, y); y += 4; }
  }

  // ══════════════════════════════════════════════════════════════
  // FOOTER
  // ══════════════════════════════════════════════════════════════
  const footerY = 268;

  // Thank you
  font("normal", 8.5);
  tc(C.dark);
  doc.text(L.thanks, PW / 2, footerY - 8, { align: "center" });

  // Separator line
  doc.setDrawColor(...C.light);
  doc.setLineWidth(0.2);
  doc.line(M, footerY - 3, RX, footerY - 3);

  // Footer text
  font("normal", 7);
  tc(C.light);
  doc.text(L.generated, M, footerY + 1);
  doc.text(L.website, PW / 2, footerY + 1, { align: "center" });
  doc.text(`#${invoiceNumber}`, RX, footerY + 1, { align: "right" });

  font("normal", 6.5);
  tc(C.light);
  doc.text(L.footer2, PW / 2, footerY + 5, { align: "center" });

  // ── Save ──
  const fileName = `${invoiceNumber}-${(booking.booker_name || "invoice").replace(/\s+/g, "-")}.pdf`;
  doc.save(fileName);
  toast.success(`${L.invoice} ${invoiceNumber} ✓`);

  return doc.output("blob");
}

export function getInvoiceNumber(provider: any): string {
  const prefix = provider?.invoice_prefix || "INV";
  const num = String(provider?.invoice_next_number || 1).padStart(4, "0");
  return `${prefix}-${num}`;
}
