export const V1_SECONDARY_ROUTE_BLOCKLIST = [
  "/admin/",
  "/merchant/reviews/",
  "/merchant/menu-cloner/",
  "/merchant/holiday-schedule/",
  "/merchant/featured-items/",
  "/merchant/packaging/",
  "/merchant/order-throttle/",
  "/merchant/chat-settings/",
  "/merchant/cancellation-rules/",
  "/merchant/auto-accept/",
  "/merchant/driver-handoff/",
  "/merchant/queue-limit/",
  "/merchant/store-announcement/",
  "/merchant/temporary-closure/",
  "/merchant/menu-categories/",
  "/merchant/item-badges/",
  "/merchant/instructions-policy/",
  "/merchant/business-hours/",
  "/merchant/delivery-zones/",
  "/merchant/rush-pricing/",
  "/merchant/prep-time/",
  "/merchant/staff-roles/",
  "/merchant/permissions/",
  "/merchant/live-ops/",
  "/me/family-profile",
  "/me/favorite-items",
  "/me/lunch-subscription",
  "/me/weekly-meal-plan",
  "/me/kids-meal-profile",
  "/me/address-book",
  "/me/order-preferences",
  "/me/saved-carts",
  "/checkout/family-night",
  "/checkout/dinner-planner",
  "/checkout/group-order",
  "/checkout/party-split-links",
  "/checkout/share-cart",
  "/checkout/bulk-party-builder",
  "/checkout/guest-profile",
  "/checkout/dinner-budget",
];

export function isBlockedFromV1PrimaryNav(pathname: string) {
  return V1_SECONDARY_ROUTE_BLOCKLIST.some((p) => pathname.startsWith(p));
}
