/**
 * RiskFlagsDashboard — PASS119: Seller view of fraud/risk alerts.
 * Auto-generated by DB triggers on suspicious orders.
 */
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ShieldAlert, AlertTriangle, CheckCircle2, Eye, Loader2 } from "lucide-react";
import { toast } from "sonner";

interface Props {
  shopId: string;
}

const SEVERITY_STYLES: Record<string, { color: string; bg: string }> = {
  critical: { color: "text-destructive", bg: "bg-destructive/10" },
  high: { color: "text-destructive", bg: "bg-destructive/5" },
  medium: { color: "text-warning", bg: "bg-warning/10" },
  low: { color: "text-muted-foreground", bg: "bg-muted/30" },
};

export default function RiskFlagsDashboard({ shopId }: Props) {
  const { user } = useAuth();
  const qc = useQueryClient();

  const { data: flags = [], isLoading } = useQuery({
    queryKey: ["risk-flags", shopId],
    queryFn: async () => {
      const { data } = await (supabase as any)
        .from("storefront_risk_flags")
        .select("*")
        .eq("shop_id", shopId)
        .order("created_at", { ascending: false })
        .limit(50);
      return data || [];
    },
  });

  const resolveFlag = async (flagId: string) => {
    if (!user) return;
    const { error } = await (supabase as any)
      .from("storefront_risk_flags")
      .update({ status: "resolved", resolved_by: user.id, resolved_at: new Date().toISOString(), resolution_note: "Reviewed and cleared" })
      .eq("id", flagId);
    if (error) return toast.error(error.message);
    qc.invalidateQueries({ queryKey: ["risk-flags", shopId] });
    toast.success("Flag resolved");
  };

  const openFlags = flags.filter((f: any) => f.status === "open");
  const resolvedFlags = flags.filter((f: any) => f.status === "resolved");

  if (isLoading) return <div className="py-4 text-center"><Loader2 className="h-4 w-4 animate-spin mx-auto text-muted-foreground" /></div>;

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <h4 className="text-sm font-semibold flex items-center gap-2">
          <ShieldAlert className="h-4 w-4 text-destructive" /> Risk Alerts
        </h4>
        <Badge variant={openFlags.length > 0 ? "destructive" : "secondary"} className="text-[10px]">
          {openFlags.length} open
        </Badge>
      </div>

      {openFlags.length === 0 && resolvedFlags.length === 0 ? (
        <Card>
          <CardContent className="py-6 text-center">
            <CheckCircle2 className="h-8 w-8 mx-auto text-success/40 mb-2" />
            <p className="text-xs text-muted-foreground">No risk alerts — all clear!</p>
          </CardContent>
        </Card>
      ) : (
        <>
          {openFlags.map((flag: any) => {
            const style = SEVERITY_STYLES[flag.severity] || SEVERITY_STYLES.medium;
            return (
              <Card key={flag.id} className={`${style.bg} border-current/10`}>
                <CardContent className="p-3">
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex items-start gap-2 flex-1 min-w-0">
                      <AlertTriangle className={`h-4 w-4 mt-0.5 shrink-0 ${style.color}`} />
                      <div className="min-w-0">
                        <div className="flex items-center gap-1.5">
                          <p className="text-xs font-semibold text-foreground capitalize">{flag.flag_type.replace(/_/g, " ")}</p>
                          <Badge variant="outline" className={`text-[8px] ${style.color} border-current/20`}>{flag.severity}</Badge>
                        </div>
                        <p className="text-[10px] text-muted-foreground mt-0.5 line-clamp-2">{flag.reason}</p>
                        <p className="text-[9px] text-muted-foreground mt-1">
                          {new Date(flag.created_at).toLocaleDateString()}
                        </p>
                      </div>
                    </div>
                    <Button size="sm" variant="outline" className="h-7 text-[10px] shrink-0" onClick={() => resolveFlag(flag.id)}>
                      <Eye className="h-3 w-3 mr-1" /> Clear
                    </Button>
                  </div>
                </CardContent>
              </Card>
            );
          })}

          {resolvedFlags.length > 0 && (
            <details className="group">
              <summary className="text-[10px] text-muted-foreground cursor-pointer hover:text-foreground">
                {resolvedFlags.length} resolved alerts
              </summary>
              <div className="space-y-1.5 mt-2">
                {resolvedFlags.slice(0, 10).map((flag: any) => (
                  <div key={flag.id} className="flex items-center justify-between px-3 py-1.5 rounded-lg bg-muted/20">
                    <div className="flex items-center gap-2">
                      <CheckCircle2 className="h-3 w-3 text-success" />
                      <span className="text-[10px] text-muted-foreground capitalize">{flag.flag_type.replace(/_/g, " ")}</span>
                    </div>
                    <span className="text-[9px] text-muted-foreground">{new Date(flag.resolved_at || flag.created_at).toLocaleDateString()}</span>
                  </div>
                ))}
              </div>
            </details>
          )}
        </>
      )}
    </div>
  );
}
