import {
  CATEGORY_TREE,
  type PrimaryCategory,
  type CategorySubcategory,
  getAllSubcategoryValues,
} from "./category-tree";

import {
  CATEGORY_KEY_TO_VERTICAL,
  VERTICAL_TO_RADAR,
  type Vertical,
  type RadarMainCategory,
  type ServiceMode,
  type TimePeriod,
  type TaxonomySubcategory,
  type TaxonomyCluster,
  type TaxonomyVertical,
} from "./world-class-taxonomy";

const SERVICE_MODE_ENRICHMENT: Record<string, ServiceMode[]> = {
  restaurant: ["delivery", "pickup", "dine_in"],
  fast_food: ["delivery", "pickup", "dine_in"],
  pizza: ["delivery", "pickup", "dine_in"],
  burger: ["delivery", "pickup", "dine_in"],
  fried_chicken: ["delivery", "pickup", "dine_in"],
  shawarma: ["delivery", "pickup", "dine_in"],
  sushi: ["delivery", "pickup", "dine_in"],
  cafe: ["pickup", "dine_in", "delivery"],
  coffee: ["pickup", "dine_in"],
  bakery: ["pickup", "delivery", "dine_in"],
  desserts: ["pickup", "delivery", "dine_in"],
  beverages: ["pickup", "delivery"],
  breakfast: ["delivery", "pickup", "dine_in"],
  brunch: ["dine_in"],
  catering: ["home_service"],
  fine_dining: ["dine_in"],
  pakistani: ["delivery", "pickup", "dine_in"],
  pasta: ["delivery", "pickup", "dine_in"],
  asian: ["delivery", "pickup", "dine_in"],
  mexican: ["delivery", "pickup", "dine_in"],
  turkish: ["delivery", "pickup", "dine_in"],
  italian: ["delivery", "pickup", "dine_in"],
  indian: ["delivery", "pickup", "dine_in"],
  chinese: ["delivery", "pickup", "dine_in"],
  lebanese: ["delivery", "pickup", "dine_in"],
  arabic: ["delivery", "pickup", "dine_in"],
  thai: ["delivery", "pickup", "dine_in"],
  korean: ["delivery", "pickup", "dine_in"],
  japanese: ["delivery", "pickup", "dine_in"],
  seafood: ["delivery", "pickup", "dine_in"],
  healthy: ["delivery", "pickup", "dine_in"],
  vietnamese: ["delivery", "pickup", "dine_in"],
  greek: ["delivery", "pickup", "dine_in"],
  french: ["delivery", "pickup", "dine_in"],
  spanish: ["delivery", "pickup", "dine_in"],
  african: ["delivery", "pickup", "dine_in"],
  ethiopian: ["delivery", "pickup", "dine_in"],
  caribbean: ["delivery", "pickup", "dine_in"],
  persian: ["delivery", "pickup", "dine_in"],
  filipino: ["delivery", "pickup", "dine_in"],
  brazilian: ["delivery", "pickup", "dine_in"],
  german: ["delivery", "pickup", "dine_in"],
  moroccan: ["delivery", "pickup", "dine_in"],
  bbq: ["delivery", "pickup", "dine_in"],
  vegan: ["delivery", "pickup", "dine_in"],
  juice_bar: ["pickup", "delivery"],
  food_truck: ["pickup"],
  ice_cream: ["pickup", "delivery", "dine_in"],
  steakhouse: ["dine_in", "delivery"],
  buffet: ["dine_in"],
  cloud_kitchen: ["delivery"],
  food_court: ["dine_in", "pickup"],
  casual_dining: ["dine_in", "delivery", "pickup"],
  smoothie_bar: ["pickup", "delivery"],
  tea_house: ["dine_in", "pickup"],
  chocolate: ["pickup", "delivery"],
  pastry: ["pickup", "delivery", "dine_in"],
  delivery_takeaway: ["delivery", "pickup"],
  supermarket: ["delivery", "pickup"],
  mini_mart: ["delivery", "pickup"],
  organic_store: ["delivery", "pickup"],
  fruits_vegetables: ["delivery", "pickup"],
  butcher: ["delivery", "pickup"],
  dairy: ["delivery", "pickup"],
  beverages_store: ["delivery", "pickup"],
  snacks: ["delivery", "pickup"],
  frozen: ["delivery", "pickup"],
  bakery_grocery: ["delivery", "pickup"],
  baby_products: ["delivery", "pickup"],
  household: ["delivery", "pickup"],
  personal_care: ["delivery", "pickup"],
  pet_food: ["delivery", "pickup"],
  fish_market: ["delivery", "pickup"],
  spices: ["delivery", "pickup"],
  health_food: ["delivery", "pickup"],
  gourmet: ["delivery", "pickup"],
  water_delivery: ["delivery"],
  cleaning: ["home_service", "onsite"],
  laundry: ["pickup", "delivery", "onsite"],
  handyman: ["home_service", "onsite"],
  plumbing: ["home_service", "onsite"],
  electrical: ["home_service", "onsite"],
  ac_repair: ["home_service", "onsite"],
  mobile_repair: ["onsite"],
  car_repair: ["onsite"],
  car_wash: ["onsite", "home_service"],
  salon: ["onsite"],
  barber: ["onsite"],
  spa: ["onsite"],
  beauty: ["onsite", "home_service"],
  movers: ["home_service"],
  pest_control: ["home_service"],
  tailoring: ["onsite"],
  printing: ["onsite"],
  tutoring: ["onsite", "virtual"],
  legal: ["onsite", "virtual"],
  photography: ["onsite", "home_service"],
  accounting: ["onsite", "virtual"],
  insurance: ["onsite", "virtual"],
  pet_grooming: ["onsite", "home_service"],
  gardening: ["home_service", "onsite"],
  painting: ["home_service", "onsite"],
  interior_design: ["onsite", "virtual"],
  key_cutting: ["onsite", "home_service"],
  carpentry: ["home_service", "onsite"],
  it_support: ["onsite", "home_service", "virtual"],
  consulting: ["onsite", "virtual"],
  marketing: ["onsite", "virtual"],
  hvac: ["home_service", "onsite"],
  tire_service: ["onsite"],
  technician: ["home_service", "onsite"],
  delivery_service: ["home_service"],
  nails: ["onsite"],
  makeup: ["onsite", "home_service"],
  lashes: ["onsite"],
  tattoo: ["onsite"],
  massage: ["onsite", "home_service"],
  taxi: ["onsite"],
  chauffeur: ["onsite"],
  car_rental: ["onsite"],
  premium: ["onsite"],
  bike: ["onsite"],
  scooter: ["onsite"],
  courier: ["delivery"],
  freight: ["delivery"],
  hotel: ["onsite"],
  resort: ["onsite"],
  boutique: ["onsite"],
  hostel: ["onsite"],
  apartment_hotel: ["onsite"],
  holiday_rental: ["onsite"],
  serviced_apartment: ["onsite"],
  short_stay: ["onsite"],
  motel: ["onsite"],
  bed_breakfast: ["onsite"],
  glamping: ["onsite"],
  eco_lodge: ["onsite"],
  budget_hotel: ["onsite"],
  luxury_hotel: ["onsite"],
  desert_camp: ["onsite"],
  unique_stay: ["onsite"],
  pharmacy: ["onsite", "delivery"],
  clinic: ["onsite"],
  hospital: ["onsite"],
  dentist: ["onsite"],
  physio: ["onsite"],
  veterinary: ["onsite"],
  optical: ["onsite"],
  lab: ["onsite"],
  mental_health: ["onsite", "virtual"],
  dermatology: ["onsite"],
  pediatrics: ["onsite"],
  wholesale: ["onsite"],
  digital_products: ["delivery"],
  property_management: ["onsite"],
  cruise: ["onsite"],
  safari: ["onsite"],
  diving: ["onsite"],
  ski: ["onsite"],
  museum: ["onsite"],
  theme_park: ["onsite"],
  concert: ["onsite"],
  water_sports: ["onsite"],
  hiking: ["onsite"],
  city_tour: ["onsite"],
  cinema: ["onsite"],
  sports: ["onsite"],
  tourism: ["onsite"],
  k12_school: ["onsite"],
  university: ["onsite"],
  courses: ["onsite", "virtual"],
  coaching: ["onsite", "virtual"],
  online_learning: ["virtual"],
  language_school: ["onsite"],
  driving_school: ["onsite"],
  daycare: ["onsite"],
  vocational: ["onsite"],
  music_school: ["onsite"],
  payments: ["onsite", "virtual"],
  transfers: ["virtual"],
  banking: ["onsite"],
  insurance_finance: ["onsite", "virtual"],
  exchange: ["onsite"],
  crypto: ["virtual"],
  investment_finance: ["onsite", "virtual"],
  microfinance: ["onsite"],
};

const TIME_RELEVANCE_ENRICHMENT: Record<string, TimePeriod[]> = {
  restaurant: ["lunch", "dinner"],
  fast_food: ["lunch", "dinner", "late_night"],
  pizza: ["lunch", "dinner", "late_night"],
  burger: ["lunch", "dinner", "late_night"],
  fried_chicken: ["lunch", "dinner", "late_night"],
  shawarma: ["lunch", "dinner", "late_night"],
  cafe: ["breakfast", "snack"],
  coffee: ["breakfast", "snack"],
  bakery: ["breakfast", "snack"],
  desserts: ["snack", "dinner", "late_night"],
  breakfast: ["breakfast"],
  brunch: ["breakfast", "lunch"],
  sushi: ["lunch", "dinner"],
  beverages: ["snack"],
  fine_dining: ["dinner"],
  pakistani: ["lunch", "dinner"],
  pasta: ["lunch", "dinner"],
  asian: ["lunch", "dinner"],
  mexican: ["lunch", "dinner", "late_night"],
  turkish: ["lunch", "dinner"],
  italian: ["lunch", "dinner"],
  indian: ["lunch", "dinner"],
  chinese: ["lunch", "dinner"],
  lebanese: ["lunch", "dinner"],
  arabic: ["lunch", "dinner"],
  thai: ["lunch", "dinner"],
  korean: ["lunch", "dinner"],
  japanese: ["lunch", "dinner"],
  seafood: ["lunch", "dinner"],
  healthy: ["breakfast", "lunch", "snack"],
  vietnamese: ["lunch", "dinner"],
  greek: ["lunch", "dinner"],
  french: ["lunch", "dinner"],
  spanish: ["lunch", "dinner", "late_night"],
  african: ["lunch", "dinner"],
  ethiopian: ["lunch", "dinner"],
  caribbean: ["lunch", "dinner"],
  persian: ["lunch", "dinner"],
  filipino: ["lunch", "dinner"],
  brazilian: ["lunch", "dinner"],
  german: ["lunch", "dinner"],
  moroccan: ["lunch", "dinner"],
  bbq: ["lunch", "dinner"],
  vegan: ["breakfast", "lunch", "dinner"],
  juice_bar: ["breakfast", "snack"],
  food_truck: ["lunch", "snack", "late_night"],
  ice_cream: ["snack", "dinner"],
  steakhouse: ["dinner"],
};

function enrichSub(sub: CategorySubcategory): TaxonomySubcategory {
  return {
    value: sub.value,
    label: sub.label,
    emoji: sub.emoji,
    icon: sub.emoji,
    cluster: sub.cluster,
    tags: sub.tags ?? [],
    serviceModes: SERVICE_MODE_ENRICHMENT[sub.value] ?? [],
    timeRelevance: TIME_RELEVANCE_ENRICHMENT[sub.value] ?? [],
    geoHints: [],
  };
}

function extractClusters(subs: CategorySubcategory[]): TaxonomyCluster[] {
  const seen = new Map<string, TaxonomyCluster>();
  for (const s of subs) {
    if (!seen.has(s.cluster)) {
      seen.set(s.cluster, { value: s.cluster, label: s.cluster.charAt(0).toUpperCase() + s.cluster.slice(1).replace(/_/g, " "), emoji: s.emoji });
    }
  }
  return [...seen.values()];
}

function buildWorldTaxonomy(): TaxonomyVertical[] {
  const verticalGroups = new Map<Vertical, PrimaryCategory[]>();
  for (const primary of CATEGORY_TREE) {
    const v = CATEGORY_KEY_TO_VERTICAL[primary.key] ?? ("services" as Vertical);
    const arr = verticalGroups.get(v) ?? [];
    arr.push(primary);
    verticalGroups.set(v, arr);
  }

  const result: TaxonomyVertical[] = [];
  for (const [vertical, primaries] of verticalGroups) {
    const allSubs = primaries.flatMap(p => p.subcategories);
    const uniqueSubs = new Map<string, CategorySubcategory>();
    for (const s of allSubs) {
      if (!uniqueSubs.has(s.value)) uniqueSubs.set(s.value, s);
    }
    const enrichedSubs = [...uniqueSubs.values()].map(enrichSub);
    const clusters = extractClusters([...uniqueSubs.values()]);

    result.push({
      value: vertical,
      label: primaries[0].label,
      emoji: primaries[0].emoji,
      radarCategory: VERTICAL_TO_RADAR[vertical] ?? "services",
      clusters,
      subcategories: enrichedSubs,
    });
  }
  return result;
}

export const WORLD_TAXONOMY: TaxonomyVertical[] = buildWorldTaxonomy();
export const CANONICAL_VERTICALS = WORLD_TAXONOMY;
export const VERTICALS = WORLD_TAXONOMY;
export const ALL_SUBCATEGORY_VALUES = getAllSubcategoryValues();
