import type { CanonicalGlobalFeedItem } from "@/domains/shared/canonical-types";

const now = new Date().toISOString();
const expiresAt = new Date(Date.now() + 24 * 3_600_000).toISOString();

function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 3_600_000).toISOString();
}

export const FALLBACK_NEWS_FR: CanonicalGlobalFeedItem[] = [
  {
    id: "fallback_fr_1",
    sourceId: "fallback_static",
    sourceName: "Indicatif",
    sourceTrust: 0.5,
    sourceTier: "tier_3",
    category: "news",
    subcategory: "immobilier",
    title: "Le marché immobilier français montre des signes de stabilisation",
    summary: "Après plusieurs trimestres de baisse, les prix de l'immobilier en France semblent se stabiliser dans les grandes métropoles. Les experts anticipent une reprise progressive du volume de transactions.",
    body: null,
    language: "fr",
    originalLanguage: "fr",
    country: "FR",
    region: null,
    city: null,
    priority: "P3",
    relevanceScore: 0.75,
    freshnessScore: 0.6,
    personalRelevance: 0.7,
    publishedAt: hoursAgo(2),
    fetchedAt: now,
    expiresAt,
    tags: ["immobilier", "marché", "france", "indicatif"],
    mediaUrl: null,
    deepLinkUrl: null,
    contentHash: "fallback_immo_stabilisation",
  },
  {
    id: "fallback_fr_2",
    sourceId: "fallback_static",
    sourceName: "Indicatif",
    sourceTrust: 0.5,
    sourceTier: "tier_3",
    category: "news",
    subcategory: "finance",
    title: "La BCE maintient ses taux directeurs : impact sur les crédits immobiliers",
    summary: "La Banque centrale européenne a décidé de maintenir ses taux directeurs. Cette décision aura un impact direct sur les taux de crédit immobilier proposés par les banques françaises.",
    body: null,
    language: "fr",
    originalLanguage: "fr",
    country: "FR",
    region: null,
    city: null,
    priority: "P3",
    relevanceScore: 0.72,
    freshnessScore: 0.6,
    personalRelevance: 0.65,
    publishedAt: hoursAgo(3),
    fetchedAt: now,
    expiresAt,
    tags: ["finance", "taux", "bce", "crédit", "indicatif"],
    mediaUrl: null,
    deepLinkUrl: null,
    contentHash: "fallback_bce_taux",
  },
  {
    id: "fallback_fr_3",
    sourceId: "fallback_static",
    sourceName: "Indicatif",
    sourceTrust: 0.5,
    sourceTier: "tier_3",
    category: "news",
    subcategory: "economie",
    title: "Croissance économique : la France affiche un PIB en hausse de 0.3%",
    summary: "L'INSEE a publié les derniers chiffres de croissance économique. Le PIB français progresse de 0.3% au dernier trimestre, porté par la consommation des ménages et les exportations.",
    body: null,
    language: "fr",
    originalLanguage: "fr",
    country: "FR",
    region: null,
    city: null,
    priority: "P3",
    relevanceScore: 0.70,
    freshnessScore: 0.55,
    personalRelevance: 0.6,
    publishedAt: hoursAgo(4),
    fetchedAt: now,
    expiresAt,
    tags: ["économie", "pib", "croissance", "france", "indicatif"],
    mediaUrl: null,
    deepLinkUrl: null,
    contentHash: "fallback_pib_croissance",
  },
  {
    id: "fallback_fr_4",
    sourceId: "fallback_static",
    sourceName: "Indicatif",
    sourceTrust: 0.5,
    sourceTier: "tier_3",
    category: "news",
    subcategory: "immobilier",
    title: "DPE : les nouvelles réglementations pour les propriétaires bailleurs",
    summary: "Le gouvernement renforce les exigences en matière de diagnostic de performance énergétique. Les logements classés G devront être rénovés avant la prochaine échéance réglementaire.",
    body: null,
    language: "fr",
    originalLanguage: "fr",
    country: "FR",
    region: null,
    city: null,
    priority: "P3",
    relevanceScore: 0.68,
    freshnessScore: 0.55,
    personalRelevance: 0.72,
    publishedAt: hoursAgo(5),
    fetchedAt: now,
    expiresAt,
    tags: ["immobilier", "dpe", "réglementation", "location", "indicatif"],
    mediaUrl: null,
    deepLinkUrl: null,
    contentHash: "fallback_dpe_reglementation",
  },
  {
    id: "fallback_fr_5",
    sourceId: "fallback_static",
    sourceName: "Indicatif",
    sourceTrust: 0.5,
    sourceTier: "tier_3",
    category: "news",
    subcategory: "local",
    title: "Urbanisme : les métropoles investissent dans le logement social",
    summary: "Plusieurs grandes villes françaises ont annoncé de nouveaux programmes de construction de logements sociaux pour répondre à la demande croissante et réduire les délais d'attente.",
    body: null,
    language: "fr",
    originalLanguage: "fr",
    country: "FR",
    region: null,
    city: null,
    priority: "P3",
    relevanceScore: 0.65,
    freshnessScore: 0.5,
    personalRelevance: 0.6,
    publishedAt: hoursAgo(6),
    fetchedAt: now,
    expiresAt,
    tags: ["local", "urbanisme", "logement", "ville", "indicatif"],
    mediaUrl: null,
    deepLinkUrl: null,
    contentHash: "fallback_urbanisme_logement",
  },
  {
    id: "fallback_fr_6",
    sourceId: "fallback_static",
    sourceName: "Indicatif",
    sourceTrust: 0.5,
    sourceTier: "tier_3",
    category: "news",
    subcategory: "finance",
    title: "Épargne : le Livret A maintient son taux attractif",
    summary: "Le taux du Livret A reste inchangé pour les prochains mois. Les Français continuent de privilégier cette épargne réglementée face aux incertitudes économiques.",
    body: null,
    language: "fr",
    originalLanguage: "fr",
    country: "FR",
    region: null,
    city: null,
    priority: "P3",
    relevanceScore: 0.63,
    freshnessScore: 0.5,
    personalRelevance: 0.55,
    publishedAt: hoursAgo(7),
    fetchedAt: now,
    expiresAt,
    tags: ["finance", "épargne", "livret", "taux", "indicatif"],
    mediaUrl: null,
    deepLinkUrl: null,
    contentHash: "fallback_livret_a",
  },
  {
    id: "fallback_fr_7",
    sourceId: "fallback_static",
    sourceName: "Indicatif",
    sourceTrust: 0.5,
    sourceTier: "tier_3",
    category: "news",
    subcategory: "immobilier",
    title: "Location meublée : les règles fiscales à connaître",
    summary: "Le régime fiscal de la location meublée offre des avantages significatifs pour les propriétaires bailleurs. Décryptage des dispositifs LMNP et LMP en vigueur.",
    body: null,
    language: "fr",
    originalLanguage: "fr",
    country: "FR",
    region: null,
    city: null,
    priority: "P3",
    relevanceScore: 0.60,
    freshnessScore: 0.45,
    personalRelevance: 0.68,
    publishedAt: hoursAgo(8),
    fetchedAt: now,
    expiresAt,
    tags: ["immobilier", "location", "fiscal", "lmnp", "indicatif"],
    mediaUrl: null,
    deepLinkUrl: null,
    contentHash: "fallback_location_meublee",
  },
  {
    id: "fallback_fr_8",
    sourceId: "fallback_static",
    sourceName: "Indicatif",
    sourceTrust: 0.5,
    sourceTier: "tier_3",
    category: "news",
    subcategory: "economie",
    title: "Inflation en zone euro : tendance à la baisse confirmée",
    summary: "Les derniers chiffres d'Eurostat confirment un ralentissement de l'inflation en zone euro. La stabilité des prix de l'énergie contribue à cette amélioration.",
    body: null,
    language: "fr",
    originalLanguage: "fr",
    country: "FR",
    region: null,
    city: null,
    priority: "P3",
    relevanceScore: 0.58,
    freshnessScore: 0.45,
    personalRelevance: 0.5,
    publishedAt: hoursAgo(9),
    fetchedAt: now,
    expiresAt,
    tags: ["économie", "inflation", "europe", "indicatif"],
    mediaUrl: null,
    deepLinkUrl: null,
    contentHash: "fallback_inflation_euro",
  },
  {
    id: "fallback_fr_9",
    sourceId: "fallback_static",
    sourceName: "Indicatif",
    sourceTrust: 0.5,
    sourceTier: "tier_3",
    category: "news",
    subcategory: "local",
    title: "Transport en commun : nouvelles lignes de métro en projet",
    summary: "Le Grand Paris Express avance avec l'ouverture prochaine de nouvelles stations. Ces infrastructures de transport transformeront l'attractivité de plusieurs communes d'Île-de-France.",
    body: null,
    language: "fr",
    originalLanguage: "fr",
    country: "FR",
    region: null,
    city: null,
    priority: "P3",
    relevanceScore: 0.55,
    freshnessScore: 0.4,
    personalRelevance: 0.5,
    publishedAt: hoursAgo(10),
    fetchedAt: now,
    expiresAt,
    tags: ["local", "transport", "métro", "ville", "indicatif"],
    mediaUrl: null,
    deepLinkUrl: null,
    contentHash: "fallback_transport_metro",
  },
  {
    id: "fallback_fr_10",
    sourceId: "fallback_static",
    sourceName: "Indicatif",
    sourceTrust: 0.5,
    sourceTier: "tier_3",
    category: "news",
    subcategory: "immobilier",
    title: "Copropriété : les obligations du syndic renforcées",
    summary: "La loi renforce les obligations de transparence des syndics de copropriété. Les copropriétaires disposent désormais de nouveaux droits pour contrôler la gestion de leur immeuble.",
    body: null,
    language: "fr",
    originalLanguage: "fr",
    country: "FR",
    region: null,
    city: null,
    priority: "P3",
    relevanceScore: 0.52,
    freshnessScore: 0.35,
    personalRelevance: 0.6,
    publishedAt: hoursAgo(11),
    fetchedAt: now,
    expiresAt,
    tags: ["immobilier", "copropriété", "syndic", "indicatif"],
    mediaUrl: null,
    deepLinkUrl: null,
    contentHash: "fallback_copropriete_syndic",
  },
  {
    id: "fallback_fr_11",
    sourceId: "fallback_static",
    sourceName: "Indicatif",
    sourceTrust: 0.5,
    sourceTier: "tier_3",
    category: "news",
    subcategory: "finance",
    title: "Assurance habitation : comparatif des meilleures offres",
    summary: "Les tarifs d'assurance habitation varient considérablement selon les assureurs. Une comparaison des offres permet d'économiser jusqu'à 30% sur la prime annuelle.",
    body: null,
    language: "fr",
    originalLanguage: "fr",
    country: "FR",
    region: null,
    city: null,
    priority: "P3",
    relevanceScore: 0.50,
    freshnessScore: 0.35,
    personalRelevance: 0.55,
    publishedAt: hoursAgo(12),
    fetchedAt: now,
    expiresAt,
    tags: ["finance", "assurance", "habitation", "indicatif"],
    mediaUrl: null,
    deepLinkUrl: null,
    contentHash: "fallback_assurance_habitation",
  },
  {
    id: "fallback_fr_12",
    sourceId: "fallback_static",
    sourceName: "Indicatif",
    sourceTrust: 0.5,
    sourceTier: "tier_3",
    category: "news",
    subcategory: "economie",
    title: "Emploi : le secteur du bâtiment recrute massivement",
    summary: "Face aux besoins de rénovation énergétique et aux grands projets d'infrastructure, le secteur du bâtiment connaît une forte demande de main-d'œuvre qualifiée.",
    body: null,
    language: "fr",
    originalLanguage: "fr",
    country: "FR",
    region: null,
    city: null,
    priority: "P3",
    relevanceScore: 0.48,
    freshnessScore: 0.3,
    personalRelevance: 0.45,
    publishedAt: hoursAgo(13),
    fetchedAt: now,
    expiresAt,
    tags: ["économie", "emploi", "bâtiment", "construction", "indicatif"],
    mediaUrl: null,
    deepLinkUrl: null,
    contentHash: "fallback_emploi_batiment",
  },
];

export function getFallbackNews(country: string): CanonicalGlobalFeedItem[] {
  if (country === "FR") return FALLBACK_NEWS_FR;
  return FALLBACK_NEWS_FR.map(item => ({
    ...item,
    country,
    id: item.id.replace("_fr_", `_${country.toLowerCase()}_`),
  }));
}
